let ECAP_EmulationMode = [
	{ name: "ECAP_EMULATION_STOP", displayName: "TSCTR is stopped on emulation suspension" },
	{ name: "ECAP_EMULATION_RUN_TO_ZERO", displayName: "TSCTR runs until 0 before stopping on emulation suspension" },
	{ name: "ECAP_EMULATION_FREE_RUN", displayName: "TSCTR is not affected by emulation suspension" },
]
let ECAP_CaptureMode = [
	{ name: "ECAP_CONTINUOUS_CAPTURE_MODE", displayName: "eCAP operates in continuous capture mode" },
	{ name: "ECAP_ONE_SHOT_CAPTURE_MODE", displayName: "eCAP operates in one shot capture mode" },
]
let ECAP_Events = [
	{ name: "ECAP_EVENT_1", displayName: "eCAP event 1" },
	{ name: "ECAP_EVENT_2", displayName: "eCAP event 2" },
	{ name: "ECAP_EVENT_3", displayName: "eCAP event 3" },
	{ name: "ECAP_EVENT_4", displayName: "eCAP event 4" },
]
let ECAP_SyncOutMode = [
	{ name: "ECAP_SYNC_OUT_SYNCI", displayName: "sync out on the sync in signal and software force" },
	{ name: "ECAP_SYNC_OUT_COUNTER_PRD", displayName: "sync out on counter equals period" },
	{ name: "ECAP_SYNC_OUT_DISABLED", displayName: "Disable sync out signal" },
]
let ECAP_APWMPolarity = [
	{ name: "ECAP_APWM_ACTIVE_HIGH", displayName: "APWM is active high" },
	{ name: "ECAP_APWM_ACTIVE_LOW", displayName: "APWM is active low" },
]
let ECAP_EventPolarity = [
	{ name: "ECAP_EVNT_RISING_EDGE", displayName: "Rising edge polarity" },
	{ name: "ECAP_EVNT_FALLING_EDGE", displayName: "Falling edge polarity" },
]
let ECAP_InputCaptureSignals = [
    { name: "ECAP_INPUT_FSI_RX0_TRIG_0", displayName: "Capture input is FSI_RX0 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX0_TRIG_1", displayName: "Capture input is FSI_RX0 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX0_TRIG_2", displayName: "Capture input is FSI_RX0 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX0_TRIG_3", displayName: "Capture input is FSI_RX0 Trigger 3" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_0", displayName: "Capture input is FSI_RX1 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_1", displayName: "Capture input is FSI_RX1 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_2", displayName: "Capture input is FSI_RX1 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_3", displayName: "Capture input is FSI_RX1 Trigger 3" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_0", displayName: "Capture input is FSI_RX2 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_1", displayName: "Capture input is FSI_RX2 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_2", displayName: "Capture input is FSI_RX2 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_3", displayName: "Capture input is FSI_RX2 Trigger 3" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_0", displayName: "Capture input is FSI_RX3 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_1", displayName: "Capture input is FSI_RX3 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_2", displayName: "Capture input is FSI_RX3 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_3", displayName: "Capture input is FSI_RX3 Trigger 3" },
    { name: "ECAP_INPUT_EQEP0_QI", displayName: "Capture input is EQEP0 QI Signal" },
    { name: "ECAP_INPUT_EQEP0_QS", displayName: "Capture input is EQEP0 QS Signal" },
    { name: "ECAP_INPUT_EQEP1_QI", displayName: "Capture input is EQEP1 QI Signal" },
    { name: "ECAP_INPUT_EQEP1_QS", displayName: "Capture input is EQEP1 QS Signal" },
    { name: "ECAP_INPUT_EQEP2_QI", displayName: "Capture input is EQEP2 QI Signal" },
    { name: "ECAP_INPUT_EQEP2_QS", displayName: "Capture input is EQEP2 QS Signal" },
    { name: "ECAP_INPUT_EPWM0_SOCA", displayName: "Capture input is EPWM0 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM1_SOCA", displayName: "Capture input is EPWM1 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM2_SOCA", displayName: "Capture input is EPWM2 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM3_SOCA", displayName: "Capture input is EPWM3 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM4_SOCA", displayName: "Capture input is EPWM4 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM5_SOCA", displayName: "Capture input is EPWM5 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM6_SOCA", displayName: "Capture input is EPWM6 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM7_SOCA", displayName: "Capture input is EPWM7 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM8_SOCA", displayName: "Capture input is EPWM8 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM9_SOCA", displayName: "Capture input is EPWM9 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM10_SOCA", displayName: "Capture input is EPWM10 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM11_SOCA", displayName: "Capture input is EPWM11 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM12_SOCA", displayName: "Capture input is EPWM12 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM13_SOCA", displayName: "Capture input is EPWM13 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM14_SOCA", displayName: "Capture input is EPWM14 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM15_SOCA", displayName: "Capture input is EPWM15 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM16_SOCA", displayName: "Capture input is EPWM16 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM17_SOCA", displayName: "Capture input is EPWM17 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM18_SOCA", displayName: "Capture input is EPWM18 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM19_SOCA", displayName: "Capture input is EPWM19 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM20_SOCA", displayName: "Capture input is EPWM20 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM21_SOCA", displayName: "Capture input is EPWM21 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM22_SOCA", displayName: "Capture input is EPWM22 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM23_SOCA", displayName: "Capture input is EPWM23 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM24_SOCA", displayName: "Capture input is EPWM24 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM25_SOCA", displayName: "Capture input is EPWM25 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM26_SOCA", displayName: "Capture input is EPWM26 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM27_SOCA", displayName: "Capture input is EPWM27 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM28_SOCA", displayName: "Capture input is EPWM28 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM29_SOCA", displayName: "Capture input is EPWM29 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM30_SOCA", displayName: "Capture input is EPWM30 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM31_SOCA", displayName: "Capture input is EPWM31 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM0_SOCB", displayName: "Capture input is EPWM0 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM1_SOCB", displayName: "Capture input is EPWM1 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM2_SOCB", displayName: "Capture input is EPWM2 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM3_SOCB", displayName: "Capture input is EPWM3 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM4_SOCB", displayName: "Capture input is EPWM4 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM5_SOCB", displayName: "Capture input is EPWM5 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM6_SOCB", displayName: "Capture input is EPWM6 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM7_SOCB", displayName: "Capture input is EPWM7 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM8_SOCB", displayName: "Capture input is EPWM8 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM9_SOCB", displayName: "Capture input is EPWM9 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM10_SOCB", displayName: "Capture input is EPWM10 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM11_SOCB", displayName: "Capture input is EPWM11 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM12_SOCB", displayName: "Capture input is EPWM12 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM13_SOCB", displayName: "Capture input is EPWM13 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM14_SOCB", displayName: "Capture input is EPWM14 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM15_SOCB", displayName: "Capture input is EPWM15 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM16_SOCB", displayName: "Capture input is EPWM16 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM17_SOCB", displayName: "Capture input is EPWM17 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM18_SOCB", displayName: "Capture input is EPWM18 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM19_SOCB", displayName: "Capture input is EPWM19 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM20_SOCB", displayName: "Capture input is EPWM20 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM21_SOCB", displayName: "Capture input is EPWM21 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM22_SOCB", displayName: "Capture input is EPWM22 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM23_SOCB", displayName: "Capture input is EPWM23 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM24_SOCB", displayName: "Capture input is EPWM24 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM25_SOCB", displayName: "Capture input is EPWM25 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM26_SOCB", displayName: "Capture input is EPWM26 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM27_SOCB", displayName: "Capture input is EPWM27 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM28_SOCB", displayName: "Capture input is EPWM28 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM29_SOCB", displayName: "Capture input is EPWM29 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM30_SOCB", displayName: "Capture input is EPWM30 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM31_SOCB", displayName: "Capture input is EPWM31 SOC-B Signal" },
    { name: "ECAP_INPUT_SDFM0_COMPARE1_HIGH", displayName: "Capture input is SDFM0 Compare1 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE1_LOW", displayName: "Capture input is SDFM0 Compare1 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z1", displayName: "Capture input is SDFM0 Compare Z1" },
    { name: "ECAP_INPUT_SDFM0_COMPARE2_HIGH", displayName: "Capture input is SDFM0 Compare2 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE2_LOW", displayName: "Capture input is SDFM0 Compare2 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z2", displayName: "Capture input is SDFM0 Compare Z2" },
    { name: "ECAP_INPUT_SDFM0_COMPARE3_HIGH", displayName: "Capture input is SDFM0 Compare3 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE3_LOW", displayName: "Capture input is SDFM0 Compare3 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z3", displayName: "Capture input is SDFM0 Compare Z3" },
    { name: "ECAP_INPUT_SDFM0_COMPARE4_HIGH", displayName: "Capture input is SDFM0 Compare4 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE4_LOW", displayName: "Capture input is SDFM0 Compare4 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z4", displayName: "Capture input is SDFM0 Compare Z4" },
    { name: "ECAP_INPUT_SDFM1_COMPARE1_HIGH", displayName: "Capture input is SDFM1 Compare1 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE1_LOW", displayName: "Capture input is SDFM1 Compare1 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z1", displayName: "Capture input is SDFM1 Compare Z1" },
    { name: "ECAP_INPUT_SDFM1_COMPARE2_HIGH", displayName: "Capture input is SDFM1 Compare2 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE2_LOW", displayName: "Capture input is SDFM1 Compare2 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z2", displayName: "Capture input is SDFM1 Compare Z2" },
    { name: "ECAP_INPUT_SDFM1_COMPARE3_HIGH", displayName: "Capture input is SDFM1 Compare3 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE3_LOW", displayName: "Capture input is SDFM1 Compare3 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z3", displayName: "Capture input is SDFM1 Compare Z3" },
    { name: "ECAP_INPUT_SDFM1_COMPARE4_HIGH", displayName: "Capture input is SDFM1 Compare4 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE4_LOW", displayName: "Capture input is SDFM1 Compare4 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z4", displayName: "Capture input is SDFM1 Compare Z4" },
    { name: "ECAP_INPUT_CMPSSA0_CTRIP_LOW", displayName: "Capture input is CMPSSA0 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA0_CTRIP_HIGH", displayName: "Capture input is CMPSSA0 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA1_CTRIP_LOW", displayName: "Capture input is CMPSSA1 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA1_CTRIP_HIGH", displayName: "Capture input is CMPSSA1 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA2_CTRIP_LOW", displayName: "Capture input is CMPSSA2 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA2_CTRIP_HIGH", displayName: "Capture input is CMPSSA2 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA3_CTRIP_LOW", displayName: "Capture input is CMPSSA3 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA3_CTRIP_HIGH", displayName: "Capture input is CMPSSA3 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA4_CTRIP_LOW", displayName: "Capture input is CMPSSA4 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA4_CTRIP_HIGH", displayName: "Capture input is CMPSSA4 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA5_CTRIP_LOW", displayName: "Capture input is CMPSSA5 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA5_CTRIP_HIGH", displayName: "Capture input is CMPSSA5 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA6_CTRIP_LOW", displayName: "Capture input is CMPSSA6 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA6_CTRIP_HIGH", displayName: "Capture input is CMPSSA6 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA7_CTRIP_LOW", displayName: "Capture input is CMPSSA7 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA7_CTRIP_HIGH", displayName: "Capture input is CMPSSA7 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA8_CTRIP_LOW", displayName: "Capture input is CMPSSA8 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA8_CTRIP_HIGH", displayName: "Capture input is CMPSSA8 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA9_CTRIP_LOW", displayName: "Capture input is CMPSSA9 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA9_CTRIP_HIGH", displayName: "Capture input is CMPSSA9 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB0_CTRIP_LOW", displayName: "Capture input is CMPSSB0 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB0_CTRIP_HIGH", displayName: "Capture input is CMPSSB0 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB1_CTRIP_LOW", displayName: "Capture input is CMPSSB1 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB1_CTRIP_HIGH", displayName: "Capture input is CMPSSB1 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB2_CTRIP_LOW", displayName: "Capture input is CMPSSB2 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB2_CTRIP_HIGH", displayName: "Capture input is CMPSSB2 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB3_CTRIP_LOW", displayName: "Capture input is CMPSSB3 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB3_CTRIP_HIGH", displayName: "Capture input is CMPSSB3 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB4_CTRIP_LOW", displayName: "Capture input is CMPSSB4 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB4_CTRIP_HIGH", displayName: "Capture input is CMPSSB4 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB5_CTRIP_LOW", displayName: "Capture input is CMPSSB5 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB5_CTRIP_HIGH", displayName: "Capture input is CMPSSB5 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB6_CTRIP_LOW", displayName: "Capture input is CMPSSB6 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB6_CTRIP_HIGH", displayName: "Capture input is CMPSSB6 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB7_CTRIP_LOW", displayName: "Capture input is CMPSSB7 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB7_CTRIP_HIGH", displayName: "Capture input is CMPSSB7 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB8_CTRIP_LOW", displayName: "Capture input is CMPSSB8 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB8_CTRIP_HIGH", displayName: "Capture input is CMPSSB8 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB9_CTRIP_LOW", displayName: "Capture input is CMPSSB9 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB9_CTRIP_HIGH", displayName: "Capture input is CMPSSB9 CTRIP_HIGH" },
    { name: "ECAP_INPUT_ADC0_EVT0", displayName: "Capture input is ADC0 Event 0" },
    { name: "ECAP_INPUT_ADC0_EVT1", displayName: "Capture input is ADC0 Event 1" },
    { name: "ECAP_INPUT_ADC0_EVT2", displayName: "Capture input is ADC0 Event 2" },
    { name: "ECAP_INPUT_ADC0_EVT3", displayName: "Capture input is ADC0 Event 3" },
    { name: "ECAP_INPUT_ADC1_EVT0", displayName: "Capture input is ADC1 Event 0" },
    { name: "ECAP_INPUT_ADC1_EVT1", displayName: "Capture input is ADC1 Event 1" },
    { name: "ECAP_INPUT_ADC1_EVT2", displayName: "Capture input is ADC1 Event 2" },
    { name: "ECAP_INPUT_ADC1_EVT3", displayName: "Capture input is ADC1 Event 3" },
    { name: "ECAP_INPUT_ADC2_EVT0", displayName: "Capture input is ADC2 Event 0" },
    { name: "ECAP_INPUT_ADC2_EVT1", displayName: "Capture input is ADC2 Event 1" },
    { name: "ECAP_INPUT_ADC2_EVT2", displayName: "Capture input is ADC2 Event 2" },
    { name: "ECAP_INPUT_ADC2_EVT3", displayName: "Capture input is ADC2 Event 3" },
    { name: "ECAP_INPUT_ADC3_EVT0", displayName: "Capture input is ADC3 Event 0" },
    { name: "ECAP_INPUT_ADC3_EVT1", displayName: "Capture input is ADC3 Event 1" },
    { name: "ECAP_INPUT_ADC3_EVT2", displayName: "Capture input is ADC3 Event 2" },
    { name: "ECAP_INPUT_ADC3_EVT3", displayName: "Capture input is ADC3 Event 3" },
    { name: "ECAP_INPUT_ADC4_EVT0", displayName: "Capture input is ADC4 Event 0" },
    { name: "ECAP_INPUT_ADC4_EVT1", displayName: "Capture input is ADC4 Event 1" },
    { name: "ECAP_INPUT_ADC4_EVT2", displayName: "Capture input is ADC4 Event 2" },
    { name: "ECAP_INPUT_ADC4_EVT3", displayName: "Capture input is ADC4 Event 3" },
    { name: "ECAP_INPUT_INPUTXBAR0", displayName: "Capture input is InputXBar Output 0" },
    { name: "ECAP_INPUT_INPUTXBAR1", displayName: "Capture input is InputXBar Output 1" },
    { name: "ECAP_INPUT_INPUTXBAR2", displayName: "Capture input is InputXBar Output 2" },
    { name: "ECAP_INPUT_INPUTXBAR3", displayName: "Capture input is InputXBar Output 3" },
    { name: "ECAP_INPUT_INPUTXBAR4", displayName: "Capture input is InputXBar Output 4" },
    { name: "ECAP_INPUT_INPUTXBAR5", displayName: "Capture input is InputXBar Output 5" },
    { name: "ECAP_INPUT_INPUTXBAR6", displayName: "Capture input is InputXBar Output 6" },
    { name: "ECAP_INPUT_INPUTXBAR7", displayName: "Capture input is InputXBar Output 7" },
    { name: "ECAP_INPUT_INPUTXBAR8", displayName: "Capture input is InputXBar Output 8" },
    { name: "ECAP_INPUT_INPUTXBAR9", displayName: "Capture input is InputXBar Output 9" },
    { name: "ECAP_INPUT_INPUTXBAR10", displayName: "Capture input is InputXBar Output 10" },
    { name: "ECAP_INPUT_INPUTXBAR11", displayName: "Capture input is InputXBar Output 11" },
    { name: "ECAP_INPUT_INPUTXBAR12", displayName: "Capture input is InputXBar Output 12" },
    { name: "ECAP_INPUT_INPUTXBAR13", displayName: "Capture input is InputXBar Output 13" },
    { name: "ECAP_INPUT_INPUTXBAR14", displayName: "Capture input is InputXBar Output 14" },
    { name: "ECAP_INPUT_INPUTXBAR15", displayName: "Capture input is InputXBar Output 15" },
    { name: "ECAP_INPUT_INPUTXBAR16", displayName: "Capture input is InputXBar Output 16" },
    { name: "ECAP_INPUT_INPUTXBAR17", displayName: "Capture input is InputXBar Output 17" },
    { name: "ECAP_INPUT_INPUTXBAR18", displayName: "Capture input is InputXBar Output 18" },
    { name: "ECAP_INPUT_INPUTXBAR19", displayName: "Capture input is InputXBar Output 19" },
    { name: "ECAP_INPUT_INPUTXBAR20", displayName: "Capture input is InputXBar Output 20" },
    { name: "ECAP_INPUT_INPUTXBAR21", displayName: "Capture input is InputXBar Output 21" },
    { name: "ECAP_INPUT_INPUTXBAR22", displayName: "Capture input is InputXBar Output 22" },
    { name: "ECAP_INPUT_INPUTXBAR23", displayName: "Capture input is InputXBar Output 23" },
    { name: "ECAP_INPUT_INPUTXBAR24", displayName: "Capture input is InputXBar Output 24" },
    { name: "ECAP_INPUT_INPUTXBAR25", displayName: "Capture input is InputXBar Output 25" },
    { name: "ECAP_INPUT_INPUTXBAR26", displayName: "Capture input is InputXBar Output 26" },
    { name: "ECAP_INPUT_INPUTXBAR27", displayName: "Capture input is InputXBar Output 27" },
    { name: "ECAP_INPUT_INPUTXBAR28", displayName: "Capture input is InputXBar Output 28" },
    { name: "ECAP_INPUT_INPUTXBAR29", displayName: "Capture input is InputXBar Output 29" },
    { name: "ECAP_INPUT_INPUTXBAR30", displayName: "Capture input is InputXBar Output 30" },
    { name: "ECAP_INPUT_INPUTXBAR31", displayName: "Capture input is InputXBar Output 31" },
]
let ECAP_SyncInPulseSource = [
	{ name: "ECAP_SYNC_IN_PULSE_SRC_DISABLE", displayName: "Disable Sync-in" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM0", displayName: "Sync-in source is EPWM0 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM1", displayName: "Sync-in source is EPWM1 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM2", displayName: "Sync-in source is EPWM2 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM3", displayName: "Sync-in source is EPWM3 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM4", displayName: "Sync-in source is EPWM4 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM5", displayName: "Sync-in source is EPWM5 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM6", displayName: "Sync-in source is EPWM6 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM7", displayName: "Sync-in source is EPWM7 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM8", displayName: "Sync-in source is EPWM8 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM9", displayName: "Sync-in source is EPWM9 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM10", displayName: "Sync-in source is EPWM10 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM11", displayName: "Sync-in source is EPWM11 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM12", displayName: "Sync-in source is EPWM12 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM13", displayName: "Sync-in source is EPWM13 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM14", displayName: "Sync-in source is EPWM14 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM15", displayName: "Sync-in source is EPWM15 sync-out signal" },
    { name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM16", displayName: "Sync-in source is EPWM16 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM17", displayName: "Sync-in source is EPWM17 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM18", displayName: "Sync-in source is EPWM18 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM19", displayName: "Sync-in source is EPWM19 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM20", displayName: "Sync-in source is EPWM20 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM21", displayName: "Sync-in source is EPWM21 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM22", displayName: "Sync-in source is EPWM22 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM23", displayName: "Sync-in source is EPWM23 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM24", displayName: "Sync-in source is EPWM24 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM25", displayName: "Sync-in source is EPWM25 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM26", displayName: "Sync-in source is EPWM26 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM27", displayName: "Sync-in source is EPWM27 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM28", displayName: "Sync-in source is EPWM28 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM29", displayName: "Sync-in source is EPWM29 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM30", displayName: "Sync-in source is EPWM30 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM31", displayName: "Sync-in source is EPWM31 sync-out signal" },
]
let ECAP_MAX_PRESCALER_VALUE = [
	{ name: "ECAP_MAX_PRESCALER_VALUE", displayName: "Maximum Pre-scaler value" },
]
let ECAP_ISR_SOURCE = [
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_1", displayName: "Event 1 ISR source" },
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_2", displayName: "Event 2 ISR source" },
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_3", displayName: "Event 3 ISR source" },
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_4", displayName: "Event 4 ISR source" },
	{ name: "ECAP_ISR_SOURCE_COUNTER_OVERFLOW", displayName: "Counter overflow ISR source" },
	{ name: "ECAP_ISR_SOURCE_COUNTER_PERIOD", displayName: "Counter equals period ISR source" },
	{ name: "ECAP_ISR_SOURCE_COUNTER_COMPARE", displayName: "Counter equals compare ISR source" },
    { name: "ECAP_ISR_SOURCE_HR_ERROR", displayName: "High Resolution Error ISR source" },
]
exports = {
	ECAP_EmulationMode: ECAP_EmulationMode,
	ECAP_CaptureMode: ECAP_CaptureMode,
	ECAP_Events: ECAP_Events,
	ECAP_SyncOutMode: ECAP_SyncOutMode,
	ECAP_APWMPolarity: ECAP_APWMPolarity,
	ECAP_EventPolarity: ECAP_EventPolarity,
	ECAP_InputCaptureSignals: ECAP_InputCaptureSignals,
	ECAP_SyncInPulseSource: ECAP_SyncInPulseSource,
	ECAP_MAX_PRESCALER_VALUE: ECAP_MAX_PRESCALER_VALUE,
	ECAP_ISR_SOURCE: ECAP_ISR_SOURCE,
}
