let ECAP_EmulationMode = [
	{ name: "ECAP_EMULATION_STOP", displayName: "TSCTR is stopped on emulation suspension" },
	{ name: "ECAP_EMULATION_RUN_TO_ZERO", displayName: "TSCTR runs until 0 before stopping on emulation suspension" },
	{ name: "ECAP_EMULATION_FREE_RUN", displayName: "TSCTR is not affected by emulation suspension" },
]
let ECAP_CaptureMode = [
	{ name: "ECAP_CONTINUOUS_CAPTURE_MODE", displayName: "eCAP operates in continuous capture mode" },
	{ name: "ECAP_ONE_SHOT_CAPTURE_MODE", displayName: "eCAP operates in one shot capture mode" },
]
let ECAP_Events = [
	{ name: "ECAP_EVENT_1", displayName: "eCAP event 1" },
	{ name: "ECAP_EVENT_2", displayName: "eCAP event 2" },
	{ name: "ECAP_EVENT_3", displayName: "eCAP event 3" },
	{ name: "ECAP_EVENT_4", displayName: "eCAP event 4" },
]
let ECAP_SyncOutMode = [
	{ name: "ECAP_SYNC_OUT_SYNCI", displayName: "sync out on the sync in signal and software force" },
	{ name: "ECAP_SYNC_OUT_COUNTER_PRD", displayName: "sync out on counter equals period" },
	{ name: "ECAP_SYNC_OUT_DISABLED", displayName: "Disable sync out signal" },
]
let ECAP_APWMPolarity = [
	{ name: "ECAP_APWM_ACTIVE_HIGH", displayName: "APWM is active high" },
	{ name: "ECAP_APWM_ACTIVE_LOW", displayName: "APWM is active low" },
]
let ECAP_EventPolarity = [
	{ name: "ECAP_EVNT_RISING_EDGE", displayName: "Rising edge polarity" },
	{ name: "ECAP_EVNT_FALLING_EDGE", displayName: "Falling edge polarity" },
]
let ECAP_InputCaptureSignals = [
    { name: "ECAP_INPUT_FSI_RX0_TRIG_0", displayName: "Capture input is FSI_RX0 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX0_TRIG_1", displayName: "Capture input is FSI_RX0 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX0_TRIG_2", displayName: "Capture input is FSI_RX0 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX0_TRIG_3", displayName: "Capture input is FSI_RX0 Trigger 3" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_0", displayName: "Capture input is FSI_RX1 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_1", displayName: "Capture input is FSI_RX1 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_2", displayName: "Capture input is FSI_RX1 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX1_TRIG_3", displayName: "Capture input is FSI_RX1 Trigger 3" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_0", displayName: "Capture input is FSI_RX2 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_1", displayName: "Capture input is FSI_RX2 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_2", displayName: "Capture input is FSI_RX2 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX2_TRIG_3", displayName: "Capture input is FSI_RX2 Trigger 3" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_0", displayName: "Capture input is FSI_RX3 Trigger 0" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_1", displayName: "Capture input is FSI_RX3 Trigger 1" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_2", displayName: "Capture input is FSI_RX3 Trigger 2" },
    { name: "ECAP_INPUT_FSI_RX3_TRIG_3", displayName: "Capture input is FSI_RX3 Trigger 3" },
    { name: "ECAP_INPUT_EQEP0_QI", displayName: "Capture input is EQEP0 QI Signal" },
    { name: "ECAP_INPUT_EQEP0_QS", displayName: "Capture input is EQEP0 QS Signal" },
    { name: "ECAP_INPUT_EQEP1_QI", displayName: "Capture input is EQEP1 QI Signal" },
    { name: "ECAP_INPUT_EQEP1_QS", displayName: "Capture input is EQEP1 QS Signal" },
    { name: "ECAP_INPUT_EQEP2_QI", displayName: "Capture input is EQEP2 QI Signal" },
    { name: "ECAP_INPUT_EQEP2_QS", displayName: "Capture input is EQEP2 QS Signal" },
    { name: "ECAP_INPUT_EPWM0_DELACTIVE", displayName: "Capture input is EPWM0 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM1_DELACTIVE", displayName: "Capture input is EPWM1 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM2_DELACTIVE", displayName: "Capture input is EPWM2 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM3_DELACTIVE", displayName: "Capture input is EPWM3 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM4_DELACTIVE", displayName: "Capture input is EPWM4 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM5_DELACTIVE", displayName: "Capture input is EPWM5 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM6_DELACTIVE", displayName: "Capture input is EPWM6 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM7_DELACTIVE", displayName: "Capture input is EPWM7 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM8_DELACTIVE", displayName: "Capture input is EPWM8 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM9_DELACTIVE", displayName: "Capture input is EPWM9 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM10_DELACTIVE", displayName: "Capture input is EPWM10 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM11_DELACTIVE", displayName: "Capture input is EPWM11 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM12_DELACTIVE", displayName: "Capture input is EPWM12 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM13_DELACTIVE", displayName: "Capture input is EPWM13 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM14_DELACTIVE", displayName: "Capture input is EPWM14 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM15_DELACTIVE", displayName: "Capture input is EPWM15 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM16_DELACTIVE", displayName: "Capture input is EPWM16 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM17_DELACTIVE", displayName: "Capture input is EPWM17 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM18_DELACTIVE", displayName: "Capture input is EPWM18 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM19_DELACTIVE", displayName: "Capture input is EPWM19 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM20_DELACTIVE", displayName: "Capture input is EPWM20 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM21_DELACTIVE", displayName: "Capture input is EPWM21 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM22_DELACTIVE", displayName: "Capture input is EPWM22 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM23_DELACTIVE", displayName: "Capture input is EPWM23 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM24_DELACTIVE", displayName: "Capture input is EPWM24 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM25_DELACTIVE", displayName: "Capture input is EPWM25 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM26_DELACTIVE", displayName: "Capture input is EPWM26 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM27_DELACTIVE", displayName: "Capture input is EPWM27 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM28_DELACTIVE", displayName: "Capture input is EPWM28 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM29_DELACTIVE", displayName: "Capture input is EPWM29 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM30_DELACTIVE", displayName: "Capture input is EPWM30 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM31_DELACTIVE", displayName: "Capture input is EPWM31 DEL ACTIVE Signal" },
    { name: "ECAP_INPUT_EPWM0_SOCA", displayName: "Capture input is EPWM0 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM1_SOCA", displayName: "Capture input is EPWM1 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM2_SOCA", displayName: "Capture input is EPWM2 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM3_SOCA", displayName: "Capture input is EPWM3 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM4_SOCA", displayName: "Capture input is EPWM4 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM5_SOCA", displayName: "Capture input is EPWM5 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM6_SOCA", displayName: "Capture input is EPWM6 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM7_SOCA", displayName: "Capture input is EPWM7 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM8_SOCA", displayName: "Capture input is EPWM8 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM9_SOCA", displayName: "Capture input is EPWM9 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM10_SOCA", displayName: "Capture input is EPWM10 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM11_SOCA", displayName: "Capture input is EPWM11 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM12_SOCA", displayName: "Capture input is EPWM12 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM13_SOCA", displayName: "Capture input is EPWM13 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM14_SOCA", displayName: "Capture input is EPWM14 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM15_SOCA", displayName: "Capture input is EPWM15 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM16_SOCA", displayName: "Capture input is EPWM16 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM17_SOCA", displayName: "Capture input is EPWM17 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM18_SOCA", displayName: "Capture input is EPWM18 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM19_SOCA", displayName: "Capture input is EPWM19 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM20_SOCA", displayName: "Capture input is EPWM20 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM21_SOCA", displayName: "Capture input is EPWM21 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM22_SOCA", displayName: "Capture input is EPWM22 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM23_SOCA", displayName: "Capture input is EPWM23 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM24_SOCA", displayName: "Capture input is EPWM24 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM25_SOCA", displayName: "Capture input is EPWM25 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM26_SOCA", displayName: "Capture input is EPWM26 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM27_SOCA", displayName: "Capture input is EPWM27 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM28_SOCA", displayName: "Capture input is EPWM28 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM29_SOCA", displayName: "Capture input is EPWM29 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM30_SOCA", displayName: "Capture input is EPWM30 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM31_SOCA", displayName: "Capture input is EPWM31 SOC-A Signal" },
    { name: "ECAP_INPUT_EPWM0_SOCB", displayName: "Capture input is EPWM0 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM1_SOCB", displayName: "Capture input is EPWM1 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM2_SOCB", displayName: "Capture input is EPWM2 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM3_SOCB", displayName: "Capture input is EPWM3 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM4_SOCB", displayName: "Capture input is EPWM4 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM5_SOCB", displayName: "Capture input is EPWM5 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM6_SOCB", displayName: "Capture input is EPWM6 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM7_SOCB", displayName: "Capture input is EPWM7 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM8_SOCB", displayName: "Capture input is EPWM8 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM9_SOCB", displayName: "Capture input is EPWM9 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM10_SOCB", displayName: "Capture input is EPWM10 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM11_SOCB", displayName: "Capture input is EPWM11 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM12_SOCB", displayName: "Capture input is EPWM12 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM13_SOCB", displayName: "Capture input is EPWM13 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM14_SOCB", displayName: "Capture input is EPWM14 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM15_SOCB", displayName: "Capture input is EPWM15 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM16_SOCB", displayName: "Capture input is EPWM16 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM17_SOCB", displayName: "Capture input is EPWM17 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM18_SOCB", displayName: "Capture input is EPWM18 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM19_SOCB", displayName: "Capture input is EPWM19 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM20_SOCB", displayName: "Capture input is EPWM20 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM21_SOCB", displayName: "Capture input is EPWM21 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM22_SOCB", displayName: "Capture input is EPWM22 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM23_SOCB", displayName: "Capture input is EPWM23 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM24_SOCB", displayName: "Capture input is EPWM24 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM25_SOCB", displayName: "Capture input is EPWM25 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM26_SOCB", displayName: "Capture input is EPWM26 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM27_SOCB", displayName: "Capture input is EPWM27 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM28_SOCB", displayName: "Capture input is EPWM28 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM29_SOCB", displayName: "Capture input is EPWM29 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM30_SOCB", displayName: "Capture input is EPWM30 SOC-B Signal" },
    { name: "ECAP_INPUT_EPWM31_SOCB", displayName: "Capture input is EPWM31 SOC-B Signal" },
    { name: "ECAP_INPUT_SDFM0_COMPARE1_HIGH", displayName: "Capture input is SDFM0 Compare1 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE1_LOW", displayName: "Capture input is SDFM0 Compare1 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z1", displayName: "Capture input is SDFM0 Compare Z1" },
    { name: "ECAP_INPUT_SDFM0_COMPARE2_HIGH", displayName: "Capture input is SDFM0 Compare2 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE2_LOW", displayName: "Capture input is SDFM0 Compare2 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z2", displayName: "Capture input is SDFM0 Compare Z2" },
    { name: "ECAP_INPUT_SDFM0_COMPARE3_HIGH", displayName: "Capture input is SDFM0 Compare3 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE3_LOW", displayName: "Capture input is SDFM0 Compare3 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z3", displayName: "Capture input is SDFM0 Compare Z3" },
    { name: "ECAP_INPUT_SDFM0_COMPARE4_HIGH", displayName: "Capture input is SDFM0 Compare4 High" },
    { name: "ECAP_INPUT_SDFM0_COMPARE4_LOW", displayName: "Capture input is SDFM0 Compare4 Low" },
    { name: "ECAP_INPUT_SDFM0_COMPARE_Z4", displayName: "Capture input is SDFM0 Compare Z4" },
    { name: "ECAP_INPUT_SDFM1_COMPARE1_HIGH", displayName: "Capture input is SDFM1 Compare1 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE1_LOW", displayName: "Capture input is SDFM1 Compare1 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z1", displayName: "Capture input is SDFM1 Compare Z1" },
    { name: "ECAP_INPUT_SDFM1_COMPARE2_HIGH", displayName: "Capture input is SDFM1 Compare2 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE2_LOW", displayName: "Capture input is SDFM1 Compare2 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z2", displayName: "Capture input is SDFM1 Compare Z2" },
    { name: "ECAP_INPUT_SDFM1_COMPARE3_HIGH", displayName: "Capture input is SDFM1 Compare3 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE3_LOW", displayName: "Capture input is SDFM1 Compare3 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z3", displayName: "Capture input is SDFM1 Compare Z3" },
    { name: "ECAP_INPUT_SDFM1_COMPARE4_HIGH", displayName: "Capture input is SDFM1 Compare4 High" },
    { name: "ECAP_INPUT_SDFM1_COMPARE4_LOW", displayName: "Capture input is SDFM1 Compare4 Low" },
    { name: "ECAP_INPUT_SDFM1_COMPARE_Z4", displayName: "Capture input is SDFM1 Compare Z4" },
    { name: "ECAP_INPUT_CMPSSA0_CTRIP_LOW", displayName: "Capture input is CMPSSA0 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA0_CTRIP_HIGH", displayName: "Capture input is CMPSSA0 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA1_CTRIP_LOW", displayName: "Capture input is CMPSSA1 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA1_CTRIP_HIGH", displayName: "Capture input is CMPSSA1 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA2_CTRIP_LOW", displayName: "Capture input is CMPSSA2 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA2_CTRIP_HIGH", displayName: "Capture input is CMPSSA2 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA3_CTRIP_LOW", displayName: "Capture input is CMPSSA3 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA3_CTRIP_HIGH", displayName: "Capture input is CMPSSA3 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA4_CTRIP_LOW", displayName: "Capture input is CMPSSA4 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA4_CTRIP_HIGH", displayName: "Capture input is CMPSSA4 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA5_CTRIP_LOW", displayName: "Capture input is CMPSSA5 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA5_CTRIP_HIGH", displayName: "Capture input is CMPSSA5 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA6_CTRIP_LOW", displayName: "Capture input is CMPSSA6 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA6_CTRIP_HIGH", displayName: "Capture input is CMPSSA6 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA7_CTRIP_LOW", displayName: "Capture input is CMPSSA7 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA7_CTRIP_HIGH", displayName: "Capture input is CMPSSA7 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA8_CTRIP_LOW", displayName: "Capture input is CMPSSA8 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA8_CTRIP_HIGH", displayName: "Capture input is CMPSSA8 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSA9_CTRIP_LOW", displayName: "Capture input is CMPSSA9 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSA9_CTRIP_HIGH", displayName: "Capture input is CMPSSA9 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB0_CTRIP_LOW", displayName: "Capture input is CMPSSB0 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB0_CTRIP_HIGH", displayName: "Capture input is CMPSSB0 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB1_CTRIP_LOW", displayName: "Capture input is CMPSSB1 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB1_CTRIP_HIGH", displayName: "Capture input is CMPSSB1 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB2_CTRIP_LOW", displayName: "Capture input is CMPSSB2 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB2_CTRIP_HIGH", displayName: "Capture input is CMPSSB2 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB3_CTRIP_LOW", displayName: "Capture input is CMPSSB3 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB3_CTRIP_HIGH", displayName: "Capture input is CMPSSB3 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB4_CTRIP_LOW", displayName: "Capture input is CMPSSB4 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB4_CTRIP_HIGH", displayName: "Capture input is CMPSSB4 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB5_CTRIP_LOW", displayName: "Capture input is CMPSSB5 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB5_CTRIP_HIGH", displayName: "Capture input is CMPSSB5 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB6_CTRIP_LOW", displayName: "Capture input is CMPSSB6 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB6_CTRIP_HIGH", displayName: "Capture input is CMPSSB6 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB7_CTRIP_LOW", displayName: "Capture input is CMPSSB7 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB7_CTRIP_HIGH", displayName: "Capture input is CMPSSB7 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB8_CTRIP_LOW", displayName: "Capture input is CMPSSB8 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB8_CTRIP_HIGH", displayName: "Capture input is CMPSSB8 CTRIP_HIGH" },
    { name: "ECAP_INPUT_CMPSSB9_CTRIP_LOW", displayName: "Capture input is CMPSSB9 CTRIP_LOW" },
    { name: "ECAP_INPUT_CMPSSB9_CTRIP_HIGH", displayName: "Capture input is CMPSSB9 CTRIP_HIGH" },
    { name: "ECAP_INPUT_ADC0_EVT0", displayName: "Capture input is ADC0 Event 0" },
    { name: "ECAP_INPUT_ADC0_EVT1", displayName: "Capture input is ADC0 Event 1" },
    { name: "ECAP_INPUT_ADC0_EVT2", displayName: "Capture input is ADC0 Event 2" },
    { name: "ECAP_INPUT_ADC0_EVT3", displayName: "Capture input is ADC0 Event 3" },
    { name: "ECAP_INPUT_ADC1_EVT0", displayName: "Capture input is ADC1 Event 0" },
    { name: "ECAP_INPUT_ADC1_EVT1", displayName: "Capture input is ADC1 Event 1" },
    { name: "ECAP_INPUT_ADC1_EVT2", displayName: "Capture input is ADC1 Event 2" },
    { name: "ECAP_INPUT_ADC1_EVT3", displayName: "Capture input is ADC1 Event 3" },
    { name: "ECAP_INPUT_ADC2_EVT0", displayName: "Capture input is ADC2 Event 0" },
    { name: "ECAP_INPUT_ADC2_EVT1", displayName: "Capture input is ADC2 Event 1" },
    { name: "ECAP_INPUT_ADC2_EVT2", displayName: "Capture input is ADC2 Event 2" },
    { name: "ECAP_INPUT_ADC2_EVT3", displayName: "Capture input is ADC2 Event 3" },
    { name: "ECAP_INPUT_ADC3_EVT0", displayName: "Capture input is ADC3 Event 0" },
    { name: "ECAP_INPUT_ADC3_EVT1", displayName: "Capture input is ADC3 Event 1" },
    { name: "ECAP_INPUT_ADC3_EVT2", displayName: "Capture input is ADC3 Event 2" },
    { name: "ECAP_INPUT_ADC3_EVT3", displayName: "Capture input is ADC3 Event 3" },
    { name: "ECAP_INPUT_ADC4_EVT0", displayName: "Capture input is ADC4 Event 0" },
    { name: "ECAP_INPUT_ADC4_EVT1", displayName: "Capture input is ADC4 Event 1" },
    { name: "ECAP_INPUT_ADC4_EVT2", displayName: "Capture input is ADC4 Event 2" },
    { name: "ECAP_INPUT_ADC4_EVT3", displayName: "Capture input is ADC4 Event 3" },
    { name: "ECAP_INPUT_INPUTXBAR0", displayName: "Capture input is InputXBar Output 0" },
    { name: "ECAP_INPUT_INPUTXBAR1", displayName: "Capture input is InputXBar Output 1" },
    { name: "ECAP_INPUT_INPUTXBAR2", displayName: "Capture input is InputXBar Output 2" },
    { name: "ECAP_INPUT_INPUTXBAR3", displayName: "Capture input is InputXBar Output 3" },
    { name: "ECAP_INPUT_INPUTXBAR4", displayName: "Capture input is InputXBar Output 4" },
    { name: "ECAP_INPUT_INPUTXBAR5", displayName: "Capture input is InputXBar Output 5" },
    { name: "ECAP_INPUT_INPUTXBAR6", displayName: "Capture input is InputXBar Output 6" },
    { name: "ECAP_INPUT_INPUTXBAR7", displayName: "Capture input is InputXBar Output 7" },
    { name: "ECAP_INPUT_INPUTXBAR8", displayName: "Capture input is InputXBar Output 8" },
    { name: "ECAP_INPUT_INPUTXBAR9", displayName: "Capture input is InputXBar Output 9" },
    { name: "ECAP_INPUT_INPUTXBAR10", displayName: "Capture input is InputXBar Output 10" },
    { name: "ECAP_INPUT_INPUTXBAR11", displayName: "Capture input is InputXBar Output 11" },
    { name: "ECAP_INPUT_INPUTXBAR12", displayName: "Capture input is InputXBar Output 12" },
    { name: "ECAP_INPUT_INPUTXBAR13", displayName: "Capture input is InputXBar Output 13" },
    { name: "ECAP_INPUT_INPUTXBAR14", displayName: "Capture input is InputXBar Output 14" },
    { name: "ECAP_INPUT_INPUTXBAR15", displayName: "Capture input is InputXBar Output 15" },
    { name: "ECAP_INPUT_INPUTXBAR16", displayName: "Capture input is InputXBar Output 16" },
    { name: "ECAP_INPUT_INPUTXBAR17", displayName: "Capture input is InputXBar Output 17" },
    { name: "ECAP_INPUT_INPUTXBAR18", displayName: "Capture input is InputXBar Output 18" },
    { name: "ECAP_INPUT_INPUTXBAR19", displayName: "Capture input is InputXBar Output 19" },
    { name: "ECAP_INPUT_INPUTXBAR20", displayName: "Capture input is InputXBar Output 20" },
    { name: "ECAP_INPUT_INPUTXBAR21", displayName: "Capture input is InputXBar Output 21" },
    { name: "ECAP_INPUT_INPUTXBAR22", displayName: "Capture input is InputXBar Output 22" },
    { name: "ECAP_INPUT_INPUTXBAR23", displayName: "Capture input is InputXBar Output 23" },
    { name: "ECAP_INPUT_INPUTXBAR24", displayName: "Capture input is InputXBar Output 24" },
    { name: "ECAP_INPUT_INPUTXBAR25", displayName: "Capture input is InputXBar Output 25" },
    { name: "ECAP_INPUT_INPUTXBAR26", displayName: "Capture input is InputXBar Output 26" },
    { name: "ECAP_INPUT_INPUTXBAR27", displayName: "Capture input is InputXBar Output 27" },
    { name: "ECAP_INPUT_INPUTXBAR28", displayName: "Capture input is InputXBar Output 28" },
    { name: "ECAP_INPUT_INPUTXBAR29", displayName: "Capture input is InputXBar Output 29" },
    { name: "ECAP_INPUT_INPUTXBAR30", displayName: "Capture input is InputXBar Output 30" },
    { name: "ECAP_INPUT_INPUTXBAR31", displayName: "Capture input is InputXBar Output 31" },
]
let ECAP_SyncInPulseSource = [
	{ name: "ECAP_SYNC_IN_PULSE_SRC_DISABLE", displayName: "Disable Sync-in" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM0", displayName: "Sync-in source is EPWM0 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM1", displayName: "Sync-in source is EPWM1 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM2", displayName: "Sync-in source is EPWM2 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM3", displayName: "Sync-in source is EPWM3 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM4", displayName: "Sync-in source is EPWM4 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM5", displayName: "Sync-in source is EPWM5 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM6", displayName: "Sync-in source is EPWM6 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM7", displayName: "Sync-in source is EPWM7 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM8", displayName: "Sync-in source is EPWM8 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM9", displayName: "Sync-in source is EPWM9 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM10", displayName: "Sync-in source is EPWM10 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM11", displayName: "Sync-in source is EPWM11 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM12", displayName: "Sync-in source is EPWM12 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM13", displayName: "Sync-in source is EPWM13 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM14", displayName: "Sync-in source is EPWM14 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM15", displayName: "Sync-in source is EPWM15 sync-out signal" },
    { name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM16", displayName: "Sync-in source is EPWM16 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM17", displayName: "Sync-in source is EPWM17 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM18", displayName: "Sync-in source is EPWM18 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM19", displayName: "Sync-in source is EPWM19 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM20", displayName: "Sync-in source is EPWM20 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM21", displayName: "Sync-in source is EPWM21 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM22", displayName: "Sync-in source is EPWM22 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM23", displayName: "Sync-in source is EPWM23 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM24", displayName: "Sync-in source is EPWM24 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM25", displayName: "Sync-in source is EPWM25 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM26", displayName: "Sync-in source is EPWM26 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM27", displayName: "Sync-in source is EPWM27 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM28", displayName: "Sync-in source is EPWM28 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM29", displayName: "Sync-in source is EPWM29 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM30", displayName: "Sync-in source is EPWM30 sync-out signal" },
	{ name: "ECAP_SYNC_IN_PULSE_SRC_SYNCOUT_EPWM31", displayName: "Sync-in source is EPWM31 sync-out signal" },
]
let ECAP_DMA_TRIGGER_SOURCE =[
    { name: "ECAP_CAP_MODE_DMA_TRIGGER_SRC_CEVT1", displayName: "DMA trigger source is eCAP event 1"},
    { name: "ECAP_CAP_MODE_DMA_TRIGGER_SRC_CEVT2", displayName: "DMA trigger source is eCAP event 2"},
    { name: "ECAP_CAP_MODE_DMA_TRIGGER_SRC_CEVT3", displayName: "DMA trigger source is eCAP event 3"},
    { name: "ECAP_CAP_MODE_DMA_TRIGGER_SRC_CEVT4", displayName: "DMA trigger source is eCAP event 4"},
    { name: "ECAP_APWM_MODE_DMA_TRIGGER_SRC_PRD", displayName: "DMA trigger source is eCAP Period match"  },
    { name: "ECAP_APWM_MODE_DMA_TRIGGER_SRC_CMP", displayName: "DMA trigger source is eCAP Compare match" },
    { name: "ECAP_APWM_MODE_DMA_TRIGGER_SRC_PRD_CMP", displayName: "DMA trigger source is eCAP Period or Compare match"},
    { name: "ECAP_APWM_MODE_DMA_TRIGGER_SRC_DISABLED", displayName: "DMA trigger source is Disabled" },
]
let ECAP_ADC_TRIGGER_SOURCE =[
    { name: "ECAP_CAP_MODE_SOC_TRIGGER_SRC_CEVT1", displayName: "ADC SOC trigger source is eCAP event 1"},
    { name: "ECAP_CAP_MODE_SOC_TRIGGER_SRC_CEVT2", displayName: "ADC SOC trigger source is eCAP event 2"},
    { name: "ECAP_CAP_MODE_SOC_TRIGGER_SRC_CEVT3", displayName: "ADC SOC trigger source is eCAP event 3"},
    { name: "ECAP_CAP_MODE_SOC_TRIGGER_SRC_CEVT4", displayName: "ADC SOC trigger source is eCAP event 4"},
    { name: "ECAP_APWM_MODE_SOC_TRIGGER_SRC_PRD", displayName: "ADC SOC trigger source is eCAP Period match"  },
    { name: "ECAP_APWM_MODE_SOC_TRIGGER_SRC_CMP", displayName: "ADC SOC trigger source is eCAP Compare match" },
    { name: "ECAP_APWM_MODE_SOC_TRIGGER_SRC_PRD_CMP", displayName: "ADC SOC trigger source is eCAP Period or Compare match"},
    { name: "ECAP_APWM_MODE_SOC_TRIGGER_SRC_DISABLED", displayName: "ADC SOC trigger source is Disabled" },
]
let ECAP_MAX_PRESCALER_VALUE = [
	{ name: "ECAP_MAX_PRESCALER_VALUE", displayName: "Maximum Pre-scaler value" },
]
let ECAP_ISR_SOURCE = [
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_1", displayName: "Event 1 ISR source" },
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_2", displayName: "Event 2 ISR source" },
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_3", displayName: "Event 3 ISR source" },
	{ name: "ECAP_ISR_SOURCE_CAPTURE_EVENT_4", displayName: "Event 4 ISR source" },
	{ name: "ECAP_ISR_SOURCE_COUNTER_OVERFLOW", displayName: "Counter overflow ISR source" },
	{ name: "ECAP_ISR_SOURCE_COUNTER_PERIOD", displayName: "Counter equals period ISR source" },
	{ name: "ECAP_ISR_SOURCE_COUNTER_COMPARE", displayName: "Counter equals compare ISR source" },
]
let ECAP_QualPeriodSelect = [
    { name: "ECAP_PULSE_WIDTH_FILTER_BYPASS", displayName: "ECAP PULSE WIDTH FILTER BYPASS" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE1", displayName: "ECAP PULSE WIDTH FILTER CYCLE1" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE2", displayName: "ECAP PULSE WIDTH FILTER CYCLE2" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE3", displayName: "ECAP PULSE WIDTH FILTER CYCLE3" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE4", displayName: "ECAP PULSE WIDTH FILTER CYCLE4" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE5", displayName: "ECAP PULSE WIDTH FILTER CYCLE5" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE6", displayName: "ECAP PULSE WIDTH FILTER CYCLE6" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE7", displayName: "ECAP PULSE WIDTH FILTER CYCLE7" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE8", displayName: "ECAP PULSE WIDTH FILTER CYCLE8" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE9", displayName: "ECAP PULSE WIDTH FILTER CYCLE9" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE10", displayName: "ECAP PULSE WIDTH FILTER CYCLE10" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE11", displayName: "ECAP PULSE WIDTH FILTER CYCLE11" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE12", displayName: "ECAP PULSE WIDTH FILTER CYCLE12" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE13", displayName: "ECAP PULSE WIDTH FILTER CYCLE13" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE14", displayName: "ECAP PULSE WIDTH FILTER CYCLE14" },
    { name: "ECAP_PULSE_WIDTH_FILTER_CYCLE15", displayName: "ECAP PULSE WIDTH FILTER CYCLE15" },
]
let ECAP_Monitoring_Unit = [
    { name: "ECAP_MONITORING_UNIT_1", displayName: "ECAP MONITORING UNIT 1" },
    { name: "ECAP_MONITORING_UNIT_2", displayName: "ECAP MONITORING UNIT 2" },
]
let ECAP_MunitTripInputSelect = [
	{ name: "ECAP_MUNIT_TRIP_DISABLED", displayName: "Disabled" },
	{ name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT0", displayName: "PWM XBAR OUT0" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT1", displayName: "PWM XBAR OUT1" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT2", displayName: "PWM XBAR OUT2" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT3", displayName: "PWM XBAR OUT3" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT4", displayName: "PWM XBAR OUT4" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT5", displayName: "PWM XBAR OUT5" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT6", displayName: "PWM XBAR OUT6" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT7", displayName: "PWM XBAR OUT7" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT8", displayName: "PWM XBAR OUT8" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT9", displayName: "PWM XBAR OUT9" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT10", displayName: "PWM XBAR OUT10" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT11", displayName: "PWM XBAR OUT11" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT12", displayName: "PWM XBAR OUT12" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT13", displayName: "PWM XBAR OUT13" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT14", displayName: "PWM XBAR OUT14" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT15", displayName: "PWM XBAR OUT15" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT16", displayName: "PWM XBAR OUT16" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT17", displayName: "PWM XBAR OUT17" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT18", displayName: "PWM XBAR OUT18" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT19", displayName: "PWM XBAR OUT19" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT20", displayName: "PWM XBAR OUT20" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT21", displayName: "PWM XBAR OUT21" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT22", displayName: "PWM XBAR OUT22" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT23", displayName: "PWM XBAR OUT23" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT24", displayName: "PWM XBAR OUT24" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT25", displayName: "PWM XBAR OUT25" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT26", displayName: "PWM XBAR OUT26" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT27", displayName: "PWM XBAR OUT27" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT28", displayName: "PWM XBAR OUT28" },
    { name: "ECAP_MUNIT_TRIP_EPWM_XBAR_OUT29", displayName: "PWM XBAR OUT29" },
    { name: "ECAP_MUNIT_TRIP_EPWM0_TRIPOUT", displayName: "EPWM0 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM1_TRIPOUT", displayName: "EPWM1 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM2_TRIPOUT", displayName: "EPWM2 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM3_TRIPOUT", displayName: "EPWM3 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM4_TRIPOUT", displayName: "EPWM4 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM5_TRIPOUT", displayName: "EPWM5 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM6_TRIPOUT", displayName: "EPWM6 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM7_TRIPOUT", displayName: "EPWM7 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM8_TRIPOUT", displayName: "EPWM8 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM9_TRIPOUT", displayName: "EPWM9 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM10_TRIPOUT", displayName: "EPWM10 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM11_TRIPOUT", displayName: "EPWM11 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM12_TRIPOUT", displayName: "EPWM12 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM13_TRIPOUT", displayName: "EPWM13 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM14_TRIPOUT", displayName: "EPWM14 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM15_TRIPOUT", displayName: "EPWM15 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM16_TRIPOUT", displayName: "EPWM16 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM17_TRIPOUT", displayName: "EPWM17 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM18_TRIPOUT", displayName: "EPWM18 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM19_TRIPOUT", displayName: "EPWM19 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM20_TRIPOUT", displayName: "EPWM20 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM21_TRIPOUT", displayName: "EPWM21 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM22_TRIPOUT", displayName: "EPWM22 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM23_TRIPOUT", displayName: "EPWM23 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM24_TRIPOUT", displayName: "EPWM24 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM25_TRIPOUT", displayName: "EPWM25 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM26_TRIPOUT", displayName: "EPWM26 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM27_TRIPOUT", displayName: "EPWM27 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM28_TRIPOUT", displayName: "EPWM28 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM29_TRIPOUT", displayName: "EPWM29 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM30_TRIPOUT", displayName: "EPWM30 TRIPOUT" },
    { name: "ECAP_MUNIT_TRIP_EPWM31_TRIPOUT", displayName: "EPWM31 TRIPOUT" },
]
let ECAP_MunitGlobalStrobeSelect = [
	{ name: "ECAP_MUNIT_GLDSTRB_DISABLED", displayName: "Disabled" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM0", displayName: "EPWM0 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM1", displayName: "EPWM1 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM2", displayName: "EPWM2 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM3", displayName: "EPWM3 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM4", displayName: "EPWM4 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM5", displayName: "EPWM5 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM6", displayName: "EPWM6 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM7", displayName: "EPWM7 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM8", displayName: "EPWM8 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM9", displayName: "EPWM9 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM10", displayName: "EPWM10 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM11", displayName: "EPWM11 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM12", displayName: "EPWM12 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM13", displayName: "EPWM13 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM14", displayName: "EPWM14 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM15", displayName: "EPWM15 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM16", displayName: "EPWM16 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM17", displayName: "EPWM17 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM18", displayName: "EPWM18 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM19", displayName: "EPWM19 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM20", displayName: "EPWM20 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM21", displayName: "EPWM21 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM22", displayName: "EPWM22 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM23", displayName: "EPWM23 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM24", displayName: "EPWM24 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM25", displayName: "EPWM25 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM26", displayName: "EPWM26 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM27", displayName: "EPWM27 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM28", displayName: "EPWM28 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM29", displayName: "EPWM29 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM30", displayName: "EPWM30 GLOBAL LOAD STROBE" },
    { name: "ECAP_MUNIT_GLDSTRB_EPWM31", displayName: "EPWM31 GLOBAL LOAD STROBE" },
]
let ECAP_MonitoringTypeSelect = [
    { name: "ECAP_MUNIT_HIGH_PULSE_WIDTH", displayName: "High Pulse Width" },
    { name: "ECAP_MUNIT_LOW_PULSE_WIDTH", displayName: "Low Pulse Width" },
    { name: "ECAP_MUNIT_PERIOD_WIDTH_RISE_RISE", displayName: "Period width from rise to rise" },
    { name: "ECAP_MUNIT_PERIOD_WIDTH_FALL_FALL", displayName: "Period width from fall to fall" },
    { name: "ECAP_MUNIT_MONITOR_RISE_EDGE", displayName: "Monitor rise edge" },
    { name: "ECAP_MUNIT_MONITOR_FALL_EDGE", displayName: "Monitor fall edge" },
]
let ECAP_MunitloadMode = [
    { name: "ECAP_ACTIVE_LOAD_SYNC_EVT", displayName: "Load On Next Sync Event" },
    { name: "ECAP_ACTIVE_LOAD_GLDLCSTRB_EVT", displayName: "Load On EPWM GLDLCSTRB Event" }
]

let ECAP_INSTANCE = [
    { name: "CSL_CONTROLSS_ECAP0_U_BASE", displayName: "ECAP0"},
    { name: "CSL_CONTROLSS_ECAP1_U_BASE", displayName: "ECAP1"},
    { name: "CSL_CONTROLSS_ECAP2_U_BASE", displayName: "ECAP2"},
    { name: "CSL_CONTROLSS_ECAP3_U_BASE", displayName: "ECAP3"},
    { name: "CSL_CONTROLSS_ECAP4_U_BASE", displayName: "ECAP4"},
    { name: "CSL_CONTROLSS_ECAP5_U_BASE", displayName: "ECAP5"},
    { name: "CSL_CONTROLSS_ECAP6_U_BASE", displayName: "ECAP6"},
    { name: "CSL_CONTROLSS_ECAP7_U_BASE", displayName: "ECAP7"},
    { name: "CSL_CONTROLSS_ECAP8_U_BASE", displayName: "ECAP8"},
    { name: "CSL_CONTROLSS_ECAP9_U_BASE", displayName: "ECAP9"},
    { name: "CSL_CONTROLSS_ECAP10_U_BASE", displayName: "ECAP10"},
    { name: "CSL_CONTROLSS_ECAP11_U_BASE", displayName: "ECAP11"},
    { name: "CSL_CONTROLSS_ECAP12_U_BASE", displayName: "ECAP12"},
    { name: "CSL_CONTROLSS_ECAP13_U_BASE", displayName: "ECAP13"},
    { name: "CSL_CONTROLSS_ECAP14_U_BASE", displayName: "ECAP14"},
    { name: "CSL_CONTROLSS_ECAP15_U_BASE", displayName: "ECAP15"},
]

let numberOfECAPs = ECAP_INSTANCE.length;

exports = {
	ECAP_EmulationMode: ECAP_EmulationMode,
	ECAP_CaptureMode: ECAP_CaptureMode,
	ECAP_Events: ECAP_Events,
	ECAP_SyncOutMode: ECAP_SyncOutMode,
	ECAP_APWMPolarity: ECAP_APWMPolarity,
	ECAP_EventPolarity: ECAP_EventPolarity,
	ECAP_InputCaptureSignals: ECAP_InputCaptureSignals,
	ECAP_SyncInPulseSource: ECAP_SyncInPulseSource,
    ECAP_DMA_TRIGGER_SOURCE: ECAP_DMA_TRIGGER_SOURCE,
    ECAP_ADC_TRIGGER_SOURCE: ECAP_ADC_TRIGGER_SOURCE,
	ECAP_MAX_PRESCALER_VALUE: ECAP_MAX_PRESCALER_VALUE,
	ECAP_ISR_SOURCE: ECAP_ISR_SOURCE,
    ECAP_QualPeriodSelect:ECAP_QualPeriodSelect,
    ECAP_Monitoring_Unit: ECAP_Monitoring_Unit,
    ECAP_MunitTripInputSelect:ECAP_MunitTripInputSelect,
    ECAP_MunitGlobalStrobeSelect: ECAP_MunitGlobalStrobeSelect,
    ECAP_MonitoringTypeSelect: ECAP_MonitoringTypeSelect,
    ECAP_MunitloadMode: ECAP_MunitloadMode,
    ECAP_INSTANCE: ECAP_INSTANCE,
    numberOfECAPs : numberOfECAPs,
}
