#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am65x libs
	$(MAKE) -f makefile.am65x sbl
	$(MAKE) -f makefile.am65x examples


clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am65x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am65x all
	@echo  $(MAKE) -s -f makefile.am65x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am65x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am65x libs
	@echo  $(MAKE) -s -f makefile.am65x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am65x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am65x examples
	@echo  $(MAKE) -s -f makefile.am65x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am65x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am65x unity_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am65x doxy_samples_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am65x unity_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am65x doxy_samples_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C drivers/gpio/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/mmcsd/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  $(MAKE) -s -C drivers/ipc_notify/am65x-idk/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ipc_rpmsg/am65x-idk/system_freertos [all clean syscfg-gui syscfg]
	@echo  .

# Various Component Targets
BUILD_COMBO_unity = unity_r5f.ti-arm-clang
BUILD_COMBO_doxy_samples = doxy_samples_r5f.ti-arm-clang


# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_unity) $(BUILD_COMBO_doxy_samples)


# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =


# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)


$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.am65x.$(subst unity_,,$@) all

$(BUILD_COMBO_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am65x.$(subst doxy_samples_,,$@) all



# Various Component Clean Targets
BUILD_COMBO_CLEAN_unity = unity_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_doxy_samples = doxy_samples_r5f.ti-arm-clang_clean


# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_unity) $(BUILD_COMBO_CLEAN_doxy_samples)


# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =


libs-clean: $(BUILD_COMBO_CLEAN_ALL)
libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)


$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.am65x.$(subst unity_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am65x.$(subst doxy_samples_,,$(subst _clean,,$@)) clean



# Various Component Scrub Targets
BUILD_COMBO_SCRUB_unity = unity_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_doxy_samples = doxy_samples_r5f.ti-arm-clang_scrub_scrub


# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_unity) $(BUILD_COMBO_SCRUB_doxy_samples)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =


libs-scrub: $(BUILD_COMBO_SCRUB_ALL)
libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)


$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.am65x.$(subst unity_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am65x.$(subst doxy_samples_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am65x-idk_r5fss0-0_freertos_ti-arm-clang

# Various System Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_ipc_notify_am65x-idk_system_freertos
BUILD_COMBO_EXAMPLE_ALL += test_ipc_rpmsg_am65x-idk_system_freertos



BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets


examples: $(BUILD_COMBO_EXAMPLE_ALL)



examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 test_gpio_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_i2c_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_mmcsd_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/mmcsd/mmcsd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_sciclient_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_ipc_notify_am65x-idk_system_freertos:
	$(MAKE) -C drivers/ipc_notify/am65x-idk/system_freertos -f makefile all

 test_ipc_rpmsg_am65x-idk_system_freertos:
	$(MAKE) -C drivers/ipc_rpmsg/am65x-idk/system_freertos -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ipc_notify_am65x-idk_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ipc_rpmsg_am65x-idk_system_freertos_clean


BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 test_gpio_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_i2c_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_mmcsd_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/mmcsd/mmcsd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_sciclient_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_ipc_notify_am65x-idk_system_freertos_clean:
	$(MAKE) -C drivers/ipc_notify/am65x-idk/system_freertos -f makefile clean

 test_ipc_rpmsg_am65x-idk_system_freertos_clean:
	$(MAKE) -C drivers/ipc_rpmsg/am65x-idk/system_freertos -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ipc_notify_am65x-idk_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ipc_rpmsg_am65x-idk_system_freertos_scrub


BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 test_gpio_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_i2c_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_mmcsd_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/mmcsd/mmcsd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_sciclient_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_ipc_notify_am65x-idk_system_freertos_scrub:
	$(MAKE) -C drivers/ipc_notify/am65x-idk/system_freertos -f makefile scrub

 test_ipc_rpmsg_am65x-idk_system_freertos_scrub:
	$(MAKE) -C drivers/ipc_rpmsg/am65x-idk/system_freertos -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:




.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)