#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am263px libs
	$(MAKE) -f makefile.am263px sbl
	$(MAKE) -f makefile.am263px examples

clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px all
	@echo  $(MAKE) -s -f makefile.am263px clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px libs
	@echo  $(MAKE) -s -f makefile.am263px libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px examples
	@echo  $(MAKE) -s -f makefile.am263px examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px unity_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px unity_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C board/eeprom/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C board/eeprom/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C board/led/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C board/led/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/boot/boot_testapp_mb/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/boot/boot_testapp_mb/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/edma/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/edma/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/lin/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/lin/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  $(MAKE) -s -C drivers/mcspi/mcspi_controller_peripheral/am263px-cc/system_freertos_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mcspi/mcspi_controller_peripheral/am263px-lp/system_freertos_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-cc/system_freertos_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-lp/system_freertos_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/soc/soc_r5f/am263px-cc/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/soc/soc_r5f/am263px-lp/system_freertos [all clean syscfg-gui syscfg]
	@echo  .

# Various Component Targets
BUILD_COMBO_unity = unity_r5f.ti-arm-clang

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_unity)

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.am263px.$(subst unity_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_unity = unity_r5f.ti-arm-clang_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_unity)

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.am263px.$(subst unity_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_unity = unity_r5f.ti-arm-clang_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_unity)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.am263px.$(subst unity_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_eeprom_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_eeprom_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_led_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_led_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += boot_testapp_mb_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += boot_testapp_mb_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_edma_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_edma_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_lin_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_lin_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am263px-lp_r5fss0-0_freertos_ti-arm-clang
# Various System Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_mcspi_controller_peripheral_am263px-cc_system_freertos_nortos
BUILD_COMBO_EXAMPLE_ALL += test_mcspi_controller_peripheral_am263px-lp_system_freertos_nortos
BUILD_COMBO_EXAMPLE_ALL += test_mcspi_controller_peripheral_dma_am263px-cc_system_freertos_nortos
BUILD_COMBO_EXAMPLE_ALL += test_mcspi_controller_peripheral_dma_am263px-lp_system_freertos_nortos
BUILD_COMBO_EXAMPLE_ALL += test_soc_r5f_am263px-cc_system_freertos
BUILD_COMBO_EXAMPLE_ALL += test_soc_r5f_am263px-lp_system_freertos

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 test_eeprom_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C board/eeprom/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_eeprom_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C board/eeprom/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_led_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C board/led/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_led_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C board/led/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 boot_testapp_mb_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/boot/boot_testapp_mb/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 boot_testapp_mb_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/boot/boot_testapp_mb/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_edma_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/edma/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_edma_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/edma/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_gpio_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_gpio_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_i2c_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_lin_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/lin/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_lin_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/lin/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_uart_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_mcspi_controller_peripheral_am263px-cc_system_freertos_nortos:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral/am263px-cc/system_freertos_nortos -f makefile all

 test_mcspi_controller_peripheral_am263px-lp_system_freertos_nortos:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral/am263px-lp/system_freertos_nortos -f makefile all

 test_mcspi_controller_peripheral_dma_am263px-cc_system_freertos_nortos:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-cc/system_freertos_nortos -f makefile all

 test_mcspi_controller_peripheral_dma_am263px-lp_system_freertos_nortos:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-lp/system_freertos_nortos -f makefile all

 test_soc_r5f_am263px-cc_system_freertos:
	$(MAKE) -C drivers/soc/soc_r5f/am263px-cc/system_freertos -f makefile all

 test_soc_r5f_am263px-lp_system_freertos:
	$(MAKE) -C drivers/soc/soc_r5f/am263px-lp/system_freertos -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_eeprom_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_eeprom_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_led_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_led_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += boot_testapp_mb_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += boot_testapp_mb_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_edma_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_edma_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_lin_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_lin_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mcspi_controller_peripheral_am263px-cc_system_freertos_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mcspi_controller_peripheral_am263px-lp_system_freertos_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mcspi_controller_peripheral_dma_am263px-cc_system_freertos_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mcspi_controller_peripheral_dma_am263px-lp_system_freertos_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_soc_r5f_am263px-cc_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_soc_r5f_am263px-lp_system_freertos_clean

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 test_eeprom_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C board/eeprom/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_eeprom_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C board/eeprom/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_led_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C board/led/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_led_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C board/led/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 boot_testapp_mb_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/boot/boot_testapp_mb/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 boot_testapp_mb_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/boot/boot_testapp_mb/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_edma_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/edma/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_edma_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/edma/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_gpio_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_gpio_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_i2c_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_lin_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/lin/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_lin_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/lin/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_uart_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_mcspi_controller_peripheral_am263px-cc_system_freertos_nortos_clean:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral/am263px-cc/system_freertos_nortos -f makefile clean

 test_mcspi_controller_peripheral_am263px-lp_system_freertos_nortos_clean:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral/am263px-lp/system_freertos_nortos -f makefile clean

 test_mcspi_controller_peripheral_dma_am263px-cc_system_freertos_nortos_clean:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-cc/system_freertos_nortos -f makefile clean

 test_mcspi_controller_peripheral_dma_am263px-lp_system_freertos_nortos_clean:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-lp/system_freertos_nortos -f makefile clean

 test_soc_r5f_am263px-cc_system_freertos_clean:
	$(MAKE) -C drivers/soc/soc_r5f/am263px-cc/system_freertos -f makefile clean

 test_soc_r5f_am263px-lp_system_freertos_clean:
	$(MAKE) -C drivers/soc/soc_r5f/am263px-lp/system_freertos -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_eeprom_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_eeprom_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_led_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_led_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += boot_testapp_mb_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += boot_testapp_mb_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_edma_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_edma_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_lin_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_lin_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mcspi_controller_peripheral_am263px-cc_system_freertos_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mcspi_controller_peripheral_am263px-lp_system_freertos_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mcspi_controller_peripheral_dma_am263px-cc_system_freertos_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mcspi_controller_peripheral_dma_am263px-lp_system_freertos_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_soc_r5f_am263px-cc_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_soc_r5f_am263px-lp_system_freertos_scrub

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 test_eeprom_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C board/eeprom/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_eeprom_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C board/eeprom/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_led_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C board/led/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_led_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C board/led/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 boot_testapp_mb_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/boot/boot_testapp_mb/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 boot_testapp_mb_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/boot/boot_testapp_mb/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_edma_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/edma/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_edma_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/edma/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_gpio_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_gpio_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_i2c_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_lin_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/lin/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_lin_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/lin/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_uart_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_mcspi_controller_peripheral_am263px-cc_system_freertos_nortos_scrub:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral/am263px-cc/system_freertos_nortos -f makefile scrub

 test_mcspi_controller_peripheral_am263px-lp_system_freertos_nortos_scrub:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral/am263px-lp/system_freertos_nortos -f makefile scrub

 test_mcspi_controller_peripheral_dma_am263px-cc_system_freertos_nortos_scrub:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-cc/system_freertos_nortos -f makefile scrub

 test_mcspi_controller_peripheral_dma_am263px-lp_system_freertos_nortos_scrub:
	$(MAKE) -C drivers/mcspi/mcspi_controller_peripheral_dma/am263px-lp/system_freertos_nortos -f makefile scrub

 test_soc_r5f_am263px-cc_system_freertos_scrub:
	$(MAKE) -C drivers/soc/soc_r5f/am263px-cc/system_freertos -f makefile scrub

 test_soc_r5f_am263px-lp_system_freertos_scrub:
	$(MAKE) -C drivers/soc/soc_r5f/am263px-lp/system_freertos -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:


.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
