#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am62x libs
	$(MAKE) -f makefile.am62x sbl
	$(MAKE) -f makefile.am62x examples


clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62x all
	@echo  $(MAKE) -s -f makefile.am62x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62x libs
	@echo  $(MAKE) -s -f makefile.am62x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62x examples
	@echo  $(MAKE) -s -f makefile.am62x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62x board_m4f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am62x drivers_m4f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am62x middleware_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am62x nortos_m4f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am62x freertos_m4f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62x board_m4f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am62x drivers_m4f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am62x middleware_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am62x nortos_m4f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am62x freertos_m4f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/hello_world/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/hello_world/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/hello_world/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/hello_world/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/i2c/i2c_read/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/i2c/i2c_read/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/sciclient/sciclient_get_version/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/sciclient/sciclient_get_version/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_callback/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_callback/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  $(MAKE) -s -C examples/empty/am62x-sk/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am62x-sk-lp/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am62x-sk/system_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am62x-sk-lp/system_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk-lp/system_freertos [all clean syscfg-gui syscfg]
	@echo  .

# Various Component Targets
BUILD_COMBO_board = board_m4f.ti-arm-clang
BUILD_COMBO_drivers = drivers_m4f.ti-arm-clang
BUILD_COMBO_middleware = middleware_r5f.ti-arm-clang
BUILD_COMBO_nortos = nortos_m4f.ti-arm-clang
BUILD_COMBO_freertos = freertos_m4f.ti-arm-clang


# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_board) $(BUILD_COMBO_drivers) $(BUILD_COMBO_middleware) $(BUILD_COMBO_nortos) $(BUILD_COMBO_freertos)


# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =


# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)


$(BUILD_COMBO_board):
	$(MAKE) -C source/board -f makefile.am62x.$(subst board_,,$@) all

$(BUILD_COMBO_drivers):
	$(MAKE) -C source/drivers -f makefile.am62x.$(subst drivers_,,$@) all

$(BUILD_COMBO_middleware):
	$(MAKE) -C source/middleware -f makefile.am62x.$(subst middleware_,,$@) all

$(BUILD_COMBO_nortos):
	$(MAKE) -C source/kernel/nortos -f makefile.am62x.$(subst nortos_,,$@) all

$(BUILD_COMBO_freertos):
	$(MAKE) -C source/kernel/freertos -f makefile.am62x.$(subst freertos_,,$@) all



# Various Component Clean Targets
BUILD_COMBO_CLEAN_board = board_m4f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_drivers = drivers_m4f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_middleware = middleware_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_nortos = nortos_m4f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_freertos = freertos_m4f.ti-arm-clang_clean


# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_board) $(BUILD_COMBO_CLEAN_drivers) $(BUILD_COMBO_CLEAN_middleware) $(BUILD_COMBO_CLEAN_nortos) $(BUILD_COMBO_CLEAN_freertos)


# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =


libs-clean: $(BUILD_COMBO_CLEAN_ALL)
libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)


$(BUILD_COMBO_CLEAN_board):
	$(MAKE) -C source/board -f makefile.am62x.$(subst board_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_drivers):
	$(MAKE) -C source/drivers -f makefile.am62x.$(subst drivers_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_middleware):
	$(MAKE) -C source/middleware -f makefile.am62x.$(subst middleware_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_nortos):
	$(MAKE) -C source/kernel/nortos -f makefile.am62x.$(subst nortos_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_freertos):
	$(MAKE) -C source/kernel/freertos -f makefile.am62x.$(subst freertos_,,$(subst _clean,,$@)) clean



# Various Component Scrub Targets
BUILD_COMBO_SCRUB_board = board_m4f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_drivers = drivers_m4f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_middleware = middleware_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_nortos = nortos_m4f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_freertos = freertos_m4f.ti-arm-clang_scrub_scrub


# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_board) $(BUILD_COMBO_SCRUB_drivers) $(BUILD_COMBO_SCRUB_middleware) $(BUILD_COMBO_SCRUB_nortos) $(BUILD_COMBO_SCRUB_freertos)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =


libs-scrub: $(BUILD_COMBO_SCRUB_ALL)
libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)


$(BUILD_COMBO_SCRUB_board):
	$(MAKE) -C source/board -f makefile.am62x.$(subst board_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_drivers):
	$(MAKE) -C source/drivers -f makefile.am62x.$(subst drivers_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_middleware):
	$(MAKE) -C source/middleware -f makefile.am62x.$(subst middleware_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_nortos):
	$(MAKE) -C source/kernel/nortos -f makefile.am62x.$(subst nortos_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_freertos):
	$(MAKE) -C source/kernel/freertos -f makefile.am62x.$(subst freertos_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += hello_world_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += hello_world_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += hello_world_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += hello_world_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dpl_demo_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dpl_demo_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dpl_demo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dpl_demo_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_input_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_input_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_led_blink_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_led_blink_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_led_blink_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_led_blink_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += i2c_read_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += i2c_read_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_polling_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_polling_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_interrupt_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcspi_loopback_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcspi_loopback_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcspi_performance_8bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcspi_performance_8bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcspi_performance_32bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcspi_performance_32bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sciclient_get_version_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sciclient_get_version_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_callback_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_callback_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_low_latency_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_low_latency_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_low_latency_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_low_latency_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang

# Various System Example Targets
BUILD_COMBO_EXAMPLE_ALL += empty_am62x-sk_system_freertos
BUILD_COMBO_EXAMPLE_ALL += empty_am62x-sk-lp_system_freertos
BUILD_COMBO_EXAMPLE_ALL += empty_am62x-sk_system_nortos
BUILD_COMBO_EXAMPLE_ALL += empty_am62x-sk-lp_system_nortos
BUILD_COMBO_EXAMPLE_ALL += ipc_rpmsg_echo_linux_am62x-sk_system_freertos
BUILD_COMBO_EXAMPLE_ALL += ipc_rpmsg_echo_linux_am62x-sk-lp_system_freertos



BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets


examples: $(BUILD_COMBO_EXAMPLE_ALL)



examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 hello_world_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/hello_world/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 hello_world_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/hello_world/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 hello_world_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/hello_world/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 hello_world_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/hello_world/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile all

 dpl_demo_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 dpl_demo_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 dpl_demo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 dpl_demo_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile all

 gpio_input_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 gpio_input_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 gpio_led_blink_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 gpio_led_blink_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 gpio_led_blink_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 gpio_led_blink_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile all

 i2c_read_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 i2c_read_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcan_loopback_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcan_loopback_polling_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 mcan_loopback_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcan_loopback_polling_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile all

 mcan_loopback_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcan_loopback_interrupt_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile all

 mcspi_loopback_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcspi_loopback_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 mcspi_performance_8bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcspi_performance_8bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 mcspi_performance_32bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 mcspi_performance_32bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile all

 sciclient_get_version_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 sciclient_get_version_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_callback_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_callback_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_low_latency_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_low_latency_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_low_latency_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_low_latency_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile all

 empty_am62x-sk_system_freertos:
	$(MAKE) -C examples/empty/am62x-sk/system_freertos -f makefile all

 empty_am62x-sk-lp_system_freertos:
	$(MAKE) -C examples/empty/am62x-sk-lp/system_freertos -f makefile all

 empty_am62x-sk_system_nortos:
	$(MAKE) -C examples/empty/am62x-sk/system_nortos -f makefile all

 empty_am62x-sk-lp_system_nortos:
	$(MAKE) -C examples/empty/am62x-sk-lp/system_nortos -f makefile all

 ipc_rpmsg_echo_linux_am62x-sk_system_freertos:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk/system_freertos -f makefile all

 ipc_rpmsg_echo_linux_am62x-sk-lp_system_freertos:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk-lp/system_freertos -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += hello_world_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += hello_world_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += hello_world_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += hello_world_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dpl_demo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dpl_demo_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dpl_demo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dpl_demo_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_input_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_input_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_led_blink_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_led_blink_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_led_blink_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_led_blink_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += i2c_read_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += i2c_read_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_polling_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_polling_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_interrupt_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcspi_loopback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcspi_loopback_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcspi_performance_8bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcspi_performance_8bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcspi_performance_32bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcspi_performance_32bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sciclient_get_version_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sciclient_get_version_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_callback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_callback_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_low_latency_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_low_latency_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_low_latency_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_low_latency_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean
# Various System Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am62x-sk_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am62x-sk-lp_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am62x-sk_system_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am62x-sk-lp_system_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ipc_rpmsg_echo_linux_am62x-sk_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ipc_rpmsg_echo_linux_am62x-sk-lp_system_freertos_clean


BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 hello_world_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/hello_world/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 hello_world_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/hello_world/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 hello_world_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/hello_world/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 hello_world_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/hello_world/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 dpl_demo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 dpl_demo_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 dpl_demo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 dpl_demo_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 gpio_input_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 gpio_input_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 gpio_led_blink_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 gpio_led_blink_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 gpio_led_blink_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 gpio_led_blink_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 i2c_read_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 i2c_read_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcan_loopback_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcan_loopback_polling_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 mcan_loopback_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcan_loopback_polling_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 mcan_loopback_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcan_loopback_interrupt_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 mcspi_loopback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcspi_loopback_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 mcspi_performance_8bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcspi_performance_8bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 mcspi_performance_32bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 mcspi_performance_32bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile clean

 sciclient_get_version_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 sciclient_get_version_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_callback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_callback_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_low_latency_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_low_latency_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_low_latency_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_low_latency_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile clean

 empty_am62x-sk_system_freertos_clean:
	$(MAKE) -C examples/empty/am62x-sk/system_freertos -f makefile clean

 empty_am62x-sk-lp_system_freertos_clean:
	$(MAKE) -C examples/empty/am62x-sk-lp/system_freertos -f makefile clean

 empty_am62x-sk_system_nortos_clean:
	$(MAKE) -C examples/empty/am62x-sk/system_nortos -f makefile clean

 empty_am62x-sk-lp_system_nortos_clean:
	$(MAKE) -C examples/empty/am62x-sk-lp/system_nortos -f makefile clean

 ipc_rpmsg_echo_linux_am62x-sk_system_freertos_clean:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk/system_freertos -f makefile clean

 ipc_rpmsg_echo_linux_am62x-sk-lp_system_freertos_clean:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk-lp/system_freertos -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += hello_world_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += hello_world_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += hello_world_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += hello_world_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dpl_demo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dpl_demo_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dpl_demo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dpl_demo_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_input_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_input_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_led_blink_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_led_blink_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_led_blink_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_led_blink_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += i2c_read_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += i2c_read_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_polling_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_polling_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_interrupt_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcspi_loopback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcspi_loopback_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcspi_performance_8bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcspi_performance_8bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcspi_performance_32bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcspi_performance_32bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sciclient_get_version_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sciclient_get_version_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_callback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_callback_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_low_latency_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_low_latency_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_low_latency_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_low_latency_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub
# Various System Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am62x-sk_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am62x-sk-lp_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am62x-sk_system_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am62x-sk-lp_system_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ipc_rpmsg_echo_linux_am62x-sk_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ipc_rpmsg_echo_linux_am62x-sk-lp_system_freertos_scrub


BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 hello_world_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/hello_world/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 hello_world_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/hello_world/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 hello_world_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/hello_world/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 hello_world_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/hello_world/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 dpl_demo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 dpl_demo_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 dpl_demo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 dpl_demo_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 gpio_input_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 gpio_input_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 gpio_led_blink_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 gpio_led_blink_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 gpio_led_blink_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 gpio_led_blink_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 i2c_read_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 i2c_read_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcan_loopback_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcan_loopback_polling_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 mcan_loopback_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcan_loopback_polling_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_polling/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 mcan_loopback_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcan_loopback_interrupt_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcan_loopback_interrupt_am62x-sk-lp_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcan/mcan_loopback_interrupt/am62x-sk-lp/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 mcspi_loopback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcspi_loopback_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcspi/mcspi_loopback/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 mcspi_performance_8bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcspi_performance_8bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_8bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 mcspi_performance_32bit_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcspi_performance_32bit_am62x-sk_m4fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mcspi/mcspi_performance_32bit/am62x-sk/m4fss0-0_freertos/ti-arm-clang -f makefile scrub

 sciclient_get_version_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 sciclient_get_version_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_callback_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_callback_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_low_latency_interrupt_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_low_latency_interrupt_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_low_latency_polling_am62x-sk_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_low_latency_polling_am62x-sk-lp_m4fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am62x-sk-lp/m4fss0-0_nortos/ti-arm-clang -f makefile scrub

 empty_am62x-sk_system_freertos_scrub:
	$(MAKE) -C examples/empty/am62x-sk/system_freertos -f makefile scrub

 empty_am62x-sk-lp_system_freertos_scrub:
	$(MAKE) -C examples/empty/am62x-sk-lp/system_freertos -f makefile scrub

 empty_am62x-sk_system_nortos_scrub:
	$(MAKE) -C examples/empty/am62x-sk/system_nortos -f makefile scrub

 empty_am62x-sk-lp_system_nortos_scrub:
	$(MAKE) -C examples/empty/am62x-sk-lp/system_nortos -f makefile scrub

 ipc_rpmsg_echo_linux_am62x-sk_system_freertos_scrub:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk/system_freertos -f makefile scrub

 ipc_rpmsg_echo_linux_am62x-sk-lp_system_freertos_scrub:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-sk-lp/system_freertos -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:




.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)