#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am65x libs
	$(MAKE) -f makefile.am65x sbl
	$(MAKE) -f makefile.am65x examples


clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am65x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am65x all
	@echo  $(MAKE) -s -f makefile.am65x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am65x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am65x libs
	@echo  $(MAKE) -s -f makefile.am65x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am65x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am65x examples
	@echo  $(MAKE) -s -f makefile.am65x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am65x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am65x board_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am65x drivers_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am65x freertos_fat_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am65x middleware_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am65x freertos_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am65x nortos_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am65x board_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am65x drivers_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am65x freertos_fat_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am65x middleware_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am65x freertos_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am65x nortos_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_pcie_host/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_input_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/gpio/gpio_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/i2c/i2c_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/i2c/i2c_read/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/i2c/i2c_temperature/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mmcsd/mmcsd_file_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/mmcsd/mmcsd_raw_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/ospi/ospi_flash_diag/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/ospi/ospi_flash_dma/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/ospi/ospi_flash_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_ep/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_rc/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-1_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/sciclient/sciclient_set_boardcfg/am65x-idk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_callback/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_dma/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_low_latency_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/uart/uart_echo_low_latency_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/udma/udma_chaining/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/udma/udma_memcpy_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/udma/udma_memcpy_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/drivers/udma/udma_sw_trigger/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/hello_world/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/hello_world_cpp/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/dpl/dpl_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/freertos/posix_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/kernel/freertos/task_switch/am65x-idk/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  $(MAKE) -s -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am65x-idk/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am65x-idk/system_freertos [all clean syscfg-gui syscfg]
	@echo  .

# Various Component Targets
BUILD_COMBO_board = board_r5f.ti-arm-clang
BUILD_COMBO_drivers = drivers_r5f.ti-arm-clang
BUILD_COMBO_freertos_fat = freertos_fat_r5f.ti-arm-clang
BUILD_COMBO_middleware = middleware_r5f.ti-arm-clang
BUILD_COMBO_freertos = freertos_r5f.ti-arm-clang
BUILD_COMBO_nortos = nortos_r5f.ti-arm-clang


# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_board) $(BUILD_COMBO_drivers) $(BUILD_COMBO_freertos_fat) $(BUILD_COMBO_middleware) $(BUILD_COMBO_freertos) $(BUILD_COMBO_nortos)


# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =


# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)


$(BUILD_COMBO_board):
	$(MAKE) -C source/board -f makefile.am65x.$(subst board_,,$@) all

$(BUILD_COMBO_drivers):
	$(MAKE) -C source/drivers -f makefile.am65x.$(subst drivers_,,$@) all

$(BUILD_COMBO_freertos_fat):
	$(MAKE) -C source/fs/freertos_fat -f makefile.am65x.$(subst freertos_fat_,,$@) all

$(BUILD_COMBO_middleware):
	$(MAKE) -C source/middleware -f makefile.am65x.$(subst middleware_,,$@) all

$(BUILD_COMBO_freertos):
	$(MAKE) -C source/kernel/freertos -f makefile.am65x.$(subst freertos_,,$@) all

$(BUILD_COMBO_nortos):
	$(MAKE) -C source/kernel/nortos -f makefile.am65x.$(subst nortos_,,$@) all



# Various Component Clean Targets
BUILD_COMBO_CLEAN_board = board_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_drivers = drivers_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_freertos_fat = freertos_fat_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_middleware = middleware_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_freertos = freertos_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_nortos = nortos_r5f.ti-arm-clang_clean


# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_board) $(BUILD_COMBO_CLEAN_drivers) $(BUILD_COMBO_CLEAN_freertos_fat) $(BUILD_COMBO_CLEAN_middleware) $(BUILD_COMBO_CLEAN_freertos) $(BUILD_COMBO_CLEAN_nortos)


# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =


libs-clean: $(BUILD_COMBO_CLEAN_ALL)
libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)


$(BUILD_COMBO_CLEAN_board):
	$(MAKE) -C source/board -f makefile.am65x.$(subst board_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_drivers):
	$(MAKE) -C source/drivers -f makefile.am65x.$(subst drivers_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_freertos_fat):
	$(MAKE) -C source/fs/freertos_fat -f makefile.am65x.$(subst freertos_fat_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_middleware):
	$(MAKE) -C source/middleware -f makefile.am65x.$(subst middleware_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_freertos):
	$(MAKE) -C source/kernel/freertos -f makefile.am65x.$(subst freertos_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_nortos):
	$(MAKE) -C source/kernel/nortos -f makefile.am65x.$(subst nortos_,,$(subst _clean,,$@)) clean



# Various Component Scrub Targets
BUILD_COMBO_SCRUB_board = board_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_drivers = drivers_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_freertos_fat = freertos_fat_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_middleware = middleware_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_freertos = freertos_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_nortos = nortos_r5f.ti-arm-clang_scrub_scrub


# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_board) $(BUILD_COMBO_SCRUB_drivers) $(BUILD_COMBO_SCRUB_freertos_fat) $(BUILD_COMBO_SCRUB_middleware) $(BUILD_COMBO_SCRUB_freertos) $(BUILD_COMBO_SCRUB_nortos)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =


libs-scrub: $(BUILD_COMBO_SCRUB_ALL)
libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)


$(BUILD_COMBO_SCRUB_board):
	$(MAKE) -C source/board -f makefile.am65x.$(subst board_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_drivers):
	$(MAKE) -C source/drivers -f makefile.am65x.$(subst drivers_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_freertos_fat):
	$(MAKE) -C source/fs/freertos_fat -f makefile.am65x.$(subst freertos_fat_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_middleware):
	$(MAKE) -C source/middleware -f makefile.am65x.$(subst middleware_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_freertos):
	$(MAKE) -C source/kernel/freertos -f makefile.am65x.$(subst freertos_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_nortos):
	$(MAKE) -C source/kernel/nortos -f makefile.am65x.$(subst nortos_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += sbl_pcie_host_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_input_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += gpio_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += i2c_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += i2c_read_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += i2c_temperature_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mmcsd_file_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mmcsd_raw_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ospi_flash_diag_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ospi_flash_dma_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ospi_flash_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += pcie_buf_transfer_ep_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += pcie_buf_transfer_rc_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sciclient_get_version_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sciclient_get_version_am65x-idk_r5fss0-1_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sciclient_set_boardcfg_am65x-idk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_callback_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_dma_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_low_latency_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += uart_echo_low_latency_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += udma_chaining_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += udma_memcpy_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += udma_memcpy_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += udma_sw_trigger_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += hello_world_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += hello_world_cpp_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dpl_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += posix_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += task_switch_am65x-idk_r5fss0-0_freertos_ti-arm-clang

# Various System Example Targets
BUILD_COMBO_EXAMPLE_ALL += ipc_rpmsg_echo_linux_am65x-idk_system_freertos
BUILD_COMBO_EXAMPLE_ALL += empty_am65x-idk_system_freertos



BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets


examples: $(BUILD_COMBO_EXAMPLE_ALL)



examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 sbl_null_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_ospi_linux_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_sd_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_pcie_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_pcie_host_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_pcie_host/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_uart_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 sbl_uart_uniflash_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 gpio_input_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 gpio_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 i2c_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/i2c/i2c_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 i2c_read_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 i2c_temperature_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/i2c/i2c_temperature/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mmcsd_file_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mmcsd/mmcsd_file_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 mmcsd_raw_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/mmcsd/mmcsd_raw_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 ospi_flash_diag_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_diag/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 ospi_flash_dma_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_dma/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 ospi_flash_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 pcie_buf_transfer_ep_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_ep/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 pcie_buf_transfer_rc_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_rc/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 sciclient_get_version_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 sciclient_get_version_am65x-idk_r5fss0-1_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-1_freertos/ti-arm-clang -f makefile all

 sciclient_set_boardcfg_am65x-idk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/drivers/sciclient/sciclient_set_boardcfg/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 uart_echo_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 uart_echo_callback_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 uart_echo_dma_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_dma/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 uart_echo_low_latency_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 uart_echo_low_latency_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 udma_chaining_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/udma/udma_chaining/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 udma_memcpy_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/udma/udma_memcpy_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 udma_memcpy_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/udma/udma_memcpy_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 udma_sw_trigger_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/drivers/udma/udma_sw_trigger/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 hello_world_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/hello_world/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 hello_world_cpp_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/hello_world_cpp/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dpl_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 posix_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/kernel/freertos/posix_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 task_switch_am65x-idk_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/kernel/freertos/task_switch/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ipc_rpmsg_echo_linux_am65x-idk_system_freertos:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am65x-idk/system_freertos -f makefile all

 empty_am65x-idk_system_freertos:
	$(MAKE) -C examples/empty/am65x-idk/system_freertos -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sbl_pcie_host_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_input_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += gpio_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += i2c_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += i2c_read_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += i2c_temperature_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mmcsd_file_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mmcsd_raw_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ospi_flash_diag_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ospi_flash_dma_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ospi_flash_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += pcie_buf_transfer_ep_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += pcie_buf_transfer_rc_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sciclient_get_version_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sciclient_get_version_am65x-idk_r5fss0-1_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sciclient_set_boardcfg_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_callback_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_dma_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_low_latency_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += uart_echo_low_latency_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += udma_chaining_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += udma_memcpy_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += udma_memcpy_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += udma_sw_trigger_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += hello_world_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += hello_world_cpp_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dpl_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += posix_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += task_switch_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ipc_rpmsg_echo_linux_am65x-idk_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am65x-idk_system_freertos_clean


BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 sbl_null_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_ospi_linux_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_sd_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_pcie_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_pcie_host_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_pcie_host/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_uart_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sbl_uart_uniflash_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 gpio_input_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 gpio_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 i2c_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/i2c/i2c_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 i2c_read_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 i2c_temperature_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/i2c/i2c_temperature/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mmcsd_file_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mmcsd/mmcsd_file_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 mmcsd_raw_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/mmcsd/mmcsd_raw_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 ospi_flash_diag_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_diag/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 ospi_flash_dma_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_dma/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 ospi_flash_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 pcie_buf_transfer_ep_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_ep/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 pcie_buf_transfer_rc_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_rc/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sciclient_get_version_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sciclient_get_version_am65x-idk_r5fss0-1_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-1_freertos/ti-arm-clang -f makefile clean

 sciclient_set_boardcfg_am65x-idk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/sciclient/sciclient_set_boardcfg/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 uart_echo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 uart_echo_callback_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 uart_echo_dma_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_dma/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 uart_echo_low_latency_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 uart_echo_low_latency_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 udma_chaining_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/udma/udma_chaining/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 udma_memcpy_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/udma/udma_memcpy_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 udma_memcpy_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/udma/udma_memcpy_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 udma_sw_trigger_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/drivers/udma/udma_sw_trigger/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 hello_world_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/hello_world/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 hello_world_cpp_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/hello_world_cpp/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dpl_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 posix_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/freertos/posix_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 task_switch_am65x-idk_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/kernel/freertos/task_switch/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ipc_rpmsg_echo_linux_am65x-idk_system_freertos_clean:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am65x-idk/system_freertos -f makefile clean

 empty_am65x-idk_system_freertos_clean:
	$(MAKE) -C examples/empty/am65x-idk/system_freertos -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sbl_pcie_host_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_input_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += gpio_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += i2c_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += i2c_read_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += i2c_temperature_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mmcsd_file_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mmcsd_raw_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ospi_flash_diag_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ospi_flash_dma_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ospi_flash_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += pcie_buf_transfer_ep_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += pcie_buf_transfer_rc_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sciclient_get_version_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sciclient_get_version_am65x-idk_r5fss0-1_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sciclient_set_boardcfg_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_callback_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_dma_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_low_latency_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += uart_echo_low_latency_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += udma_chaining_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += udma_memcpy_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += udma_memcpy_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += udma_sw_trigger_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += hello_world_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += hello_world_cpp_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dpl_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += posix_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += task_switch_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ipc_rpmsg_echo_linux_am65x-idk_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am65x-idk_system_freertos_scrub


BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 sbl_null_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_ospi_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_ospi_linux_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_sd_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_pcie_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_pcie_host_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_pcie_host/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_uart_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sbl_uart_uniflash_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 gpio_input_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_input_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 gpio_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/gpio/gpio_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 i2c_led_blink_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/i2c/i2c_led_blink/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 i2c_read_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/i2c/i2c_read/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 i2c_temperature_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/i2c/i2c_temperature/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mmcsd_file_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mmcsd/mmcsd_file_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 mmcsd_raw_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/mmcsd/mmcsd_raw_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 ospi_flash_diag_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_diag/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 ospi_flash_dma_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_dma/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 ospi_flash_io_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/ospi/ospi_flash_io/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 pcie_buf_transfer_ep_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_ep/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 pcie_buf_transfer_rc_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/pcie/pcie_buf_transfer/pcie_buf_transfer_rc/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sciclient_get_version_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sciclient_get_version_am65x-idk_r5fss0-1_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/sciclient/sciclient_get_version/am65x-idk/r5fss0-1_freertos/ti-arm-clang -f makefile scrub

 sciclient_set_boardcfg_am65x-idk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/sciclient/sciclient_set_boardcfg/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 uart_echo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 uart_echo_callback_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_callback/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 uart_echo_dma_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_dma/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 uart_echo_low_latency_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 uart_echo_low_latency_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/uart/uart_echo_low_latency_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 udma_chaining_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/udma/udma_chaining/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 udma_memcpy_interrupt_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/udma/udma_memcpy_interrupt/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 udma_memcpy_polling_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/udma/udma_memcpy_polling/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 udma_sw_trigger_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/drivers/udma/udma_sw_trigger/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 hello_world_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/hello_world/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 hello_world_cpp_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/hello_world_cpp/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dpl_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/dpl/dpl_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 posix_demo_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/freertos/posix_demo/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 task_switch_am65x-idk_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/kernel/freertos/task_switch/am65x-idk/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ipc_rpmsg_echo_linux_am65x-idk_system_freertos_scrub:
	$(MAKE) -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am65x-idk/system_freertos -f makefile scrub

 empty_am65x-idk_system_freertos_scrub:
	$(MAKE) -C examples/empty/am65x-idk/system_freertos -f makefile scrub


sbl: libs
	$(MAKE) -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile all

sbl-clean:
	$(MAKE) -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

sbl-scrub:
	$(MAKE) -C examples/drivers/boot/sbl_null/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C examples/drivers/boot/sbl_ospi/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C examples/drivers/boot/sbl_ospi_linux/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C examples/drivers/boot/sbl_sd/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C examples/drivers/boot/sbl_pcie/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C examples/drivers/boot/sbl_uart/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C examples/drivers/boot/sbl_uart_uniflash/am65x-idk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub




.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)