let common = system.getScript("/common");
let xbarSoc = system.getScript(`/xbar/soc/xbar_${common.getSocName()}`);

const internal_list = [
    {  name: "GPIO0", displayName: "GPIO0", path: "input_xbar", group: 0 },
    {  name: "GPIO1", displayName: "GPIO1", path: "input_xbar", group: 0 },
    {  name: "GPIO2", displayName: "GPIO2", path: "input_xbar", group: 0 },
    {  name: "GPIO3", displayName: "GPIO3", path: "input_xbar", group: 0 },
    {  name: "GPIO4", displayName: "GPIO4", path: "input_xbar", group: 0 },
    {  name: "GPIO5", displayName: "GPIO5", path: "input_xbar", group: 0 },
    {  name: "GPIO6", displayName: "GPIO6", path: "input_xbar", group: 0 },
    {  name: "GPIO7", displayName: "GPIO7", path: "input_xbar", group: 0 },
    {  name: "GPIO8", displayName: "GPIO8", path: "input_xbar", group: 0 },
    {  name: "GPIO9", displayName: "GPIO9", path: "input_xbar", group: 0 },
    {  name: "GPIO10", displayName: "GPIO10", path: "input_xbar", group: 0 },
    {  name: "GPIO11", displayName: "GPIO11", path: "input_xbar", group: 0 },
    {  name: "GPIO12", displayName: "GPIO12", path: "input_xbar", group: 0 },
    {  name: "GPIO13", displayName: "GPIO13", path: "input_xbar", group: 0 },
    {  name: "GPIO14", displayName: "GPIO14", path: "input_xbar", group: 0 },
    {  name: "GPIO15", displayName: "GPIO15", path: "input_xbar", group: 0 },
    {  name: "GPIO16", displayName: "GPIO16", path: "input_xbar", group: 0 },
    {  name: "GPIO17", displayName: "GPIO17", path: "input_xbar", group: 0 },
    {  name: "GPIO18", displayName: "GPIO18", path: "input_xbar", group: 0 },
    {  name: "GPIO19", displayName: "GPIO19", path: "input_xbar", group: 0 },
    {  name: "GPIO20", displayName: "GPIO20", path: "input_xbar", group: 0 },
    {  name: "GPIO21", displayName: "GPIO21", path: "input_xbar", group: 0 },
    {  name: "GPIO22", displayName: "GPIO22", path: "input_xbar", group: 0 },
    {  name: "GPIO23", displayName: "GPIO23", path: "input_xbar", group: 0 },
    {  name: "GPIO24", displayName: "GPIO24", path: "input_xbar", group: 0 },
    {  name: "GPIO25", displayName: "GPIO25", path: "input_xbar", group: 0 },
    {  name: "GPIO26", displayName: "GPIO26", path: "input_xbar", group: 0 },
    {  name: "GPIO27", displayName: "GPIO27", path: "input_xbar", group: 0 },
    {  name: "GPIO28", displayName: "GPIO28", path: "input_xbar", group: 0 },
    {  name: "GPIO29", displayName: "GPIO29", path: "input_xbar", group: 0 },
    {  name: "GPIO30", displayName: "GPIO30", path: "input_xbar", group: 0 },
    {  name: "GPIO31", displayName: "GPIO31", path: "input_xbar", group: 0 },
    {  name: "GPIO32", displayName: "GPIO32", path: "input_xbar", group: 0 },
    {  name: "GPIO33", displayName: "GPIO33", path: "input_xbar", group: 0 },
    {  name: "GPIO34", displayName: "GPIO34", path: "input_xbar", group: 0 },
    {  name: "GPIO35", displayName: "GPIO35", path: "input_xbar", group: 0 },
    {  name: "GPIO36", displayName: "GPIO36", path: "input_xbar", group: 0 },
    {  name: "GPIO37", displayName: "GPIO37", path: "input_xbar", group: 0 },
    {  name: "GPIO38", displayName: "GPIO38", path: "input_xbar", group: 0 },
    {  name: "GPIO39", displayName: "GPIO39", path: "input_xbar", group: 0 },
    {  name: "GPIO40", displayName: "GPIO40", path: "input_xbar", group: 0 },
    {  name: "GPIO41", displayName: "GPIO41", path: "input_xbar", group: 0 },
    {  name: "GPIO42", displayName: "GPIO42", path: "input_xbar", group: 0 },
    {  name: "GPIO43", displayName: "GPIO43", path: "input_xbar", group: 0 },
    {  name: "GPIO44", displayName: "GPIO44", path: "input_xbar", group: 0 },
    {  name: "GPIO45", displayName: "GPIO45", path: "input_xbar", group: 0 },
    {  name: "GPIO46", displayName: "GPIO46", path: "input_xbar", group: 0 },
    {  name: "GPIO47", displayName: "GPIO47", path: "input_xbar", group: 0 },
    {  name: "GPIO48", displayName: "GPIO48", path: "input_xbar", group: 0 },
    {  name: "GPIO49", displayName: "GPIO49", path: "input_xbar", group: 0 },
    {  name: "GPIO50", displayName: "GPIO50", path: "input_xbar", group: 0 },
    {  name: "GPIO51", displayName: "GPIO51", path: "input_xbar", group: 0 },
    {  name: "GPIO52", displayName: "GPIO52", path: "input_xbar", group: 0 },
    {  name: "GPIO53", displayName: "GPIO53", path: "input_xbar", group: 0 },
    {  name: "GPIO54", displayName: "GPIO54", path: "input_xbar", group: 0 },
    {  name: "GPIO55", displayName: "GPIO55", path: "input_xbar", group: 0 },
    {  name: "GPIO56", displayName: "GPIO56", path: "input_xbar", group: 0 },
    {  name: "GPIO57", displayName: "GPIO57", path: "input_xbar", group: 0 },
    {  name: "GPIO58", displayName: "GPIO58", path: "input_xbar", group: 0 },
    {  name: "GPIO59", displayName: "GPIO59", path: "input_xbar", group: 0 },
    {  name: "GPIO60", displayName: "GPIO60", path: "input_xbar", group: 0 },
    {  name: "GPIO61", displayName: "GPIO61", path: "input_xbar", group: 0 },
    {  name: "GPIO62", displayName: "GPIO62", path: "input_xbar", group: 0 },
    {  name: "GPIO63", displayName: "GPIO63", path: "input_xbar", group: 0 },
    {  name: "GPIO64", displayName: "GPIO64", path: "input_xbar", group: 0 },
    {  name: "GPIO65", displayName: "GPIO65", path: "input_xbar", group: 0 },
    {  name: "GPIO66", displayName: "GPIO66", path: "input_xbar", group: 0 },
    {  name: "GPIO67", displayName: "GPIO67", path: "input_xbar", group: 0 },
    {  name: "GPIO68", displayName: "GPIO68", path: "input_xbar", group: 0 },
    {  name: "GPIO69", displayName: "GPIO69", path: "input_xbar", group: 0 },
    {  name: "GPIO70", displayName: "GPIO70", path: "input_xbar", group: 0 },
    {  name: "GPIO71", displayName: "GPIO71", path: "input_xbar", group: 0 },
    {  name: "GPIO72", displayName: "GPIO72", path: "input_xbar", group: 0 },
    {  name: "GPIO73", displayName: "GPIO73", path: "input_xbar", group: 0 },
    {  name: "GPIO74", displayName: "GPIO74", path: "input_xbar", group: 0 },
    {  name: "GPIO75", displayName: "GPIO75", path: "input_xbar", group: 0 },
    {  name: "GPIO76", displayName: "GPIO76", path: "input_xbar", group: 0 },
    {  name: "GPIO77", displayName: "GPIO77", path: "input_xbar", group: 0 },
    {  name: "GPIO78", displayName: "GPIO78", path: "input_xbar", group: 0 },
    {  name: "GPIO79", displayName: "GPIO79", path: "input_xbar", group: 0 },
    {  name: "GPIO80", displayName: "GPIO80", path: "input_xbar", group: 0 },
    {  name: "GPIO81", displayName: "GPIO81", path: "input_xbar", group: 0 },
    {  name: "GPIO82", displayName: "GPIO82", path: "input_xbar", group: 0 },
    {  name: "GPIO83", displayName: "GPIO83", path: "input_xbar", group: 0 },
    {  name: "GPIO84", displayName: "GPIO84", path: "input_xbar", group: 0 },
    {  name: "GPIO85", displayName: "GPIO85", path: "input_xbar", group: 0 },
    {  name: "GPIO86", displayName: "GPIO86", path: "input_xbar", group: 0 },
    {  name: "GPIO87", displayName: "GPIO87", path: "input_xbar", group: 0 },
    {  name: "GPIO88", displayName: "GPIO88", path: "input_xbar", group: 0 },
    {  name: "GPIO89", displayName: "GPIO89", path: "input_xbar", group: 0 },
    {  name: "GPIO90", displayName: "GPIO90", path: "input_xbar", group: 0 },
    {  name: "GPIO91", displayName: "GPIO91", path: "input_xbar", group: 0 },
    {  name: "GPIO92", displayName: "GPIO92", path: "input_xbar", group: 0 },
    {  name: "GPIO93", displayName: "GPIO93", path: "input_xbar", group: 0 },
    {  name: "GPIO94", displayName: "GPIO94", path: "input_xbar", group: 0 },
    {  name: "GPIO95", displayName: "GPIO95", path: "input_xbar", group: 0 },
    {  name: "GPIO96", displayName: "GPIO96", path: "input_xbar", group: 0 },
    {  name: "GPIO97", displayName: "GPIO97", path: "input_xbar", group: 0 },
    {  name: "GPIO98", displayName: "GPIO98", path: "input_xbar", group: 0 },
    {  name: "GPIO99", displayName: "GPIO99", path: "input_xbar", group: 0 },
    {  name: "GPIO100", displayName: "GPIO100", path: "input_xbar", group: 0 },
    {  name: "GPIO101", displayName: "GPIO101", path: "input_xbar", group: 0 },
    {  name: "GPIO102", displayName: "GPIO102", path: "input_xbar", group: 0 },
    {  name: "GPIO103", displayName: "GPIO103", path: "input_xbar", group: 0 },
    {  name: "GPIO104", displayName: "GPIO104", path: "input_xbar", group: 0 },
    {  name: "GPIO105", displayName: "GPIO105", path: "input_xbar", group: 0 },
    {  name: "GPIO106", displayName: "GPIO106", path: "input_xbar", group: 0 },
    {  name: "GPIO107", displayName: "GPIO107", path: "input_xbar", group: 0 },
    {  name: "GPIO108", displayName: "GPIO108", path: "input_xbar", group: 0 },
    {  name: "GPIO109", displayName: "GPIO109", path: "input_xbar", group: 0 },
    {  name: "GPIO110", displayName: "GPIO110", path: "input_xbar", group: 0 },
    {  name: "GPIO111", displayName: "GPIO111", path: "input_xbar", group: 0 },
    {  name: "GPIO112", displayName: "GPIO112", path: "input_xbar", group: 0 },
    {  name: "GPIO113", displayName: "GPIO113", path: "input_xbar", group: 0 },
    {  name: "GPIO114", displayName: "GPIO114", path: "input_xbar", group: 0 },
    {  name: "GPIO115", displayName: "GPIO115", path: "input_xbar", group: 0 },
    {  name: "GPIO116", displayName: "GPIO116", path: "input_xbar", group: 0 },
    {  name: "GPIO117", displayName: "GPIO117", path: "input_xbar", group: 0 },
    {  name: "GPIO118", displayName: "GPIO118", path: "input_xbar", group: 0 },
    {  name: "GPIO119", displayName: "GPIO119", path: "input_xbar", group: 0 },
    {  name: "GPIO120", displayName: "GPIO120", path: "input_xbar", group: 0 },
    {  name: "GPIO121", displayName: "GPIO121", path: "input_xbar", group: 0 },
    {  name: "GPIO122", displayName: "GPIO122", path: "input_xbar", group: 0 },
    {  name: "GPIO123", displayName: "GPIO123", path: "input_xbar", group: 0 },
    {  name: "GPIO124", displayName: "GPIO124", path: "input_xbar", group: 0 },
    {  name: "GPIO125", displayName: "GPIO125", path: "input_xbar", group: 0 },
    {  name: "GPIO126", displayName: "GPIO126", path: "input_xbar", group: 0 },
    {  name: "GPIO127", displayName: "GPIO127", path: "input_xbar", group: 0 },
    {  name: "GPIO128", displayName: "GPIO128", path: "input_xbar", group: 0 },
    {  name: "GPIO129", displayName: "GPIO129", path: "input_xbar", group: 0 },
    {  name: "GPIO130", displayName: "GPIO130", path: "input_xbar", group: 0 },
    {  name: "GPIO131", displayName: "GPIO131", path: "input_xbar", group: 0 },
    {  name: "GPIO132", displayName: "GPIO132", path: "input_xbar", group: 0 },
    {  name: "GPIO133", displayName: "GPIO133", path: "input_xbar", group: 0 },
    {  name: "GPIO134", displayName: "GPIO134", path: "input_xbar", group: 0 },
    {  name: "GPIO135", displayName: "GPIO135", path: "input_xbar", group: 0 },
    {  name: "GPIO136", displayName: "GPIO136", path: "input_xbar", group: 0 },
    {  name: "GPIO137", displayName: "GPIO137", path: "input_xbar", group: 0 },
    {  name: "GPIO138", displayName: "GPIO138", path: "input_xbar", group: 0 },
    {  name: "GPIO139", displayName: "GPIO139", path: "input_xbar", group: 0 },
    {  name: "GPIO140", displayName: "GPIO140", path: "input_xbar", group: 0 },
    {  name: "GPIO141", displayName: "GPIO141", path: "input_xbar", group: 0 },
    {  name: "GPIO142", displayName: "GPIO142", path: "input_xbar", group: 0 },
    {  name: "GPIO143", displayName: "GPIO143", path: "input_xbar", group: 0 },
    {  name: "ICSSGPO0_PORT0", displayName: "ICSSGPO0_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO1_PORT0", displayName: "ICSSGPO1_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO2_PORT0", displayName: "ICSSGPO2_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO3_PORT0", displayName: "ICSSGPO3_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO4_PORT0", displayName: "ICSSGPO4_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO5_PORT0", displayName: "ICSSGPO5_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO6_PORT0", displayName: "ICSSGPO6_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO7_PORT0", displayName: "ICSSGPO7_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO8_PORT0", displayName: "ICSSGPO8_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO9_PORT0", displayName: "ICSSGPO9_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO10_PORT0", displayName: "ICSSGPO10_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO11_PORT0", displayName: "ICSSGPO11_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO12_PORT0", displayName: "ICSSGPO12_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO13_PORT0", displayName: "ICSSGPO13_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO14_PORT0", displayName: "ICSSGPO14_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO15_PORT0", displayName: "ICSSGPO15_PORT0", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO0_PORT1", displayName: "ICSSGPO0_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO1_PORT1", displayName: "ICSSGPO1_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO2_PORT1", displayName: "ICSSGPO2_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO3_PORT1", displayName: "ICSSGPO3_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO4_PORT1", displayName: "ICSSGPO4_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO5_PORT1", displayName: "ICSSGPO5_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO6_PORT1", displayName: "ICSSGPO6_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO7_PORT1", displayName: "ICSSGPO7_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO8_PORT1", displayName: "ICSSGPO8_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO9_PORT1", displayName: "ICSSGPO9_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO10_PORT1", displayName: "ICSSGPO10_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO11_PORT1", displayName: "ICSSGPO11_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO12_PORT1", displayName: "ICSSGPO12_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO13_PORT1", displayName: "ICSSGPO13_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO14_PORT1", displayName: "ICSSGPO14_PORT1", path: "input_xbar", group: 1 },
    {  name: "ICSSGPO15_PORT1", displayName: "ICSSGPO15_PORT1", path: "input_xbar", group: 1 },
    {  name: "OUTPUTXBAR_OUT0", displayName: "OUTPUTXBAR_OUT0", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT1", displayName: "OUTPUTXBAR_OUT1", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT2", displayName: "OUTPUTXBAR_OUT2", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT3", displayName: "OUTPUTXBAR_OUT3", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT4", displayName: "OUTPUTXBAR_OUT4", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT5", displayName: "OUTPUTXBAR_OUT5", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT6", displayName: "OUTPUTXBAR_OUT6", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT7", displayName: "OUTPUTXBAR_OUT7", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT8", displayName: "OUTPUTXBAR_OUT8", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT9", displayName: "OUTPUTXBAR_OUT9", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT10", displayName: "OUTPUTXBAR_OUT10", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT11", displayName: "OUTPUTXBAR_OUT11", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT12", displayName: "OUTPUTXBAR_OUT12", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT13", displayName: "OUTPUTXBAR_OUT13", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT14", displayName: "OUTPUTXBAR_OUT14", path: "input_xbar", group: 2 },
    {  name: "OUTPUTXBAR_OUT15", displayName: "OUTPUTXBAR_OUT15", path: "input_xbar", group: 2 },
];

let xbarProperties = {
    masterXbarList: [],
    outputInstanceList: [
        { name: "INPUT_XBAR", count: 32},
    ],
    duplicatesPresent: false,
    moduleString: "input_xbar",
}

function getOptionList(calledBy) {
    return xbarSoc.getOptionListSoc(calledBy, xbarProperties, internal_list);
}

function getConfigArr() {
    return xbarSoc.getXbarInstanceConfig(xbarProperties);
}

exports = {
    getConfigArr,
    getOptionList,
};
