/* =============================================================================
 *   Copyright (c) Texas Instruments Incorporated 2022
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef SDL_MBOX_HW_H_
#define SDL_MBOX_HW_H_

#ifdef __cplusplus
extern "C"
{
#endif

/****************************************************************************************************
* Register Definitions
****************************************************************************************************/
/* DSS */
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL                                       (0x00000800U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL                                  (0x00000C88U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI                                    (0x00000C8CU)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR                                   (0x00000C90U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT1                              (0x00000808U)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD                          (0x00000C98U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE                        (0x00000C9CU)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ                         (0x00000CA0U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP                    (0x00000CA4U)
/* RSS */
#if defined (SOC_AWR294X)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL                                       (0x00000090U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL                                  (0x000001F4U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI                                    (0x000001F8U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR                                   (0x000001FCU)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_SEC_ERR_STAT0                              (0x00000094U)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD                          (0x00000204U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE                        (0x00000208U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ                         (0x0000020CU)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP                    (0x00000210U)
#endif
/* MSS */
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_CTRL                                       (0x000001A0U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL                                  (0x000004B0U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI                                    (0x000004B4U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR                                   (0x000004B8U)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_SEC_ERR_STAT0                              (0x00000510U)


/****************************************************************************************************
* Field Definition Macros
****************************************************************************************************/
/* DSS_BUS_SAFETY_CTRL */
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_MASK       (0x00000007U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_SHIFT      (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_RESETVAL   (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_MAX        (0x00000007U)


/* DSS_BUS_SAFETY_SEC_ERR_STAT1 */
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_MBOX_MASK (0x00000020U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_MBOX_SHIFT (0x00000005U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_MBOX_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_BUS_SAFETY_SEC_ERR_STAT1_DSS_MBOX_MAX (0x00000001U)


/* DSS_MBOX_BUS_SAFETY_CTRL */
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_DSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)


/* DSS_MBOX_BUS_SAFETY_FI */

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SEC_MASK    (0x00000010U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SEC_SHIFT   (0x00000004U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SEC_MAX     (0x00000001U)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DED_MASK    (0x00000020U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DED_SHIFT   (0x00000005U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DED_MAX     (0x00000001U)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DATA_MASK   (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DATA_SHIFT  (0x00000008U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_DATA_MAX    (0x000000FFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_MAIN_MASK   (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_MAIN_SHIFT  (0x00000010U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_MAIN_MAX    (0x000000FFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SAFE_MASK   (0xFF000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SAFE_SHIFT  (0x00000018U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_FI_DSS_MBOX_BUS_SAFETY_FI_SAFE_MAX    (0x000000FFU)


/* DSS_MBOX_BUS_SAFETY_ERR */
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_SEC_MASK  (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_SEC_MAX   (0x000000FFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_DED_MASK  (0xFF000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_DSS_MBOX_BUS_SAFETY_ERR_DED_MAX   (0x000000FFU)

#if defined (SOC_AWR294X)
/* RSS_BUS_SAFETY_CTRL */

#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_ENABLE_MASK       (0x00000007U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_ENABLE_SHIFT      (0x00000000U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_ENABLE_RESETVAL   (0x00000000U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_ENABLE_MAX        (0x00000007U)

#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_CLK_DISABLE_MASK  (0x00000070U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_CLK_DISABLE_SHIFT (0x00000004U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_CLK_DISABLE_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RSS_BUS_SAFETY_CTRL_CLK_DISABLE_MAX   (0x00000007U)

#define SDL_RSS_CTRL_RSS_BUS_SAFETY_CTRL_RESETVAL                              (0x00000000U)

/* RSS_BUS_SAFETY_SEC_ERR_STAT0 */
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_MBOX_MASK (0x00000400U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_MBOX_SHIFT (0x0000000AU)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_MBOX_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_BUS_SAFETY_SEC_ERR_STAT0_RSS_MBOX_MAX (0x00000001U)

/* RSS_MBOX_BUS_SAFETY_CTRL */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_RSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)

/* RSS_MBOX_BUS_SAFETY_FI */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SEC_MASK    (0x00000010U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SEC_SHIFT   (0x00000004U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SEC_MAX     (0x00000001U)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DED_MASK    (0x00000020U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DED_SHIFT   (0x00000005U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DED_MAX     (0x00000001U)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DATA_MASK   (0x0000FF00U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DATA_SHIFT  (0x00000008U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_DATA_MAX    (0x000000FFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_MAIN_MASK   (0x00FF0000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_MAIN_SHIFT  (0x00000010U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_MAIN_MAX    (0x000000FFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SAFE_MASK   (0xFF000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SAFE_SHIFT  (0x00000018U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RSS_MBOX_BUS_SAFETY_FI_SAFE_MAX    (0x000000FFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_FI_RESETVAL                           (0x00000000U)

/* RSS_MBOX_BUS_SAFETY_ERR */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_SEC_MASK  (0x00FF0000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_SEC_MAX   (0x000000FFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_DED_MASK  (0xFF000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_RSS_MBOX_BUS_SAFETY_ERR_DED_MAX   (0x000000FFU)

#endif

/* MSS_BUS_SAFETY_CTRL */

#define SDL_MSS_CTRL_MSS_BUS_SAFETY_CTRL_MSS_BUS_SAFETY_CTRL_ENABLE_MASK       (0x00000007U)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_CTRL_MSS_BUS_SAFETY_CTRL_ENABLE_SHIFT      (0x00000000U)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_CTRL_MSS_BUS_SAFETY_CTRL_ENABLE_RESETVAL   (0x00000000U)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_CTRL_MSS_BUS_SAFETY_CTRL_ENABLE_MAX        (0x00000007U)


/* MSS_BUS_SAFETY_SEC_ERR_STAT0 */
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_MBOX_MASK (0x08000000U)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_MBOX_SHIFT (0x0000001BU)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_MBOX_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_BUS_SAFETY_SEC_ERR_STAT0_MSS_MBOX_MAX (0x00000001U)

/* MSS_MBOX_BUS_SAFETY_CTRL */

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_MSS_MBOX_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)

/* MSS_MBOX_BUS_SAFETY_FI */

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SEC_MASK    (0x00000010U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SEC_SHIFT   (0x00000004U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SEC_MAX     (0x00000001U)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DED_MASK    (0x00000020U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DED_SHIFT   (0x00000005U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DED_MAX     (0x00000001U)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DATA_MASK   (0x0000FF00U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DATA_SHIFT  (0x00000008U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_DATA_MAX    (0x000000FFU)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_MAIN_MASK   (0x00FF0000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_MAIN_SHIFT  (0x00000010U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_MAIN_MAX    (0x000000FFU)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SAFE_MASK   (0xFF000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SAFE_SHIFT  (0x00000018U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_FI_MSS_MBOX_BUS_SAFETY_FI_SAFE_MAX    (0x000000FFU)


/* MSS_MBOX_BUS_SAFETY_ERR */

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_SEC_MASK  (0x00FF0000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_SEC_MAX   (0x000000FFU)

#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_DED_MASK  (0xFF000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_MSS_CTRL_MSS_MBOX_BUS_SAFETY_ERR_MSS_MBOX_BUS_SAFETY_ERR_DED_MAX   (0x000000FFU)


/* DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD */

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_RESETVAL                 (0x00000000U)

/* DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE */

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_RESETVAL               (0x00000000U)

/* DSS_MBOX_BUS_SAFETY_ERR_STAT_READ */

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_READ_RESETVAL                (0x00000000U)

/* DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP */

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_RESETVAL           (0x00000000U)

#if defined (SOC_AWR294X)

/* RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_MASK (0xFFFFFFFFU)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_SHIFT (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_STAT_MAX (0xFFFFFFFFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_CMD_RESETVAL                 (0x00000000U)

/* RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_MASK (0xFFFFFFFFU)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_SHIFT (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_STAT_MAX (0xFFFFFFFFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITE_RESETVAL               (0x00000000U)

/* RSS_MBOX_BUS_SAFETY_ERR_STAT_READ */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_MASK (0xFFFFFFFFU)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_SHIFT (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_STAT_MAX (0xFFFFFFFFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_READ_RESETVAL                (0x00000000U)

/* RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP */

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MASK (0xFFFFFFFFU)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_SHIFT (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_RESETVAL (0x00000000U)
#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MAX (0xFFFFFFFFU)

#define SDL_RSS_CTRL_RSS_MBOX_BUS_SAFETY_ERR_STAT_WRITERESP_RESETVAL           (0x00000000U)

#endif

#ifdef __cplusplus
}
#endif
#endif  /* SDL_MBOX_HW_H_ */
