let common = system.getScript("/common");
let xbarSoc = system.getScript(`/xbar/soc/xbar_${common.getSocName()}`);

const internal_list = [
    {  name: "EPWM0_TRIPOUT", displayName: "EPWM0_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM1_TRIPOUT", displayName: "EPWM1_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM2_TRIPOUT", displayName: "EPWM2_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM3_TRIPOUT", displayName: "EPWM3_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM4_TRIPOUT", displayName: "EPWM4_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM5_TRIPOUT", displayName: "EPWM5_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM6_TRIPOUT", displayName: "EPWM6_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM7_TRIPOUT", displayName: "EPWM7_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM8_TRIPOUT", displayName: "EPWM8_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM9_TRIPOUT", displayName: "EPWM9_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM10_TRIPOUT", displayName: "EPWM10_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM11_TRIPOUT", displayName: "EPWM11_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM12_TRIPOUT", displayName: "EPWM12_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM13_TRIPOUT", displayName: "EPWM13_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM14_TRIPOUT", displayName: "EPWM14_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM15_TRIPOUT", displayName: "EPWM15_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM16_TRIPOUT", displayName: "EPWM16_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM17_TRIPOUT", displayName: "EPWM17_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM18_TRIPOUT", displayName: "EPWM18_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM19_TRIPOUT", displayName: "EPWM19_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM20_TRIPOUT", displayName: "EPWM20_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM21_TRIPOUT", displayName: "EPWM21_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM22_TRIPOUT", displayName: "EPWM22_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM23_TRIPOUT", displayName: "EPWM23_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM24_TRIPOUT", displayName: "EPWM24_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM25_TRIPOUT", displayName: "EPWM25_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM26_TRIPOUT", displayName: "EPWM26_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM27_TRIPOUT", displayName: "EPWM27_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM28_TRIPOUT", displayName: "EPWM28_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM29_TRIPOUT", displayName: "EPWM29_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM30_TRIPOUT", displayName: "EPWM30_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM31_TRIPOUT", displayName: "EPWM31_TRIPOUT", path: "output_xbar", group: 0 },
    {  name: "EPWM0_SOCA", displayName: "EPWM0_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM1_SOCA", displayName: "EPWM1_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM2_SOCA", displayName: "EPWM2_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM3_SOCA", displayName: "EPWM3_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM4_SOCA", displayName: "EPWM4_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM5_SOCA", displayName: "EPWM5_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM6_SOCA", displayName: "EPWM6_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM7_SOCA", displayName: "EPWM7_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM8_SOCA", displayName: "EPWM8_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM9_SOCA", displayName: "EPWM9_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM10_SOCA", displayName: "EPWM10_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM11_SOCA", displayName: "EPWM11_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM12_SOCA", displayName: "EPWM12_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM13_SOCA", displayName: "EPWM13_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM14_SOCA", displayName: "EPWM14_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM15_SOCA", displayName: "EPWM15_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM16_SOCA", displayName: "EPWM16_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM17_SOCA", displayName: "EPWM17_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM18_SOCA", displayName: "EPWM18_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM19_SOCA", displayName: "EPWM19_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM20_SOCA", displayName: "EPWM20_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM21_SOCA", displayName: "EPWM21_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM22_SOCA", displayName: "EPWM22_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM23_SOCA", displayName: "EPWM23_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM24_SOCA", displayName: "EPWM24_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM25_SOCA", displayName: "EPWM25_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM26_SOCA", displayName: "EPWM26_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM27_SOCA", displayName: "EPWM27_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM28_SOCA", displayName: "EPWM28_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM29_SOCA", displayName: "EPWM29_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM30_SOCA", displayName: "EPWM30_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM31_SOCA", displayName: "EPWM31_SOCA", path: "output_xbar", group: 1 },
    {  name: "EPWM0_SOCB", displayName: "EPWM0_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM1_SOCB", displayName: "EPWM1_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM2_SOCB", displayName: "EPWM2_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM3_SOCB", displayName: "EPWM3_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM4_SOCB", displayName: "EPWM4_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM5_SOCB", displayName: "EPWM5_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM6_SOCB", displayName: "EPWM6_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM7_SOCB", displayName: "EPWM7_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM8_SOCB", displayName: "EPWM8_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM9_SOCB", displayName: "EPWM9_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM10_SOCB", displayName: "EPWM10_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM11_SOCB", displayName: "EPWM11_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM12_SOCB", displayName: "EPWM12_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM13_SOCB", displayName: "EPWM13_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM14_SOCB", displayName: "EPWM14_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM15_SOCB", displayName: "EPWM15_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM16_SOCB", displayName: "EPWM16_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM17_SOCB", displayName: "EPWM17_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM18_SOCB", displayName: "EPWM18_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM19_SOCB", displayName: "EPWM19_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM20_SOCB", displayName: "EPWM20_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM21_SOCB", displayName: "EPWM21_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM22_SOCB", displayName: "EPWM22_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM23_SOCB", displayName: "EPWM23_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM24_SOCB", displayName: "EPWM24_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM25_SOCB", displayName: "EPWM25_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM26_SOCB", displayName: "EPWM26_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM27_SOCB", displayName: "EPWM27_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM28_SOCB", displayName: "EPWM28_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM29_SOCB", displayName: "EPWM29_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM30_SOCB", displayName: "EPWM30_SOCB", path: "output_xbar", group: 2 },
    {  name: "EPWM31_SOCB", displayName: "EPWM31_SOCB", path: "output_xbar", group: 2 },
    {  name: "DEL0_ACTIVE", displayName: "DEL0_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL1_ACTIVE", displayName: "DEL1_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL2_ACTIVE", displayName: "DEL2_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL3_ACTIVE", displayName: "DEL3_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL4_ACTIVE", displayName: "DEL4_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL5_ACTIVE", displayName: "DEL5_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL6_ACTIVE", displayName: "DEL6_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL7_ACTIVE", displayName: "DEL7_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL8_ACTIVE", displayName: "DEL8_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL9_ACTIVE", displayName: "DEL9_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL10_ACTIVE", displayName: "DEL10_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL11_ACTIVE", displayName: "DEL11_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL12_ACTIVE", displayName: "DEL12_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL13_ACTIVE", displayName: "DEL13_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL14_ACTIVE", displayName: "DEL14_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL15_ACTIVE", displayName: "DEL15_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL16_ACTIVE", displayName: "DEL16_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL17_ACTIVE", displayName: "DEL17_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL18_ACTIVE", displayName: "DEL18_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL19_ACTIVE", displayName: "DEL19_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL20_ACTIVE", displayName: "DEL20_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL21_ACTIVE", displayName: "DEL21_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL22_ACTIVE", displayName: "DEL22_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL23_ACTIVE", displayName: "DEL23_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL24_ACTIVE", displayName: "DEL24_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL25_ACTIVE", displayName: "DEL25_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL26_ACTIVE", displayName: "DEL26_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL27_ACTIVE", displayName: "DEL27_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL28_ACTIVE", displayName: "DEL28_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL29_ACTIVE", displayName: "DEL29_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL30_ACTIVE", displayName: "DEL30_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL31_ACTIVE", displayName: "DEL31_ACTIVE", path: "output_xbar", group: 3 },
    {  name: "DEL0_TRIP", displayName: "DEL0_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL1_TRIP", displayName: "DEL1_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL2_TRIP", displayName: "DEL2_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL3_TRIP", displayName: "DEL3_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL4_TRIP", displayName: "DEL4_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL5_TRIP", displayName: "DEL5_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL6_TRIP", displayName: "DEL6_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL7_TRIP", displayName: "DEL7_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL8_TRIP", displayName: "DEL8_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL9_TRIP", displayName: "DEL9_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL10_TRIP", displayName: "DEL10_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL11_TRIP", displayName: "DEL11_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL12_TRIP", displayName: "DEL12_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL13_TRIP", displayName: "DEL13_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL14_TRIP", displayName: "DEL14_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL15_TRIP", displayName: "DEL15_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL16_TRIP", displayName: "DEL16_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL17_TRIP", displayName: "DEL17_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL18_TRIP", displayName: "DEL18_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL19_TRIP", displayName: "DEL19_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL20_TRIP", displayName: "DEL20_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL21_TRIP", displayName: "DEL21_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL22_TRIP", displayName: "DEL22_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL23_TRIP", displayName: "DEL23_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL24_TRIP", displayName: "DEL24_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL25_TRIP", displayName: "DEL25_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL26_TRIP", displayName: "DEL26_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL27_TRIP", displayName: "DEL27_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL28_TRIP", displayName: "DEL28_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL29_TRIP", displayName: "DEL29_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL30_TRIP", displayName: "DEL30_TRIP", path: "output_xbar", group: 4 },
    {  name: "DEL31_TRIP", displayName: "DEL31_TRIP", path: "output_xbar", group: 4 },
    {  name: "SD0_FILT0_CEVT1", displayName: "SD0_FILT0_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT0_CEVT2", displayName: "SD0_FILT0_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT0_CMPHZ", displayName: "SD0_FILT0_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT1_CEVT1", displayName: "SD0_FILT1_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT1_CEVT2", displayName: "SD0_FILT1_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT1_CMPHZ", displayName: "SD0_FILT1_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT2_CEVT1", displayName: "SD0_FILT2_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT2_CEVT2", displayName: "SD0_FILT2_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT2_CMPHZ", displayName: "SD0_FILT2_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT3_CEVT1", displayName: "SD0_FILT3_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT3_CEVT2", displayName: "SD0_FILT3_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD0_FILT3_CMPHZ", displayName: "SD0_FILT3_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT0_CEVT1", displayName: "SD1_FILT0_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT0_CEVT2", displayName: "SD1_FILT0_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT0_CMPHZ", displayName: "SD1_FILT0_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT1_CEVT1", displayName: "SD1_FILT1_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT1_CEVT2", displayName: "SD1_FILT1_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT1_CMPHZ", displayName: "SD1_FILT1_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT2_CEVT1", displayName: "SD1_FILT2_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT2_CEVT2", displayName: "SD1_FILT2_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT2_CMPHZ", displayName: "SD1_FILT2_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT3_CEVT1", displayName: "SD1_FILT3_CEVT1", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT3_CEVT2", displayName: "SD1_FILT3_CEVT2", path: "output_xbar", group: 5 },
    {  name: "SD1_FILT3_CMPHZ", displayName: "SD1_FILT3_CMPHZ", path: "output_xbar", group: 5 },
    {  name: "CMPSSA0_CTRIPL", displayName: "CMPSSA0_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA0_CTRIPH", displayName: "CMPSSA0_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA1_CTRIPL", displayName: "CMPSSA1_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA1_CTRIPH", displayName: "CMPSSA1_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA2_CTRIPL", displayName: "CMPSSA2_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA2_CTRIPH", displayName: "CMPSSA2_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA3_CTRIPL", displayName: "CMPSSA3_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA3_CTRIPH", displayName: "CMPSSA3_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA4_CTRIPL", displayName: "CMPSSA4_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA4_CTRIPH", displayName: "CMPSSA4_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA5_CTRIPL", displayName: "CMPSSA5_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA5_CTRIPH", displayName: "CMPSSA5_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA6_CTRIPL", displayName: "CMPSSA6_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA6_CTRIPH", displayName: "CMPSSA6_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA7_CTRIPL", displayName: "CMPSSA7_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA7_CTRIPH", displayName: "CMPSSA7_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA8_CTRIPL", displayName: "CMPSSA8_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA8_CTRIPH", displayName: "CMPSSA8_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSA9_CTRIPL", displayName: "CMPSSA9_CTRIPL", path: "output_xbar", group: 6 },
    {  name: "CMPSSA9_CTRIPH", displayName: "CMPSSA9_CTRIPH", path: "output_xbar", group: 6 },
    {  name: "CMPSSB0_CTRIPL", displayName: "CMPSSB0_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB0_CTRIPH", displayName: "CMPSSB0_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB1_CTRIPL", displayName: "CMPSSB1_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB1_CTRIPH", displayName: "CMPSSB1_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB2_CTRIPL", displayName: "CMPSSB2_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB2_CTRIPH", displayName: "CMPSSB2_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB3_CTRIPL", displayName: "CMPSSB3_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB3_CTRIPH", displayName: "CMPSSB3_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB4_CTRIPL", displayName: "CMPSSB4_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB4_CTRIPH", displayName: "CMPSSB4_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB5_CTRIPL", displayName: "CMPSSB5_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB5_CTRIPH", displayName: "CMPSSB5_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB6_CTRIPL", displayName: "CMPSSB6_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB6_CTRIPH", displayName: "CMPSSB6_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB7_CTRIPL", displayName: "CMPSSB7_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB7_CTRIPH", displayName: "CMPSSB7_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB8_CTRIPL", displayName: "CMPSSB8_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB8_CTRIPH", displayName: "CMPSSB8_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "CMPSSB9_CTRIPL", displayName: "CMPSSB9_CTRIPL", path: "output_xbar", group: 7 },
    {  name: "CMPSSB9_CTRIPH", displayName: "CMPSSB9_CTRIPH", path: "output_xbar", group: 7 },
    {  name: "ADC0_EVT1", displayName: "ADC0_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC0_EVT2", displayName: "ADC0_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC0_EVT3", displayName: "ADC0_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC0_EVT4", displayName: "ADC0_EVT4", path: "output_xbar", group: 8 },
    {  name: "ADC1_EVT1", displayName: "ADC1_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC1_EVT2", displayName: "ADC1_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC1_EVT3", displayName: "ADC1_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC1_EVT4", displayName: "ADC1_EVT4", path: "output_xbar", group: 8 },
    {  name: "ADC2_EVT1", displayName: "ADC2_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC2_EVT2", displayName: "ADC2_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC2_EVT3", displayName: "ADC2_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC2_EVT4", displayName: "ADC2_EVT4", path: "output_xbar", group: 8 },
    {  name: "ADC3_EVT1", displayName: "ADC3_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC3_EVT2", displayName: "ADC3_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC3_EVT3", displayName: "ADC3_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC3_EVT4", displayName: "ADC3_EVT4", path: "output_xbar", group: 8 },
    {  name: "ADC4_EVT1", displayName: "ADC4_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC4_EVT2", displayName: "ADC4_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC4_EVT3", displayName: "ADC4_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC4_EVT4", displayName: "ADC4_EVT4", path: "output_xbar", group: 8 },
    {  name: "ADC_R0_EVT1", displayName: "ADC_R0_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC_R0_EVT2", displayName: "ADC_R0_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC_R0_EVT3", displayName: "ADC_R0_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC_R0_EVT4", displayName: "ADC_R0_EVT4", path: "output_xbar", group: 8 },
    {  name: "ADC_R1_EVT1", displayName: "ADC_R1_EVT1", path: "output_xbar", group: 8 },
    {  name: "ADC_R1_EVT2", displayName: "ADC_R1_EVT2", path: "output_xbar", group: 8 },
    {  name: "ADC_R1_EVT3", displayName: "ADC_R1_EVT3", path: "output_xbar", group: 8 },
    {  name: "ADC_R1_EVT4", displayName: "ADC_R1_EVT4", path: "output_xbar", group: 8 },

    {  name: "EPWM_SYNCOUT_XBAR0", displayName: "EPWM_SYNCOUT_XBAR0", path: "output_xbar", group: 9 },
    {  name: "EPWM_SYNCOUT_XBAR1", displayName: "EPWM_SYNCOUT_XBAR1", path: "output_xbar", group: 9 },
    {  name: "EPWM_SYNCOUT_XBAR2", displayName: "EPWM_SYNCOUT_XBAR2", path: "output_xbar", group: 9 },
    {  name: "EPWM_SYNCOUT_XBAR3", displayName: "EPWM_SYNCOUT_XBAR3", path: "output_xbar", group: 9 },

    {  name: "EQEP0_I_OUT", displayName: "EQEP0_I_OUT", path: "output_xbar", group: 9 },
    {  name: "EQEP0_S_OUT", displayName: "EQEP0_S_OUT", path: "output_xbar", group: 9 },
    {  name: "EQEP1_I_OUT", displayName: "EQEP1_I_OUT", path: "output_xbar", group: 9 },
    {  name: "EQEP1_S_OUT", displayName: "EQEP1_S_OUT", path: "output_xbar", group: 9 },
    {  name: "EQEP2_I_OUT", displayName: "EQEP2_I_OUT", path: "output_xbar", group: 9 },
    {  name: "EQEP2_S_OUT", displayName: "EQEP2_S_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP0_OUT", displayName: "ECAP0_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP1_OUT", displayName: "ECAP1_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP2_OUT", displayName: "ECAP2_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP3_OUT", displayName: "ECAP3_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP4_OUT", displayName: "ECAP4_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP5_OUT", displayName: "ECAP5_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP6_OUT", displayName: "ECAP6_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP7_OUT", displayName: "ECAP7_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP8_OUT", displayName: "ECAP8_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP9_OUT", displayName: "ECAP9_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP10_OUT", displayName: "ECAP10_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP11_OUT", displayName: "ECAP11_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP12_OUT", displayName: "ECAP12_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP13_OUT", displayName: "ECAP13_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP14_OUT", displayName: "ECAP14_OUT", path: "output_xbar", group: 9 },
    {  name: "ECAP15_OUT", displayName: "ECAP15_OUT", path: "output_xbar", group: 9 },
    {  name: "FSIRX0_RX_TRIG0", displayName: "FSIRX0_RX_TRIG0", path: "output_xbar", group: 10 },
    {  name: "FSIRX0_RX_TRIG1", displayName: "FSIRX0_RX_TRIG1", path: "output_xbar", group: 10 },
    {  name: "FSIRX0_RX_TRIG2", displayName: "FSIRX0_RX_TRIG2", path: "output_xbar", group: 10 },
    {  name: "FSIRX0_RX_TRIG3", displayName: "FSIRX0_RX_TRIG3", path: "output_xbar", group: 10 },
    {  name: "FSIRX1_RX_TRIG0", displayName: "FSIRX1_RX_TRIG0", path: "output_xbar", group: 10 },
    {  name: "FSIRX1_RX_TRIG1", displayName: "FSIRX1_RX_TRIG1", path: "output_xbar", group: 10 },
    {  name: "FSIRX1_RX_TRIG2", displayName: "FSIRX1_RX_TRIG2", path: "output_xbar", group: 10 },
    {  name: "FSIRX1_RX_TRIG3", displayName: "FSIRX1_RX_TRIG3", path: "output_xbar", group: 10 },
    {  name: "FSIRX2_RX_TRIG0", displayName: "FSIRX2_RX_TRIG0", path: "output_xbar", group: 10 },
    {  name: "FSIRX2_RX_TRIG1", displayName: "FSIRX2_RX_TRIG1", path: "output_xbar", group: 10 },
    {  name: "FSIRX2_RX_TRIG2", displayName: "FSIRX2_RX_TRIG2", path: "output_xbar", group: 10 },
    {  name: "FSIRX2_RX_TRIG3", displayName: "FSIRX2_RX_TRIG3", path: "output_xbar", group: 10 },
    {  name: "FSIRX3_RX_TRIG0", displayName: "FSIRX3_RX_TRIG0", path: "output_xbar", group: 10 },
    {  name: "FSIRX3_RX_TRIG1", displayName: "FSIRX3_RX_TRIG1", path: "output_xbar", group: 10 },
    {  name: "FSIRX3_RX_TRIG2", displayName: "FSIRX3_RX_TRIG2", path: "output_xbar", group: 10 },
    {  name: "FSIRX3_RX_TRIG3", displayName: "FSIRX3_RX_TRIG3", path: "output_xbar", group: 10 },
    {  name: "INPUTXBAR_OUT7 ", displayName: "INPUTXBAR_OUT7", path: "output_xbar", group: 10 },
    {  name: "INPUTXBAR_OUT15", displayName: "INPUTXBAR_OUT15", path: "output_xbar", group: 10 },
    {  name: "INPUTXBAR_OUT23", displayName: "INPUTXBAR_OUT23", path: "output_xbar", group: 10 },
    {  name: "INPUTXBAR_OUT31", displayName: "INPUTXBAR_OUT31", path: "output_xbar", group: 10 },
    {  name: "INTXBAR_OUT7", displayName: "INTXBAR_OUT7", path: "output_xbar", group: 10 },
    {  name: "INTXBAR_OUT15", displayName: "INTXBAR_OUT15", path: "output_xbar", group: 10 },
];

const XBAR_Latch_Source = [
    {  name: "NON_LATCHED_OUTPUT", displayName: "Select Non Latched Output" },
    {  name: "LATCHED_OUTPUT", displayName: "Select Latched Output" },
];

const XBAR_Stretched_Pulse_Source = [
    {  name: "NON_STRETCHED_OUTPUT", displayName: "Select Non Stretched Output" },
    {  name: "STRETCHED_OUTPUT", displayName: "Select Stretched Output" },
];

const XBAR_Stretched_Pulse_Length = [
    {  name: "PULSE_LENGTH_16_SYSCLK", displayName: "Output Signal Stretched Pulse Length is 16 SYSCLK" },
    {  name: "PULSE_LENGTH_32_SYSCLK", displayName: "Output Signal Stretched Pulse Length is 32 SYSCLK" },
];

let xbarProperties = {
    masterXbarList: ["epwm_syncout_xbar"],
    outputInstanceList: [
        { name: "OUTPUT_XBAR", count: 16},
    ],
    duplicatesPresent: false,
    moduleString: "output_xbar",
}

function getOptionList(calledBy) {
    return xbarSoc.getOptionListSoc(calledBy, xbarProperties, internal_list);
}

function getConfigArr() {
    return xbarSoc.getXbarInstanceConfig(xbarProperties);
}

function getInterfaceName(instance) {
    return "OUTPUTXBAR";
}

function supportXbarConfig(outputSelected, instance, count) {
    return xbarSoc.supportXbarConfigSoc(outputSelected, instance, xbarProperties, count);
}

exports = {
    getConfigArr,
    getOptionList,
    XBAR_Latch_Source: XBAR_Latch_Source,
    XBAR_Stretched_Pulse_Source: XBAR_Stretched_Pulse_Source,
    XBAR_Stretched_Pulse_Length: XBAR_Stretched_Pulse_Length,
    getInterfaceName,
    supportXbarConfig,
};
