/********************************************************************
*
* TPCC0_DMATRIGGER_XBAR  INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_TPCC0_DMATRIGGER_XBAR_INTERRUPT_MAP_H_
#define CSLR_TPCC0_DMATRIGGER_XBAR_INTERRUPT_MAP_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: TPCC0_DMATRIGGER_XBAR
*/


#define  CSLR_TPCC0_TRIGGERXBAR_LIN0_RX_DMA_REQ           0
#define  CSLR_TPCC0_TRIGGERXBAR_LIN0_TX_DMA_REQ           1
#define  CSLR_TPCC0_TRIGGERXBAR_LIN1_RX_DMA_REQ           2
#define  CSLR_TPCC0_TRIGGERXBAR_LIN1_TX_DMA_REQ           3
#define  CSLR_TPCC0_TRIGGERXBAR_LIN2_RX_DMA_REQ           4
#define  CSLR_TPCC0_TRIGGERXBAR_LIN2_TX_DMA_REQ           5
#define  CSLR_TPCC0_TRIGGERXBAR_LIN3_RX_DMA_REQ           6
#define  CSLR_TPCC0_TRIGGERXBAR_LIN3_TX_DMA_REQ           7
#define  CSLR_TPCC0_TRIGGERXBAR_LIN4_RX_DMA_REQ           8
#define  CSLR_TPCC0_TRIGGERXBAR_LIN4_TX_DMA_REQ           9
#define  CSLR_TPCC0_TRIGGERXBAR_I2C0_TX_DMA_REQ           10
#define  CSLR_TPCC0_TRIGGERXBAR_I2C0_RX_DMA_REQ           11
#define  CSLR_TPCC0_TRIGGERXBAR_I2C1_TX_DMA_REQ           12
#define  CSLR_TPCC0_TRIGGERXBAR_I2C1_RX_DMA_REQ           13
#define  CSLR_TPCC0_TRIGGERXBAR_I2C2_TX_DMA_REQ           14
#define  CSLR_TPCC0_TRIGGERXBAR_I2C2_RX_DMA_REQ           15
#define  CSLR_TPCC0_TRIGGERXBAR_I2C3_TX_DMA_REQ           16
#define  CSLR_TPCC0_TRIGGERXBAR_I2C3_RX_DMA_REQ           17
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_READ_DMA_REQ_0     18
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_READ_DMA_REQ_1     19
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_READ_DMA_REQ_2     20
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_READ_DMA_REQ_3     21
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_WRITE_DMA_REQ_0    22
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_WRITE_DMA_REQ_1    23
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_WRITE_DMA_REQ_2    24
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_WRITE_DMA_REQ_3    25
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_READ_DMA_REQ_0     26
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_READ_DMA_REQ_1     27
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_READ_DMA_REQ_2     28
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_READ_DMA_REQ_3     29
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_WRITE_DMA_REQ_0    30
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_WRITE_DMA_REQ_1    31
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_WRITE_DMA_REQ_2    32
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_WRITE_DMA_REQ_3    33
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_READ_DMA_REQ_0     34
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_READ_DMA_REQ_1     35
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_READ_DMA_REQ_2     36
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_READ_DMA_REQ_3     37
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_WRITE_DMA_REQ_0    38
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_WRITE_DMA_REQ_1    39
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_WRITE_DMA_REQ_2    40
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_WRITE_DMA_REQ_3    41
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_READ_DMA_REQ_0     42
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_READ_DMA_REQ_1     43
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_READ_DMA_REQ_2     44
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_READ_DMA_REQ_3     45
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_WRITE_DMA_REQ_0    46
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_WRITE_DMA_REQ_1    47
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_WRITE_DMA_REQ_2    48
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_WRITE_DMA_REQ_3    49
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_READ_DMA_REQ_0     50
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_READ_DMA_REQ_1     51
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_READ_DMA_REQ_2     52
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_READ_DMA_REQ_3     53
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_WRITE_DMA_REQ_0    54
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_WRITE_DMA_REQ_1    55
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_WRITE_DMA_REQ_2    56
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI4_WRITE_DMA_REQ_3    57
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_0            58
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_1            59
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_2            60
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_3            61
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_0            62
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_1            63
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_2            64
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_3            65
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_0            66
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_1            67
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_2            68
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_3            69
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_0            70
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_1            71
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_2            72
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_3            73
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_0           74
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_1           75
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_2           76
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_3           77
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_0           78
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_1           79
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_2           80
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_3           81
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_DMA_REQ_0           82
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_DMA_REQ_1           83
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_DMA_REQ_2           84
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_DMA_REQ_3           85
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_DMA_REQ_0           86
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_DMA_REQ_1           87
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_DMA_REQ_2           88
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_DMA_REQ_3           89
#define  CSLR_TPCC0_TRIGGERXBAR_UART0_DMA_REQ_0           90
#define  CSLR_TPCC0_TRIGGERXBAR_UART0_DMA_REQ_1           91
#define  CSLR_TPCC0_TRIGGERXBAR_UART1_DMA_REQ_0           92
#define  CSLR_TPCC0_TRIGGERXBAR_UART1_DMA_REQ_1           93
#define  CSLR_TPCC0_TRIGGERXBAR_UART2_DMA_REQ_0           94
#define  CSLR_TPCC0_TRIGGERXBAR_UART2_DMA_REQ_1           95
#define  CSLR_TPCC0_TRIGGERXBAR_UART3_DMA_REQ_0           96
#define  CSLR_TPCC0_TRIGGERXBAR_UART3_DMA_REQ_1           97
#define  CSLR_TPCC0_TRIGGERXBAR_UART4_DMA_REQ_0           98
#define  CSLR_TPCC0_TRIGGERXBAR_UART4_DMA_REQ_1           99
#define  CSLR_TPCC0_TRIGGERXBAR_UART5_DMA_REQ_0           100
#define  CSLR_TPCC0_TRIGGERXBAR_UART5_DMA_REQ_1           101
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC0_DMA_REQ_0           102
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC0_DMA_REQ_1           103
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC0_DMA_REQ_2           104
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC0_DMA_REQ_3           105
#define  CSLR_TPCC0_TRIGGERXBAR_QSPI0_INTR_REQ            106
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_4       107
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_5       108
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_6       109
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_7       110
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR1_OUT_0   111
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR1_OUT_1   112
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR0_OUT_10  113
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR0_OUT_11  114
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_0  115
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_1   116
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_2   117
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_3   118
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_4   119
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_5   120
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_6   121
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_7   122
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_8   123
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_9   124
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_10  125
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_11  126
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_12  127
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_13  128
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_14  129
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR_OUT_15  130
#define  CSLR_TPCC0_TRIGGERXBAR_MMC0_READ_DMA_REQ         131
#define  CSLR_TPCC0_TRIGGERXBAR_MMC0_WRITE_DMA_REQ        132
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_0        133
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_1        134
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_2        135
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_3        136
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_4        137
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_5        138
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_0        139
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_1        140
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_2        141
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_3        142
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_4        143
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_5        144
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_6        145
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_7        146
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_0           147
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_1           148
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_2           149
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_3           150
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_4           151
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_5           152
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_FE_INTR_6           153
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_0           154
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_1           155
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_2           156
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_3           157
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_4           158
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_5           159
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_FE_INTR_6           160
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_0           161
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_1           162
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_2           163
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_3           164
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_4           165
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_5           166
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN2_FE_INTR_6           167
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_0           168
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_1           169
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_2           170
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_3           171
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_4           172
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_5           173
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN3_FE_INTR_6           174
#define  CSLR_TPCC0_TRIGGERXBAR_GPMC_SDMAREQ              175

#ifdef __cplusplus
}
#endif
#endif /* CSLR_TPCC0_DMATRIGGER_XBAR_INTERRUPT_MAP_H_ */
