/********************************************************************
*
* TPCC0_DMATRIGGER_XBAR  INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_TPCC0_DMATRIGGER_XBAR_INTERRUPT_MAP_H_
#define CSLR_TPCC0_DMATRIGGER_XBAR_INTERRUPT_MAP_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: TPCC0_DMATRIGGER_XBAR
*/


#define  CSLR_TPCC0_TRIGGERXBAR_LIN0_RX_DMA_REQ           0
#define  CSLR_TPCC0_TRIGGERXBAR_LIN0_TX_DMA_REQ           1
#define  CSLR_TPCC0_TRIGGERXBAR_LIN1_RX_DMA_REQ           2
#define  CSLR_TPCC0_TRIGGERXBAR_LIN1_TX_DMA_REQ           3
#define  CSLR_TPCC0_TRIGGERXBAR_LIN2_RX_DMA_REQ           4
#define  CSLR_TPCC0_TRIGGERXBAR_LIN2_TX_DMA_REQ           5
#define  CSLR_TPCC0_TRIGGERXBAR_I2C0_TX_DMA_REQ           6
#define  CSLR_TPCC0_TRIGGERXBAR_I2C0_RX_DMA_REQ           7
#define  CSLR_TPCC0_TRIGGERXBAR_I2C1_TX_DMA_REQ           8
#define  CSLR_TPCC0_TRIGGERXBAR_I2C1_RX_DMA_REQ           9
#define  CSLR_TPCC0_TRIGGERXBAR_I2C2_TX_DMA_REQ           10
#define  CSLR_TPCC0_TRIGGERXBAR_I2C2_RX_DMA_REQ           11
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_READ_DMA_REQ_0     12
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_READ_DMA_REQ_1     13
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_WRITE_DMA_REQ_0    14
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI0_WRITE_DMA_REQ_1    15
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_READ_DMA_REQ_0     16
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_READ_DMA_REQ_1     17
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_WRITE_DMA_REQ_0    18
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI1_WRITE_DMA_REQ_1    19
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_READ_DMA_REQ_0     20
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_READ_DMA_REQ_1     21
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_WRITE_DMA_REQ_0    22
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI2_WRITE_DMA_REQ_1    23
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_READ_DMA_REQ_0     24
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_READ_DMA_REQ_1     25
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_WRITE_DMA_REQ_0    26
#define  CSLR_TPCC0_TRIGGERXBAR_MCSPI3_WRITE_DMA_REQ_1    27
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_0            28
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_1            29
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_2            30
#define  CSLR_TPCC0_TRIGGERXBAR_RTI0_DMA_REQ_3            31
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_0            32
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_1            33
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_2            34
#define  CSLR_TPCC0_TRIGGERXBAR_RTI1_DMA_REQ_3            35
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_0            36
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_1            37
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_2            38
#define  CSLR_TPCC0_TRIGGERXBAR_RTI2_DMA_REQ_3            39
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_0            40
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_1            41
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_2            42
#define  CSLR_TPCC0_TRIGGERXBAR_RTI3_DMA_REQ_3            43
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_0           44
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_1           45
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_2           46
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN0_DMA_REQ_3           47
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_0           48
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_1           49
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_2           50
#define  CSLR_TPCC0_TRIGGERXBAR_MCAN1_DMA_REQ_3           51
#define  CSLR_TPCC0_TRIGGERXBAR_USART0_DMA_REQ_0          52
#define  CSLR_TPCC0_TRIGGERXBAR_USART0_DMA_REQ_1          53
#define  CSLR_TPCC0_TRIGGERXBAR_USART1_DMA_REQ_0          54
#define  CSLR_TPCC0_TRIGGERXBAR_USART1_DMA_REQ_1          55
#define  CSLR_TPCC0_TRIGGERXBAR_USART2_DMA_REQ_0          56
#define  CSLR_TPCC0_TRIGGERXBAR_USART2_DMA_REQ_1          57
#define  CSLR_TPCC0_TRIGGERXBAR_USART3_DMA_REQ_0          58
#define  CSLR_TPCC0_TRIGGERXBAR_USART3_DMA_REQ_1          59
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC_DMA_EVENT_0          60
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC_DMA_EVENT_1          61
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC_DMA_EVENT_2          62
#define  CSLR_TPCC0_TRIGGERXBAR_MCRC_DMA_EVENT_3          63
#define  CSLR_TPCC0_TRIGGERXBAR_OSPI0_INTR_REQ            64
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_4       65
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_5       66
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_6       67
#define  CSLR_TPCC0_TRIGGERXBAR_GPIO_INTRXBAR_OUT_7       68
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR1_OUT_0   69
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR1_OUT_1   70
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR0_OUT_10  71
#define  CSLR_TPCC0_TRIGGERXBAR_SOC_TIMESYNCXBAR0_OUT_11  72
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_0  73
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_1  74
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_2  75
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_3  76
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_4  77
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_5  78
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_6  79
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_7  80
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_8  81
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_9  82
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_10 83
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_11 84
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_12 85
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_13 86
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_14 87
#define  CSLR_TPCC0_TRIGGERXBAR_CONTROLSS_DMAXBAR0_OUT_15 88
#define  CSLR_TPCC0_TRIGGERXBAR_MMC0_READ_DMA_REQ         89
#define  CSLR_TPCC0_TRIGGERXBAR_MMC0_WRITE_DMA_REQ        90
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_0        91
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_1        92
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_2        93
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_3        94
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_4        95
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_SHA_DMA_REQ_5        96
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_0        97
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_1        98
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_2        99
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_3        100
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_4        101
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_5        102
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_6        103
#define  CSLR_TPCC0_TRIGGERXBAR_DTHE_AES_DMA_REQ_7        104
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_0         105
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_1         106
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_2         107
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_3         108
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_4         109
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_5         110
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS0_FE_INTR_6         111
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_0         112
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_1         113
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_2         114
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_3         115
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_4         116
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_5         117
#define  CSLR_TPCC0_TRIGGERXBAR_MCANSS1_FE_INTR_6         118
#define  CSLR_TPCC0_TRIGGERXBAR_GPMC_DMA_REQ              119
#define  CSLR_TPCC0_TRIGGERXBAR_OSPI1_INTR_REQ            120


#ifdef __cplusplus
}
#endif
#endif /* CSLR_TPCC0_DMATRIGGER_XBAR_INTERRUPT_MAP_H_ */
