let common = system.getScript("/common");
let xbarSoc = system.getScript(`/xbar/soc/xbar_${common.getSocName()}`);

const internal_list = [
    {   name: "DMA_TRIG_XBAR_LIN0_RXDMA", displayName: "LIN0_RXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN0_TXDMA", displayName: "LIN0_TXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN1_RXDMA", displayName: "LIN1_RXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN1_TXDMA", displayName: "LIN1_TXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN2_RXDMA", displayName: "LIN2_RXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN2_TXDMA", displayName: "LIN2_TXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN3_RXDMA", displayName: "LIN3_RXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN3_TXDMA", displayName: "LIN3_TXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN4_RXDMA", displayName: "LIN4_RXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_LIN4_TXDMA", displayName: "LIN4_TXDMA", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C0_TX", displayName: "I2C0_TX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C0_RX", displayName: "I2C0_RX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C1_TX", displayName: "I2C1_TX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C1_RX", displayName: "I2C1_RX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C2_TX", displayName: "I2C2_TX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C2_RX", displayName: "I2C2_RX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C3_TX", displayName: "I2C3_TX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_I2C3_RX", displayName: "I2C3_RX", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_READ_REQ0", displayName: "SPI0_DMA_READ_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_READ_REQ1", displayName: "SPI0_DMA_READ_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_READ_REQ2", displayName: "SPI0_DMA_READ_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_READ_REQ3", displayName: "SPI0_DMA_READ_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_WRITE_REQ0", displayName: "SPI0_DMA_WRITE_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_WRITE_REQ1", displayName: "SPI0_DMA_WRITE_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_WRITE_REQ2", displayName: "SPI0_DMA_WRITE_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI0_DMA_WRITE_REQ3", displayName: "SPI0_DMA_WRITE_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_READ_REQ0", displayName: "SPI1_DMA_READ_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_READ_REQ1", displayName: "SPI1_DMA_READ_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_READ_REQ2", displayName: "SPI1_DMA_READ_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_READ_REQ3", displayName: "SPI1_DMA_READ_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_WRITE_REQ0", displayName: "SPI1_DMA_WRITE_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_WRITE_REQ1", displayName: "SPI1_DMA_WRITE_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_WRITE_REQ2", displayName: "SPI1_DMA_WRITE_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI1_DMA_WRITE_REQ3", displayName: "SPI1_DMA_WRITE_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_READ_REQ0", displayName: "SPI2_DMA_READ_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_READ_REQ1", displayName: "SPI2_DMA_READ_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_READ_REQ2", displayName: "SPI2_DMA_READ_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_READ_REQ3", displayName: "SPI2_DMA_READ_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_WRITE_REQ0", displayName: "SPI2_DMA_WRITE_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_WRITE_REQ1", displayName: "SPI2_DMA_WRITE_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_WRITE_REQ2", displayName: "SPI2_DMA_WRITE_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI2_DMA_WRITE_REQ3", displayName: "SPI2_DMA_WRITE_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_READ_REQ0", displayName: "SPI3_DMA_READ_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_READ_REQ1", displayName: "SPI3_DMA_READ_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_READ_REQ2", displayName: "SPI3_DMA_READ_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_READ_REQ3", displayName: "SPI3_DMA_READ_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_WRITE_REQ0", displayName: "SPI3_DMA_WRITE_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_WRITE_REQ1", displayName: "SPI3_DMA_WRITE_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_WRITE_REQ2", displayName: "SPI3_DMA_WRITE_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI3_DMA_WRITE_REQ3", displayName: "SPI3_DMA_WRITE_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_READ_REQ0", displayName: "SPI4_DMA_READ_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_READ_REQ1", displayName: "SPI4_DMA_READ_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_READ_REQ2", displayName: "SPI4_DMA_READ_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_READ_REQ3", displayName: "SPI4_DMA_READ_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_WRITE_REQ0", displayName: "SPI4_DMA_WRITE_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_WRITE_REQ1", displayName: "SPI4_DMA_WRITE_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_WRITE_REQ2", displayName: "SPI4_DMA_WRITE_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_SPI4_DMA_WRITE_REQ3", displayName: "SPI4_DMA_WRITE_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI0_DMA_0", displayName: "RTI0_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI0_DMA_1", displayName: "RTI0_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI0_DMA_2", displayName: "RTI0_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI0_DMA_3", displayName: "RTI0_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI1_DMA_0", displayName: "RTI1_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI1_DMA_1", displayName: "RTI1_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI1_DMA_2", displayName: "RTI1_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI1_DMA_3", displayName: "RTI1_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI2_DMA_0", displayName: "RTI2_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI2_DMA_1", displayName: "RTI2_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI2_DMA_2", displayName: "RTI2_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI2_DMA_3", displayName: "RTI2_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI3_DMA_0", displayName: "RTI3_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI3_DMA_1", displayName: "RTI3_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI3_DMA_2", displayName: "RTI3_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_RTI3_DMA_3", displayName: "RTI3_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_TX_DMA_0", displayName: "MCANSS0_TX_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_TX_DMA_1", displayName: "MCANSS0_TX_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_TX_DMA_2", displayName: "MCANSS0_TX_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_TX_DMA_3", displayName: "MCANSS0_TX_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_TX_DMA_0", displayName: "MCANSS1_TX_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_TX_DMA_1", displayName: "MCANSS1_TX_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_TX_DMA_2", displayName: "MCANSS1_TX_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_TX_DMA_3", displayName: "MCANSS1_TX_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_TX_DMA_0", displayName: "MCANSS2_TX_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_TX_DMA_1", displayName: "MCANSS2_TX_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_TX_DMA_2", displayName: "MCANSS2_TX_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_TX_DMA_3", displayName: "MCANSS2_TX_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_TX_DMA_0", displayName: "MCANSS3_TX_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_TX_DMA_1", displayName: "MCANSS3_TX_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_TX_DMA_2", displayName: "MCANSS3_TX_DMA_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_TX_DMA_3", displayName: "MCANSS3_TX_DMA_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART0_DMA_0", displayName: "USART0_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART0_DMA_1", displayName: "USART0_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART1_DMA_0", displayName: "USART1_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART1_DMA_1", displayName: "USART1_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART2_DMA_0", displayName: "USART2_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART2_DMA_1", displayName: "USART2_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART3_DMA_0", displayName: "USART3_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART3_DMA_1", displayName: "USART3_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART4_DMA_0", displayName: "USART4_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART4_DMA_1", displayName: "USART4_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART5_DMA_0", displayName: "USART5_DMA_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_USART5_DMA_1", displayName: "USART5_DMA_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCRC_DMA_EVENT_0", displayName: "MCRC_DMA_EVENT_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCRC_DMA_EVENT_1", displayName: "MCRC_DMA_EVENT_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCRC_DMA_EVENT_2", displayName: "MCRC_DMA_EVENT_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCRC_DMA_EVENT_3", displayName: "MCRC_DMA_EVENT_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_QSPI_INTR", displayName: "QSPI_INTR", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MMC_DMA_RD", displayName: "MMC_DMA_RD", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MMC_DMA_WR", displayName: "MMC_DMA_WR", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_SHA_DMA_REQ0", displayName: "DTHE_SHA_DMA_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_SHA_DMA_REQ1", displayName: "DTHE_SHA_DMA_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_SHA_DMA_REQ2", displayName: "DTHE_SHA_DMA_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_SHA_DMA_REQ3", displayName: "DTHE_SHA_DMA_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_SHA_DMA_REQ4", displayName: "DTHE_SHA_DMA_REQ4", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_SHA_DMA_REQ5", displayName: "DTHE_SHA_DMA_REQ5", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ0", displayName: "DTHE_AES_DMA_REQ0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ1", displayName: "DTHE_AES_DMA_REQ1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ2", displayName: "DTHE_AES_DMA_REQ2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ3", displayName: "DTHE_AES_DMA_REQ3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ4", displayName: "DTHE_AES_DMA_REQ4", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ5", displayName: "DTHE_AES_DMA_REQ5", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ6", displayName: "DTHE_AES_DMA_REQ6", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_DTHE_AES_DMA_REQ7", displayName: "DTHE_AES_DMA_REQ7", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_0", displayName: "MCANSS0_FE_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_1", displayName: "MCANSS0_FE_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_2", displayName: "MCANSS0_FE_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_3", displayName: "MCANSS0_FE_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_4", displayName: "MCANSS0_FE_4", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_5", displayName: "MCANSS0_FE_5", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS0_FE_6", displayName: "MCANSS0_FE_6", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_0", displayName: "MCANSS1_FE_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_1", displayName: "MCANSS1_FE_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_2", displayName: "MCANSS1_FE_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_3", displayName: "MCANSS1_FE_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_4", displayName: "MCANSS1_FE_4", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_5", displayName: "MCANSS1_FE_5", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS1_FE_6", displayName: "MCANSS1_FE_6", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_0", displayName: "MCANSS2_FE_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_1", displayName: "MCANSS2_FE_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_2", displayName: "MCANSS2_FE_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_3", displayName: "MCANSS2_FE_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_4", displayName: "MCANSS2_FE_4", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_5", displayName: "MCANSS2_FE_5", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS2_FE_6", displayName: "MCANSS2_FE_6", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_0", displayName: "MCANSS3_FE_0", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_1", displayName: "MCANSS3_FE_1", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_2", displayName: "MCANSS3_FE_2", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_3", displayName: "MCANSS3_FE_3", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_4", displayName: "MCANSS3_FE_4", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_5", displayName: "MCANSS3_FE_5", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_MCANSS3_FE_6", displayName: "MCANSS3_FE_6", path: "dma_trig_xbar" },
    {   name: "DMA_TRIG_XBAR_GPMC_SDMAREQ", displayName: "GPMC_SDMAREQ", path: "dma_trig_xbar" },
];

let xbarProperties = {
    masterXbarList: ["gpio_int_xbar", "soc_timesync_xbar0", "soc_timesync_xbar1", "dma_xbar"],
    outputInstanceList: [
        { name: "DMA_TRIG_XBAR_EDMA_MODULE", count: 64},
    ],
    duplicatesPresent: true,
    moduleString: "dma_trig_xbar",
}

function getOptionList(calledBy) {
    return xbarSoc.getOptionListSoc(calledBy, xbarProperties, internal_list);
}

function getConfigArr() {
    return xbarSoc.getXbarInstanceConfig(xbarProperties);
}

function supportXbarConfig(outputSelected, instance) {
    return xbarSoc.supportXbarConfigSoc(outputSelected, instance, xbarProperties);
}

exports = {
    getConfigArr,
    getOptionList,
    supportXbarConfig,
};
