/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_ICSSUART_H_
#define CSLR_ICSSUART_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for __ALL__
**************************************************************************/
typedef struct {
    volatile Uint32 UART_RBR_TBR;
    volatile Uint32 UARTINTERRUPTENABLE;
    volatile Uint32 UARTINTERRUPTIDENTIFICATIONFIFOCONTROL;
    volatile Uint32 UARTLINECONTROL;
    volatile Uint32 UARTMODEMCONTROL;
    volatile Uint32 UARTLINESTATUS;
    volatile Uint32 UARTMODEMSTATUS;
    volatile Uint32 UARTSCRATCH;
    volatile Uint32 UARTDIVISORLSB;
    volatile Uint32 UARTDIVISORMSB;
    volatile Uint32 UARTPERIPHERALID;
    volatile Uint8  RSVD0[4];
    volatile Uint32 UARTPOWERMANAGEMENTEMULATION;
    volatile Uint32 UARTMODEDEFINITION;
    volatile Uint8  RSVD1[156];
} CSL_IcssUartRegs;


/**************************************************************************
* Register Macros
**************************************************************************/
#define CSL_ICSSUART_UART_RBR_TBR                               (0x0U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE                        (0x4U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL     (0x8U)
#define CSL_ICSSUART_UARTLINECONTROL                            (0xCU)
#define CSL_ICSSUART_UARTMODEMCONTROL                           (0x10U)
#define CSL_ICSSUART_UARTLINESTATUS                             (0x14U)
#define CSL_ICSSUART_UARTMODEMSTATUS                            (0x18U)
#define CSL_ICSSUART_UARTSCRATCH                                (0x1CU)
#define CSL_ICSSUART_UARTDIVISORLSB                             (0x20U)
#define CSL_ICSSUART_UARTDIVISORMSB                             (0x24U)
#define CSL_ICSSUART_UARTPERIPHERALID                           (0x28U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION               (0x30U)
#define CSL_ICSSUART_UARTMODEDEFINITION                         (0x34U)


/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* UART_RBR_TBR */

#define CSL_ICSSUART_UART_RBR_TBR_RBR_DATA_MASK                 (0x000000FFU)
#define CSL_ICSSUART_UART_RBR_TBR_RBR_DATA_SHIFT                (0U)
#define CSL_ICSSUART_UART_RBR_TBR_RBR_DATA_RESETVAL             (0x00000000U)
#define CSL_ICSSUART_UART_RBR_TBR_RBR_DATA_MAX                  (0x000000ffU)

#define CSL_ICSSUART_UART_RBR_TBR_TBR_DATA_MASK                 (0x0003FF00U)
#define CSL_ICSSUART_UART_RBR_TBR_TBR_DATA_SHIFT                (8U)
#define CSL_ICSSUART_UART_RBR_TBR_TBR_DATA_RESETVAL             (0x00000000U)
#define CSL_ICSSUART_UART_RBR_TBR_TBR_DATA_MAX                  (0x000003ffU)

#define CSL_ICSSUART_UART_RBR_TBR_RESETVAL                      (0x00000000U)

/* UARTINTERRUPTENABLE */

#define CSL_ICSSUART_UARTINTERRUPTENABLE_ERBI_MASK              (0x00000001U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ERBI_SHIFT             (0U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ERBI_RESETVAL          (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ERBI_MAX               (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTENABLE_ETBEI_MASK             (0x00000002U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ETBEI_SHIFT            (1U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ETBEI_RESETVAL         (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ETBEI_MAX              (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTENABLE_ELSI_MASK              (0x00000004U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ELSI_SHIFT             (2U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ELSI_RESETVAL          (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_ELSI_MAX               (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTENABLE_EDSSI_MASK             (0x00000008U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_EDSSI_SHIFT            (3U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_EDSSI_RESETVAL         (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTENABLE_EDSSI_MAX              (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTENABLE_RESETVAL               (0x00000000U)

/* UARTINTERRUPTIDENTIFICATIONFIFOCONTROL */

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_IPEND_MASK  (0x00000001U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_IPEND_SHIFT  (0U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_IPEND_RESETVAL  (0x00000001U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_IPEND_MAX  (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_INTID_MASK  (0x0000000EU)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_INTID_SHIFT  (1U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_INTID_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_INTID_MAX  (0x00000007U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_FIFOEN_MASK  (0x000000C0U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_FIFOEN_SHIFT  (6U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_FIFOEN_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_IIR_FIFOEN_MAX  (0x00000003U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_FIFOEN_MASK  (0x00000100U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_FIFOEN_SHIFT  (8U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_FIFOEN_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_FIFOEN_MAX  (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXCLR_MASK  (0x00000200U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXCLR_SHIFT  (9U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXCLR_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXCLR_MAX  (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_TXCLR_MASK  (0x00000400U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_TXCLR_SHIFT  (10U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_TXCLR_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_TXCLR_MAX  (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_DMAMODE1_MASK  (0x00000800U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_DMAMODE1_SHIFT  (11U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_DMAMODE1_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_DMAMODE1_MAX  (0x00000001U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXFIFTL_MASK  (0x0000C000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXFIFTL_SHIFT  (14U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXFIFTL_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_FCR_RXFIFTL_MAX  (0x00000003U)

#define CSL_ICSSUART_UARTINTERRUPTIDENTIFICATIONFIFOCONTROL_RESETVAL  (0x00000001U)

/* UARTLINECONTROL */

#define CSL_ICSSUART_UARTLINECONTROL_WLS0_MASK                  (0x00000001U)
#define CSL_ICSSUART_UARTLINECONTROL_WLS0_SHIFT                 (0U)
#define CSL_ICSSUART_UARTLINECONTROL_WLS0_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_WLS0_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_WLS1_MASK                  (0x00000002U)
#define CSL_ICSSUART_UARTLINECONTROL_WLS1_SHIFT                 (1U)
#define CSL_ICSSUART_UARTLINECONTROL_WLS1_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_WLS1_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_STB_MASK                   (0x00000004U)
#define CSL_ICSSUART_UARTLINECONTROL_STB_SHIFT                  (2U)
#define CSL_ICSSUART_UARTLINECONTROL_STB_RESETVAL               (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_STB_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_PEN_MASK                   (0x00000008U)
#define CSL_ICSSUART_UARTLINECONTROL_PEN_SHIFT                  (3U)
#define CSL_ICSSUART_UARTLINECONTROL_PEN_RESETVAL               (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_PEN_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_EPS_MASK                   (0x00000010U)
#define CSL_ICSSUART_UARTLINECONTROL_EPS_SHIFT                  (4U)
#define CSL_ICSSUART_UARTLINECONTROL_EPS_RESETVAL               (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_EPS_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_SP_MASK                    (0x00000020U)
#define CSL_ICSSUART_UARTLINECONTROL_SP_SHIFT                   (5U)
#define CSL_ICSSUART_UARTLINECONTROL_SP_RESETVAL                (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_SP_MAX                     (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_BC_MASK                    (0x00000040U)
#define CSL_ICSSUART_UARTLINECONTROL_BC_SHIFT                   (6U)
#define CSL_ICSSUART_UARTLINECONTROL_BC_RESETVAL                (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_BC_MAX                     (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_DLAB_MASK                  (0x00000080U)
#define CSL_ICSSUART_UARTLINECONTROL_DLAB_SHIFT                 (7U)
#define CSL_ICSSUART_UARTLINECONTROL_DLAB_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTLINECONTROL_DLAB_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTLINECONTROL_RESETVAL                   (0x00000000U)

/* UARTMODEMCONTROL */

#define CSL_ICSSUART_UARTMODEMCONTROL_RTS_MASK                  (0x00000002U)
#define CSL_ICSSUART_UARTMODEMCONTROL_RTS_SHIFT                 (1U)
#define CSL_ICSSUART_UARTMODEMCONTROL_RTS_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTMODEMCONTROL_RTS_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTMODEMCONTROL_OUT1_MASK                 (0x00000004U)
#define CSL_ICSSUART_UARTMODEMCONTROL_OUT1_SHIFT                (2U)
#define CSL_ICSSUART_UARTMODEMCONTROL_OUT1_RESETVAL             (0x00000000U)
#define CSL_ICSSUART_UARTMODEMCONTROL_OUT1_MAX                  (0x00000001U)

#define CSL_ICSSUART_UARTMODEMCONTROL_OUT2_MASK                 (0x00000008U)
#define CSL_ICSSUART_UARTMODEMCONTROL_OUT2_SHIFT                (3U)
#define CSL_ICSSUART_UARTMODEMCONTROL_OUT2_RESETVAL             (0x00000000U)
#define CSL_ICSSUART_UARTMODEMCONTROL_OUT2_MAX                  (0x00000001U)

#define CSL_ICSSUART_UARTMODEMCONTROL_LOOP_MASK                 (0x00000010U)
#define CSL_ICSSUART_UARTMODEMCONTROL_LOOP_SHIFT                (4U)
#define CSL_ICSSUART_UARTMODEMCONTROL_LOOP_RESETVAL             (0x00000000U)
#define CSL_ICSSUART_UARTMODEMCONTROL_LOOP_MAX                  (0x00000001U)

#define CSL_ICSSUART_UARTMODEMCONTROL_AFE_MASK                  (0x00000020U)
#define CSL_ICSSUART_UARTMODEMCONTROL_AFE_SHIFT                 (5U)
#define CSL_ICSSUART_UARTMODEMCONTROL_AFE_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTMODEMCONTROL_AFE_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTMODEMCONTROL_RESETVAL                  (0x00000000U)

/* UARTLINESTATUS */

#define CSL_ICSSUART_UARTLINESTATUS_DR_MASK                     (0x00000001U)
#define CSL_ICSSUART_UARTLINESTATUS_DR_SHIFT                    (0U)
#define CSL_ICSSUART_UARTLINESTATUS_DR_RESETVAL                 (0x00000000U)
#define CSL_ICSSUART_UARTLINESTATUS_DR_MAX                      (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_OE_MASK                     (0x00000002U)
#define CSL_ICSSUART_UARTLINESTATUS_OE_SHIFT                    (1U)
#define CSL_ICSSUART_UARTLINESTATUS_OE_RESETVAL                 (0x00000000U)
#define CSL_ICSSUART_UARTLINESTATUS_OE_MAX                      (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_PE_MASK                     (0x00000004U)
#define CSL_ICSSUART_UARTLINESTATUS_PE_SHIFT                    (2U)
#define CSL_ICSSUART_UARTLINESTATUS_PE_RESETVAL                 (0x00000000U)
#define CSL_ICSSUART_UARTLINESTATUS_PE_MAX                      (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_FE_MASK                     (0x00000008U)
#define CSL_ICSSUART_UARTLINESTATUS_FE_SHIFT                    (3U)
#define CSL_ICSSUART_UARTLINESTATUS_FE_RESETVAL                 (0x00000000U)
#define CSL_ICSSUART_UARTLINESTATUS_FE_MAX                      (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_BI_MASK                     (0x00000010U)
#define CSL_ICSSUART_UARTLINESTATUS_BI_SHIFT                    (4U)
#define CSL_ICSSUART_UARTLINESTATUS_BI_RESETVAL                 (0x00000000U)
#define CSL_ICSSUART_UARTLINESTATUS_BI_MAX                      (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_THRE_MASK                   (0x00000020U)
#define CSL_ICSSUART_UARTLINESTATUS_THRE_SHIFT                  (5U)
#define CSL_ICSSUART_UARTLINESTATUS_THRE_RESETVAL               (0x00000001U)
#define CSL_ICSSUART_UARTLINESTATUS_THRE_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_TEMT_MASK                   (0x00000040U)
#define CSL_ICSSUART_UARTLINESTATUS_TEMT_SHIFT                  (6U)
#define CSL_ICSSUART_UARTLINESTATUS_TEMT_RESETVAL               (0x00000001U)
#define CSL_ICSSUART_UARTLINESTATUS_TEMT_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_RXFIFOE_MASK                (0x00000080U)
#define CSL_ICSSUART_UARTLINESTATUS_RXFIFOE_SHIFT               (7U)
#define CSL_ICSSUART_UARTLINESTATUS_RXFIFOE_RESETVAL            (0x00000000U)
#define CSL_ICSSUART_UARTLINESTATUS_RXFIFOE_MAX                 (0x00000001U)

#define CSL_ICSSUART_UARTLINESTATUS_RESETVAL                    (0x00000060U)

/* UARTMODEMSTATUS */

#define CSL_ICSSUART_UARTMODEMSTATUS_DCTS_MASK                  (0x00000001U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DCTS_SHIFT                 (0U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DCTS_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DCTS_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_DDSR_MASK                  (0x00000002U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DDSR_SHIFT                 (1U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DDSR_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DDSR_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_TERI_MASK                  (0x00000004U)
#define CSL_ICSSUART_UARTMODEMSTATUS_TERI_SHIFT                 (2U)
#define CSL_ICSSUART_UARTMODEMSTATUS_TERI_RESETVAL              (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_TERI_MAX                   (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_DCD_MASK                   (0x00000008U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DCD_SHIFT                  (3U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DCD_RESETVAL               (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DCD_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_CTS_MASK                   (0x00000010U)
#define CSL_ICSSUART_UARTMODEMSTATUS_CTS_SHIFT                  (4U)
#define CSL_ICSSUART_UARTMODEMSTATUS_CTS_RESETVAL               (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_CTS_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_DSR_MASK                   (0x00000020U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DSR_SHIFT                  (5U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DSR_RESETVAL               (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_DSR_MAX                    (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_RI_MASK                    (0x00000040U)
#define CSL_ICSSUART_UARTMODEMSTATUS_RI_SHIFT                   (6U)
#define CSL_ICSSUART_UARTMODEMSTATUS_RI_RESETVAL                (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_RI_MAX                     (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_CD_MASK                    (0x00000080U)
#define CSL_ICSSUART_UARTMODEMSTATUS_CD_SHIFT                   (7U)
#define CSL_ICSSUART_UARTMODEMSTATUS_CD_RESETVAL                (0x00000000U)
#define CSL_ICSSUART_UARTMODEMSTATUS_CD_MAX                     (0x00000001U)

#define CSL_ICSSUART_UARTMODEMSTATUS_RESETVAL                   (0x00000000U)

/* UARTSCRATCH */

#define CSL_ICSSUART_UARTSCRATCH_DATA_MASK                      (0x000000FFU)
#define CSL_ICSSUART_UARTSCRATCH_DATA_SHIFT                     (0U)
#define CSL_ICSSUART_UARTSCRATCH_DATA_RESETVAL                  (0x00000000U)
#define CSL_ICSSUART_UARTSCRATCH_DATA_MAX                       (0x000000ffU)

#define CSL_ICSSUART_UARTSCRATCH_RESETVAL                       (0x00000000U)

/* UARTDIVISORLSB */

#define CSL_ICSSUART_UARTDIVISORLSB_DLL_MASK                    (0x000000FFU)
#define CSL_ICSSUART_UARTDIVISORLSB_DLL_SHIFT                   (0U)
#define CSL_ICSSUART_UARTDIVISORLSB_DLL_RESETVAL                (0x00000000U)
#define CSL_ICSSUART_UARTDIVISORLSB_DLL_MAX                     (0x000000ffU)

#define CSL_ICSSUART_UARTDIVISORLSB_RESETVAL                    (0x00000000U)

/* UARTDIVISORMSB */

#define CSL_ICSSUART_UARTDIVISORMSB_DLH_MASK                    (0x000000FFU)
#define CSL_ICSSUART_UARTDIVISORMSB_DLH_SHIFT                   (0U)
#define CSL_ICSSUART_UARTDIVISORMSB_DLH_RESETVAL                (0x00000000U)
#define CSL_ICSSUART_UARTDIVISORMSB_DLH_MAX                     (0x000000ffU)

#define CSL_ICSSUART_UARTDIVISORMSB_RESETVAL                    (0x00000000U)

/* UARTPERIPHERALID */

#define CSL_ICSSUART_UARTPERIPHERALID_PID_MASK                  (0xFFFFFFFFU)
#define CSL_ICSSUART_UARTPERIPHERALID_PID_SHIFT                 (0U)
#define CSL_ICSSUART_UARTPERIPHERALID_PID_RESETVAL              (0x44141102U)
#define CSL_ICSSUART_UARTPERIPHERALID_PID_MAX                   (0xffffffffU)

#define CSL_ICSSUART_UARTPERIPHERALID_RESETVAL                  (0x44141102U)

/* UARTPOWERMANAGEMENTEMULATION */

#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_FREE_MASK     (0x00000001U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_FREE_SHIFT    (0U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_FREE_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_FREE_MAX      (0x00000001U)

#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_URRST_MASK    (0x00002000U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_URRST_SHIFT   (13U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_URRST_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_URRST_MAX     (0x00000001U)

#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_UTRST_MASK    (0x00004000U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_UTRST_SHIFT   (14U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_UTRST_RESETVAL  (0x00000000U)
#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_UTRST_MAX     (0x00000001U)

#define CSL_ICSSUART_UARTPOWERMANAGEMENTEMULATION_RESETVAL      (0x00000000U)

/* UARTMODEDEFINITION */

#define CSL_ICSSUART_UARTMODEDEFINITION_OSM_SEL_MASK            (0x00000001U)
#define CSL_ICSSUART_UARTMODEDEFINITION_OSM_SEL_SHIFT           (0U)
#define CSL_ICSSUART_UARTMODEDEFINITION_OSM_SEL_RESETVAL        (0x00000000U)
#define CSL_ICSSUART_UARTMODEDEFINITION_OSM_SEL_MAX             (0x00000001U)

#define CSL_ICSSUART_UARTMODEDEFINITION_RESETVAL                (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
