#ifndef INPUT_CONFIG_H_
#define INPUT_CONFIG_H_

#define SKIP_NORMALIZE
#define FE_CONCAT
#define FE_NUM_FRAME_CONCAT 1
#define FE_VARIABLES 1
#define FE_FRAME_SIZE 100
#define FE_HL 1
#define FE_FEATURE_SIZE_PER_FRAME 100
#define FE_STACKING_CHANNELS 1
#define FE_STACKING_FRAME_WIDTH 100
#define FE_OFFSET 0
#define FE_SCALE None
#define FE_MIN_FFT_BIN 1
#define FE_NUM_FRAME_CONCAT 1
#define FE_NN_OUT_SIZE 100
#define FE_FEATURE_SIZE 100
#define FE_FRAME_SKIP 1
#define FE_FFT_STAGES 6
#define RECONSTRUCTION_ERROR_THRESHOLD 0.014545786194503307


#endif /* INPUT_CONFIG_H_ */
