/********************************************************************
 * Copyright (C) 2020 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_top_anareg.h
*/
#ifndef CSLR_TOP_ANAREG_H_
#define CSLR_TOP_ANAREG_H_

#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>

#ifdef __cplusplus
extern "C"
{
#endif

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t CLK_CTRL_REG1_CLKTOP;
    volatile uint32_t CLK_CTRL_REG1_LDO_CLKTOP;
    volatile uint32_t CLK_CTRL_REG1_XO_SLICER;
    volatile uint32_t CLK_CTRL_REG2_CLKTOP;
    volatile uint32_t CLK_CTRL_REG2_LDO_CLKTOP;
    volatile uint32_t CLK_STATUS_REG;
    volatile uint32_t REFSYS_CTRL_REG;
    volatile uint32_t REFSYS_SPARE_REG;
    volatile uint32_t REFSYS_TMUX_CTRL;
    volatile uint32_t RFANA_BIST_CTRL5;
    volatile uint32_t TW_ANA_TMUX_CTRL;
    volatile uint32_t TW_CTRL_REG;
    volatile uint32_t TW_SPARE;
    volatile uint32_t WU_CTRL_REG;
    volatile uint32_t WU_MODE_REG;
    volatile uint32_t WU_SPARE_OUT;
    volatile uint32_t WU_STATUS_REG;
    volatile uint32_t WU_TMUX_CTRL;
} CSL_top_anaregRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP                                    (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP                                (0x00000004U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER                                 (0x00000008U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP                                    (0x0000000CU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP                                (0x00000010U)
#define CSL_TOP_ANAREG_CLK_STATUS_REG                                          (0x00000014U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG                                         (0x00000018U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG                                        (0x0000001CU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL                                        (0x00000020U)
#define CSL_TOP_ANAREG_RFANA_BIST_CTRL5                                        (0x00000024U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL                                        (0x00000028U)
#define CSL_TOP_ANAREG_TW_CTRL_REG                                             (0x0000002CU)
#define CSL_TOP_ANAREG_TW_SPARE                                                (0x00000030U)
#define CSL_TOP_ANAREG_WU_CTRL_REG                                             (0x00000034U)
#define CSL_TOP_ANAREG_WU_MODE_REG                                             (0x00000038U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT                                            (0x0000003CU)
#define CSL_TOP_ANAREG_WU_STATUS_REG                                           (0x00000040U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL                                            (0x00000044U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* CLK_CTRL_REG1_CLKTOP */

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_BIAS_XO_SLICER_MASK         (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_BIAS_XO_SLICER_SHIFT        (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_BIAS_XO_SLICER_RESETVAL     (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_BIAS_XO_SLICER_MAX          (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_SLICER_CLKP_MASK            (0x00000002U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_SLICER_CLKP_SHIFT           (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_SLICER_CLKP_RESETVAL        (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_SLICER_CLKP_MAX             (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_XOSC_MASK                   (0x00000004U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_XOSC_SHIFT                  (0x00000002U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_XOSC_RESETVAL               (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_ENABLE_XOSC_MAX                    (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_RESERVED0_MASK                     (0xFFFFFFF8U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_RESERVED0_SHIFT                    (0x00000003U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_RESERVED0_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_RESERVED0_MAX                      (0x1FFFFFFFU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_CLKTOP_RESETVAL                           (0x00000007U)

/* CLK_CTRL_REG1_LDO_CLKTOP */

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_EN_SLICER_LDO_MASK             (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_EN_SLICER_LDO_SHIFT            (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_EN_SLICER_LDO_RESETVAL         (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_EN_SLICER_LDO_MAX              (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED0_MASK                 (0x0000007EU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED0_SHIFT                (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED0_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED0_MAX                  (0x0000003FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_CLK_BIST_DISABLE_LDO_MASK      (0x00000080U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_CLK_BIST_DISABLE_LDO_SHIFT     (0x00000007U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_CLK_BIST_DISABLE_LDO_RESETVAL  (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_CLK_BIST_DISABLE_LDO_MAX       (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED1_MASK                 (0xFFFFFF00U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED1_SHIFT                (0x00000008U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED1_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESERVED1_MAX                  (0x00FFFFFFU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_LDO_CLKTOP_RESETVAL                       (0x00000001U)

/* CLK_CTRL_REG1_XO_SLICER */

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RTRIM_BIAS_XO_SLICER_MASK       (0x0000000FU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RTRIM_BIAS_XO_SLICER_SHIFT      (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RTRIM_BIAS_XO_SLICER_RESETVAL   (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RTRIM_BIAS_XO_SLICER_MAX        (0x0000000FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XOSC_DRIVE_XO_SLICER_MASK       (0x000001F0U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XOSC_DRIVE_XO_SLICER_SHIFT      (0x00000004U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XOSC_DRIVE_XO_SLICER_RESETVAL   (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XOSC_DRIVE_XO_SLICER_MAX        (0x0000001FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_FASTCHARGEZ_BIAS_XO_SLICER_MASK (0x00000200U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_FASTCHARGEZ_BIAS_XO_SLICER_SHIFT (0x00000009U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_FASTCHARGEZ_BIAS_XO_SLICER_RESETVAL (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_FASTCHARGEZ_BIAS_XO_SLICER_MAX  (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_HIPWR_XO_SLICER_MASK     (0x00000400U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_HIPWR_XO_SLICER_SHIFT    (0x0000000AU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_HIPWR_XO_SLICER_RESETVAL (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_HIPWR_XO_SLICER_MAX      (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_DCCPL_XO_SLICER_MASK     (0x00000800U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_DCCPL_XO_SLICER_SHIFT    (0x0000000BU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_DCCPL_XO_SLICER_RESETVAL (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_SLICER_DCCPL_XO_SLICER_MAX      (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XTAL_DETECT_XO_SLICER_MASK      (0x00001000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XTAL_DETECT_XO_SLICER_SHIFT     (0x0000000CU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XTAL_DETECT_XO_SLICER_RESETVAL  (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_XTAL_DETECT_XO_SLICER_MAX       (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RESERVED0_MASK                  (0x00FFE000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RESERVED0_SHIFT                 (0x0000000DU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RESERVED0_RESETVAL              (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RESERVED0_MAX                   (0x000007FFU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_DRV_MASK             (0x0F000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_DRV_SHIFT            (0x00000018U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_DRV_RESETVAL         (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_DRV_MAX              (0x0000000FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_CLRZ_DIV_MASK        (0x10000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_CLRZ_DIV_SHIFT       (0x0000001CU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_CLRZ_DIV_RESETVAL    (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_CLRZ_DIV_MAX         (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_FREQ_SEL_MASK        (0x60000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_FREQ_SEL_SHIFT       (0x0000001DU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_FREQ_SEL_RESETVAL    (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_FREQ_SEL_MAX         (0x00000003U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_EN_MASK              (0x80000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_EN_SHIFT             (0x0000001FU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_EN_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_OSC_CLKOUT_EN_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG1_XO_SLICER_RESETVAL                        (0x00000000U)

/* CLK_CTRL_REG2_CLKTOP */

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_RESERVED0_MASK                     (0x7FFFFFFFU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_RESERVED0_SHIFT                    (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_RESERVED0_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_RESERVED0_MAX                      (0x7FFFFFFFU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_CTRL_DC_BIST_BUFEN_MASK            (0x80000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_CTRL_DC_BIST_BUFEN_SHIFT           (0x0000001FU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_CTRL_DC_BIST_BUFEN_RESETVAL        (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_CTRL_DC_BIST_BUFEN_MAX             (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_CLKTOP_RESETVAL                           (0x00000000U)

/* CLK_CTRL_REG2_LDO_CLKTOP */

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_VOUT_CTRL_MASK             (0x0000000FU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_VOUT_CTRL_SHIFT            (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_VOUT_CTRL_RESETVAL         (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_VOUT_CTRL_MAX              (0x0000000FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENZ_LOW_BW_CAP_MASK            (0x00000010U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENZ_LOW_BW_CAP_SHIFT           (0x00000004U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENZ_LOW_BW_CAP_RESETVAL        (0x00000001U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENZ_LOW_BW_CAP_MAX             (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_TEST_MODE_MASK              (0x00000020U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_TEST_MODE_SHIFT             (0x00000005U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_TEST_MODE_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_TEST_MODE_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_SHRT_CKT_MASK               (0x00000040U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_SHRT_CKT_SHIFT              (0x00000006U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_SHRT_CKT_RESETVAL           (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_SHRT_CKT_MAX                (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_BYPASS_MASK                 (0x00000080U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_BYPASS_SHIFT                (0x00000007U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_BYPASS_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_EN_BYPASS_MAX                  (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_BW_CTRL_MASK               (0x00000700U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_BW_CTRL_SHIFT              (0x00000008U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_BW_CTRL_RESETVAL           (0x00000007U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_LDO_BW_CTRL_MAX                (0x00000007U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_SCPRT_IBIAS_CTRL_MASK          (0x00000800U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_SCPRT_IBIAS_CTRL_SHIFT         (0x0000000BU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_SCPRT_IBIAS_CTRL_RESETVAL      (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_SCPRT_IBIAS_CTRL_MAX           (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENABLE_PMOS_PULLDOWN_MASK      (0x00001000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENABLE_PMOS_PULLDOWN_SHIFT     (0x0000000CU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENABLE_PMOS_PULLDOWN_RESETVAL  (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_ENABLE_PMOS_PULLDOWN_MAX       (0x00000001U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TLOAD_CTRL_MASK                (0x0000E000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TLOAD_CTRL_SHIFT               (0x0000000DU)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TLOAD_CTRL_RESETVAL            (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TLOAD_CTRL_MAX                 (0x00000007U)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TESTMUX_CTRL_MASK              (0x000F0000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TESTMUX_CTRL_SHIFT             (0x00000010U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TESTMUX_CTRL_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_TESTMUX_CTRL_MAX               (0x0000000FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_BISTMUX_CTRL_MASK              (0x00F00000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_BISTMUX_CTRL_SHIFT             (0x00000014U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_BISTMUX_CTRL_RESETVAL          (0x00000004U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_BISTMUX_CTRL_MAX               (0x0000000FU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_RESERVED0_MASK                 (0xFF000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_RESERVED0_SHIFT                (0x00000018U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_RESERVED0_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_RESERVED0_MAX                  (0x000000FFU)

#define CSL_TOP_ANAREG_CLK_CTRL_REG2_LDO_CLKTOP_RESETVAL                       (0x00400710U)

/* CLK_STATUS_REG */

#define CSL_TOP_ANAREG_CLK_STATUS_REG_SLICER_LDO_SC_OUT_MASK                   (0x00000001U)
#define CSL_TOP_ANAREG_CLK_STATUS_REG_SLICER_LDO_SC_OUT_SHIFT                  (0x00000000U)
#define CSL_TOP_ANAREG_CLK_STATUS_REG_SLICER_LDO_SC_OUT_RESETVAL               (0x00000000U)
#define CSL_TOP_ANAREG_CLK_STATUS_REG_SLICER_LDO_SC_OUT_MAX                    (0x00000001U)

#define CSL_TOP_ANAREG_CLK_STATUS_REG_RESERVED0_MASK                           (0xFFFFFFFEU)
#define CSL_TOP_ANAREG_CLK_STATUS_REG_RESERVED0_SHIFT                          (0x00000001U)
#define CSL_TOP_ANAREG_CLK_STATUS_REG_RESERVED0_RESETVAL                       (0x00000000U)
#define CSL_TOP_ANAREG_CLK_STATUS_REG_RESERVED0_MAX                            (0x7FFFFFFFU)

#define CSL_TOP_ANAREG_CLK_STATUS_REG_RESETVAL                                 (0x00000000U)

/* REFSYS_CTRL_REG */

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_BGAP_EN_CTRL_MASK                (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_BGAP_EN_CTRL_SHIFT               (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_BGAP_EN_CTRL_RESETVAL            (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_BGAP_EN_CTRL_MAX                 (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_EN_CTRL_MASK                 (0x00000002U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_EN_CTRL_SHIFT                (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_EN_CTRL_RESETVAL             (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_EN_CTRL_MAX                  (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_CAP_SW_CTRLZ_MASK                (0x00000004U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_CAP_SW_CTRLZ_SHIFT               (0x00000002U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_CAP_SW_CTRLZ_RESETVAL            (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_CAP_SW_CTRLZ_MAX                 (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_PRE_CHARGE_MASK                  (0x00000008U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_PRE_CHARGE_SHIFT                 (0x00000003U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_PRE_CHARGE_RESETVAL              (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_PRE_CHARGE_MAX                   (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_SLOPE_TRIM_4_0_MASK                     (0x000001F0U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_SLOPE_TRIM_4_0_SHIFT                    (0x00000004U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_SLOPE_TRIM_4_0_RESETVAL                 (0x0000000DU)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_SLOPE_TRIM_4_0_MAX                      (0x0000001FU)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_MAG_TRIM_4_0_MASK                       (0x00003E00U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_MAG_TRIM_4_0_SHIFT                      (0x00000009U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_MAG_TRIM_4_0_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_MAG_TRIM_4_0_MAX                        (0x0000001FU)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IREF_TRIM_4_0_MASK                      (0x0007C000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IREF_TRIM_4_0_SHIFT                     (0x0000000EU)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IREF_TRIM_4_0_RESETVAL                  (0x00000002U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IREF_TRIM_4_0_MAX                       (0x0000001FU)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_BGAP_ISW_MASK                           (0x00080000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_BGAP_ISW_SHIFT                          (0x00000013U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_BGAP_ISW_RESETVAL                       (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_BGAP_ISW_MAX                            (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_V2I_STARTUP_MASK                        (0x00100000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_V2I_STARTUP_SHIFT                       (0x00000014U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_V2I_STARTUP_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_V2I_STARTUP_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_CLKTOP_IBIAS_EN_MASK                    (0x00200000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_CLKTOP_IBIAS_EN_SHIFT                   (0x00000015U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_CLKTOP_IBIAS_EN_RESETVAL                (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_CLKTOP_IBIAS_EN_MAX                     (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_LODIST_IBIAS_EN_MASK                    (0x00400000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_LODIST_IBIAS_EN_SHIFT                   (0x00000016U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_LODIST_IBIAS_EN_RESETVAL                (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_LODIST_IBIAS_EN_MAX                     (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_TX_TOP_IBIAS_EN_MASK                    (0x00800000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_TX_TOP_IBIAS_EN_SHIFT                   (0x00000017U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_TX_TOP_IBIAS_EN_RESETVAL                (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_TX_TOP_IBIAS_EN_MAX                     (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_BYPASS_EN_MASK               (0x01000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_BYPASS_EN_SHIFT              (0x00000018U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_BYPASS_EN_RESETVAL           (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_REFSYS_V2I_BYPASS_EN_MAX                (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IDIODE_EN_MASK                          (0x02000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IDIODE_EN_SHIFT                         (0x00000019U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IDIODE_EN_RESETVAL                      (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_IDIODE_EN_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED1_MASK                          (0x04000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED1_SHIFT                         (0x0000001AU)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED1_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED1_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_FTRIM_3_0_MASK                          (0x78000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_FTRIM_3_0_SHIFT                         (0x0000001BU)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_FTRIM_3_0_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_FTRIM_3_0_MAX                           (0x0000000FU)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED2_MASK                          (0x80000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED2_SHIFT                         (0x0000001FU)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED2_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESERVED2_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_CTRL_REG_RESETVAL                                (0x022080D3U)

/* REFSYS_SPARE_REG */

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_IR_DROP_COMP_SEL_MASK              (0x00000003U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_IR_DROP_COMP_SEL_SHIFT             (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_IR_DROP_COMP_SEL_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_IR_DROP_COMP_SEL_MAX               (0x00000003U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_IR_DROP_COMP_SEL_MASK        (0x0000000CU)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_IR_DROP_COMP_SEL_SHIFT       (0x00000002U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_IR_DROP_COMP_SEL_RESETVAL    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_IR_DROP_COMP_SEL_MAX         (0x00000003U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_IR_DROP_COMP_SEL_MASK         (0x00000030U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_IR_DROP_COMP_SEL_SHIFT        (0x00000004U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_IR_DROP_COMP_SEL_RESETVAL     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_IR_DROP_COMP_SEL_MAX          (0x00000003U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_SR_SEL_MASK                        (0x000000C0U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_SR_SEL_SHIFT                       (0x00000006U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_SR_SEL_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_SR_SEL_MAX                         (0x00000003U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_UV_SELF_TEST_SEL_MASK              (0x00000100U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_UV_SELF_TEST_SEL_SHIFT             (0x00000008U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_UV_SELF_TEST_SEL_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_UV_SELF_TEST_SEL_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_OV_SELF_TEST_SEL_MASK              (0x00000200U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_OV_SELF_TEST_SEL_SHIFT             (0x00000009U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_OV_SELF_TEST_SEL_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDD_OV_SELF_TEST_SEL_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_UV_SELF_TEST_SEL_MASK         (0x00000400U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_UV_SELF_TEST_SEL_SHIFT        (0x0000000AU)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_UV_SELF_TEST_SEL_RESETVAL     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDA_OSC_UV_SELF_TEST_SEL_MAX          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_RESERVED0_MASK                         (0x00000800U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_RESERVED0_SHIFT                        (0x0000000BU)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_RESERVED0_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_RESERVED0_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_UV_SELF_TEST_SEL_MASK        (0x00001000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_UV_SELF_TEST_SEL_SHIFT       (0x0000000CU)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_UV_SELF_TEST_SEL_RESETVAL    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_VDDS_3P3V_UV_SELF_TEST_SEL_MAX         (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_REFSYS_SPARE_30_13_MASK                (0x7FFFE000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_REFSYS_SPARE_30_13_SHIFT               (0x0000000DU)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_REFSYS_SPARE_30_13_RESETVAL            (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_REFSYS_SPARE_30_13_MAX                 (0x0003FFFFU)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_ANALOGTEST_TMUX_ESD_CTRL_MASK          (0x80000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_ANALOGTEST_TMUX_ESD_CTRL_SHIFT         (0x0000001FU)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_ANALOGTEST_TMUX_ESD_CTRL_RESETVAL      (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_ANALOGTEST_TMUX_ESD_CTRL_MAX           (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_SPARE_REG_RESETVAL                               (0x00000000U)

/* REFSYS_TMUX_CTRL */

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P45V_MASK                        (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P45V_SHIFT                       (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P45V_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P45V_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P9V_MASK                         (0x00000002U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P9V_SHIFT                        (0x00000001U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P9V_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VREF_0P9V_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBG_1P22V_MASK                         (0x00000004U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBG_1P22V_SHIFT                        (0x00000002U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBG_1P22V_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBG_1P22V_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED2_MASK                         (0x00000008U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED2_SHIFT                        (0x00000003U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED2_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED2_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBE_WEAK_MASK                          (0x00000010U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBE_WEAK_SHIFT                         (0x00000004U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBE_WEAK_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VBE_WEAK_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED3_MASK                         (0x00000020U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED3_SHIFT                        (0x00000005U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED3_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED3_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_20U_MASK                        (0x00000040U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_20U_SHIFT                       (0x00000006U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_20U_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_20U_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_TS_6U_MASK                      (0x00000080U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_TS_6U_SHIFT                     (0x00000007U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_TS_6U_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IBIASP_TS_6U_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED4_MASK                         (0x00000100U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED4_SHIFT                        (0x00000008U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED4_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED4_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IDIODEP_100U_MASK                      (0x00000200U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IDIODEP_100U_SHIFT                     (0x00000009U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IDIODEP_100U_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IDIODEP_100U_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IREFP_10UA_MASK                        (0x00000400U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IREFP_10UA_SHIFT                       (0x0000000AU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IREFP_10UA_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_IREFP_10UA_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VSSA_REF_MASK                          (0x00000800U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VSSA_REF_SHIFT                         (0x0000000BU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VSSA_REF_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_VSSA_REF_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_I2V_SENSE_MASK                         (0x00001000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_I2V_SENSE_SHIFT                        (0x0000000CU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_I2V_SENSE_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_I2V_SENSE_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_BYPASS_MIRR_VPBIAS_MASK                (0x00002000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_BYPASS_MIRR_VPBIAS_SHIFT               (0x0000000DU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_BYPASS_MIRR_VPBIAS_RESETVAL            (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_BYPASS_MIRR_VPBIAS_MAX                 (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_TX_IBIASP_20U_MASK                     (0x00004000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_TX_IBIASP_20U_SHIFT                    (0x0000000EU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_TX_IBIASP_20U_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_TX_IBIASP_20U_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_LO_IBIASP_20U_MASK                     (0x00008000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_LO_IBIASP_20U_SHIFT                    (0x0000000FU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_LO_IBIASP_20U_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_LO_IBIASP_20U_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED1_MASK                         (0x7FFF0000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED1_SHIFT                        (0x00000010U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED1_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESERVED1_MAX                          (0x00007FFFU)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_REFSYS_CTRL_8_MASK                     (0x80000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_REFSYS_CTRL_8_SHIFT                    (0x0000001FU)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_REFSYS_CTRL_8_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_REFSYS_CTRL_8_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_REFSYS_TMUX_CTRL_RESETVAL                               (0x00000000U)

/* RFANA_BIST_CTRL5 */


/* TW_ANA_TMUX_CTRL */

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_WU_ANA_TEST_OUT_1P8V_MASK              (0x00000001U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_WU_ANA_TEST_OUT_1P8V_SHIFT             (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_WU_ANA_TEST_OUT_1P8V_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_WU_ANA_TEST_OUT_1P8V_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_REFSYS_TEST_OUT_1P8V_MASK              (0x00000002U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_REFSYS_TEST_OUT_1P8V_SHIFT             (0x00000001U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_REFSYS_TEST_OUT_1P8V_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_REFSYS_TEST_OUT_1P8V_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_2_MASK                      (0x00000004U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_2_SHIFT                     (0x00000002U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_2_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_2_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_3_MASK                      (0x00000008U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_3_SHIFT                     (0x00000003U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_3_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_3_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_4_MASK                      (0x00000010U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_4_SHIFT                     (0x00000004U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_4_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_4_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_5_MASK                      (0x00000020U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_5_SHIFT                     (0x00000005U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_5_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_PM_ANA_INP_5_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_S_BUFF_MASK                        (0x00000040U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_S_BUFF_SHIFT                       (0x00000006U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_S_BUFF_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_S_BUFF_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_W_BUFF_MASK                        (0x00000080U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_W_BUFF_SHIFT                       (0x00000007U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_W_BUFF_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_W_BUFF_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DC_BIST_BUF_INP_1P8V_MASK              (0x00000100U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DC_BIST_BUF_INP_1P8V_SHIFT             (0x00000008U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DC_BIST_BUF_INP_1P8V_RESETVAL          (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DC_BIST_BUF_INP_1P8V_MAX               (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_BUF_OUT_1P8V_MASK                  (0x00000200U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_BUF_OUT_1P8V_SHIFT                 (0x00000009U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_BUF_OUT_1P8V_RESETVAL              (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_BUF_OUT_1P8V_MAX                   (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_REF_BUF_OUT_MASK                   (0x00000400U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_REF_BUF_OUT_SHIFT                  (0x0000000AU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_REF_BUF_OUT_RESETVAL               (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ADC_REF_BUF_OUT_MAX                    (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DELVBE_BUFF_OUT_MASK                   (0x00000800U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DELVBE_BUFF_OUT_SHIFT                  (0x0000000BU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DELVBE_BUFF_OUT_RESETVAL               (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_DELVBE_BUFF_OUT_MAX                    (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_STRONG_MASK                     (0x00001000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_STRONG_SHIFT                    (0x0000000CU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_STRONG_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_STRONG_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_WEAK_MASK                       (0x00002000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_WEAK_SHIFT                      (0x0000000DU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_WEAK_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_VBE_TS_WEAK_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ODP_MASK                               (0x00004000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ODP_SHIFT                              (0x0000000EU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ODP_RESETVAL                           (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ODP_MAX                                (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_BIST_MUX_OUT_1P8V_MASK                 (0x00008000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_BIST_MUX_OUT_1P8V_SHIFT                (0x0000000FU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_BIST_MUX_OUT_1P8V_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_BIST_MUX_OUT_1P8V_MAX                  (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_I2V_SENSE_MASK                         (0x00010000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_I2V_SENSE_SHIFT                        (0x00000010U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_I2V_SENSE_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_I2V_SENSE_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_TMUX_BUF_OUT_EN_MASK                   (0x00020000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_TMUX_BUF_OUT_EN_SHIFT                  (0x00000011U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_TMUX_BUF_OUT_EN_RESETVAL               (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_TMUX_BUF_OUT_EN_MAX                    (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ATESTV_VSLDO_MASK                      (0x00040000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ATESTV_VSLDO_SHIFT                     (0x00000012U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ATESTV_VSLDO_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ATESTV_VSLDO_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_RESERVED0_MASK                         (0x3FF80000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_RESERVED0_SHIFT                        (0x00000013U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_RESERVED0_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_RESERVED0_MAX                          (0x000007FFU)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_CLK_TMUX_ESD_CTRL_MASK                 (0x40000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_CLK_TMUX_ESD_CTRL_SHIFT                (0x0000001EU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_CLK_TMUX_ESD_CTRL_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_CLK_TMUX_ESD_CTRL_MAX                  (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ANA_TEST_EN_MASK                       (0x80000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ANA_TEST_EN_SHIFT                      (0x0000001FU)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ANA_TEST_EN_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_ANA_TEST_EN_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_TW_ANA_TMUX_CTRL_RESETVAL                               (0x00000000U)

/* TW_CTRL_REG */

#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_EN_MASK                                 (0x00000001U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_EN_SHIFT                                (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_EN_RESETVAL                             (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_EN_MAX                                  (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_START_CONV_MASK                         (0x00000002U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_START_CONV_SHIFT                        (0x00000001U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_START_CONV_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_START_CONV_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_RESET_MASK                              (0x00000004U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_RESET_SHIFT                             (0x00000002U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_RESET_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_RESET_MAX                               (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_INP_BUF_EN_MASK                         (0x00000008U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_INP_BUF_EN_SHIFT                        (0x00000003U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_INP_BUF_EN_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_INP_BUF_EN_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_BUF_EN_MASK                         (0x00000010U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_BUF_EN_SHIFT                        (0x00000004U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_BUF_EN_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_BUF_EN_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_SEL_2_0_MASK                        (0x000000E0U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_SEL_2_0_SHIFT                       (0x00000005U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_SEL_2_0_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ADC_REF_SEL_2_0_MAX                         (0x00000007U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_DIFF_INP_BUF_EN_MASK                     (0x00000100U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_DIFF_INP_BUF_EN_SHIFT                    (0x00000008U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_DIFF_INP_BUF_EN_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_DIFF_INP_BUF_EN_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_SE_INP_BUF_EN_MASK                       (0x00000200U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_SE_INP_BUF_EN_SHIFT                      (0x00000009U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_SE_INP_BUF_EN_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_TS_SE_INP_BUF_EN_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_IFORCE_EXT_CTRL_MASK                        (0x00000400U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_IFORCE_EXT_CTRL_SHIFT                       (0x0000000AU)
#define CSL_TOP_ANAREG_TW_CTRL_REG_IFORCE_EXT_CTRL_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_IFORCE_EXT_CTRL_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_VREF_EXT_CTRL_MASK                          (0x00000800U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_VREF_EXT_CTRL_SHIFT                         (0x0000000BU)
#define CSL_TOP_ANAREG_TW_CTRL_REG_VREF_EXT_CTRL_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_VREF_EXT_CTRL_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_VIN_EXT_CTRL_MASK                           (0x00001000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_VIN_EXT_CTRL_SHIFT                          (0x0000000CU)
#define CSL_TOP_ANAREG_TW_CTRL_REG_VIN_EXT_CTRL_RESETVAL                       (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_VIN_EXT_CTRL_MAX                            (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_BYPASS_MASK                    (0x00002000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_BYPASS_SHIFT                   (0x0000000DU)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_BYPASS_RESETVAL                (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_BYPASS_MAX                     (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_EN_MASK                        (0x00004000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_EN_SHIFT                       (0x0000000EU)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_EN_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_ANA_TMUX_BUF_EN_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_TW_CTRL_REG_RTRIM_TW_4_0_MASK                           (0x000F8000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_RTRIM_TW_4_0_SHIFT                          (0x0000000FU)
#define CSL_TOP_ANAREG_TW_CTRL_REG_RTRIM_TW_4_0_RESETVAL                       (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_RTRIM_TW_4_0_MAX                            (0x0000001FU)

#define CSL_TOP_ANAREG_TW_CTRL_REG_RESERVED1_MASK                              (0xFFF00000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_RESERVED1_SHIFT                             (0x00000014U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_RESERVED1_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_TW_CTRL_REG_RESERVED1_MAX                               (0x00000FFFU)

#define CSL_TOP_ANAREG_TW_CTRL_REG_RESETVAL                                    (0x00000000U)

/* TW_SPARE */

#define CSL_TOP_ANAREG_TW_SPARE_RESERVED0_MASK                                 (0xFFFFFFFFU)
#define CSL_TOP_ANAREG_TW_SPARE_RESERVED0_SHIFT                                (0x00000000U)
#define CSL_TOP_ANAREG_TW_SPARE_RESERVED0_RESETVAL                             (0x00000000U)
#define CSL_TOP_ANAREG_TW_SPARE_RESERVED0_MAX                                  (0xFFFFFFFFU)

#define CSL_TOP_ANAREG_TW_SPARE_RESETVAL                                       (0x00000000U)

/* WU_CTRL_REG */

#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_EN_MASK                             (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_EN_SHIFT                            (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_EN_RESETVAL                         (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_EN_MAX                              (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_STOP_MASK                           (0x00000002U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_STOP_SHIFT                          (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_STOP_RESETVAL                       (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_STOP_MAX                            (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_SW_SEL_MASK                         (0x00000004U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_SW_SEL_SHIFT                        (0x00000002U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_SW_SEL_RESETVAL                     (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_SW_SEL_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_TRIM_7_0_MASK                       (0x000007F8U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_TRIM_7_0_SHIFT                      (0x00000003U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_TRIM_7_0_RESETVAL                   (0x0000004BU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_TRIM_7_0_MAX                        (0x000000FFU)

#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_FREQ_SEL_3_0_MASK                   (0x00007800U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_FREQ_SEL_3_0_SHIFT                  (0x0000000BU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_FREQ_SEL_3_0_RESETVAL               (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_INT_CLK_FREQ_SEL_3_0_MAX                    (0x0000000FU)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_CPU_CLK_CTRL_MASK                        (0x00008000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_CPU_CLK_CTRL_SHIFT                       (0x0000000FU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_CPU_CLK_CTRL_RESETVAL                    (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_CPU_CLK_CTRL_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_XTAL_EN_OVERRIDE_MASK                       (0x00010000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_XTAL_EN_OVERRIDE_SHIFT                      (0x00000010U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_XTAL_EN_OVERRIDE_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_XTAL_EN_OVERRIDE_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_UV_DET_CTRL_MASK                         (0x00020000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_UV_DET_CTRL_SHIFT                        (0x00000011U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_UV_DET_CTRL_RESETVAL                     (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_UV_DET_CTRL_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_OV_DET_CTRL_MASK                         (0x00040000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_OV_DET_CTRL_SHIFT                        (0x00000012U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_OV_DET_CTRL_RESETVAL                     (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_OV_DET_CTRL_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_XTAL_DLY_CTRL_MASK                       (0x00080000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_XTAL_DLY_CTRL_SHIFT                      (0x00000013U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_XTAL_DLY_CTRL_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_XTAL_DLY_CTRL_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_VMON_EN_MASK                        (0x00100000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_VMON_EN_SHIFT                       (0x00000014U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_VMON_EN_RESETVAL                    (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_VMON_EN_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VRAM_VMON_EN_MASK                        (0x00200000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VRAM_VMON_EN_SHIFT                       (0x00000015U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VRAM_VMON_EN_RESETVAL                    (0x00000001U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VRAM_VMON_EN_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_DET_CTRL_MASK                       (0x00400000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_DET_CTRL_SHIFT                      (0x00000016U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_DET_CTRL_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SUPP_DET_CTRL_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_MASK                            (0x01800000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_SHIFT                           (0x00000017U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_MAX                             (0x00000003U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDS_3P3V_UV_VMON_EN_MASK                (0x02000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDS_3P3V_UV_VMON_EN_SHIFT               (0x00000019U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDS_3P3V_UV_VMON_EN_RESETVAL            (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDS_3P3V_UV_VMON_EN_MAX                 (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDA_OSC_UV_VMON_EN_MASK                 (0x04000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDA_OSC_UV_VMON_EN_SHIFT                (0x0000001AU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDA_OSC_UV_VMON_EN_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDDA_OSC_UV_VMON_EN_MAX                  (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_UV_VMON_EN_MASK                      (0x08000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_UV_VMON_EN_SHIFT                     (0x0000001BU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_UV_VMON_EN_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_UV_VMON_EN_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_OV_VMON_EN_MASK                      (0x10000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_OV_VMON_EN_SHIFT                     (0x0000001CU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_OV_VMON_EN_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_VDD_OV_VMON_EN_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_2_MASK                          (0x60000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_2_SHIFT                         (0x0000001DU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_2_RESETVAL                      (0x00000003U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_WU_SPARE_IN_2_MAX                           (0x00000003U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_RESERVED0_MASK                              (0x80000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_RESERVED0_SHIFT                             (0x0000001FU)
#define CSL_TOP_ANAREG_WU_CTRL_REG_RESERVED0_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_WU_CTRL_REG_RESERVED0_MAX                               (0x00000001U)

#define CSL_TOP_ANAREG_WU_CTRL_REG_RESETVAL                                    (0x6036825DU)

/* WU_MODE_REG */

#define CSL_TOP_ANAREG_WU_MODE_REG_FUNC_TEST_DET_SYNC_MASK                     (0x00000001U)
#define CSL_TOP_ANAREG_WU_MODE_REG_FUNC_TEST_DET_SYNC_SHIFT                    (0x00000000U)
#define CSL_TOP_ANAREG_WU_MODE_REG_FUNC_TEST_DET_SYNC_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_WU_MODE_REG_FUNC_TEST_DET_SYNC_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_WU_MODE_REG_TEST_MODE_DET_SYNC_MASK                     (0x00000002U)
#define CSL_TOP_ANAREG_WU_MODE_REG_TEST_MODE_DET_SYNC_SHIFT                    (0x00000001U)
#define CSL_TOP_ANAREG_WU_MODE_REG_TEST_MODE_DET_SYNC_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_WU_MODE_REG_TEST_MODE_DET_SYNC_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_WU_MODE_REG_SOP_MODE_LAT_4_0_MASK                       (0x0000007CU)
#define CSL_TOP_ANAREG_WU_MODE_REG_SOP_MODE_LAT_4_0_SHIFT                      (0x00000002U)
#define CSL_TOP_ANAREG_WU_MODE_REG_SOP_MODE_LAT_4_0_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_MODE_REG_SOP_MODE_LAT_4_0_MAX                        (0x0000001FU)

#define CSL_TOP_ANAREG_WU_MODE_REG_RESERVED0_MASK                              (0xFFFFFFE0U)
#define CSL_TOP_ANAREG_WU_MODE_REG_RESERVED0_SHIFT                             (0x00000005U)
#define CSL_TOP_ANAREG_WU_MODE_REG_RESERVED0_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_WU_MODE_REG_RESERVED0_MAX                               (0x07FFFFFFU)

#define CSL_TOP_ANAREG_WU_MODE_REG_RESETVAL                                    (0x00000000U)

/* WU_SPARE_OUT */

#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDCLK18DET_MASK                           (0x00000001U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDCLK18DET_SHIFT                          (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDCLK18DET_RESETVAL                       (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDCLK18DET_MAX                            (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDARF_DET_MASK                            (0x00000002U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDARF_DET_SHIFT                           (0x00000001U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDARF_DET_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDARF_DET_MAX                             (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDS18DET_MASK                             (0x00000004U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDS18DET_SHIFT                            (0x00000002U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDS18DET_RESETVAL                         (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_VDDS18DET_MAX                              (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_HVMODE_MASK                                (0x00000008U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_HVMODE_SHIFT                               (0x00000003U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_HVMODE_RESETVAL                            (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_HVMODE_MAX                                 (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_SUPPDET_OV_CTRL_MASK                       (0x00000010U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_SUPPDET_OV_CTRL_SHIFT                      (0x00000004U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_SUPPDET_OV_CTRL_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_SUPPDET_OV_CTRL_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_INT_OSC_CTRL_MASK                          (0x00000020U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_INT_OSC_CTRL_SHIFT                         (0x00000005U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_INT_OSC_CTRL_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_INT_OSC_CTRL_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_OVDET_LOWV_MASK                       (0x00000040U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_OVDET_LOWV_SHIFT                      (0x00000006U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_OVDET_LOWV_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_OVDET_LOWV_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_UVDET_LOWV_MASK                       (0x00000080U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_UVDET_LOWV_SHIFT                      (0x00000007U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_UVDET_LOWV_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_CORE_UVDET_LOWV_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_RESERVED0_MASK                             (0xFFFFFF00U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_RESERVED0_SHIFT                            (0x00000008U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_RESERVED0_RESETVAL                         (0x00000000U)
#define CSL_TOP_ANAREG_WU_SPARE_OUT_RESERVED0_MAX                              (0x00FFFFFFU)

#define CSL_TOP_ANAREG_WU_SPARE_OUT_RESETVAL                                   (0x00000000U)

/* WU_STATUS_REG */

#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_OVDET_LAT_MASK                       (0x00000001U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_OVDET_LAT_SHIFT                      (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_OVDET_LAT_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_OVDET_LAT_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_UVDET_LAT_MASK                       (0x00000002U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_UVDET_LAT_SHIFT                      (0x00000001U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_UVDET_LAT_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_CORE_UVDET_LAT_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_ANA18_MASK                        (0x00000004U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_ANA18_SHIFT                       (0x00000002U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_ANA18_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_ANA18_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_CLK18_MASK                        (0x00000008U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_CLK18_SHIFT                       (0x00000003U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_CLK18_RESETVAL                    (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_CLK18_MAX                         (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO18_MASK                         (0x00000010U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO18_SHIFT                        (0x00000004U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO18_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO18_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO33_MASK                         (0x00000020U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO33_SHIFT                        (0x00000005U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO33_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_IO33_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF10_MASK                         (0x00000040U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF10_SHIFT                        (0x00000006U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF10_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF10_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF14_MASK                         (0x00000080U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF14_SHIFT                        (0x00000007U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF14_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF14_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF2_14_MASK                       (0x00000100U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF2_14_SHIFT                      (0x00000008U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF2_14_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_RF2_14_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_SRAM12_MASK                       (0x00000200U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_SRAM12_SHIFT                      (0x00000009U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_SRAM12_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_SRAM12_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_VDDD18_MASK                       (0x00000400U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_VDDD18_SHIFT                      (0x0000000AU)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_VDDD18_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_VDDD18_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_REF_CLK_STATUS_MASK                       (0x00000800U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_REF_CLK_STATUS_SHIFT                      (0x0000000BU)
#define CSL_TOP_ANAREG_WU_STATUS_REG_REF_CLK_STATUS_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_REF_CLK_STATUS_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_RCOSC_CLK_STATUS_MASK                     (0x00001000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_RCOSC_CLK_STATUS_SHIFT                    (0x0000000CU)
#define CSL_TOP_ANAREG_WU_STATUS_REG_RCOSC_CLK_STATUS_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_RCOSC_CLK_STATUS_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_XTAL_DET_STATUS_MASK                      (0x00002000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_XTAL_DET_STATUS_SHIFT                     (0x0000000DU)
#define CSL_TOP_ANAREG_WU_STATUS_REG_XTAL_DET_STATUS_RESETVAL                  (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_XTAL_DET_STATUS_MAX                       (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_LIMP_MODE_STATUS_MASK                     (0x00004000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_LIMP_MODE_STATUS_SHIFT                    (0x0000000EU)
#define CSL_TOP_ANAREG_WU_STATUS_REG_LIMP_MODE_STATUS_RESETVAL                 (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_LIMP_MODE_STATUS_MAX                      (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_HVMODE_MASK                               (0x00008000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_HVMODE_SHIFT                              (0x0000000FU)
#define CSL_TOP_ANAREG_WU_STATUS_REG_HVMODE_RESETVAL                           (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_HVMODE_MAX                                (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_APLLVCO18_MASK                    (0x00010000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_APLLVCO18_SHIFT                   (0x00000010U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_APLLVCO18_RESETVAL                (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_SUPP_OK_APLLVCO18_MAX                     (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDA_OSC_UVDET_LAT_MASK                   (0x00020000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDA_OSC_UVDET_LAT_SHIFT                  (0x00000011U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDA_OSC_UVDET_LAT_RESETVAL               (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDA_OSC_UVDET_LAT_MAX                    (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDS_3P3V_UVDET_LAT_MASK                  (0x00040000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDS_3P3V_UVDET_LAT_SHIFT                 (0x00000012U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDS_3P3V_UVDET_LAT_RESETVAL              (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_VDDS_3P3V_UVDET_LAT_MAX                   (0x00000001U)

#define CSL_TOP_ANAREG_WU_STATUS_REG_RESERVED0_MASK                            (0xFFF80000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_RESERVED0_SHIFT                           (0x00000013U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_RESERVED0_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_STATUS_REG_RESERVED0_MAX                             (0x00001FFFU)

#define CSL_TOP_ANAREG_WU_STATUS_REG_RESETVAL                                  (0x00000000U)

/* WU_TMUX_CTRL */

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDVCO18_MASK                       (0x00000001U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDVCO18_SHIFT                      (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDVCO18_RESETVAL                   (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDVCO18_MAX                        (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDD_SRAM_MASK                              (0x00000002U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDD_SRAM_SHIFT                             (0x00000001U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDD_SRAM_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDD_SRAM_MAX                               (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS18_MASK                         (0x00000004U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS18_SHIFT                        (0x00000002U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS18_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS18_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P5V_MASK                              (0x00000008U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P5V_SHIFT                             (0x00000003U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P5V_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P5V_MAX                               (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VIOIN_MASK                          (0x00000010U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VIOIN_SHIFT                         (0x00000004U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VIOIN_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VIOIN_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_MASK                 (0x00000020U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_SHIFT                (0x00000005U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_RESETVAL             (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_MAX                  (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P6V_MASK                             (0x00000040U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P6V_SHIFT                            (0x00000006U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P6V_RESETVAL                         (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P6V_MAX                              (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P9V_MASK                             (0x00000080U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P9V_SHIFT                            (0x00000007U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P9V_RESETVAL                         (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VREF_0P9V_MAX                              (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA18_MASK                         (0x00000100U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA18_SHIFT                        (0x00000008U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA18_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA18_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P8V_MASK                              (0x00000200U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P8V_SHIFT                             (0x00000009U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P8V_RESETVAL                          (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VFB_0P8V_MAX                               (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_INT_MASK                            (0x00000400U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_INT_SHIFT                           (0x0000000AU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_INT_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_INT_MAX                             (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_1P2_MASK             (0x00000800U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_1P2_SHIFT            (0x0000000BU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_1P2_RESETVAL         (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDA_LVDS_1P8V_1P2_MAX              (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_2_INT_MASK                          (0x00001000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_2_INT_SHIFT                         (0x0000000CU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_2_INT_RESETVAL                      (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VDDA14_2_INT_MAX                           (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_ANA_SIG_MASK                            (0x00002000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_ANA_SIG_SHIFT                           (0x0000000DU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_ANA_SIG_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_ANA_SIG_MAX                             (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_DIG_SIG_MASK                            (0x00004000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_DIG_SIG_SHIFT                           (0x0000000EU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_DIG_SIG_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_VT_DIG_SIG_MAX                             (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS33_MASK                         (0x00008000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS33_SHIFT                        (0x0000000FU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS33_RESETVAL                     (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_SCALED_VDDS33_MAX                          (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_RESERVED0_MASK                             (0x7FFF0000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_RESERVED0_SHIFT                            (0x00000010U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_RESERVED0_RESETVAL                         (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_RESERVED0_MAX                              (0x00007FFFU)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_WU_TMUX_EN_MASK                            (0x80000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_WU_TMUX_EN_SHIFT                           (0x0000001FU)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_WU_TMUX_EN_RESETVAL                        (0x00000000U)
#define CSL_TOP_ANAREG_WU_TMUX_CTRL_WU_TMUX_EN_MAX                             (0x00000001U)

#define CSL_TOP_ANAREG_WU_TMUX_CTRL_RESETVAL                                   (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
