let common = system.getScript("/common");
let xbarSoc = system.getScript(`/xbar/soc/xbar_${common.getSocName()}`);

const internal_list = [
    {  name: "EPWM0_SOCA", displayName: "EPWM0_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM1_SOCA", displayName: "EPWM1_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM2_SOCA", displayName: "EPWM2_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM3_SOCA", displayName: "EPWM3_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM4_SOCA", displayName: "EPWM4_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM5_SOCA", displayName: "EPWM5_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM6_SOCA", displayName: "EPWM6_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM7_SOCA", displayName: "EPWM7_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM8_SOCA", displayName: "EPWM8_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM9_SOCA", displayName: "EPWM9_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM10_SOCA", displayName: "EPWM10_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM11_SOCA", displayName: "EPWM11_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM12_SOCA", displayName: "EPWM12_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM13_SOCA", displayName: "EPWM13_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM14_SOCA", displayName: "EPWM14_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM15_SOCA", displayName: "EPWM15_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM16_SOCA", displayName: "EPWM16_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM17_SOCA", displayName: "EPWM17_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM18_SOCA", displayName: "EPWM18_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM19_SOCA", displayName: "EPWM19_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM20_SOCA", displayName: "EPWM20_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM21_SOCA", displayName: "EPWM21_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM22_SOCA", displayName: "EPWM22_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM23_SOCA", displayName: "EPWM23_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM24_SOCA", displayName: "EPWM24_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM25_SOCA", displayName: "EPWM25_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM26_SOCA", displayName: "EPWM26_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM27_SOCA", displayName: "EPWM27_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM28_SOCA", displayName: "EPWM28_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM29_SOCA", displayName: "EPWM29_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM30_SOCA", displayName: "EPWM30_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM31_SOCA", displayName: "EPWM31_SOCA", path: "dma_xbar", group: 0 },
    {  name: "EPWM0_SOCB", displayName: "EPWM0_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM1_SOCB", displayName: "EPWM1_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM2_SOCB", displayName: "EPWM2_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM3_SOCB", displayName: "EPWM3_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM4_SOCB", displayName: "EPWM4_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM5_SOCB", displayName: "EPWM5_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM6_SOCB", displayName: "EPWM6_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM7_SOCB", displayName: "EPWM7_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM8_SOCB", displayName: "EPWM8_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM9_SOCB", displayName: "EPWM9_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM10_SOCB", displayName: "EPWM10_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM11_SOCB", displayName: "EPWM11_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM12_SOCB", displayName: "EPWM12_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM13_SOCB", displayName: "EPWM13_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM14_SOCB", displayName: "EPWM14_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM15_SOCB", displayName: "EPWM15_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM16_SOCB", displayName: "EPWM16_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM17_SOCB", displayName: "EPWM17_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM18_SOCB", displayName: "EPWM18_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM19_SOCB", displayName: "EPWM19_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM20_SOCB", displayName: "EPWM20_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM21_SOCB", displayName: "EPWM21_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM22_SOCB", displayName: "EPWM22_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM23_SOCB", displayName: "EPWM23_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM24_SOCB", displayName: "EPWM24_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM25_SOCB", displayName: "EPWM25_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM26_SOCB", displayName: "EPWM26_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM27_SOCB", displayName: "EPWM27_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM28_SOCB", displayName: "EPWM28_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM29_SOCB", displayName: "EPWM29_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM30_SOCB", displayName: "EPWM30_SOCB", path: "dma_xbar", group: 1 },
    {  name: "EPWM31_SOCB", displayName: "EPWM31_SOCB", path: "dma_xbar", group: 1 },
    {  name: "ADC0_INT1", displayName: "ADC0_INT1", path: "dma_xbar", group: 2 },
    {  name: "ADC0_INT2", displayName: "ADC0_INT2", path: "dma_xbar", group: 2 },
    {  name: "ADC0_INT3", displayName: "ADC0_INT3", path: "dma_xbar", group: 2 },
    {  name: "ADC0_INT4", displayName: "ADC0_INT4", path: "dma_xbar", group: 2 },
    {  name: "ADC0_EVTINT", displayName: "ADC0_EVTINT", path: "dma_xbar", group: 2 },
    {  name: "ADC1_INT1", displayName: "ADC1_INT1", path: "dma_xbar", group: 2 },
    {  name: "ADC1_INT2", displayName: "ADC1_INT2", path: "dma_xbar", group: 2 },
    {  name: "ADC1_INT3", displayName: "ADC1_INT3", path: "dma_xbar", group: 2 },
    {  name: "ADC1_INT4", displayName: "ADC1_INT4", path: "dma_xbar", group: 2 },
    {  name: "ADC1_EVTINT", displayName: "ADC1_EVTINT", path: "dma_xbar", group: 2 },
    {  name: "ADC2_INT1", displayName: "ADC2_INT1", path: "dma_xbar", group: 2 },
    {  name: "ADC2_INT2", displayName: "ADC2_INT2", path: "dma_xbar", group: 2 },
    {  name: "ADC2_INT3", displayName: "ADC2_INT3", path: "dma_xbar", group: 2 },
    {  name: "ADC2_INT4", displayName: "ADC2_INT4", path: "dma_xbar", group: 2 },
    {  name: "ADC2_EVTINT", displayName: "ADC2_EVTINT", path: "dma_xbar", group: 2 },
    {  name: "ADC3_INT1", displayName: "ADC3_INT1", path: "dma_xbar", group: 2 },
    {  name: "ADC3_INT2", displayName: "ADC3_INT2", path: "dma_xbar", group: 2 },
    {  name: "ADC3_INT3", displayName: "ADC3_INT3", path: "dma_xbar", group: 2 },
    {  name: "ADC3_INT4", displayName: "ADC3_INT4", path: "dma_xbar", group: 2 },
    {  name: "ADC3_EVTINT", displayName: "ADC3_EVTINT", path: "dma_xbar", group: 2 },
    {  name: "ADC4_INT1", displayName: "ADC4_INT1", path: "dma_xbar", group: 2 },
    {  name: "ADC4_INT2", displayName: "ADC4_INT2", path: "dma_xbar", group: 2 },
    {  name: "ADC4_INT3", displayName: "ADC4_INT3", path: "dma_xbar", group: 2 },
    {  name: "ADC4_INT4", displayName: "ADC4_INT4", path: "dma_xbar", group: 2 },
    {  name: "ADC4_EVTINT", displayName: "ADC4_EVTINT", path: "dma_xbar", group: 2 },
    {  name: "FSI0_RX_DMA_EVT", displayName: "FSI0_RX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI0_DMA_TRIG1", displayName: "FSI0_DMA_TRIG1", path: "dma_xbar", group: 3 },
    {  name: "FSI0_DMA_TRIG2", displayName: "FSI0_DMA_TRIG2", path: "dma_xbar", group: 3 },
    {  name: "FSI1_RX_DMA_EVT", displayName: "FSI1_RX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI1_DMA_TRIG1", displayName: "FSI1_DMA_TRIG1", path: "dma_xbar", group: 3 },
    {  name: "FSI1_DMA_TRIG1", displayName: "FSI1_DMA_TRIG2", path: "dma_xbar", group: 3 },
    {  name: "FSI2_RX_DMA_EVT", displayName: "FSI2_RX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI2_DMA_TRIG1", displayName: "FSI2_DMA_TRIG1", path: "dma_xbar", group: 3 },
    {  name: "FSI2_DMA_TRIG1", displayName: "FSI2_DMA_TRIG2", path: "dma_xbar", group: 3 },
    {  name: "FSI3_RX_DMA_EVT", displayName: "FSI3_RX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI3_DMA_TRIG1", displayName: "FSI3_DMA_TRIG1", path: "dma_xbar", group: 3 },
    {  name: "FSI3_DMA_TRIG1", displayName: "FSI3_DMA_TRIG2", path: "dma_xbar", group: 3 },
    {  name: "FSI0_TX_DMA_EVT", displayName: "FSI0_TX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI1_TX_DMA_EVT", displayName: "FSI1_TX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI2_TX_DMA_EVT", displayName: "FSI2_TX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "FSI3_TX_DMA_EVT", displayName: "FSI3_TX_DMA_EVT", path: "dma_xbar", group: 3 },
    {  name: "SD0_FILT0_DRINT", displayName: "SD0_FILT0_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD0_FILT1_DRINT", displayName: "SD0_FILT1_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD0_FILT2_DRINT", displayName: "SD0_FILT2_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD0_FILT3_DRINT", displayName: "SD0_FILT3_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD1_FILT0_DRINT", displayName: "SD1_FILT0_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD1_FILT1_DRINT", displayName: "SD1_FILT1_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD1_FILT2_DRINT", displayName: "SD1_FILT2_DRINT", path: "dma_xbar", group: 4 },
    {  name: "SD1_FILT3_DRINT", displayName: "SD1_FILT3_DRINT", path: "dma_xbar", group: 4 },
    {  name: "ECAP0_DMA_INT", displayName: "ECAP0_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP1_DMA_INT", displayName: "ECAP1_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP2_DMA_INT", displayName: "ECAP2_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP3_DMA_INT", displayName: "ECAP3_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP4_DMA_INT", displayName: "ECAP4_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP5_DMA_INT", displayName: "ECAP5_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP6_DMA_INT", displayName: "ECAP6_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP7_DMA_INT", displayName: "ECAP7_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP8_DMA_INT", displayName: "ECAP8_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP9_DMA_INT", displayName: "ECAP9_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP10_DMA_INT", displayName: "ECAP10_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP11_DMA_INT", displayName: "ECAP11_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP12_DMA_INT", displayName: "ECAP12_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP13_DMA_INT", displayName: "ECAP13_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP14_DMA_INT", displayName: "ECAP14_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ECAP15_DMA_INT", displayName: "ECAP15_DMA_INT", path: "dma_xbar", group: 5 },
    {  name: "ADC_R0_INT1", displayName: "ADC_R0_INT1", path: "dma_xbar", group: 6 },
    {  name: "ADC_R0_INT2", displayName: "ADC_R0_INT2", path: "dma_xbar", group: 6 },
    {  name: "ADC_R0_INT3", displayName: "ADC_R0_INT3", path: "dma_xbar", group: 6 },
    {  name: "ADC_R0_INT4", displayName: "ADC_R0_INT4", path: "dma_xbar", group: 6 },
    {  name: "ADC_R0_EVTINT", displayName: "ADC_R0_EVTINT", path: "dma_xbar", group: 6 },
    {  name: "ADC_R1_INT1", displayName: "ADC_R1_INT1", path: "dma_xbar", group: 6 },
    {  name: "ADC_R1_INT2", displayName: "ADC_R1_INT2", path: "dma_xbar", group: 6 },
    {  name: "ADC_R1_INT3", displayName: "ADC_R1_INT3", path: "dma_xbar", group: 6 },
    {  name: "ADC_R1_INT4", displayName: "ADC_R1_INT4", path: "dma_xbar", group: 6 },
    {  name: "ADC_R1_EVTINT", displayName: "ADC_R1_EVTINT", path: "dma_xbar", group: 6 },
];

let xbarProperties = {
    masterXbarList: [],
    outputInstanceList: [
        { name: "DMA_XBAR_DMA_TRIG_XBAR", count: 16},
    ],
    duplicatesPresent: false,
    moduleString: "dma_xbar",
}

function getOptionList(calledBy) {
    return xbarSoc.getOptionListSoc(calledBy, xbarProperties, internal_list);
}

function getConfigArr() {
    return xbarSoc.getXbarInstanceConfig(xbarProperties);
}

exports = {
    getConfigArr,
    getOptionList,
};
