let common = system.getScript("/common");
let xbarSoc = system.getScript(`/xbar/soc/xbar_${common.getSocName()}`);

const internal_list = [
    {   name: "GPIO_INT_XBAR_GPIO_MUX_0", displayName: "GPIO_MUX_0" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_1", displayName: "GPIO_MUX_1", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_2", displayName: "GPIO_MUX_2", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_3", displayName: "GPIO_MUX_3", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_4", displayName: "GPIO_MUX_4", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_5", displayName: "GPIO_MUX_5", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_6", displayName: "GPIO_MUX_6", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_7", displayName: "GPIO_MUX_7", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_8", displayName: "GPIO_MUX_8", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_9", displayName: "GPIO_MUX_9", path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_10", displayName: "GPIO_MUX_10" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_11", displayName: "GPIO_MUX_11" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_12", displayName: "GPIO_MUX_12" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_13", displayName: "GPIO_MUX_13" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_14", displayName: "GPIO_MUX_14" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_15", displayName: "GPIO_MUX_15" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_16", displayName: "GPIO_MUX_16" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_17", displayName: "GPIO_MUX_17" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_18", displayName: "GPIO_MUX_18" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_19", displayName: "GPIO_MUX_19" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_20", displayName: "GPIO_MUX_20" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_21", displayName: "GPIO_MUX_21" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_22", displayName: "GPIO_MUX_22" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_23", displayName: "GPIO_MUX_23" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_24", displayName: "GPIO_MUX_24" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_25", displayName: "GPIO_MUX_25" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_26", displayName: "GPIO_MUX_26" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_27", displayName: "GPIO_MUX_27" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_28", displayName: "GPIO_MUX_28" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_29", displayName: "GPIO_MUX_29" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_30", displayName: "GPIO_MUX_30" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_31", displayName: "GPIO_MUX_31" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_32", displayName: "GPIO_MUX_32" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_33", displayName: "GPIO_MUX_33" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_34", displayName: "GPIO_MUX_34" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_35", displayName: "GPIO_MUX_35" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_36", displayName: "GPIO_MUX_36" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_37", displayName: "GPIO_MUX_37" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_38", displayName: "GPIO_MUX_38" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_39", displayName: "GPIO_MUX_39" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_40", displayName: "GPIO_MUX_40" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_41", displayName: "GPIO_MUX_41" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_42", displayName: "GPIO_MUX_42" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_43", displayName: "GPIO_MUX_43" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_44", displayName: "GPIO_MUX_44" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_45", displayName: "GPIO_MUX_45" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_46", displayName: "GPIO_MUX_46" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_47", displayName: "GPIO_MUX_47" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_48", displayName: "GPIO_MUX_48" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_49", displayName: "GPIO_MUX_49" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_50", displayName: "GPIO_MUX_50" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_51", displayName: "GPIO_MUX_51" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_52", displayName: "GPIO_MUX_52" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_53", displayName: "GPIO_MUX_53" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_54", displayName: "GPIO_MUX_54" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_55", displayName: "GPIO_MUX_55" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_56", displayName: "GPIO_MUX_56" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_57", displayName: "GPIO_MUX_57" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_58", displayName: "GPIO_MUX_58" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_59", displayName: "GPIO_MUX_59" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_60", displayName: "GPIO_MUX_60" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_61", displayName: "GPIO_MUX_61" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_62", displayName: "GPIO_MUX_62" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_63", displayName: "GPIO_MUX_63" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_64", displayName: "GPIO_MUX_64" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_65", displayName: "GPIO_MUX_65" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_66", displayName: "GPIO_MUX_66" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_67", displayName: "GPIO_MUX_67" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_68", displayName: "GPIO_MUX_68" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_69", displayName: "GPIO_MUX_69" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_70", displayName: "GPIO_MUX_70" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_71", displayName: "GPIO_MUX_71" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_72", displayName: "GPIO_MUX_72" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_73", displayName: "GPIO_MUX_73" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_74", displayName: "GPIO_MUX_74" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_75", displayName: "GPIO_MUX_75" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_76", displayName: "GPIO_MUX_76" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_77", displayName: "GPIO_MUX_77" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_78", displayName: "GPIO_MUX_78" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_79", displayName: "GPIO_MUX_79" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_80", displayName: "GPIO_MUX_80" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_81", displayName: "GPIO_MUX_81" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_82", displayName: "GPIO_MUX_82" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_83", displayName: "GPIO_MUX_83" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_84", displayName: "GPIO_MUX_84" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_85", displayName: "GPIO_MUX_85" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_86", displayName: "GPIO_MUX_86" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_87", displayName: "GPIO_MUX_87" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_88", displayName: "GPIO_MUX_88" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_89", displayName: "GPIO_MUX_89" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_90", displayName: "GPIO_MUX_90" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_91", displayName: "GPIO_MUX_91" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_92", displayName: "GPIO_MUX_92" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_93", displayName: "GPIO_MUX_93" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_94", displayName: "GPIO_MUX_94" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_95", displayName: "GPIO_MUX_95" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_96", displayName: "GPIO_MUX_96" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_97", displayName: "GPIO_MUX_97" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_98", displayName: "GPIO_MUX_98" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_99", displayName: "GPIO_MUX_99" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_100", displayName: "GPIO_MUX_100" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_101", displayName: "GPIO_MUX_101" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_102", displayName: "GPIO_MUX_102" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_103", displayName: "GPIO_MUX_103" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_104", displayName: "GPIO_MUX_104" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_105", displayName: "GPIO_MUX_105" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_106", displayName: "GPIO_MUX_106" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_107", displayName: "GPIO_MUX_107" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_108", displayName: "GPIO_MUX_108" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_109", displayName: "GPIO_MUX_109" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_110", displayName: "GPIO_MUX_110" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_111", displayName: "GPIO_MUX_111" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_112", displayName: "GPIO_MUX_112" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_113", displayName: "GPIO_MUX_113" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_114", displayName: "GPIO_MUX_114" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_115", displayName: "GPIO_MUX_115" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_116", displayName: "GPIO_MUX_116" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_117", displayName: "GPIO_MUX_117" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_118", displayName: "GPIO_MUX_118" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_119", displayName: "GPIO_MUX_119" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_120", displayName: "GPIO_MUX_120" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_121", displayName: "GPIO_MUX_121" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_122", displayName: "GPIO_MUX_122" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_123", displayName: "GPIO_MUX_123" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_124", displayName: "GPIO_MUX_124" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_125", displayName: "GPIO_MUX_125" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_126", displayName: "GPIO_MUX_126" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_127", displayName: "GPIO_MUX_127" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_128", displayName: "GPIO_MUX_128" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_129", displayName: "GPIO_MUX_129" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_130", displayName: "GPIO_MUX_130" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_131", displayName: "GPIO_MUX_131" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_132", displayName: "GPIO_MUX_132" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_133", displayName: "GPIO_MUX_133" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_134", displayName: "GPIO_MUX_134" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_135", displayName: "GPIO_MUX_135" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_136", displayName: "GPIO_MUX_136" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_137", displayName: "GPIO_MUX_137" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_138", displayName: "GPIO_MUX_138" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_139", displayName: "GPIO_MUX_139" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_140", displayName: "GPIO_MUX_140" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_141", displayName: "GPIO_MUX_141" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_142", displayName: "GPIO_MUX_142" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_MUX_143", displayName: "GPIO_MUX_143" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_0", displayName: "GPIO_0_BANK_INTR_0" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_1", displayName: "GPIO_0_BANK_INTR_1" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_2", displayName: "GPIO_0_BANK_INTR_2" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_3", displayName: "GPIO_0_BANK_INTR_3" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_4", displayName: "GPIO_0_BANK_INTR_4" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_5", displayName: "GPIO_0_BANK_INTR_5" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_6", displayName: "GPIO_0_BANK_INTR_6" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_7", displayName: "GPIO_0_BANK_INTR_7" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_0_BANK_INTR_8", displayName: "GPIO_0_BANK_INTR_8" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_0", displayName: "GPIO_1_BANK_INTR_0" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_1", displayName: "GPIO_1_BANK_INTR_1" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_2", displayName: "GPIO_1_BANK_INTR_2" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_3", displayName: "GPIO_1_BANK_INTR_3" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_4", displayName: "GPIO_1_BANK_INTR_4" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_5", displayName: "GPIO_1_BANK_INTR_5" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_6", displayName: "GPIO_1_BANK_INTR_6" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_7", displayName: "GPIO_1_BANK_INTR_7" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_1_BANK_INTR_8", displayName: "GPIO_1_BANK_INTR_8" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_0", displayName: "GPIO_2_BANK_INTR_0" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_1", displayName: "GPIO_2_BANK_INTR_1" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_2", displayName: "GPIO_2_BANK_INTR_2" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_3", displayName: "GPIO_2_BANK_INTR_3" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_4", displayName: "GPIO_2_BANK_INTR_4" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_5", displayName: "GPIO_2_BANK_INTR_5" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_6", displayName: "GPIO_2_BANK_INTR_6" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_7", displayName: "GPIO_2_BANK_INTR_7" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_2_BANK_INTR_8", displayName: "GPIO_2_BANK_INTR_8" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_0", displayName: "GPIO_3_BANK_INTR_0" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_1", displayName: "GPIO_3_BANK_INTR_1" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_2", displayName: "GPIO_3_BANK_INTR_2" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_3", displayName: "GPIO_3_BANK_INTR_3" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_4", displayName: "GPIO_3_BANK_INTR_4" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_5", displayName: "GPIO_3_BANK_INTR_5" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_6", displayName: "GPIO_3_BANK_INTR_6" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_7", displayName: "GPIO_3_BANK_INTR_7" ,path: "gpio_int_xbar"  },
    {   name: "GPIO_INT_XBAR_GPIO_3_BANK_INTR_8", displayName: "GPIO_3_BANK_INTR_8" ,path: "gpio_int_xbar"  },
]

let xbarProperties = {
    masterXbarList: [],
    outputInstanceList: [
        { name: "GPIO_INT_XBAR_ICSS_XBAR",        count: 4},
        { name: "GPIO_INT_XBAR_DMA_TRIG_XBAR",   count: 4},
        { name: "GPIO_INT_XBAR_SOC_TIMESYNC_XBAR1", count: 6},
        { name: "GPIO_INT_XBAR_VIM_MODULE0",  count: 4},
        { name: "GPIO_INT_XBAR_VIM_MODULE1",  count: 4},
        { name: "GPIO_INT_XBAR_VIM_MODULE2",  count: 4},
        { name: "GPIO_INT_XBAR_VIM_MODULE3",  count: 4},
    ],
    duplicatesPresent: false,
    moduleString: "gpio_int_xbar",
}

function getOptionList(calledBy) {
    return xbarSoc.getOptionListSoc(calledBy, xbarProperties, internal_list);
}

function getConfigArr() {
    return xbarSoc.getXbarInstanceConfig(xbarProperties);
}

function supportXbarConfig(outputSelected, instance) {
    return xbarSoc.supportXbarConfigSoc(outputSelected, instance, xbarProperties);
}

exports = {
    getConfigArr,
    getOptionList,
    supportXbarConfig,
};
