/********************************************************************
 * Copyright (C) 2021 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_rss_proc_ctrl.h
*/
#ifndef CSLR_RSS_PROC_CTRL_H_
#define CSLR_RSS_PROC_CTRL_H_

#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>

#ifdef __cplusplus
extern "C"
{
#endif

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t PID;
    volatile uint32_t HW_REG0;
    volatile uint32_t RSS_CR4_MBOX_WRITE_DONE;
    volatile uint32_t RSS_CR4_MBOX_READ_REQ;
    volatile uint32_t RSS_CR4_MBOX_READ_DONE;
    volatile uint32_t RSS_CR4_MBOX_READ_DONE_ACK;
    volatile uint32_t BSS_TO_SOC_SW_INT;
    volatile uint32_t RSS_TO_MSS_INT_MASK;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG0;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG1;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG2;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG3;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG4;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG5;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG6;
    volatile uint32_t RSS_CR4_BOOT_INFO_REG7;
    volatile uint32_t RSS_STATIC_MEM_MEMINIT;
    volatile uint32_t RSS_STATIC_MEM_MEMINIT_DONE;
    volatile uint32_t RSS_STATIC_MEM_MEMINIT_STATUS;
    volatile uint32_t RSS_MBOX_MEMINIT;
    volatile uint32_t RSS_MBOX_MEMINIT_DONE;
    volatile uint32_t RSS_MBOX_MEMINIT_STATUS;
    volatile uint8_t  Resv_1024[936];
    volatile uint32_t FRCCFG;
    volatile uint32_t MSSEVNTGEN1LSB;
    volatile uint32_t MSSEVNTGEN1MID;
    volatile uint32_t MSSEVNTGEN1MSB;
    volatile uint32_t MSSEVNTGEN2LSB;
    volatile uint32_t MSSEVNTGEN2MID;
    volatile uint32_t MSSEVNTGEN2MSB;
    volatile uint32_t MSSEVNTGEN3LSB;
    volatile uint32_t MSSEVNTGEN3MID;
    volatile uint32_t MSSEVNTGEN3MSB;
    volatile uint32_t MSSEVNTGEN4LSB;
    volatile uint32_t MSSEVNTGEN4MID;
    volatile uint32_t MSSEVNTGEN4MSB;
    volatile uint32_t TIMSTMP1LSB;
    volatile uint32_t TIMSTMP1MID;
    volatile uint32_t TIMSTMP1MSB;
    volatile uint32_t TIMSTMP2LSB;
    volatile uint32_t TIMSTMP2MID;
    volatile uint32_t TIMSTMP2MSB;
    volatile uint32_t TIMSTMP3LSB;
    volatile uint32_t TIMSTMP3MID;
    volatile uint32_t TIMSTMP3MSB;
    volatile uint32_t TIMSTMP4LSB;
    volatile uint32_t TIMSTMP4MID;
    volatile uint32_t TIMSTMP4MSB;
    volatile uint32_t FRCLSBCNT;
    volatile uint32_t FRCMIDCNT;
    volatile uint32_t FRCMSBCNT;
    volatile uint32_t TIMSTMPTRIGSEL;
    volatile uint32_t FRCLSBPERIOD;
    volatile uint32_t FRCMIDPERIOD;
    volatile uint32_t FRCLSBCNTINITVAL;
    volatile uint32_t FRCMIDCNTINITVAL;
    volatile uint32_t FRCMSBCNTINITVAL;
    volatile uint32_t FRCSYNCOUTLSBCNT;
    volatile uint32_t FRCSYNCOUTMIDCNT;
    volatile uint32_t FRCRESETMODE;
    volatile uint32_t FRCCFG2;
    volatile uint8_t  Resv_4048[2872];
    volatile uint32_t HW_SPARE_RW0;
    volatile uint32_t HW_SPARE_RW1;
    volatile uint32_t HW_SPARE_RW2;
    volatile uint32_t HW_SPARE_RW3;
    volatile uint32_t HW_SPARE_RO0;
    volatile uint32_t HW_SPARE_RO1;
    volatile uint32_t HW_SPARE_RO2;
    volatile uint32_t HW_SPARE_RO3;
    volatile uint32_t HW_SPARE_WPH;
    volatile uint32_t HW_SPARE_REC;
    volatile uint8_t  Resv_4104[16];
    volatile uint32_t LOCK0_KICK0;
    volatile uint32_t LOCK0_KICK1;
    volatile uint32_t INTR_RAW_STATUS;
    volatile uint32_t INTR_ENABLED_STATUS_CLEAR;
    volatile uint32_t INTR_ENABLE;
    volatile uint32_t INTR_ENABLE_CLEAR;
    volatile uint32_t EOI;
    volatile uint32_t FAULT_ADDRESS;
    volatile uint32_t FAULT_TYPE_STATUS;
    volatile uint32_t FAULT_ATTR_STATUS;
    volatile uint32_t FAULT_CLEAR;
} CSL_rss_proc_ctrlRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_RSS_PROC_CTRL_PID                                                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_REG0                                              (0x00000004U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE                              (0x00000008U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ                                (0x0000000CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE                               (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_ACK                           (0x00000014U)
#define CSL_RSS_PROC_CTRL_BSS_TO_SOC_SW_INT                                    (0x00000018U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK                                  (0x0000001CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG0                               (0x00000020U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG1                               (0x00000024U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG2                               (0x00000028U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG3                               (0x0000002CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG4                               (0x00000030U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG5                               (0x00000034U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG6                               (0x00000038U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG7                               (0x0000003CU)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT                               (0x00000040U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_DONE                          (0x00000044U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_STATUS                        (0x00000048U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT                                     (0x0000004CU)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_DONE                                (0x00000050U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_STATUS                              (0x00000054U)
#define CSL_RSS_PROC_CTRL_FRCCFG                                               (0x00000400U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1LSB                                       (0x00000404U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MID                                       (0x00000408U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MSB                                       (0x0000040CU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2LSB                                       (0x00000410U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MID                                       (0x00000414U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MSB                                       (0x00000418U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3LSB                                       (0x0000041CU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MID                                       (0x00000420U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MSB                                       (0x00000424U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4LSB                                       (0x00000428U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MID                                       (0x0000042CU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MSB                                       (0x00000430U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1LSB                                          (0x00000434U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MID                                          (0x00000438U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MSB                                          (0x0000043CU)
#define CSL_RSS_PROC_CTRL_TIMSTMP2LSB                                          (0x00000440U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MID                                          (0x00000444U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MSB                                          (0x00000448U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3LSB                                          (0x0000044CU)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MID                                          (0x00000450U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MSB                                          (0x00000454U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4LSB                                          (0x00000458U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MID                                          (0x0000045CU)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MSB                                          (0x00000460U)
#define CSL_RSS_PROC_CTRL_FRCLSBCNT                                            (0x00000464U)
#define CSL_RSS_PROC_CTRL_FRCMIDCNT                                            (0x00000468U)
#define CSL_RSS_PROC_CTRL_FRCMSBCNT                                            (0x0000046CU)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL                                       (0x00000470U)
#define CSL_RSS_PROC_CTRL_FRCLSBPERIOD                                         (0x00000474U)
#define CSL_RSS_PROC_CTRL_FRCMIDPERIOD                                         (0x00000478U)
#define CSL_RSS_PROC_CTRL_FRCLSBCNTINITVAL                                     (0x0000047CU)
#define CSL_RSS_PROC_CTRL_FRCMIDCNTINITVAL                                     (0x00000480U)
#define CSL_RSS_PROC_CTRL_FRCMSBCNTINITVAL                                     (0x00000484U)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTLSBCNT                                     (0x00000488U)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTMIDCNT                                     (0x0000048CU)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE                                         (0x00000490U)
#define CSL_RSS_PROC_CTRL_FRCCFG2                                              (0x00000494U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW0                                         (0x00000FD0U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW1                                         (0x00000FD4U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW2                                         (0x00000FD8U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW3                                         (0x00000FDCU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO0                                         (0x00000FE0U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO1                                         (0x00000FE4U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO2                                         (0x00000FE8U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO3                                         (0x00000FECU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_WPH                                         (0x00000FF0U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC                                         (0x00000FF4U)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK0                                          (0x00001008U)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK1                                          (0x0000100CU)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS                                      (0x00001010U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR                            (0x00001014U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE                                          (0x00001018U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR                                    (0x0000101CU)
#define CSL_RSS_PROC_CTRL_EOI                                                  (0x00001020U)
#define CSL_RSS_PROC_CTRL_FAULT_ADDRESS                                        (0x00001024U)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS                                    (0x00001028U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS                                    (0x0000102CU)
#define CSL_RSS_PROC_CTRL_FAULT_CLEAR                                          (0x00001030U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* PID */

#define CSL_RSS_PROC_CTRL_PID_PID_MINOR_MASK                                   (0x0000003FU)
#define CSL_RSS_PROC_CTRL_PID_PID_MINOR_SHIFT                                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_PID_PID_MINOR_RESETVAL                               (0x00000014U)
#define CSL_RSS_PROC_CTRL_PID_PID_MINOR_MAX                                    (0x0000003FU)

#define CSL_RSS_PROC_CTRL_PID_PID_CUSTOM_MASK                                  (0x000000C0U)
#define CSL_RSS_PROC_CTRL_PID_PID_CUSTOM_SHIFT                                 (0x00000006U)
#define CSL_RSS_PROC_CTRL_PID_PID_CUSTOM_RESETVAL                              (0x00000000U)
#define CSL_RSS_PROC_CTRL_PID_PID_CUSTOM_MAX                                   (0x00000003U)

#define CSL_RSS_PROC_CTRL_PID_PID_MAJOR_MASK                                   (0x00000700U)
#define CSL_RSS_PROC_CTRL_PID_PID_MAJOR_SHIFT                                  (0x00000008U)
#define CSL_RSS_PROC_CTRL_PID_PID_MAJOR_RESETVAL                               (0x00000002U)
#define CSL_RSS_PROC_CTRL_PID_PID_MAJOR_MAX                                    (0x00000007U)

#define CSL_RSS_PROC_CTRL_PID_PID_MISC_MASK                                    (0x0000F800U)
#define CSL_RSS_PROC_CTRL_PID_PID_MISC_SHIFT                                   (0x0000000BU)
#define CSL_RSS_PROC_CTRL_PID_PID_MISC_RESETVAL                                (0x00000000U)
#define CSL_RSS_PROC_CTRL_PID_PID_MISC_MAX                                     (0x0000001FU)

#define CSL_RSS_PROC_CTRL_PID_PID_MSB16_MASK                                   (0xFFFF0000U)
#define CSL_RSS_PROC_CTRL_PID_PID_MSB16_SHIFT                                  (0x00000010U)
#define CSL_RSS_PROC_CTRL_PID_PID_MSB16_RESETVAL                               (0x00006180U)
#define CSL_RSS_PROC_CTRL_PID_PID_MSB16_MAX                                    (0x0000FFFFU)

#define CSL_RSS_PROC_CTRL_PID_RESETVAL                                         (0x61800214U)

/* HW_REG0 */

#define CSL_RSS_PROC_CTRL_HW_REG0_HW_REG0_REG_MASK                             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_REG0_HW_REG0_REG_SHIFT                            (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_REG0_HW_REG0_REG_RESETVAL                         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_REG0_HW_REG0_REG_MAX                              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_REG0_RESETVAL                                     (0x00000000U)

/* RSS_CR4_MBOX_WRITE_DONE */

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_0_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_0_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_0_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_0_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_1_MASK (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_1_SHIFT (0x00000004U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_1_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_1_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_2_MASK (0x00000100U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_2_SHIFT (0x00000008U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_2_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_2_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_3_MASK (0x00001000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_3_SHIFT (0x0000000CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_3_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_3_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_4_MASK (0x00010000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_4_SHIFT (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_4_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_4_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_5_MASK (0x00100000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_5_SHIFT (0x00000014U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_5_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_5_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_6_MASK (0x01000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_6_SHIFT (0x00000018U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_6_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_6_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_7_MASK (0x10000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_7_SHIFT (0x0000001CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_7_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RSS_CR4_MBOX_WRITE_DONE_PROC_7_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_WRITE_DONE_RESETVAL                     (0x00000000U)

/* RSS_CR4_MBOX_READ_REQ */

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_0_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_0_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_0_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_0_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_1_MASK (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_1_SHIFT (0x00000004U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_1_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_1_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_2_MASK (0x00000100U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_2_SHIFT (0x00000008U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_2_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_2_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_3_MASK (0x00001000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_3_SHIFT (0x0000000CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_3_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_3_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_4_MASK (0x00010000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_4_SHIFT (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_4_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_4_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_5_MASK (0x00100000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_5_SHIFT (0x00000014U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_5_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_5_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_6_MASK (0x01000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_6_SHIFT (0x00000018U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_6_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_6_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_7_MASK (0x10000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_7_SHIFT (0x0000001CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_7_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RSS_CR4_MBOX_READ_REQ_PROC_7_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_REQ_RESETVAL                       (0x00000000U)

/* RSS_CR4_MBOX_READ_DONE */

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_0_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_0_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_0_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_0_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_1_MASK (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_1_SHIFT (0x00000004U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_1_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_1_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_2_MASK (0x00000100U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_2_SHIFT (0x00000008U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_2_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_2_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_3_MASK (0x00001000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_3_SHIFT (0x0000000CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_3_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_3_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_4_MASK (0x00010000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_4_SHIFT (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_4_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_4_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_5_MASK (0x00100000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_5_SHIFT (0x00000014U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_5_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_5_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_6_MASK (0x01000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_6_SHIFT (0x00000018U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_6_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_6_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_7_MASK (0x10000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_7_SHIFT (0x0000001CU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_7_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RSS_CR4_MBOX_READ_DONE_PROC_7_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_RESETVAL                      (0x00000000U)

/* RSS_CR4_MBOX_READ_DONE_ACK */

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_ACK_RSS_CR4_MBOX_READ_DONE_ACK_PROC_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_ACK_RSS_CR4_MBOX_READ_DONE_ACK_PROC_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_ACK_RSS_CR4_MBOX_READ_DONE_ACK_PROC_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_ACK_RSS_CR4_MBOX_READ_DONE_ACK_PROC_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_MBOX_READ_DONE_ACK_RESETVAL                  (0x00000000U)

/* BSS_TO_SOC_SW_INT */

#define CSL_RSS_PROC_CTRL_BSS_TO_SOC_SW_INT_BSS_TO_SOC_SW_INT_TRIG_MASK        (0x0000000FU)
#define CSL_RSS_PROC_CTRL_BSS_TO_SOC_SW_INT_BSS_TO_SOC_SW_INT_TRIG_SHIFT       (0x00000000U)
#define CSL_RSS_PROC_CTRL_BSS_TO_SOC_SW_INT_BSS_TO_SOC_SW_INT_TRIG_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_BSS_TO_SOC_SW_INT_BSS_TO_SOC_SW_INT_TRIG_MAX         (0x0000000FU)

#define CSL_RSS_PROC_CTRL_BSS_TO_SOC_SW_INT_RESETVAL                           (0x00000000U)

/* RSS_TO_MSS_INT_MASK */

#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_HI_MASK  (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_HI_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_HI_RESETVAL (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_HI_MAX   (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_LO_MASK  (0x00000010U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_LO_SHIFT (0x00000004U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_LO_RESETVAL (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RSS_TO_MSS_INT_MASK_ESM_LO_MAX   (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_TO_MSS_INT_MASK_RESETVAL                         (0x00000011U)

/* RSS_CR4_BOOT_INFO_REG0 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG0_RSS_CR4_BOOT_INFO_REG0_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG0_RSS_CR4_BOOT_INFO_REG0_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG0_RSS_CR4_BOOT_INFO_REG0_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG0_RSS_CR4_BOOT_INFO_REG0_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG0_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG1 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG1_RSS_CR4_BOOT_INFO_REG1_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG1_RSS_CR4_BOOT_INFO_REG1_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG1_RSS_CR4_BOOT_INFO_REG1_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG1_RSS_CR4_BOOT_INFO_REG1_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG1_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG2 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG2_RSS_CR4_BOOT_INFO_REG2_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG2_RSS_CR4_BOOT_INFO_REG2_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG2_RSS_CR4_BOOT_INFO_REG2_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG2_RSS_CR4_BOOT_INFO_REG2_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG2_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG3 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG3_RSS_CR4_BOOT_INFO_REG3_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG3_RSS_CR4_BOOT_INFO_REG3_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG3_RSS_CR4_BOOT_INFO_REG3_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG3_RSS_CR4_BOOT_INFO_REG3_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG3_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG4 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG4_RSS_CR4_BOOT_INFO_REG4_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG4_RSS_CR4_BOOT_INFO_REG4_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG4_RSS_CR4_BOOT_INFO_REG4_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG4_RSS_CR4_BOOT_INFO_REG4_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG4_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG5 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG5_RSS_CR4_BOOT_INFO_REG5_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG5_RSS_CR4_BOOT_INFO_REG5_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG5_RSS_CR4_BOOT_INFO_REG5_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG5_RSS_CR4_BOOT_INFO_REG5_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG5_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG6 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG6_RSS_CR4_BOOT_INFO_REG6_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG6_RSS_CR4_BOOT_INFO_REG6_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG6_RSS_CR4_BOOT_INFO_REG6_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG6_RSS_CR4_BOOT_INFO_REG6_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG6_RESETVAL                      (0x00000000U)

/* RSS_CR4_BOOT_INFO_REG7 */

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG7_RSS_CR4_BOOT_INFO_REG7_CONFIG_MASK (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG7_RSS_CR4_BOOT_INFO_REG7_CONFIG_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG7_RSS_CR4_BOOT_INFO_REG7_CONFIG_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG7_RSS_CR4_BOOT_INFO_REG7_CONFIG_MAX (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_RSS_CR4_BOOT_INFO_REG7_RESETVAL                      (0x00000000U)

/* RSS_STATIC_MEM_MEMINIT */

#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_RSS_STATIC_MEM_MEMINIT_START_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_RSS_STATIC_MEM_MEMINIT_START_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_RSS_STATIC_MEM_MEMINIT_START_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_RSS_STATIC_MEM_MEMINIT_START_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_RESETVAL                      (0x00000000U)

/* RSS_STATIC_MEM_MEMINIT_DONE */

#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_DONE_RSS_STATIC_MEM_MEMINIT_DONE_DONE_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_DONE_RSS_STATIC_MEM_MEMINIT_DONE_DONE_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_DONE_RSS_STATIC_MEM_MEMINIT_DONE_DONE_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_DONE_RSS_STATIC_MEM_MEMINIT_DONE_DONE_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_DONE_RESETVAL                 (0x00000000U)

/* RSS_STATIC_MEM_MEMINIT_STATUS */

#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_STATUS_RSS_STATIC_MEM_MEMINIT_STATUS_STATUS_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_STATUS_RSS_STATIC_MEM_MEMINIT_STATUS_STATUS_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_STATUS_RSS_STATIC_MEM_MEMINIT_STATUS_STATUS_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_STATUS_RSS_STATIC_MEM_MEMINIT_STATUS_STATUS_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_STATIC_MEM_MEMINIT_STATUS_RESETVAL               (0x00000000U)

/* RSS_MBOX_MEMINIT */

#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_RSS_MBOX_MEMINIT_START_MASK         (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_RSS_MBOX_MEMINIT_START_SHIFT        (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_RSS_MBOX_MEMINIT_START_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_RSS_MBOX_MEMINIT_START_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_RESETVAL                            (0x00000000U)

/* RSS_MBOX_MEMINIT_DONE */

#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_DONE_RSS_MBOX_MEMINIT_DONE_DONE_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_DONE_RSS_MBOX_MEMINIT_DONE_DONE_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_DONE_RSS_MBOX_MEMINIT_DONE_DONE_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_DONE_RSS_MBOX_MEMINIT_DONE_DONE_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_DONE_RESETVAL                       (0x00000000U)

/* RSS_MBOX_MEMINIT_STATUS */

#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_STATUS_RSS_MBOX_MEMINIT_STATUS_STATUS_MASK (0x00000001U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_STATUS_RSS_MBOX_MEMINIT_STATUS_STATUS_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_STATUS_RSS_MBOX_MEMINIT_STATUS_STATUS_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_STATUS_RSS_MBOX_MEMINIT_STATUS_STATUS_MAX (0x00000001U)

#define CSL_RSS_PROC_CTRL_RSS_MBOX_MEMINIT_STATUS_RESETVAL                     (0x00000000U)

/* FRCCFG */

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENSEL_MASK                    (0x00000006U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENSEL_SHIFT                   (0x00000001U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENSEL_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENSEL_MAX                     (0x00000003U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTMODE_MASK                    (0x00000008U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTMODE_SHIFT                   (0x00000003U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTMODE_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTMODE_MAX                     (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTGATE_MASK                    (0x00000010U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTGATE_SHIFT                   (0x00000004U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTGATE_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCOUTGATE_MAX                     (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINGATE_MASK                     (0x00000020U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINGATE_SHIFT                    (0x00000005U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINGATE_RESETVAL                 (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINGATE_MAX                      (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENGATE_MASK                   (0x00000040U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENGATE_SHIFT                  (0x00000006U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENGATE_RESETVAL               (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCADCCLKENGATE_MAX                    (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCEN_MASK                             (0x00000080U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCEN_SHIFT                            (0x00000007U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCEN_RESETVAL                         (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCEN_MAX                              (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG2_MASK                        (0x00000200U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG2_SHIFT                       (0x00000009U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG2_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG2_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG1_MASK                        (0x00000400U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG1_SHIFT                       (0x0000000AU)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG1_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSSWTRIG1_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN4UMOD_MASK                   (0x00001800U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN4UMOD_SHIFT                  (0x0000000BU)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN4UMOD_RESETVAL               (0x00000003U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN4UMOD_MAX                    (0x00000003U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN3UMOD_MASK                   (0x00006000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN3UMOD_SHIFT                  (0x0000000DU)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN3UMOD_RESETVAL               (0x00000003U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN3UMOD_MAX                    (0x00000003U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN2UMOD_MASK                   (0x00018000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN2UMOD_SHIFT                  (0x0000000FU)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN2UMOD_RESETVAL               (0x00000003U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN2UMOD_MAX                    (0x00000003U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN1UMOD_MASK                   (0x00060000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN1UMOD_SHIFT                  (0x00000011U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN1UMOD_RESETVAL               (0x00000003U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_MSSEVNTGEN1UMOD_MAX                    (0x00000003U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRSSYNCIN_MASK                        (0x00080000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRSSYNCIN_SHIFT                       (0x00000013U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRSSYNCIN_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRSSYNCIN_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPANDOUTMSK_MASK                   (0x00100000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPANDOUTMSK_SHIFT                  (0x00000014U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPANDOUTMSK_RESETVAL               (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPANDOUTMSK_MAX                    (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPOROUTMSK_MASK                    (0x00200000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPOROUTMSK_SHIFT                   (0x00000015U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPOROUTMSK_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPOROUTMSK_MAX                     (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXOROUTINV_MASK                   (0x00400000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXOROUTINV_SHIFT                  (0x00000016U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXOROUTINV_RESETVAL               (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXOROUTINV_MAX                    (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXORININV_MASK                    (0x00800000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXORININV_SHIFT                   (0x00000017U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXORININV_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPXORININV_MAX                     (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPDIS_MASK                         (0x01000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPDIS_SHIFT                        (0x00000018U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPDIS_RESETVAL                     (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCMPDIS_MAX                          (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCFGSWRST_MASK                       (0x02000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCFGSWRST_SHIFT                      (0x00000019U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCFGSWRST_RESETVAL                   (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCCFGSWRST_MAX                        (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINSRCSEL_MASK                   (0x1C000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINSRCSEL_SHIFT                  (0x0000001AU)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINSRCSEL_RESETVAL               (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG_FRCCFG_FRCSYNCINSRCSEL_MAX                    (0x00000007U)

#define CSL_RSS_PROC_CTRL_FRCCFG_RESETVAL                                      (0x0007F800U)

/* MSSEVNTGEN1LSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_MSSEVNTGEN1LSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1LSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN1MID */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MID_MSSEVNTGEN1MID_MSSEVNTGEN1MID_MASK    (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MID_MSSEVNTGEN1MID_MSSEVNTGEN1MID_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MID_MSSEVNTGEN1MID_MSSEVNTGEN1MID_RESETVAL (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MID_MSSEVNTGEN1MID_MSSEVNTGEN1MID_MAX     (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MID_RESETVAL                              (0x00000FFFU)

/* MSSEVNTGEN1MSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_MSSEVNTGEN1MSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN1MSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN2LSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_MSSEVNTGEN2LSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2LSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN2MID */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MID_MSSEVNTGEN2MID_MSSEVNTGEN2MID_MASK    (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MID_MSSEVNTGEN2MID_MSSEVNTGEN2MID_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MID_MSSEVNTGEN2MID_MSSEVNTGEN2MID_RESETVAL (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MID_MSSEVNTGEN2MID_MSSEVNTGEN2MID_MAX     (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MID_RESETVAL                              (0x00000FFFU)

/* MSSEVNTGEN2MSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_MSSEVNTGEN2MSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN2MSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN3LSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_MSSEVNTGEN3LSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3LSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN3MID */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MID_MSSEVNTGEN3MID_MSSEVNTGEN3MID_MASK    (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MID_MSSEVNTGEN3MID_MSSEVNTGEN3MID_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MID_MSSEVNTGEN3MID_MSSEVNTGEN3MID_RESETVAL (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MID_MSSEVNTGEN3MID_MSSEVNTGEN3MID_MAX     (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MID_RESETVAL                              (0x00000FFFU)

/* MSSEVNTGEN3MSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_MSSEVNTGEN3MSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN3MSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN4LSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_MSSEVNTGEN4LSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4LSB_RESETVAL                              (0x0FFFFFFFU)

/* MSSEVNTGEN4MID */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MID_MSSEVNTGEN4MID_MSSEVNTGEN4MID_MASK    (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MID_MSSEVNTGEN4MID_MSSEVNTGEN4MID_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MID_MSSEVNTGEN4MID_MSSEVNTGEN4MID_RESETVAL (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MID_MSSEVNTGEN4MID_MSSEVNTGEN4MID_MAX     (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MID_RESETVAL                              (0x00000FFFU)

/* MSSEVNTGEN4MSB */

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_MASK    (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_SHIFT   (0x00000000U)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_MSSEVNTGEN4MSB_MAX     (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_MSSEVNTGEN4MSB_RESETVAL                              (0x0FFFFFFFU)

/* TIMSTMP1LSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP1LSB_TIMSTMP1LSB_TIMSTMP1LSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP1LSB_TIMSTMP1LSB_TIMSTMP1LSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1LSB_TIMSTMP1LSB_TIMSTMP1LSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1LSB_TIMSTMP1LSB_TIMSTMP1LSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP1LSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP1MID */

#define CSL_RSS_PROC_CTRL_TIMSTMP1MID_TIMSTMP1MID_TIMSTMP1MID_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MID_TIMSTMP1MID_TIMSTMP1MID_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MID_TIMSTMP1MID_TIMSTMP1MID_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MID_TIMSTMP1MID_TIMSTMP1MID_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP1MID_RESETVAL                                 (0x00000000U)

/* TIMSTMP1MSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP1MSB_TIMSTMP1MSB_TIMSTMP1MSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MSB_TIMSTMP1MSB_TIMSTMP1MSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MSB_TIMSTMP1MSB_TIMSTMP1MSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP1MSB_TIMSTMP1MSB_TIMSTMP1MSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP1MSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP2LSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP2LSB_TIMSTMP2LSB_TIMSTMP2LSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP2LSB_TIMSTMP2LSB_TIMSTMP2LSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2LSB_TIMSTMP2LSB_TIMSTMP2LSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2LSB_TIMSTMP2LSB_TIMSTMP2LSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP2LSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP2MID */

#define CSL_RSS_PROC_CTRL_TIMSTMP2MID_TIMSTMP2MID_TIMSTMP2MID_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MID_TIMSTMP2MID_TIMSTMP2MID_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MID_TIMSTMP2MID_TIMSTMP2MID_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MID_TIMSTMP2MID_TIMSTMP2MID_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP2MID_RESETVAL                                 (0x00000000U)

/* TIMSTMP2MSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP2MSB_TIMSTMP2MSB_TIMSTMP2MSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MSB_TIMSTMP2MSB_TIMSTMP2MSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MSB_TIMSTMP2MSB_TIMSTMP2MSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP2MSB_TIMSTMP2MSB_TIMSTMP2MSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP2MSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP3LSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP3LSB_TIMSTMP3LSB_TIMSTMP3LSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP3LSB_TIMSTMP3LSB_TIMSTMP3LSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3LSB_TIMSTMP3LSB_TIMSTMP3LSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3LSB_TIMSTMP3LSB_TIMSTMP3LSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP3LSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP3MID */

#define CSL_RSS_PROC_CTRL_TIMSTMP3MID_TIMSTMP3MID_TIMSTMP3MID_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MID_TIMSTMP3MID_TIMSTMP3MID_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MID_TIMSTMP3MID_TIMSTMP3MID_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MID_TIMSTMP3MID_TIMSTMP3MID_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP3MID_RESETVAL                                 (0x00000000U)

/* TIMSTMP3MSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP3MSB_TIMSTMP3MSB_TIMSTMP3MSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MSB_TIMSTMP3MSB_TIMSTMP3MSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MSB_TIMSTMP3MSB_TIMSTMP3MSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP3MSB_TIMSTMP3MSB_TIMSTMP3MSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP3MSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP4LSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP4LSB_TIMSTMP4LSB_TIMSTMP4LSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP4LSB_TIMSTMP4LSB_TIMSTMP4LSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4LSB_TIMSTMP4LSB_TIMSTMP4LSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4LSB_TIMSTMP4LSB_TIMSTMP4LSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP4LSB_RESETVAL                                 (0x00000000U)

/* TIMSTMP4MID */

#define CSL_RSS_PROC_CTRL_TIMSTMP4MID_TIMSTMP4MID_TIMSTMP4MID_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MID_TIMSTMP4MID_TIMSTMP4MID_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MID_TIMSTMP4MID_TIMSTMP4MID_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MID_TIMSTMP4MID_TIMSTMP4MID_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP4MID_RESETVAL                                 (0x00000000U)

/* TIMSTMP4MSB */

#define CSL_RSS_PROC_CTRL_TIMSTMP4MSB_TIMSTMP4MSB_TIMSTMP4MSB_MASK             (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MSB_TIMSTMP4MSB_TIMSTMP4MSB_SHIFT            (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MSB_TIMSTMP4MSB_TIMSTMP4MSB_RESETVAL         (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMP4MSB_TIMSTMP4MSB_TIMSTMP4MSB_MAX              (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_TIMSTMP4MSB_RESETVAL                                 (0x00000000U)

/* FRCLSBCNT */

#define CSL_RSS_PROC_CTRL_FRCLSBCNT_FRCLSBCNT_FRCLSBCNT_MASK                   (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCLSBCNT_FRCLSBCNT_FRCLSBCNT_SHIFT                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCLSBCNT_FRCLSBCNT_FRCLSBCNT_RESETVAL               (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCLSBCNT_FRCLSBCNT_FRCLSBCNT_MAX                    (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCLSBCNT_RESETVAL                                   (0x0FFFFFFFU)

/* FRCMIDCNT */

#define CSL_RSS_PROC_CTRL_FRCMIDCNT_FRCMIDCNT_FRCMIDCNT_MASK                   (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCMIDCNT_FRCMIDCNT_FRCMIDCNT_SHIFT                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMIDCNT_FRCMIDCNT_FRCMIDCNT_RESETVAL               (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMIDCNT_FRCMIDCNT_FRCMIDCNT_MAX                    (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCMIDCNT_RESETVAL                                   (0x00000000U)

/* FRCMSBCNT */

#define CSL_RSS_PROC_CTRL_FRCMSBCNT_FRCMSBCNT_FRCMSBCNT_MASK                   (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCMSBCNT_FRCMSBCNT_FRCMSBCNT_SHIFT                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMSBCNT_FRCMSBCNT_FRCMSBCNT_RESETVAL               (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMSBCNT_FRCMSBCNT_FRCMSBCNT_MAX                    (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCMSBCNT_RESETVAL                                   (0x00000000U)

/* TIMSTMPTRIGSEL */

#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG4SEL_MASK   (0x0000000FU)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG4SEL_SHIFT  (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG4SEL_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG4SEL_MAX    (0x0000000FU)

#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG3SEL_MASK   (0x00000F00U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG3SEL_SHIFT  (0x00000008U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG3SEL_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG3SEL_MAX    (0x0000000FU)

#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG2SEL_MASK   (0x000F0000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG2SEL_SHIFT  (0x00000010U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG2SEL_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG2SEL_MAX    (0x0000000FU)

#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG1SEL_MASK   (0x0F000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG1SEL_SHIFT  (0x00000018U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG1SEL_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_TIMSTMPTRIGSEL_TIMSTMPTRIG1SEL_MAX    (0x0000000FU)

#define CSL_RSS_PROC_CTRL_TIMSTMPTRIGSEL_RESETVAL                              (0x00000000U)

/* FRCLSBPERIOD */

#define CSL_RSS_PROC_CTRL_FRCLSBPERIOD_FRCLSBPERIOD_FRCLSBPERIOD_MASK          (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCLSBPERIOD_FRCLSBPERIOD_FRCLSBPERIOD_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCLSBPERIOD_FRCLSBPERIOD_FRCLSBPERIOD_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCLSBPERIOD_FRCLSBPERIOD_FRCLSBPERIOD_MAX           (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCLSBPERIOD_RESETVAL                                (0x00000000U)

/* FRCMIDPERIOD */

#define CSL_RSS_PROC_CTRL_FRCMIDPERIOD_FRCMIDPERIOD_FRCMIDPERIOD_MASK          (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_FRCMIDPERIOD_FRCMIDPERIOD_FRCMIDPERIOD_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMIDPERIOD_FRCMIDPERIOD_FRCMIDPERIOD_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMIDPERIOD_FRCMIDPERIOD_FRCMIDPERIOD_MAX           (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_FRCMIDPERIOD_RESETVAL                                (0x00000000U)

/* FRCLSBCNTINITVAL */

#define CSL_RSS_PROC_CTRL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_MASK (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_RESETVAL (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_FRCLSBCNTINITVAL_MAX (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCLSBCNTINITVAL_RESETVAL                            (0x0FFFFFFFU)

/* FRCMIDCNTINITVAL */

#define CSL_RSS_PROC_CTRL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_MASK (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_FRCMIDCNTINITVAL_MAX (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_FRCMIDCNTINITVAL_RESETVAL                            (0x00000000U)

/* FRCMSBCNTINITVAL */

#define CSL_RSS_PROC_CTRL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_MASK (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_FRCMSBCNTINITVAL_MAX (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCMSBCNTINITVAL_RESETVAL                            (0x00000000U)

/* FRCSYNCOUTLSBCNT */

#define CSL_RSS_PROC_CTRL_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_MASK (0x0FFFFFFFU)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_FRCSYNCOUTLSBCNT_MAX (0x0FFFFFFFU)

#define CSL_RSS_PROC_CTRL_FRCSYNCOUTLSBCNT_RESETVAL                            (0x00000000U)

/* FRCSYNCOUTMIDCNT */

#define CSL_RSS_PROC_CTRL_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_MASK (0x00000FFFU)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_SHIFT (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_FRCSYNCOUTMIDCNT_MAX (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_FRCSYNCOUTMIDCNT_RESETVAL                            (0x00000000U)

/* FRCRESETMODE */

#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCLSBRESETMODE_MASK       (0x00000001U)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCLSBRESETMODE_SHIFT      (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCLSBRESETMODE_RESETVAL   (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCLSBRESETMODE_MAX        (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCMIDRESETMODE_MASK       (0x00000002U)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCMIDRESETMODE_SHIFT      (0x00000001U)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCMIDRESETMODE_RESETVAL   (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCRESETMODE_FRCRESETMODE_FRCMIDRESETMODE_MAX        (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCRESETMODE_RESETVAL                                (0x00000000U)

/* FRCCFG2 */

#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANINTRMASK_MASK                     (0x0000000FU)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANINTRMASK_SHIFT                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANINTRMASK_RESETVAL                 (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANINTRMASK_MAX                      (0x0000000FU)

#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANTRIGDLYVAL_MASK                   (0x0000FFF0U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANTRIGDLYVAL_SHIFT                  (0x00000004U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANTRIGDLYVAL_RESETVAL               (0x00000001U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_CANTRIGDLYVAL_MAX                    (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCSYNCINSEL_MASK                    (0x00030000U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCSYNCINSEL_SHIFT                   (0x00000010U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCSYNCINSEL_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCSYNCINSEL_MAX                     (0x00000003U)

#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCTRIGMSS_MASK                      (0x01000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCTRIGMSS_SHIFT                     (0x00000018U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCTRIGMSS_RESETVAL                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_FRCCFG2_FRCCFG2_FRCTRIGMSS_MAX                       (0x00000001U)

#define CSL_RSS_PROC_CTRL_FRCCFG2_RESETVAL                                     (0x00000010U)

/* HW_SPARE_RW0 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW0_HW_SPARE_RW0_HW_SPARE_RW0_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW0_RESETVAL                                (0x00000000U)

/* HW_SPARE_RW1 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW1_HW_SPARE_RW1_HW_SPARE_RW1_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW1_RESETVAL                                (0x00000000U)

/* HW_SPARE_RW2 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW2_HW_SPARE_RW2_HW_SPARE_RW2_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW2_HW_SPARE_RW2_HW_SPARE_RW2_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW2_HW_SPARE_RW2_HW_SPARE_RW2_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW2_HW_SPARE_RW2_HW_SPARE_RW2_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW2_RESETVAL                                (0x00000000U)

/* HW_SPARE_RW3 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW3_HW_SPARE_RW3_HW_SPARE_RW3_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW3_HW_SPARE_RW3_HW_SPARE_RW3_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW3_HW_SPARE_RW3_HW_SPARE_RW3_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RW3_HW_SPARE_RW3_HW_SPARE_RW3_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RW3_RESETVAL                                (0x00000000U)

/* HW_SPARE_RO0 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO0_HW_SPARE_RO0_HW_SPARE_RO0_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO0_HW_SPARE_RO0_HW_SPARE_RO0_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO0_HW_SPARE_RO0_HW_SPARE_RO0_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO0_HW_SPARE_RO0_HW_SPARE_RO0_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO0_RESETVAL                                (0x00000000U)

/* HW_SPARE_RO1 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO1_HW_SPARE_RO1_HW_SPARE_RO1_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO1_HW_SPARE_RO1_HW_SPARE_RO1_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO1_HW_SPARE_RO1_HW_SPARE_RO1_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO1_HW_SPARE_RO1_HW_SPARE_RO1_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO1_RESETVAL                                (0x00000000U)

/* HW_SPARE_RO2 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO2_HW_SPARE_RO2_HW_SPARE_RO2_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO2_HW_SPARE_RO2_HW_SPARE_RO2_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO2_HW_SPARE_RO2_HW_SPARE_RO2_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO2_HW_SPARE_RO2_HW_SPARE_RO2_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO2_RESETVAL                                (0x00000000U)

/* HW_SPARE_RO3 */

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO3_HW_SPARE_RO3_HW_SPARE_RO3_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO3_HW_SPARE_RO3_HW_SPARE_RO3_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO3_HW_SPARE_RO3_HW_SPARE_RO3_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_RO3_HW_SPARE_RO3_HW_SPARE_RO3_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_RO3_RESETVAL                                (0x00000000U)

/* HW_SPARE_WPH */

#define CSL_RSS_PROC_CTRL_HW_SPARE_WPH_HW_SPARE_WPH_HW_SPARE_WPH_MASK          (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_WPH_HW_SPARE_WPH_HW_SPARE_WPH_SHIFT         (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_WPH_HW_SPARE_WPH_HW_SPARE_WPH_RESETVAL      (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_WPH_HW_SPARE_WPH_HW_SPARE_WPH_MAX           (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_HW_SPARE_WPH_RESETVAL                                (0x00000000U)

/* HW_SPARE_REC */

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC0_MASK         (0x00000001U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC0_SHIFT        (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC0_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC0_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC1_MASK         (0x00000002U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC1_SHIFT        (0x00000001U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC1_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC1_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC2_MASK         (0x00000004U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC2_SHIFT        (0x00000002U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC2_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC2_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC3_MASK         (0x00000008U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC3_SHIFT        (0x00000003U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC3_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC3_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC4_MASK         (0x00000010U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC4_SHIFT        (0x00000004U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC4_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC4_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC5_MASK         (0x00000020U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC5_SHIFT        (0x00000005U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC5_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC5_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC6_MASK         (0x00000040U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC6_SHIFT        (0x00000006U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC6_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC6_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC7_MASK         (0x00000080U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC7_SHIFT        (0x00000007U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC7_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC7_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC8_MASK         (0x00000100U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC8_SHIFT        (0x00000008U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC8_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC8_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC9_MASK         (0x00000200U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC9_SHIFT        (0x00000009U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC9_RESETVAL     (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC9_MAX          (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC10_MASK        (0x00000400U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC10_SHIFT       (0x0000000AU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC10_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC10_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC11_MASK        (0x00000800U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC11_SHIFT       (0x0000000BU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC11_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC11_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC12_MASK        (0x00001000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC12_SHIFT       (0x0000000CU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC12_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC12_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC13_MASK        (0x00002000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC13_SHIFT       (0x0000000DU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC13_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC13_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC14_MASK        (0x00004000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC14_SHIFT       (0x0000000EU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC14_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC14_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC15_MASK        (0x00008000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC15_SHIFT       (0x0000000FU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC15_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC15_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC16_MASK        (0x00010000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC16_SHIFT       (0x00000010U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC16_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC16_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC17_MASK        (0x00020000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC17_SHIFT       (0x00000011U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC17_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC17_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC18_MASK        (0x00040000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC18_SHIFT       (0x00000012U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC18_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC18_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC19_MASK        (0x00080000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC19_SHIFT       (0x00000013U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC19_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC19_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC20_MASK        (0x00100000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC20_SHIFT       (0x00000014U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC20_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC20_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC21_MASK        (0x00200000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC21_SHIFT       (0x00000015U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC21_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC21_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC22_MASK        (0x00400000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC22_SHIFT       (0x00000016U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC22_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC22_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC23_MASK        (0x00800000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC23_SHIFT       (0x00000017U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC23_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC23_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC24_MASK        (0x01000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC24_SHIFT       (0x00000018U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC24_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC24_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC25_MASK        (0x02000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC25_SHIFT       (0x00000019U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC25_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC25_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC26_MASK        (0x04000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC26_SHIFT       (0x0000001AU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC26_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC26_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC27_MASK        (0x08000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC27_SHIFT       (0x0000001BU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC27_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC27_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC28_MASK        (0x10000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC28_SHIFT       (0x0000001CU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC28_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC28_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC29_MASK        (0x20000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC29_SHIFT       (0x0000001DU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC29_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC29_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC30_MASK        (0x40000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC30_SHIFT       (0x0000001EU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC30_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC30_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC31_MASK        (0x80000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC31_SHIFT       (0x0000001FU)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC31_RESETVAL    (0x00000000U)
#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_HW_SPARE_REC_HW_SPARE_REC31_MAX         (0x00000001U)

#define CSL_RSS_PROC_CTRL_HW_SPARE_REC_RESETVAL                                (0x00000000U)

/* LOCK0_KICK0 */

#define CSL_RSS_PROC_CTRL_LOCK0_KICK0_LOCK0_KICK0_MASK                         (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK0_LOCK0_KICK0_SHIFT                        (0x00000000U)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK0_LOCK0_KICK0_RESETVAL                     (0x00000000U)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK0_LOCK0_KICK0_MAX                          (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_LOCK0_KICK0_RESETVAL                                 (0x00000000U)

/* LOCK0_KICK1 */

#define CSL_RSS_PROC_CTRL_LOCK0_KICK1_LOCK0_KICK1_MASK                         (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK1_LOCK0_KICK1_SHIFT                        (0x00000000U)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK1_LOCK0_KICK1_RESETVAL                     (0x00000000U)
#define CSL_RSS_PROC_CTRL_LOCK0_KICK1_LOCK0_KICK1_MAX                          (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_LOCK0_KICK1_RESETVAL                                 (0x00000000U)

/* INTR_RAW_STATUS */

#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROT_ERR_MASK                        (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROT_ERR_SHIFT                       (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROT_ERR_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROT_ERR_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_ADDR_ERR_MASK                        (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_ADDR_ERR_SHIFT                       (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_ADDR_ERR_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_ADDR_ERR_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_KICK_ERR_MASK                        (0x00000004U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_KICK_ERR_SHIFT                       (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_KICK_ERR_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_KICK_ERR_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROXY_ERR_MASK                       (0x00000008U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROXY_ERR_SHIFT                      (0x00000003U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROXY_ERR_RESETVAL                   (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_PROXY_ERR_MAX                        (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_RAW_STATUS_RESETVAL                             (0x00000000U)

/* INTR_ENABLED_STATUS_CLEAR */

#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MASK      (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_SHIFT     (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_RESETVAL  (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MAX       (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MASK      (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_SHIFT     (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_RESETVAL  (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MAX       (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MASK      (0x00000004U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_SHIFT     (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_RESETVAL  (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MAX       (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MASK     (0x00000008U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_SHIFT    (0x00000003U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_RESETVAL (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MAX      (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLED_STATUS_CLEAR_RESETVAL                   (0x00000000U)

/* INTR_ENABLE */

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROT_ERR_EN_MASK                         (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROT_ERR_EN_SHIFT                        (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROT_ERR_EN_RESETVAL                     (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROT_ERR_EN_MAX                          (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_ADDR_ERR_EN_MASK                         (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_ADDR_ERR_EN_SHIFT                        (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_ADDR_ERR_EN_RESETVAL                     (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_ADDR_ERR_EN_MAX                          (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_KICK_ERR_EN_MASK                         (0x00000004U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_KICK_ERR_EN_SHIFT                        (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_KICK_ERR_EN_RESETVAL                     (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_KICK_ERR_EN_MAX                          (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROXY_ERR_EN_MASK                        (0x00000008U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROXY_ERR_EN_SHIFT                       (0x00000003U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROXY_ERR_EN_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_PROXY_ERR_EN_MAX                         (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_RESETVAL                                 (0x00000000U)

/* INTR_ENABLE_CLEAR */

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MASK               (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_SHIFT              (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_RESETVAL           (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MAX                (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MASK               (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_SHIFT              (0x00000001U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_RESETVAL           (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MAX                (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MASK               (0x00000004U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_SHIFT              (0x00000002U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_RESETVAL           (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MAX                (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MASK              (0x00000008U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_SHIFT             (0x00000003U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_RESETVAL          (0x00000000U)
#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MAX               (0x00000001U)

#define CSL_RSS_PROC_CTRL_INTR_ENABLE_CLEAR_RESETVAL                           (0x00000000U)

/* EOI */

#define CSL_RSS_PROC_CTRL_EOI_EOI_VECTOR_MASK                                  (0x000000FFU)
#define CSL_RSS_PROC_CTRL_EOI_EOI_VECTOR_SHIFT                                 (0x00000000U)
#define CSL_RSS_PROC_CTRL_EOI_EOI_VECTOR_RESETVAL                              (0x00000000U)
#define CSL_RSS_PROC_CTRL_EOI_EOI_VECTOR_MAX                                   (0x000000FFU)

#define CSL_RSS_PROC_CTRL_EOI_RESETVAL                                         (0x00000000U)

/* FAULT_ADDRESS */

#define CSL_RSS_PROC_CTRL_FAULT_ADDRESS_FAULT_ADDR_MASK                        (0xFFFFFFFFU)
#define CSL_RSS_PROC_CTRL_FAULT_ADDRESS_FAULT_ADDR_SHIFT                       (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_ADDRESS_FAULT_ADDR_RESETVAL                    (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_ADDRESS_FAULT_ADDR_MAX                         (0xFFFFFFFFU)

#define CSL_RSS_PROC_CTRL_FAULT_ADDRESS_RESETVAL                               (0x00000000U)

/* FAULT_TYPE_STATUS */

#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MASK                    (0x0000003FU)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_SHIFT                   (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_RESETVAL                (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_TYPE_MAX                     (0x0000003FU)

#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MASK                      (0x00000040U)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_SHIFT                     (0x00000006U)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_RESETVAL                  (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_FAULT_NS_MAX                       (0x00000001U)

#define CSL_RSS_PROC_CTRL_FAULT_TYPE_STATUS_RESETVAL                           (0x00000000U)

/* FAULT_ATTR_STATUS */

#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MASK                  (0x000000FFU)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_SHIFT                 (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_RESETVAL              (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_PRIVID_MAX                   (0x000000FFU)

#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MASK                 (0x000FFF00U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_SHIFT                (0x00000008U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_RESETVAL             (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_ROUTEID_MAX                  (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MASK                     (0xFFF00000U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_SHIFT                    (0x00000014U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_RESETVAL                 (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_FAULT_XID_MAX                      (0x00000FFFU)

#define CSL_RSS_PROC_CTRL_FAULT_ATTR_STATUS_RESETVAL                           (0x00000000U)

/* FAULT_CLEAR */

#define CSL_RSS_PROC_CTRL_FAULT_CLEAR_FAULT_CLR_MASK                           (0x00000001U)
#define CSL_RSS_PROC_CTRL_FAULT_CLEAR_FAULT_CLR_SHIFT                          (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_CLEAR_FAULT_CLR_RESETVAL                       (0x00000000U)
#define CSL_RSS_PROC_CTRL_FAULT_CLEAR_FAULT_CLR_MAX                            (0x00000001U)

#define CSL_RSS_PROC_CTRL_FAULT_CLEAR_RESETVAL                                 (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
