/*
 *  Copyright (C) 2024 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef ICSS_TIMESYNC_COMMON_MACROS_H_
#define ICSS_TIMESYNC_COMMON_MACROS_H_

#ifdef __cplusplus
extern "C"
{
#endif

/* Generic ICSS Offset macros */
#if defined(SOC_AM64X) || defined (SOC_AM243X)
    #define CSL_ICSS_PR1_IEP0_SLV_CMP1_REG0                           (CSL_ICSS_G_PR1_IEP0_SLV_CMP1_REG0)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC_START_REG                      (CSL_ICSS_G_PR1_IEP0_SLV_SYNC_START_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC_CTRL_REG                       (CSL_ICSS_G_PR1_IEP0_SLV_SYNC_CTRL_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC1_DELAY_REG                     (CSL_ICSS_G_PR1_IEP0_SLV_SYNC1_DELAY_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_PD_WD_TIM_REG                       (CSL_ICSS_G_PR1_IEP0_SLV_PD_WD_TIM_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_CMP_CFG_REG                         (CSL_ICSS_G_PR1_IEP0_SLV_CMP_CFG_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC_PWIDTH_REG                     (CSL_ICSS_G_PR1_IEP0_SLV_SYNC_PWIDTH_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_SHIFT    (CSL_ICSS_G_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_SHIFT)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_CNT_ENABLE_MAX       (CSL_ICSS_G_PR1_IEP0_SLV_GLOBAL_CFG_REG_CNT_ENABLE_MAX)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_MASK     (CSL_ICSS_G_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_MASK)
    #define CSL_ICSS_PR1_IEP0_SLV_SLOW_COMPEN_REG                     (CSL_ICSS_G_PR1_IEP0_SLV_SLOW_COMPEN_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_CMP_INC_SHIFT        (CSL_ICSS_G_PR1_IEP0_SLV_GLOBAL_CFG_REG_CMP_INC_SHIFT)
    #define CSL_ICSS_PR1_IEP0_SLV_CMP0_REG0                           (CSL_ICSS_G_PR1_IEP0_SLV_CMP0_REG0)
    #define CSL_ICSS_PR1_ICSS_INTC_SLV_ENA_STATUS_REG0                (CSL_ICSS_G_PR1_ICSS_INTC_INTC_SLV_ENA_STATUS_REG0)
#else
    #define CSL_ICSS_PR1_IEP0_SLV_CMP1_REG0                           (CSL_ICSS_M_PR1_IEP0_SLV_CMP1_REG0)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC_START_REG                      (CSL_ICSS_M_PR1_IEP0_SLV_SYNC_START_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC_CTRL_REG                       (CSL_ICSS_M_PR1_IEP0_SLV_SYNC_CTRL_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC1_DELAY_REG                     (CSL_ICSS_M_PR1_IEP0_SLV_SYNC1_DELAY_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_PD_WD_TIM_REG                       (CSL_ICSS_M_PR1_IEP0_SLV_PD_WD_TIM_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_CMP_CFG_REG                         (CSL_ICSS_M_PR1_IEP0_SLV_CMP_CFG_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_SYNC_PWIDTH_REG                     (CSL_ICSS_M_PR1_IEP0_SLV_SYNC_PWIDTH_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_SHIFT    (CSL_ICSS_M_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_SHIFT)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_CNT_ENABLE_MAX       (CSL_ICSS_M_PR1_IEP0_SLV_GLOBAL_CFG_REG_CNT_ENABLE_MAX)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_MASK     (CSL_ICSS_M_PR1_IEP0_SLV_GLOBAL_CFG_REG_DEFAULT_INC_MASK)
    #define CSL_ICSS_PR1_IEP0_SLV_SLOW_COMPEN_REG                     (CSL_ICSS_M_PR1_IEP0_SLV_SLOW_COMPEN_REG)
    #define CSL_ICSS_PR1_IEP0_SLV_GLOBAL_CFG_REG_CMP_INC_SHIFT        (CSL_ICSS_M_PR1_IEP0_SLV_GLOBAL_CFG_REG_CMP_INC_SHIFT)
    #define CSL_ICSS_PR1_IEP0_SLV_CMP0_REG0                           (CSL_ICSS_M_PR1_IEP0_SLV_CMP0_REG0)
    #define CSL_ICSS_PR1_ICSS_INTC_SLV_ENA_STATUS_REG0                (CSL_ICSS_M_PR1_ICSS_INTC_SLV_ENA_STATUS_REG0)
#endif

#ifdef __cplusplus
}
#endif

#endif /* ICSS_TIMESYNC_COMMON_MACROS_H_ */