/********************************************************************
* Copyright (C) 2024 Texas Instruments Incorporated.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_INTR_GIC0_H_
#define CSLR_INTR_GIC0_H_

#ifdef __cplusplus
extern "C"
{
#endif


/* List of intr sources for receiver: gic0 */
/* This instance name corresponds to design instance name: gic500ss_main_0 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_COMMIRQ0              (22U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_commirq0_0, Dest signal name: bus_ppi0_0_22 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_COMMIRQ1              (22U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_commirq1_0, Dest signal name: bus_ppi0_1_22 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_COMMIRQ0              (22U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_commirq0_0, Dest signal name: bus_ppi1_0_22 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_COMMIRQ1              (22U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_commirq1_0, Dest signal name: bus_ppi1_1_22 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_PMUIRQ0               (23U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_pmuirq0_0, Dest signal name: bus_ppi0_0_23 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_PMUIRQ1               (23U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_pmuirq1_0, Dest signal name: bus_ppi0_1_23 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_PMUIRQ0               (23U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_pmuirq0_0, Dest signal name: bus_ppi1_0_23 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_PMUIRQ1               (23U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_pmuirq1_0, Dest signal name: bus_ppi1_1_23 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CTIIRQ0               (24U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_ctiirq0_0, Dest signal name: bus_ppi0_0_24 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CTIIRQ1               (24U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_ctiirq1_0, Dest signal name: bus_ppi0_1_24 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CTIIRQ0               (24U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_ctiirq0_0, Dest signal name: bus_ppi1_0_24 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CTIIRQ1               (24U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_ctiirq1_0, Dest signal name: bus_ppi1_1_24 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_VCPUMNTIRQ0           (25U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_vcpumntirq0_0, Dest signal name: bus_ppi0_0_25 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_VCPUMNTIRQ1           (25U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_vcpumntirq1_0, Dest signal name: bus_ppi0_1_25 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_VCPUMNTIRQ0           (25U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_vcpumntirq0_0, Dest signal name: bus_ppi1_0_25 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_VCPUMNTIRQ1           (25U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_vcpumntirq1_0, Dest signal name: bus_ppi1_1_25 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTHPIRQ0             (26U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cnthpirq0_0, Dest signal name: bus_ppi0_0_26 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTHPIRQ1             (26U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cnthpirq1_0, Dest signal name: bus_ppi0_1_26 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTHPIRQ0             (26U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cnthpirq0_0, Dest signal name: bus_ppi1_0_26 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTHPIRQ1             (26U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cnthpirq1_0, Dest signal name: bus_ppi1_1_26 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTVIRQ0              (27U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cntvirq0_0, Dest signal name: bus_ppi0_0_27 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTVIRQ1              (27U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cntvirq1_0, Dest signal name: bus_ppi0_1_27 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTVIRQ0              (27U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cntvirq0_0, Dest signal name: bus_ppi1_0_27 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTVIRQ1              (27U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cntvirq1_0, Dest signal name: bus_ppi1_1_27 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTPSIRQ0             (29U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cntpsirq0_0, Dest signal name: bus_ppi0_0_29 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTPSIRQ1             (29U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cntpsirq1_0, Dest signal name: bus_ppi0_1_29 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTPSIRQ0             (29U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cntpsirq0_0, Dest signal name: bus_ppi1_0_29 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTPSIRQ1             (29U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cntpsirq1_0, Dest signal name: bus_ppi1_1_29 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTPNSIRQ0            (30U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cntpnsirq0_0, Dest signal name: bus_ppi0_0_30 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM0_CNTPNSIRQ1            (30U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm0_cntpnsirq1_0, Dest signal name: bus_ppi0_1_30 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTPNSIRQ0            (30U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cntpnsirq0_0, Dest signal name: bus_ppi1_0_30 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_ARM1_CNTPNSIRQ1            (30U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_arm1_cntpnsirq1_0, Dest signal name: bus_ppi1_1_30 */
#define CSL_GIC0_INTR_CTRL_MMR0_BUS_IPC_SET8_IPC_SET_IPCFG            (32U)  /* Design details: Source signal name: main_ctrl_mmr_main_0_bus_IPC_SET8_ipc_set_ipcfg_0, Dest signal name: bus_spi_32 */
#define CSL_GIC0_INTR_CTRL_MMR0_BUS_IPC_SET9_IPC_SET_IPCFG            (33U)  /* Design details: Source signal name: main_ctrl_mmr_main_0_bus_IPC_SET9_ipc_set_ipcfg_0, Dest signal name: bus_spi_33 */
#define CSL_GIC0_INTR_CTRL_MMR0_BUS_IPC_SET10_IPC_SET_IPCFG           (34U)  /* Design details: Source signal name: main_ctrl_mmr_main_0_bus_IPC_SET10_ipc_set_ipcfg_0, Dest signal name: bus_spi_34 */
#define CSL_GIC0_INTR_CTRL_MMR0_BUS_IPC_SET11_IPC_SET_IPCFG           (35U)  /* Design details: Source signal name: main_ctrl_mmr_main_0_bus_IPC_SET11_ipc_set_ipcfg_0, Dest signal name: bus_spi_35 */
#define CSL_GIC0_INTR_GPMC0_BUS_GPMC_SINTERRUPT                       (40U)  /* Design details: Source signal name: gpmc_main_0_bus_gpmc_sinterrupt_0, Dest signal name: bus_spi_40 */
#define CSL_GIC0_INTR_ELM0_BUS_ELM_POROCPSINTERRUPT_LVL               (41U)  /* Design details: Source signal name: elm_main_0_bus_elm_porocpsinterrupt_lvl_0, Dest signal name: bus_spi_41 */
#define CSL_GIC0_INTR_DDRSS0_BUS_DDRSS_V2H_OTHER_ERR_LVL              (44U)  /* Design details: Source signal name: ddr39ss_gs80_main_0_bus_ddrss_v2h_other_err_lvl_0, Dest signal name: bus_spi_44 */
#define CSL_GIC0_INTR_CCDEBUGSS0_BUS_AQCMPINTR_LEVEL                  (48U)  /* Design details: Source signal name: k3_cc_debug_cell_main_0_bus_aqcmpintr_level_0, Dest signal name: bus_spi_48 */
#define CSL_GIC0_INTR_DEBUGSS0_BUS_AQCMPINTR_LEVEL                    (49U)  /* Design details: Source signal name: k3_main_debug_cell_main_0_bus_aqcmpintr_level_0, Dest signal name: bus_spi_49 */
#define CSL_GIC0_INTR_DEBUGSS0_BUS_CTM_LEVEL                          (50U)  /* Design details: Source signal name: k3_main_debug_cell_main_0_bus_ctm_level_0, Dest signal name: bus_spi_50 */
#define CSL_GIC0_INTR_PSC0_BUS_PSC_ALLINT_0                           (51U)  /* Design details: Source signal name: k3_main_psc_wrap_main_0_bus_psc_allint_0, Dest signal name: bus_spi_51 */
#define CSL_GIC0_INTR_PBIST0_BUS_DFT_PBIST_CPU                        (52U)  /* Design details: Source signal name: k3_pbist_4c28p_wrap_main_0_bus_dft_pbist_cpu_0, Dest signal name: bus_spi_52 */
#define CSL_GIC0_INTR_PBIST1_BUS_DFT_PBIST_CPU                        (53U)  /* Design details: Source signal name: k3_pbist_4c28p_wrap_main_1_bus_dft_pbist_cpu_0, Dest signal name: bus_spi_53 */
#define CSL_GIC0_INTR_ESM0_BUS_ESM_INT_LOW_LVL                        (54U)  /* Design details: Source signal name: esm_main_main_0_bus_esm_int_low_lvl_0, Dest signal name: bus_spi_54 */
#define CSL_GIC0_INTR_ESM0_BUS_ESM_INT_HI_LVL                         (55U)  /* Design details: Source signal name: esm_main_main_0_bus_esm_int_hi_lvl_0, Dest signal name: bus_spi_55 */
#define CSL_GIC0_INTR_SA2_UL0_BUS_SA_UL_TRNG                          (56U)  /* Design details: Source signal name: sa2_ul_main_0_bus_sa_ul_trng_0, Dest signal name: bus_spi_56 */
#define CSL_GIC0_INTR_SA2_UL0_BUS_SA_UL_PKA                           (57U)  /* Design details: Source signal name: sa2_ul_main_0_bus_sa_ul_pka_0, Dest signal name: bus_spi_57 */
#define CSL_GIC0_INTR_CTRL_MMR0_BUS_ACCESS_ERR                        (58U)  /* Design details: Source signal name: main_ctrl_mmr_main_0_bus_access_err_0, Dest signal name: bus_spi_58 */
#define CSL_GIC0_INTR_ESM0_BUS_ESM_INT_CFG_LVL                        (59U)  /* Design details: Source signal name: esm_main_main_0_bus_esm_int_cfg_lvl_0, Dest signal name: bus_spi_59 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_0                           (64U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_0, Dest signal name: bus_spi_64 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_1                           (65U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_1, Dest signal name: bus_spi_65 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_2                           (66U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_2, Dest signal name: bus_spi_66 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_3                           (67U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_3, Dest signal name: bus_spi_67 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_4                           (68U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_4, Dest signal name: bus_spi_68 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_5                           (69U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_5, Dest signal name: bus_spi_69 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_6                           (70U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_6, Dest signal name: bus_spi_70 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_7                           (71U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_7, Dest signal name: bus_spi_71 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_8                           (72U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_8, Dest signal name: bus_spi_72 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_9                           (73U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_9, Dest signal name: bus_spi_73 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_10                          (74U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_10, Dest signal name: bus_spi_74 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_11                          (75U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_11, Dest signal name: bus_spi_75 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_12                          (76U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_12, Dest signal name: bus_spi_76 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_13                          (77U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_13, Dest signal name: bus_spi_77 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_14                          (78U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_14, Dest signal name: bus_spi_78 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_15                          (79U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_15, Dest signal name: bus_spi_79 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_16                          (80U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_16, Dest signal name: bus_spi_80 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_17                          (81U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_17, Dest signal name: bus_spi_81 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_18                          (82U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_18, Dest signal name: bus_spi_82 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_19                          (83U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_19, Dest signal name: bus_spi_83 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_20                          (84U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_20, Dest signal name: bus_spi_84 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_21                          (85U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_21, Dest signal name: bus_spi_85 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_22                          (86U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_22, Dest signal name: bus_spi_86 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_23                          (87U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_23, Dest signal name: bus_spi_87 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_24                          (88U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_24, Dest signal name: bus_spi_88 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_25                          (89U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_25, Dest signal name: bus_spi_89 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_26                          (90U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_26, Dest signal name: bus_spi_90 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_27                          (91U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_27, Dest signal name: bus_spi_91 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_28                          (92U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_28, Dest signal name: bus_spi_92 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_29                          (93U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_29, Dest signal name: bus_spi_93 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_30                          (94U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_30, Dest signal name: bus_spi_94 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_31                          (95U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_31, Dest signal name: bus_spi_95 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_32                          (96U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_32, Dest signal name: bus_spi_96 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_33                          (97U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_33, Dest signal name: bus_spi_97 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_34                          (98U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_34, Dest signal name: bus_spi_98 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_35                          (99U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_35, Dest signal name: bus_spi_99 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_36                         (100U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_36, Dest signal name: bus_spi_100 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_37                         (101U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_37, Dest signal name: bus_spi_101 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_38                         (102U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_38, Dest signal name: bus_spi_102 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_39                         (103U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_39, Dest signal name: bus_spi_103 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_40                         (104U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_40, Dest signal name: bus_spi_104 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_41                         (105U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_41, Dest signal name: bus_spi_105 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_42                         (106U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_42, Dest signal name: bus_spi_106 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_43                         (107U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_43, Dest signal name: bus_spi_107 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_44                         (108U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_44, Dest signal name: bus_spi_108 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_45                         (109U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_45, Dest signal name: bus_spi_109 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_46                         (110U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_46, Dest signal name: bus_spi_110 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_47                         (111U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_47, Dest signal name: bus_spi_111 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_48                         (112U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_48, Dest signal name: bus_spi_112 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_49                         (113U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_49, Dest signal name: bus_spi_113 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_50                         (114U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_50, Dest signal name: bus_spi_114 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_51                         (115U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_51, Dest signal name: bus_spi_115 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_52                         (116U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_52, Dest signal name: bus_spi_116 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_53                         (117U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_53, Dest signal name: bus_spi_117 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_54                         (118U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_54, Dest signal name: bus_spi_118 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_55                         (119U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_55, Dest signal name: bus_spi_119 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_56                         (120U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_56, Dest signal name: bus_spi_120 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_57                         (121U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_57, Dest signal name: bus_spi_121 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_58                         (122U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_58, Dest signal name: bus_spi_122 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_59                         (123U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_59, Dest signal name: bus_spi_123 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_60                         (124U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_60, Dest signal name: bus_spi_124 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_61                         (125U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_61, Dest signal name: bus_spi_125 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_62                         (126U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_62, Dest signal name: bus_spi_126 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_63                         (127U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_63, Dest signal name: bus_spi_127 */
#define CSL_GIC0_INTR_USB3SS0_BUS_OTG_LVL                            (128U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_otg_lvl_0, Dest signal name: bus_spi_128 */
#define CSL_GIC0_INTR_USB3SS0_BUS_MISC_LVL                           (129U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_misc_lvl_0, Dest signal name: bus_spi_129 */
#define CSL_GIC0_INTR_USB3SS0_BUS_BC_LVL                             (130U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_bc_lvl_0, Dest signal name: bus_spi_130 */
#define CSL_GIC0_INTR_USB3SS0_BUS_PME_GEN_LVL                        (131U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_pme_gen_lvl_0, Dest signal name: bus_spi_131 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I00_LVL                            (132U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i00_lvl_0, Dest signal name: bus_spi_132 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I01_LVL                            (133U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i01_lvl_0, Dest signal name: bus_spi_133 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I02_LVL                            (134U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i02_lvl_0, Dest signal name: bus_spi_134 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I03_LVL                            (135U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i03_lvl_0, Dest signal name: bus_spi_135 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I04_LVL                            (136U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i04_lvl_0, Dest signal name: bus_spi_136 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I05_LVL                            (137U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i05_lvl_0, Dest signal name: bus_spi_137 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I06_LVL                            (138U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i06_lvl_0, Dest signal name: bus_spi_138 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I07_LVL                            (139U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i07_lvl_0, Dest signal name: bus_spi_139 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I08_LVL                            (140U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i08_lvl_0, Dest signal name: bus_spi_140 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I09_LVL                            (141U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i09_lvl_0, Dest signal name: bus_spi_141 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I10_LVL                            (142U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i10_lvl_0, Dest signal name: bus_spi_142 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I11_LVL                            (143U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i11_lvl_0, Dest signal name: bus_spi_143 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I12_LVL                            (144U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i12_lvl_0, Dest signal name: bus_spi_144 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I13_LVL                            (145U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i13_lvl_0, Dest signal name: bus_spi_145 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I14_LVL                            (146U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i14_lvl_0, Dest signal name: bus_spi_146 */
#define CSL_GIC0_INTR_USB3SS0_BUS_I15_LVL                            (147U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_0_bus_i15_lvl_0, Dest signal name: bus_spi_147 */
#define CSL_GIC0_INTR_USB3SS1_BUS_OTG_LVL                            (148U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_otg_lvl_0, Dest signal name: bus_spi_148 */
#define CSL_GIC0_INTR_USB3SS1_BUS_MISC_LVL                           (149U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_misc_lvl_0, Dest signal name: bus_spi_149 */
#define CSL_GIC0_INTR_USB3SS1_BUS_BC_LVL                             (150U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_bc_lvl_0, Dest signal name: bus_spi_150 */
#define CSL_GIC0_INTR_USB3SS1_BUS_PME_GEN_LVL                        (151U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_pme_gen_lvl_0, Dest signal name: bus_spi_151 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I00_LVL                            (152U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i00_lvl_0, Dest signal name: bus_spi_152 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I01_LVL                            (153U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i01_lvl_0, Dest signal name: bus_spi_153 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I02_LVL                            (154U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i02_lvl_0, Dest signal name: bus_spi_154 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I03_LVL                            (155U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i03_lvl_0, Dest signal name: bus_spi_155 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I04_LVL                            (156U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i04_lvl_0, Dest signal name: bus_spi_156 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I05_LVL                            (157U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i05_lvl_0, Dest signal name: bus_spi_157 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I06_LVL                            (158U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i06_lvl_0, Dest signal name: bus_spi_158 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I07_LVL                            (159U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i07_lvl_0, Dest signal name: bus_spi_159 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I08_LVL                            (160U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i08_lvl_0, Dest signal name: bus_spi_160 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I09_LVL                            (161U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i09_lvl_0, Dest signal name: bus_spi_161 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I10_LVL                            (162U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i10_lvl_0, Dest signal name: bus_spi_162 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I11_LVL                            (163U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i11_lvl_0, Dest signal name: bus_spi_163 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I12_LVL                            (164U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i12_lvl_0, Dest signal name: bus_spi_164 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I13_LVL                            (165U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i13_lvl_0, Dest signal name: bus_spi_165 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I14_LVL                            (166U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i14_lvl_0, Dest signal name: bus_spi_166 */
#define CSL_GIC0_INTR_USB3SS1_BUS_I15_LVL                            (167U)  /* Design details: Source signal name: usb3ss2p0_gs80_main_1_bus_i15_lvl_0, Dest signal name: bus_spi_167 */
#define CSL_GIC0_INTR_MMC0_BUS_EMMCSDSS_INTR                         (168U)  /* Design details: Source signal name: emmc4sd3ss_gs80_main_0_bus_emmcsdss_intr_0, Dest signal name: bus_spi_168 */
#define CSL_GIC0_INTR_MMC1_BUS_EMMCSDSS_INTR                         (169U)  /* Design details: Source signal name: emmc2sd3ss_gs80_main_0_bus_emmcsdss_intr_0, Dest signal name: bus_spi_169 */
#define CSL_GIC0_INTR_GLUELOGIC_SOCA_INT_GLUE_GLUELOGIC_SOCA_INT_GLUE_BUS_SOCA_INT  (180U)  /* Design details: Source signal name: GLUELOGIC_soca_int_glue_bus_soca_int_0, Dest signal name: bus_spi_180 */
#define CSL_GIC0_INTR_GLUELOGIC_SOCB_INT_GLUE_GLUELOGIC_SOCB_INT_GLUE_BUS_SOCB_INT  (181U)  /* Design details: Source signal name: GLUELOGIC_socb_int_glue_bus_socb_int_0, Dest signal name: bus_spi_181 */
#define CSL_GIC0_INTR_GLUELOGIC_NMI_INVERTER_GLUELOGIC_NMI_INVERTER_BUS_NMI_Z_INVERTED   (182U)  /* Design details: Source signal name: GLUELOGIC_NMI_INVERTER_bus_nmi_z_inverted_0, Dest signal name: bus_spi_182 */
#define CSL_GIC0_INTR_CAL0_BUS_INT_CAL_L                             (184U)  /* Design details: Source signal name: cal_main_0_bus_int_cal_l_0, Dest signal name: bus_spi_184 */
#define CSL_GIC0_INTR_CAL0_BUS_INT_LVDSRX1_P                         (185U)  /* Design details: Source signal name: cal_main_0_bus_int_lvdsrx1_p_0, Dest signal name: bus_spi_185 */
#define CSL_GIC0_INTR_CAL0_BUS_INT_LVDSRX2_P                         (186U)  /* Design details: Source signal name: cal_main_0_bus_int_lvdsrx2_p_0, Dest signal name: bus_spi_186 */
#define CSL_GIC0_INTR_CAL0_BUS_INT_LVDSRX3_P                         (187U)  /* Design details: Source signal name: cal_main_0_bus_int_lvdsrx3_p_0, Dest signal name: bus_spi_187 */
#define CSL_GIC0_INTR_CAL0_BUS_INT_LVDSRX4_P                         (188U)  /* Design details: Source signal name: cal_main_0_bus_int_lvdsrx4_p_0, Dest signal name: bus_spi_188 */
#define CSL_GIC0_INTR_GPU0_BUS_GPU_IRQ                               (194U)  /* Design details: Source signal name: k3_boltv2_main_0_bus_gpu_irq_0, Dest signal name: bus_spi_194 */
#define CSL_GIC0_INTR_GPU0_BUS_EXP_INTR_0                            (195U)  /* Design details: Source signal name: k3_boltv2_main_0_bus_exp_intr_0, Dest signal name: bus_spi_195 */
#define CSL_GIC0_INTR_GPU0_BUS_INIT_ERR                              (196U)  /* Design details: Source signal name: k3_boltv2_main_0_bus_init_err_0, Dest signal name: bus_spi_196 */
#define CSL_GIC0_INTR_GPU0_BUS_TARGET_ERR                            (197U)  /* Design details: Source signal name: k3_boltv2_main_0_bus_target_err_0, Dest signal name: bus_spi_197 */
#define CSL_GIC0_INTR_DSS0_BUS_DISPC_INTR_REQ_0                      (198U)  /* Design details: Source signal name: k3_dss_ul_main_0_bus_dispc_intr_req_0_0, Dest signal name: bus_spi_198 */
#define CSL_GIC0_INTR_DSS0_BUS_DISPC_INTR_REQ_1                      (199U)  /* Design details: Source signal name: k3_dss_ul_main_0_bus_dispc_intr_req_1_0, Dest signal name: bus_spi_199 */
#define CSL_GIC0_INTR_MCSPI0_BUS_INTR_SPI                            (216U)  /* Design details: Source signal name: spi_main_0_bus_intr_spi_0, Dest signal name: bus_spi_216 */
#define CSL_GIC0_INTR_MCSPI1_BUS_INTR_SPI                            (217U)  /* Design details: Source signal name: spi_main_1_bus_intr_spi_0, Dest signal name: bus_spi_217 */
#define CSL_GIC0_INTR_MCSPI2_BUS_INTR_SPI                            (218U)  /* Design details: Source signal name: spi_main_2_bus_intr_spi_0, Dest signal name: bus_spi_218 */
#define CSL_GIC0_INTR_MCSPI3_BUS_INTR_SPI                            (219U)  /* Design details: Source signal name: spi_main_3_bus_intr_spi_0, Dest signal name: bus_spi_219 */
#define CSL_GIC0_INTR_MCSPI4_BUS_INTR_SPI                            (220U)  /* Design details: Source signal name: spi_main_4_bus_intr_spi_0, Dest signal name: bus_spi_220 */
#define CSL_GIC0_INTR_USART0_BUS_USART_IRQ                           (224U)  /* Design details: Source signal name: usart_main_0_bus_usart_irq_0, Dest signal name: bus_spi_224 */
#define CSL_GIC0_INTR_USART1_BUS_USART_IRQ                           (225U)  /* Design details: Source signal name: usart_main_1_bus_usart_irq_0, Dest signal name: bus_spi_225 */
#define CSL_GIC0_INTR_USART2_BUS_USART_IRQ                           (226U)  /* Design details: Source signal name: usart_main_2_bus_usart_irq_0, Dest signal name: bus_spi_226 */
#define CSL_GIC0_INTR_I2C0_BUS_POINTRPEND                            (232U)  /* Design details: Source signal name: mshsi2c_main_0_bus_pointrpend_0, Dest signal name: bus_spi_232 */
#define CSL_GIC0_INTR_I2C1_BUS_POINTRPEND                            (233U)  /* Design details: Source signal name: mshsi2c_main_1_bus_pointrpend_0, Dest signal name: bus_spi_233 */
#define CSL_GIC0_INTR_I2C2_BUS_POINTRPEND                            (234U)  /* Design details: Source signal name: mshsi2c_main_2_bus_pointrpend_0, Dest signal name: bus_spi_234 */
#define CSL_GIC0_INTR_I2C3_BUS_POINTRPEND                            (235U)  /* Design details: Source signal name: mshsi2c_main_3_bus_pointrpend_0, Dest signal name: bus_spi_235 */
#define CSL_GIC0_INTR_MCASP0_BUS_XMIT_INTR_PEND                      (240U)  /* Design details: Source signal name: mcasp_main_0_bus_xmit_intr_pend_0, Dest signal name: bus_spi_240 */
#define CSL_GIC0_INTR_MCASP0_BUS_REC_INTR_PEND                       (241U)  /* Design details: Source signal name: mcasp_main_0_bus_rec_intr_pend_0, Dest signal name: bus_spi_241 */
#define CSL_GIC0_INTR_MCASP1_BUS_XMIT_INTR_PEND                      (242U)  /* Design details: Source signal name: mcasp_main_1_bus_xmit_intr_pend_0, Dest signal name: bus_spi_242 */
#define CSL_GIC0_INTR_MCASP1_BUS_REC_INTR_PEND                       (243U)  /* Design details: Source signal name: mcasp_main_1_bus_rec_intr_pend_0, Dest signal name: bus_spi_243 */
#define CSL_GIC0_INTR_MCASP2_BUS_XMIT_INTR_PEND                      (244U)  /* Design details: Source signal name: mcasp_main_2_bus_xmit_intr_pend_0, Dest signal name: bus_spi_244 */
#define CSL_GIC0_INTR_MCASP2_BUS_REC_INTR_PEND                       (245U)  /* Design details: Source signal name: mcasp_main_2_bus_rec_intr_pend_0, Dest signal name: bus_spi_245 */
#define CSL_GIC0_INTR_TIMER0_BUS_INTR_PEND                           (256U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_0_bus_intr_pend_0, Dest signal name: bus_spi_256 */
#define CSL_GIC0_INTR_TIMER1_BUS_INTR_PEND                           (257U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_1_bus_intr_pend_0, Dest signal name: bus_spi_257 */
#define CSL_GIC0_INTR_TIMER2_BUS_INTR_PEND                           (258U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_2_bus_intr_pend_0, Dest signal name: bus_spi_258 */
#define CSL_GIC0_INTR_TIMER3_BUS_INTR_PEND                           (259U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_3_bus_intr_pend_0, Dest signal name: bus_spi_259 */
#define CSL_GIC0_INTR_TIMER4_BUS_INTR_PEND                           (260U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_4_bus_intr_pend_0, Dest signal name: bus_spi_260 */
#define CSL_GIC0_INTR_TIMER5_BUS_INTR_PEND                           (261U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_5_bus_intr_pend_0, Dest signal name: bus_spi_261 */
#define CSL_GIC0_INTR_TIMER6_BUS_INTR_PEND                           (262U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_6_bus_intr_pend_0, Dest signal name: bus_spi_262 */
#define CSL_GIC0_INTR_TIMER7_BUS_INTR_PEND                           (263U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_7_bus_intr_pend_0, Dest signal name: bus_spi_263 */
#define CSL_GIC0_INTR_TIMER8_BUS_INTR_PEND                           (264U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_8_bus_intr_pend_0, Dest signal name: bus_spi_264 */
#define CSL_GIC0_INTR_TIMER9_BUS_INTR_PEND                           (265U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_9_bus_intr_pend_0, Dest signal name: bus_spi_265 */
#define CSL_GIC0_INTR_TIMER10_BUS_INTR_PEND                          (266U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_10_bus_intr_pend_0, Dest signal name: bus_spi_266 */
#define CSL_GIC0_INTR_TIMER11_BUS_INTR_PEND                          (267U)  /* Design details: Source signal name: dmtimer_dmc1ms_main_11_bus_intr_pend_0, Dest signal name: bus_spi_267 */
#define CSL_GIC0_INTR_RTI0_BUS_INTR_WWD                              (280U)  /* Design details: Source signal name: rti_main_0_bus_intr_wwd_0, Dest signal name: bus_spi_280 */
#define CSL_GIC0_INTR_RTI1_BUS_INTR_WWD                              (281U)  /* Design details: Source signal name: rti_main_1_bus_intr_wwd_0, Dest signal name: bus_spi_281 */
#define CSL_GIC0_INTR_RTI2_BUS_INTR_WWD                              (282U)  /* Design details: Source signal name: rti_main_2_bus_intr_wwd_0, Dest signal name: bus_spi_282 */
#define CSL_GIC0_INTR_RTI3_BUS_INTR_WWD                              (283U)  /* Design details: Source signal name: rti_main_3_bus_intr_wwd_0, Dest signal name: bus_spi_283 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_0            (286U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_0, Dest signal name: bus_spi_286 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_1            (287U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_1, Dest signal name: bus_spi_287 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_2            (288U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_2, Dest signal name: bus_spi_288 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_3            (289U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_3, Dest signal name: bus_spi_289 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_4            (290U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_4, Dest signal name: bus_spi_290 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_5            (291U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_5, Dest signal name: bus_spi_291 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_6            (292U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_6, Dest signal name: bus_spi_292 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_HOST_INTR_PEND_7            (293U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_host_intr_pend_7, Dest signal name: bus_spi_293 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_0            (294U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_0, Dest signal name: bus_spi_294 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_1            (295U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_1, Dest signal name: bus_spi_295 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_2            (296U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_2, Dest signal name: bus_spi_296 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_3            (297U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_3, Dest signal name: bus_spi_297 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_4            (298U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_4, Dest signal name: bus_spi_298 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_5            (299U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_5, Dest signal name: bus_spi_299 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_6            (300U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_6, Dest signal name: bus_spi_300 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_HOST_INTR_PEND_7            (301U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_host_intr_pend_7, Dest signal name: bus_spi_301 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_0            (302U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_0, Dest signal name: bus_spi_302 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_1            (303U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_1, Dest signal name: bus_spi_303 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_2            (304U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_2, Dest signal name: bus_spi_304 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_3            (305U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_3, Dest signal name: bus_spi_305 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_4            (306U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_4, Dest signal name: bus_spi_306 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_5            (307U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_5, Dest signal name: bus_spi_307 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_6            (308U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_6, Dest signal name: bus_spi_308 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_HOST_INTR_PEND_7            (309U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_host_intr_pend_7, Dest signal name: bus_spi_309 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_TX_SOF_INTR_REQ_0           (310U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_tx_sof_intr_req_0, Dest signal name: bus_spi_310 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_TX_SOF_INTR_REQ_1           (311U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_tx_sof_intr_req_1, Dest signal name: bus_spi_311 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_RX_SOF_INTR_REQ_0           (312U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_rx_sof_intr_req_0, Dest signal name: bus_spi_312 */
#define CSL_GIC0_INTR_PRU_ICSSG0_BUS_PR1_RX_SOF_INTR_REQ_1           (313U)  /* Design details: Source signal name: icss_g_main_0_bus_pr1_rx_sof_intr_req_1, Dest signal name: bus_spi_313 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_TX_SOF_INTR_REQ_0           (314U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_tx_sof_intr_req_0, Dest signal name: bus_spi_314 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_TX_SOF_INTR_REQ_1           (315U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_tx_sof_intr_req_1, Dest signal name: bus_spi_315 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_RX_SOF_INTR_REQ_0           (316U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_rx_sof_intr_req_0, Dest signal name: bus_spi_316 */
#define CSL_GIC0_INTR_PRU_ICSSG1_BUS_PR1_RX_SOF_INTR_REQ_1           (317U)  /* Design details: Source signal name: icss_g_main_1_bus_pr1_rx_sof_intr_req_1, Dest signal name: bus_spi_317 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_TX_SOF_INTR_REQ_0           (318U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_tx_sof_intr_req_0, Dest signal name: bus_spi_318 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_TX_SOF_INTR_REQ_1           (319U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_tx_sof_intr_req_1, Dest signal name: bus_spi_319 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_RX_SOF_INTR_REQ_0           (320U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_rx_sof_intr_req_0, Dest signal name: bus_spi_320 */
#define CSL_GIC0_INTR_PRU_ICSSG2_BUS_PR1_RX_SOF_INTR_REQ_1           (321U)  /* Design details: Source signal name: icss_g_main_2_bus_pr1_rx_sof_intr_req_1, Dest signal name: bus_spi_321 */
#define CSL_GIC0_INTR_EHRPWM0_BUS_EPWM_ETINT                         (334U)  /* Design details: Source signal name: ehrpwm_main_0_bus_epwm_etint_0, Dest signal name: bus_spi_334 */
#define CSL_GIC0_INTR_EHRPWM1_BUS_EPWM_ETINT                         (335U)  /* Design details: Source signal name: ehrpwm_main_1_bus_epwm_etint_0, Dest signal name: bus_spi_335 */
#define CSL_GIC0_INTR_EHRPWM2_BUS_EPWM_ETINT                         (336U)  /* Design details: Source signal name: ehrpwm_main_2_bus_epwm_etint_0, Dest signal name: bus_spi_336 */
#define CSL_GIC0_INTR_EHRPWM3_BUS_EPWM_ETINT                         (337U)  /* Design details: Source signal name: ehrpwm_main_3_bus_epwm_etint_0, Dest signal name: bus_spi_337 */
#define CSL_GIC0_INTR_EHRPWM4_BUS_EPWM_ETINT                         (338U)  /* Design details: Source signal name: ehrpwm_main_4_bus_epwm_etint_0, Dest signal name: bus_spi_338 */
#define CSL_GIC0_INTR_EHRPWM5_BUS_EPWM_ETINT                         (339U)  /* Design details: Source signal name: ehrpwm_main_5_bus_epwm_etint_0, Dest signal name: bus_spi_339 */
#define CSL_GIC0_INTR_EHRPWM0_BUS_EPWM_TRIPZINT                      (340U)  /* Design details: Source signal name: ehrpwm_main_0_bus_epwm_tripzint_0, Dest signal name: bus_spi_340 */
#define CSL_GIC0_INTR_EHRPWM1_BUS_EPWM_TRIPZINT                      (341U)  /* Design details: Source signal name: ehrpwm_main_1_bus_epwm_tripzint_0, Dest signal name: bus_spi_341 */
#define CSL_GIC0_INTR_EHRPWM2_BUS_EPWM_TRIPZINT                      (342U)  /* Design details: Source signal name: ehrpwm_main_2_bus_epwm_tripzint_0, Dest signal name: bus_spi_342 */
#define CSL_GIC0_INTR_EHRPWM3_BUS_EPWM_TRIPZINT                      (343U)  /* Design details: Source signal name: ehrpwm_main_3_bus_epwm_tripzint_0, Dest signal name: bus_spi_343 */
#define CSL_GIC0_INTR_EHRPWM4_BUS_EPWM_TRIPZINT                      (344U)  /* Design details: Source signal name: ehrpwm_main_4_bus_epwm_tripzint_0, Dest signal name: bus_spi_344 */
#define CSL_GIC0_INTR_EHRPWM5_BUS_EPWM_TRIPZINT                      (345U)  /* Design details: Source signal name: ehrpwm_main_5_bus_epwm_tripzint_0, Dest signal name: bus_spi_345 */
#define CSL_GIC0_INTR_EQEP0_BUS_EQEP_INT                             (346U)  /* Design details: Source signal name: eqep_main_0_bus_eqep_int_0, Dest signal name: bus_spi_346 */
#define CSL_GIC0_INTR_EQEP1_BUS_EQEP_INT                             (347U)  /* Design details: Source signal name: eqep_main_1_bus_eqep_int_0, Dest signal name: bus_spi_347 */
#define CSL_GIC0_INTR_EQEP2_BUS_EQEP_INT                             (348U)  /* Design details: Source signal name: eqep_main_2_bus_eqep_int_0, Dest signal name: bus_spi_348 */
#define CSL_GIC0_INTR_ECAP0_BUS_ECAP_INT                             (349U)  /* Design details: Source signal name: ecap_main_0_bus_ecap_int_0, Dest signal name: bus_spi_349 */
#define CSL_GIC0_INTR_DCC0_BUS_INTR_DONE_LEVEL                       (352U)  /* Design details: Source signal name: dcc_main_0_bus_intr_done_level_0, Dest signal name: bus_spi_352 */
#define CSL_GIC0_INTR_DCC1_BUS_INTR_DONE_LEVEL                       (353U)  /* Design details: Source signal name: dcc_main_1_bus_intr_done_level_0, Dest signal name: bus_spi_353 */
#define CSL_GIC0_INTR_DCC2_BUS_INTR_DONE_LEVEL                       (354U)  /* Design details: Source signal name: dcc_main_2_bus_intr_done_level_0, Dest signal name: bus_spi_354 */
#define CSL_GIC0_INTR_DCC3_BUS_INTR_DONE_LEVEL                       (355U)  /* Design details: Source signal name: dcc_main_3_bus_intr_done_level_0, Dest signal name: bus_spi_355 */
#define CSL_GIC0_INTR_DCC4_BUS_INTR_DONE_LEVEL                       (356U)  /* Design details: Source signal name: dcc_main_4_bus_intr_done_level_0, Dest signal name: bus_spi_356 */
#define CSL_GIC0_INTR_DCC5_BUS_INTR_DONE_LEVEL                       (357U)  /* Design details: Source signal name: dcc_main_5_bus_intr_done_level_0, Dest signal name: bus_spi_357 */
#define CSL_GIC0_INTR_DCC6_BUS_INTR_DONE_LEVEL                       (358U)  /* Design details: Source signal name: dcc_main_6_bus_intr_done_level_0, Dest signal name: bus_spi_358 */
#define CSL_GIC0_INTR_DCC7_BUS_INTR_DONE_LEVEL                       (359U)  /* Design details: Source signal name: dcc_main_7_bus_intr_done_level_0, Dest signal name: bus_spi_359 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE0_PEND                           (360U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie0_pend_0, Dest signal name: bus_spi_360 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE1_PEND                           (361U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie1_pend_0, Dest signal name: bus_spi_361 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE2_PEND                           (362U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie2_pend_0, Dest signal name: bus_spi_362 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE3_PEND                           (363U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie3_pend_0, Dest signal name: bus_spi_363 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE4_PEND                           (364U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie4_pend_0, Dest signal name: bus_spi_364 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE5_PEND                           (365U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie5_pend_0, Dest signal name: bus_spi_365 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE6_PEND                           (366U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie6_pend_0, Dest signal name: bus_spi_366 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE7_PEND                           (367U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie7_pend_0, Dest signal name: bus_spi_367 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE8_PEND                           (368U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie8_pend_0, Dest signal name: bus_spi_368 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE9_PEND                           (369U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie9_pend_0, Dest signal name: bus_spi_369 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE10_PEND                          (370U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie10_pend_0, Dest signal name: bus_spi_370 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE11_PEND                          (371U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie11_pend_0, Dest signal name: bus_spi_371 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE12_PEND                          (372U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie12_pend_0, Dest signal name: bus_spi_372 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE13_PEND                          (373U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie13_pend_0, Dest signal name: bus_spi_373 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE14_PEND                          (374U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie14_pend_0, Dest signal name: bus_spi_374 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE0_PEND                           (375U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie0_pend_0, Dest signal name: bus_spi_375 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE1_PEND                           (376U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie1_pend_0, Dest signal name: bus_spi_376 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE2_PEND                           (377U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie2_pend_0, Dest signal name: bus_spi_377 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE3_PEND                           (378U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie3_pend_0, Dest signal name: bus_spi_378 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE4_PEND                           (379U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie4_pend_0, Dest signal name: bus_spi_379 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE5_PEND                           (380U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie5_pend_0, Dest signal name: bus_spi_380 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE6_PEND                           (381U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie6_pend_0, Dest signal name: bus_spi_381 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE7_PEND                           (382U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie7_pend_0, Dest signal name: bus_spi_382 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE8_PEND                           (383U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie8_pend_0, Dest signal name: bus_spi_383 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE9_PEND                           (384U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie9_pend_0, Dest signal name: bus_spi_384 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE10_PEND                          (385U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie10_pend_0, Dest signal name: bus_spi_385 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE11_PEND                          (386U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie11_pend_0, Dest signal name: bus_spi_386 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE12_PEND                          (387U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie12_pend_0, Dest signal name: bus_spi_387 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE13_PEND                          (388U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie13_pend_0, Dest signal name: bus_spi_388 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE14_PEND                          (389U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie14_pend_0, Dest signal name: bus_spi_389 */
#define CSL_GIC0_INTR_PCIE0_BUS_PCIE_CPTS_PEND                       (390U)  /* Design details: Source signal name: pcie_g3x2_main_0_bus_pcie_cpts_pend_0, Dest signal name: bus_spi_390 */
#define CSL_GIC0_INTR_PCIE1_BUS_PCIE_CPTS_PEND                       (391U)  /* Design details: Source signal name: pcie_g3x2_main_1_bus_pcie_cpts_pend_0, Dest signal name: bus_spi_391 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_0    (392U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_0, Dest signal name: bus_spi_392 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_1    (393U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_1, Dest signal name: bus_spi_393 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_2    (394U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_2, Dest signal name: bus_spi_394 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_3    (395U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_3, Dest signal name: bus_spi_395 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_4    (396U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_4, Dest signal name: bus_spi_396 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_5    (397U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_5, Dest signal name: bus_spi_397 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_6    (398U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_6, Dest signal name: bus_spi_398 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_7    (399U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_7, Dest signal name: bus_spi_399 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_8    (400U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_8, Dest signal name: bus_spi_400 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_9    (401U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_9, Dest signal name: bus_spi_401 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_10   (402U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_10, Dest signal name: bus_spi_402 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_11   (403U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_11, Dest signal name: bus_spi_403 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_12   (404U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_12, Dest signal name: bus_spi_404 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_13   (405U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_13, Dest signal name: bus_spi_405 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_14   (406U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_14, Dest signal name: bus_spi_406 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_15   (407U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_15, Dest signal name: bus_spi_407 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_16   (408U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_16, Dest signal name: bus_spi_408 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_17   (409U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_17, Dest signal name: bus_spi_409 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_18   (410U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_18, Dest signal name: bus_spi_410 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_19   (411U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_19, Dest signal name: bus_spi_411 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_20   (412U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_20, Dest signal name: bus_spi_412 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_21   (413U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_21, Dest signal name: bus_spi_413 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_22   (414U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_22, Dest signal name: bus_spi_414 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_23   (415U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_23, Dest signal name: bus_spi_415 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_24   (416U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_24, Dest signal name: bus_spi_416 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_25   (417U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_25, Dest signal name: bus_spi_417 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_26   (418U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_26, Dest signal name: bus_spi_418 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_27   (419U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_27, Dest signal name: bus_spi_419 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_28   (420U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_28, Dest signal name: bus_spi_420 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_29   (421U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_29, Dest signal name: bus_spi_421 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_30   (422U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_30, Dest signal name: bus_spi_422 */
#define CSL_GIC0_INTR_MAIN_GPIOMUX_INTROUTER_MAIN_GPIOMUX_INTROUTER_MAIN_0_BUS_OUTP_31   (423U)  /* Design details: Source signal name: main_gpiomux_introuter_main_0_bus_outp_31, Dest signal name: bus_spi_423 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_64                         (448U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_64, Dest signal name: bus_spi_448 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_65                         (449U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_65, Dest signal name: bus_spi_449 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_66                         (450U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_66, Dest signal name: bus_spi_450 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_67                         (451U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_67, Dest signal name: bus_spi_451 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_68                         (452U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_68, Dest signal name: bus_spi_452 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_69                         (453U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_69, Dest signal name: bus_spi_453 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_70                         (454U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_70, Dest signal name: bus_spi_454 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_71                         (455U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_71, Dest signal name: bus_spi_455 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_72                         (456U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_72, Dest signal name: bus_spi_456 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_73                         (457U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_73, Dest signal name: bus_spi_457 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_74                         (458U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_74, Dest signal name: bus_spi_458 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_75                         (459U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_75, Dest signal name: bus_spi_459 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_76                         (460U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_76, Dest signal name: bus_spi_460 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_77                         (461U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_77, Dest signal name: bus_spi_461 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_78                         (462U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_78, Dest signal name: bus_spi_462 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_79                         (463U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_79, Dest signal name: bus_spi_463 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_80                         (464U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_80, Dest signal name: bus_spi_464 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_81                         (465U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_81, Dest signal name: bus_spi_465 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_82                         (466U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_82, Dest signal name: bus_spi_466 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_83                         (467U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_83, Dest signal name: bus_spi_467 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_84                         (468U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_84, Dest signal name: bus_spi_468 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_85                         (469U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_85, Dest signal name: bus_spi_469 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_86                         (470U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_86, Dest signal name: bus_spi_470 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_87                         (471U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_87, Dest signal name: bus_spi_471 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_88                         (472U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_88, Dest signal name: bus_spi_472 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_89                         (473U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_89, Dest signal name: bus_spi_473 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_90                         (474U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_90, Dest signal name: bus_spi_474 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_91                         (475U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_91, Dest signal name: bus_spi_475 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_92                         (476U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_92, Dest signal name: bus_spi_476 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_93                         (477U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_93, Dest signal name: bus_spi_477 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_94                         (478U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_94, Dest signal name: bus_spi_478 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_95                         (479U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_95, Dest signal name: bus_spi_479 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_96                         (480U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_96, Dest signal name: bus_spi_480 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_97                         (481U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_97, Dest signal name: bus_spi_481 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_98                         (482U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_98, Dest signal name: bus_spi_482 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_99                         (483U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_99, Dest signal name: bus_spi_483 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_100                        (484U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_100, Dest signal name: bus_spi_484 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_101                        (485U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_101, Dest signal name: bus_spi_485 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_102                        (486U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_102, Dest signal name: bus_spi_486 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_103                        (487U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_103, Dest signal name: bus_spi_487 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_104                        (488U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_104, Dest signal name: bus_spi_488 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_105                        (489U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_105, Dest signal name: bus_spi_489 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_106                        (490U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_106, Dest signal name: bus_spi_490 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_107                        (491U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_107, Dest signal name: bus_spi_491 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_108                        (492U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_108, Dest signal name: bus_spi_492 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_109                        (493U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_109, Dest signal name: bus_spi_493 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_110                        (494U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_110, Dest signal name: bus_spi_494 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_111                        (495U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_111, Dest signal name: bus_spi_495 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_112                        (496U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_112, Dest signal name: bus_spi_496 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_113                        (497U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_113, Dest signal name: bus_spi_497 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_114                        (498U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_114, Dest signal name: bus_spi_498 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_115                        (499U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_115, Dest signal name: bus_spi_499 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_116                        (500U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_116, Dest signal name: bus_spi_500 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_117                        (501U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_117, Dest signal name: bus_spi_501 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_118                        (502U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_118, Dest signal name: bus_spi_502 */
#define CSL_GIC0_INTR_NAVSS0_BUS_A53_PEND_119                        (503U)  /* Design details: Source signal name: navss256l_main_0_bus_a53_pend_119, Dest signal name: bus_spi_503 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_0    (512U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_0, Dest signal name: bus_spi_512 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_1    (513U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_1, Dest signal name: bus_spi_513 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_2    (514U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_2, Dest signal name: bus_spi_514 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_3    (515U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_3, Dest signal name: bus_spi_515 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_4    (516U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_4, Dest signal name: bus_spi_516 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_5    (517U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_5, Dest signal name: bus_spi_517 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_6    (518U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_6, Dest signal name: bus_spi_518 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_7    (519U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_7, Dest signal name: bus_spi_519 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_8    (520U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_8, Dest signal name: bus_spi_520 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_9    (521U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_9, Dest signal name: bus_spi_521 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_10   (522U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_10, Dest signal name: bus_spi_522 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_11   (523U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_11, Dest signal name: bus_spi_523 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_12   (524U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_12, Dest signal name: bus_spi_524 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_13   (525U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_13, Dest signal name: bus_spi_525 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_14   (526U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_14, Dest signal name: bus_spi_526 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_15   (527U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_15, Dest signal name: bus_spi_527 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_16   (528U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_16, Dest signal name: bus_spi_528 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_17   (529U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_17, Dest signal name: bus_spi_529 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_18   (530U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_18, Dest signal name: bus_spi_530 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_19   (531U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_19, Dest signal name: bus_spi_531 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_20   (532U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_20, Dest signal name: bus_spi_532 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_21   (533U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_21, Dest signal name: bus_spi_533 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_22   (534U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_22, Dest signal name: bus_spi_534 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_23   (535U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_23, Dest signal name: bus_spi_535 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_24   (536U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_24, Dest signal name: bus_spi_536 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_25   (537U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_25, Dest signal name: bus_spi_537 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_26   (538U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_26, Dest signal name: bus_spi_538 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_27   (539U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_27, Dest signal name: bus_spi_539 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_28   (540U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_28, Dest signal name: bus_spi_540 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_29   (541U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_29, Dest signal name: bus_spi_541 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_30   (542U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_30, Dest signal name: bus_spi_542 */
#define CSL_GIC0_INTR_COMPUTE_CLUSTER0_BUS_SOC_EVENTS_OUT_LEVEL_31   (543U)  /* Design details: Source signal name: compute_cluster_maxwell_tb_vdc_main_0_bus_soc_events_out_level_31, Dest signal name: bus_spi_543 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_0     (544U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_0, Dest signal name: bus_spi_544 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_1     (545U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_1, Dest signal name: bus_spi_545 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_2     (546U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_2, Dest signal name: bus_spi_546 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_3     (547U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_3, Dest signal name: bus_spi_547 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_4     (548U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_4, Dest signal name: bus_spi_548 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_5     (549U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_5, Dest signal name: bus_spi_549 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_6     (550U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_6, Dest signal name: bus_spi_550 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_7     (551U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_7, Dest signal name: bus_spi_551 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_8     (552U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_8, Dest signal name: bus_spi_552 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_9     (553U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_9, Dest signal name: bus_spi_553 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_10    (554U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_10, Dest signal name: bus_spi_554 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_11    (555U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_11, Dest signal name: bus_spi_555 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_12    (556U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_12, Dest signal name: bus_spi_556 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_13    (557U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_13, Dest signal name: bus_spi_557 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_14    (558U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_14, Dest signal name: bus_spi_558 */
#define CSL_GIC0_INTR_CMP_EVENT_INTROUTER_CMP_EVENT_INTROUTER_MAIN_0_BUS_OUTP_15    (559U)  /* Design details: Source signal name: cmp_event_introuter_main_0_bus_outp_15, Dest signal name: bus_spi_559 */
#define CSL_GIC0_INTR_CBASS0_BUS_LPSC_PER_COMMON_ERR_INTR_0          (566U)  /* Design details: Source signal name: m4_main_cbass_main_0_bus_LPSC_per_common_err_intr_0, Dest signal name: bus_spi_566 */
#define CSL_GIC0_INTR_CBASS_DEBUG0_BUS_LPSC_MAIN_DEBUG_ERR_INTR_0    (567U)  /* Design details: Source signal name: m4_main_dbg_cbass_main_0_bus_LPSC_main_debug_err_intr_0, Dest signal name: bus_spi_567 */
#define CSL_GIC0_INTR_CBASS_FW0_BUS_LPSC_MAIN_INFRA_ERR_INTR_0       (568U)  /* Design details: Source signal name: m4_main_fw_cbass_main_0_bus_LPSC_main_infra_err_intr_0, Dest signal name: bus_spi_568 */
#define CSL_GIC0_INTR_CBASS_INFRA0_BUS_LPSC_MAIN_INFRA_ERR_INTR_0    (569U)  /* Design details: Source signal name: m4_main_infra_cbass_main_0_bus_LPSC_main_infra_err_intr_0, Dest signal name: bus_spi_569 */
#define CSL_GIC0_INTR_MCU_MCAN0_BUS_MCANSS_MCAN_LVL_INT_0            (576U)  /* Design details: Source signal name: mcanss_mcu_0_bus_mcanss_mcan_lvl_int_0, Dest signal name: bus_spi_576 */
#define CSL_GIC0_INTR_MCU_MCAN0_BUS_MCANSS_MCAN_LVL_INT_1            (577U)  /* Design details: Source signal name: mcanss_mcu_0_bus_mcanss_mcan_lvl_int_1, Dest signal name: bus_spi_577 */
#define CSL_GIC0_INTR_MCU_MCAN0_BUS_MCANSS_EXT_TS_ROLLOVER_LVL_INT   (578U)  /* Design details: Source signal name: mcanss_mcu_0_bus_mcanss_ext_ts_rollover_lvl_int_0, Dest signal name: bus_spi_578 */
#define CSL_GIC0_INTR_MCU_MCAN1_BUS_MCANSS_MCAN_LVL_INT_0            (579U)  /* Design details: Source signal name: mcanss_mcu_1_bus_mcanss_mcan_lvl_int_0, Dest signal name: bus_spi_579 */
#define CSL_GIC0_INTR_MCU_MCAN1_BUS_MCANSS_MCAN_LVL_INT_1            (580U)  /* Design details: Source signal name: mcanss_mcu_1_bus_mcanss_mcan_lvl_int_1, Dest signal name: bus_spi_580 */
#define CSL_GIC0_INTR_MCU_MCAN1_BUS_MCANSS_EXT_TS_ROLLOVER_LVL_INT   (581U)  /* Design details: Source signal name: mcanss_mcu_1_bus_mcanss_ext_ts_rollover_lvl_int_0, Dest signal name: bus_spi_581 */
#define CSL_GIC0_INTR_MCU_FSS0_BUS_OSPI0_LVL_INTR                    (584U)  /* Design details: Source signal name: fss_mcu_0_bus_ospi0_lvl_intr_0, Dest signal name: bus_spi_584 */
#define CSL_GIC0_INTR_MCU_FSS0_BUS_OSPI1_LVL_INTR                    (585U)  /* Design details: Source signal name: fss_mcu_0_bus_ospi1_lvl_intr_0, Dest signal name: bus_spi_585 */
#define CSL_GIC0_INTR_MCU_FSS0_BUS_HPB_INTR                          (586U)  /* Design details: Source signal name: fss_mcu_0_bus_hpb_intr_0, Dest signal name: bus_spi_586 */
#define CSL_GIC0_INTR_MCU_FSS0_BUS_OTFA_INTR_ERR_PEND                (587U)  /* Design details: Source signal name: fss_mcu_0_bus_otfa_intr_err_pend_0, Dest signal name: bus_spi_587 */
#define CSL_GIC0_INTR_MCU_FSS0_BUS_FSAS_ECC_INTR_ERR_PEND            (588U)  /* Design details: Source signal name: fss_mcu_0_bus_fsas_ecc_intr_err_pend_0, Dest signal name: bus_spi_588 */
#define CSL_GIC0_INTR_MCU_MCSPI0_BUS_INTR_SPI                        (592U)  /* Design details: Source signal name: spi_mcu_0_bus_intr_spi_0, Dest signal name: bus_spi_592 */
#define CSL_GIC0_INTR_MCU_MCSPI1_BUS_INTR_SPI                        (593U)  /* Design details: Source signal name: spi_mcu_1_bus_intr_spi_0, Dest signal name: bus_spi_593 */
#define CSL_GIC0_INTR_MCU_MCSPI2_BUS_INTR_SPI                        (594U)  /* Design details: Source signal name: spi_mcu_2_bus_intr_spi_0, Dest signal name: bus_spi_594 */
#define CSL_GIC0_INTR_MCU_I2C0_BUS_POINTRPEND                        (596U)  /* Design details: Source signal name: mshsi2c_mcu_0_bus_pointrpend_0, Dest signal name: bus_spi_596 */
#define CSL_GIC0_INTR_MCU_USART0_BUS_USART_IRQ                       (597U)  /* Design details: Source signal name: usart_mcu_0_bus_usart_irq_0, Dest signal name: bus_spi_597 */
#define CSL_GIC0_INTR_MCU_CPSW0_BUS_STAT_PEND                        (600U)  /* Design details: Source signal name: cpsw_2guss_mcu_0_bus_stat_pend_0, Dest signal name: bus_spi_600 */
#define CSL_GIC0_INTR_MCU_CPSW0_BUS_EVNT_PEND                        (602U)  /* Design details: Source signal name: cpsw_2guss_mcu_0_bus_evnt_pend_0, Dest signal name: bus_spi_602 */
#define CSL_GIC0_INTR_MCU_CPSW0_BUS_MDIO_PEND                        (603U)  /* Design details: Source signal name: cpsw_2guss_mcu_0_bus_mdio_pend_0, Dest signal name: bus_spi_603 */
#define CSL_GIC0_INTR_MCU_ARMSS0_BUS_CPU0_PMU                        (608U)  /* Design details: Source signal name: pulsar_sl_mcu_0_bus_cpu0_pmu_0, Dest signal name: bus_spi_608 */
#define CSL_GIC0_INTR_MCU_ARMSS0_BUS_CPU1_PMU                        (609U)  /* Design details: Source signal name: pulsar_sl_mcu_0_bus_cpu1_pmu_0, Dest signal name: bus_spi_609 */
#define CSL_GIC0_INTR_MCU_DEBUGSS0_BUS_AQCMPINTR_LEVEL               (610U)  /* Design details: Source signal name: k3_mcu_debug_cell_main_0_bus_aqcmpintr_level_0, Dest signal name: bus_spi_610 */
#define CSL_GIC0_INTR_MCU_DEBUGSS0_BUS_CTM_LEVEL                     (611U)  /* Design details: Source signal name: k3_mcu_debug_cell_main_0_bus_ctm_level_0, Dest signal name: bus_spi_611 */
#define CSL_GIC0_INTR_MCU_ADC0_BUS_GEN_LEVEL                         (612U)  /* Design details: Source signal name: adc12_gs80_mcu_0_bus_gen_level_0, Dest signal name: bus_spi_612 */
#define CSL_GIC0_INTR_MCU_ADC1_BUS_GEN_LEVEL                         (613U)  /* Design details: Source signal name: adc12_gs80_mcu_1_bus_gen_level_0, Dest signal name: bus_spi_613 */
#define CSL_GIC0_INTR_MCU_CBASS0_BUS_LPSC_MCU_COMMON_ERR_INTR_0      (620U)  /* Design details: Source signal name: m4_mcu_cbass_mcu_0_bus_LPSC_mcu_common_err_intr_0, Dest signal name: bus_spi_620 */
#define CSL_GIC0_INTR_MCU_CBASS_DEBUG0_BUS_LPSC_MCU_DEBUG_ERR_INTR_0 (621U)  /* Design details: Source signal name: m4_mcu_dbg_cbass_mcu_0_bus_LPSC_MCU_Debug_err_intr_0, Dest signal name: bus_spi_621 */
#define CSL_GIC0_INTR_MCU_CBASS_FW0_BUS_LPSC_MCU_COMMON_ERR_INTR_0   (622U)  /* Design details: Source signal name: m4_mcu_fw_cbass_mcu_0_bus_LPSC_MCU_common_err_intr_0, Dest signal name: bus_spi_622 */
#define CSL_GIC0_INTR_WKUP_DMSC0_BUS_SEC_OUT_0                       (708U)  /* Design details: Source signal name: dmsc_wkup_0_bus_sec_out_0, Dest signal name: bus_spi_708 */
#define CSL_GIC0_INTR_WKUP_DMSC0_BUS_SEC_OUT_1                       (709U)  /* Design details: Source signal name: dmsc_wkup_0_bus_sec_out_1, Dest signal name: bus_spi_709 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_0                (712U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_0, Dest signal name: bus_spi_712 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_1                (713U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_1, Dest signal name: bus_spi_713 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_2                (714U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_2, Dest signal name: bus_spi_714 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_3                (715U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_3, Dest signal name: bus_spi_715 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_4                (716U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_4, Dest signal name: bus_spi_716 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_5                (717U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_5, Dest signal name: bus_spi_717 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_6                (718U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_6, Dest signal name: bus_spi_718 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_7                (719U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_7, Dest signal name: bus_spi_719 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_8                (720U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_8, Dest signal name: bus_spi_720 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_9                (721U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_9, Dest signal name: bus_spi_721 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_10               (722U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_10, Dest signal name: bus_spi_722 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_11               (723U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_11, Dest signal name: bus_spi_723 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_12               (724U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_12, Dest signal name: bus_spi_724 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_13               (725U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_13, Dest signal name: bus_spi_725 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_14               (726U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_14, Dest signal name: bus_spi_726 */
#define CSL_GIC0_INTR_WKUP_GPIOMUX_INTRTR0_BUS_OUTP_15               (727U)  /* Design details: Source signal name: wkup_gpiomux_introuter_wkup_0_bus_outp_15, Dest signal name: bus_spi_727 */
#define CSL_GIC0_INTR_WKUP_I2C0_BUS_POINTRPEND                       (728U)  /* Design details: Source signal name: mshsi2c_wkup_0_bus_pointrpend_0, Dest signal name: bus_spi_728 */
#define CSL_GIC0_INTR_WKUP_USART0_BUS_USART_IRQ                      (729U)  /* Design details: Source signal name: usart_wkup_0_bus_usart_irq_0, Dest signal name: bus_spi_729 */
#define CSL_GIC0_INTR_WKUP_CBASS0_BUS_LPSC_WKUP_COMMON_ERR_INTR_0    (736U)  /* Design details: Source signal name: m4_wkup_cbass_wkup_0_bus_LPSC_wkup_common_err_intr_0, Dest signal name: bus_spi_736 */
#define CSL_GIC0_INTR_WKUP_CBASS_FW0_BUS_LPSC_WKUP_COMMON_ERR_INTR_0 (737U)  /* Design details: Source signal name: m4_wkup_fw_cbass_wkup_0_bus_LPSC_wkup_common_err_intr_0, Dest signal name: bus_spi_737 */

#ifdef __cplusplus
}
#endif
#endif /* CSLR_INTR_GIC0_H_ */
