#ifndef INPUT_CONFIG_H_
#define INPUT_CONFIG_H_

#define FE_STACKING_CHANNELS 6
#define FE_VARIABLES 6
#define FE_STACKING_FRAME_WIDTH 3
#define FE_HL 1
#define FE_FRAME_SIZE 3
#define FE_FEATURE_SIZE_PER_FRAME 3
#define FE_NN_OUT_SIZE 1

#endif /* INPUT_CONFIG_H_ */
