/*
 *   Copyright (c) Texas Instruments Incorporated 2022
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef SDL_DSS_L3_HW_H_
#define SDL_DSS_L3_HW_H_

#ifdef __cplusplus
extern "C"
{
#endif

/****************************************************************************************************
* Register Definitions
****************************************************************************************************/
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START                                   (0x00000098U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS                                  (0x0000009CU)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE                                    (0x000000A0U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL                                       (0x00000800U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0                              (0x00000804U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT1                              (0x00000808U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL                              (0x00000830U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI                                (0x00000834U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR                               (0x00000838U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0                    (0x0000083CU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1                    (0x00000840U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD                      (0x00000844U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE                    (0x00000848U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ                     (0x0000084CU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP                (0x00000850U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL                              (0x00000854U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI                                (0x00000858U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR                               (0x0000085CU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0                    (0x00000860U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1                    (0x00000864U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD                      (0x00000868U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE                    (0x0000086CU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ                     (0x00000870U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP                (0x00000874U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL                              (0x00000878U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI                                (0x0000087CU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR                               (0x00000880U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0                    (0x00000884U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1                    (0x00000888U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD                      (0x0000088CU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE                    (0x00000890U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ                     (0x00000894U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP                (0x00000898U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL                              (0x0000089CU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI                                (0x000008A0U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR                               (0x000008A4U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0                    (0x000008A8U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1                    (0x000008ACU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD                      (0x000008B0U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE                    (0x000008B4U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ                     (0x000008B8U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP                (0x000008BCU)

/****************************************************************************************************
* Field Definition Macros
****************************************************************************************************/
/* DSS_BUS_SAFETY_CTRL */

#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_MASK       (0x00000007U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_SHIFT      (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_RESETVAL   (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_ENABLE_MAX        (0x00000007U)

#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_CLK_DISABLE_MASK  (0x00000070U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_CLK_DISABLE_SHIFT (0x00000004U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_CLK_DISABLE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_DSS_BUS_SAFETY_CTRL_CLK_DISABLE_MAX   (0x00000007U)

#define SDL_DSS_CTRL_DSS_BUS_SAFETY_CTRL_RESETVAL                              (0x00000000U)

/* DSS_L3RAM_MEMINIT_START */

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM0_MEMINIT_START_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM0_MEMINIT_START_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM0_MEMINIT_START_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM0_MEMINIT_START_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM1_MEMINIT_START_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM1_MEMINIT_START_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM1_MEMINIT_START_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM1_MEMINIT_START_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM2_MEMINIT_START_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM2_MEMINIT_START_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM2_MEMINIT_START_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM2_MEMINIT_START_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM3_MEMINIT_START_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM3_MEMINIT_START_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM3_MEMINIT_START_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_DSS_L3RAM_MEMINIT_START_L3RAM3_MEMINIT_START_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_START_RESETVAL                          (0x00000000U)

/* DSS_L3RAM_MEMINIT_STATUS */

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM0_MEMINIT_STATUS_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM0_MEMINIT_STATUS_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM0_MEMINIT_STATUS_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM0_MEMINIT_STATUS_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM1_MEMINIT_STATUS_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM1_MEMINIT_STATUS_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM1_MEMINIT_STATUS_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM1_MEMINIT_STATUS_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM2_MEMINIT_STATUS_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM2_MEMINIT_STATUS_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM2_MEMINIT_STATUS_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM2_MEMINIT_STATUS_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM3_MEMINIT_STATUS_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM3_MEMINIT_STATUS_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM3_MEMINIT_STATUS_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_DSS_L3RAM_MEMINIT_STATUS_L3RAM3_MEMINIT_STATUS_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_STATUS_RESETVAL                         (0x00000000U)

/* DSS_L3RAM_MEMINIT_DONE */

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM0_MEMINIT_DONE_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM0_MEMINIT_DONE_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM0_MEMINIT_DONE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM0_MEMINIT_DONE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM1_MEMINIT_DONE_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM1_MEMINIT_DONE_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM1_MEMINIT_DONE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM1_MEMINIT_DONE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM2_MEMINIT_DONE_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM2_MEMINIT_DONE_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM2_MEMINIT_DONE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM2_MEMINIT_DONE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM3_MEMINIT_DONE_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM3_MEMINIT_DONE_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM3_MEMINIT_DONE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_DSS_L3RAM_MEMINIT_DONE_L3RAM3_MEMINIT_DONE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3RAM_MEMINIT_DONE_RESETVAL                           (0x00000000U)

/* DSS_BUS_SAFETY_SEC_ERR_STAT0 */
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKA_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKA_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKA_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKA_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKB_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKB_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKB_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKB_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKC_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKC_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKC_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKD_MASK (0x00000010U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKD_SHIFT (0x00000004U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKD_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_BUS_SAFETY_SEC_ERR_STAT0_DSS_L3_BANKD_MAX (0x00000001U)

/* DSS_L3_BANKA_BUS_SAFETY_CTRL */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_TYPE_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_TYPE_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_TYPE_RESETVAL (0x0000001FU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_TYPE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_CTRL_RESETVAL                     (0x001F0007U)

/* DSS_L3_BANKA_BUS_SAFETY_FI */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SEC_MASK (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SEC_SHIFT (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SEC_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DED_MASK (0x00000020U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DED_SHIFT (0x00000005U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DED_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DATA_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DATA_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_DATA_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_MAIN_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_MAIN_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_MAIN_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SAFE_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SAFE_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_DSS_L3_BANKA_BUS_SAFETY_FI_SAFE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_FI_RESETVAL                       (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_ERR_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_ERR_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_ERR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_ERR_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_CHECK_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_CHECK_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_CHECK_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_COMP_CHECK_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_SEC_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_SEC_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_DED_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_DSS_L3_BANKA_BUS_SAFETY_ERR_DED_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_RESETVAL                      (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0 */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D0_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D0_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D0_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D0_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D1_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D1_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D1_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D1_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D2_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D2_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D2_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D2_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D3_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D3_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D3_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_D3_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA0_RESETVAL           (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1 */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D4_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D4_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D4_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D4_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D5_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D5_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D5_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D5_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D6_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D6_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D6_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D6_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D7_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D7_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D7_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_D7_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_DATA1_RESETVAL           (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_CMD_RESETVAL             (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITE_RESETVAL           (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_READ_RESETVAL            (0x00000000U)

/* DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP */

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKA_BUS_SAFETY_ERR_STAT_WRITERESP_RESETVAL       (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_CTRL */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_TYPE_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_TYPE_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_TYPE_RESETVAL (0x0000001FU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_TYPE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_CTRL_RESETVAL                     (0x001F0007U)

/* DSS_L3_BANKB_BUS_SAFETY_FI */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SEC_MASK (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SEC_SHIFT (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SEC_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DED_MASK (0x00000020U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DED_SHIFT (0x00000005U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DED_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DATA_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DATA_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_DATA_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_MAIN_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_MAIN_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_MAIN_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SAFE_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SAFE_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_DSS_L3_BANKB_BUS_SAFETY_FI_SAFE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_FI_RESETVAL                       (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_ERR_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_ERR_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_ERR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_ERR_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_CHECK_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_CHECK_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_CHECK_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_COMP_CHECK_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_SEC_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_SEC_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_DED_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_DSS_L3_BANKB_BUS_SAFETY_ERR_DED_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_RESETVAL                      (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0 */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D0_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D0_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D0_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D0_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D1_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D1_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D1_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D1_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D2_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D2_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D2_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D2_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D3_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D3_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D3_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_D3_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA0_RESETVAL           (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1 */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D4_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D4_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D4_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D4_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D5_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D5_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D5_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D5_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D6_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D6_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D6_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D6_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D7_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D7_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D7_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_D7_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_DATA1_RESETVAL           (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_CMD_RESETVAL             (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITE_RESETVAL           (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_READ_RESETVAL            (0x00000000U)

/* DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP */

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKB_BUS_SAFETY_ERR_STAT_WRITERESP_RESETVAL       (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_CTRL */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_TYPE_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_TYPE_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_TYPE_RESETVAL (0x0000001FU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_TYPE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_CTRL_RESETVAL                     (0x001F0007U)

/* DSS_L3_BANKC_BUS_SAFETY_FI */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SEC_MASK (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SEC_SHIFT (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SEC_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DED_MASK (0x00000020U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DED_SHIFT (0x00000005U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DED_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DATA_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DATA_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_DATA_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_MAIN_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_MAIN_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_MAIN_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SAFE_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SAFE_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_DSS_L3_BANKC_BUS_SAFETY_FI_SAFE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_FI_RESETVAL                       (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_ERR_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_ERR_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_ERR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_ERR_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_CHECK_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_CHECK_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_CHECK_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_COMP_CHECK_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_SEC_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_SEC_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_DED_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_DSS_L3_BANKC_BUS_SAFETY_ERR_DED_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_RESETVAL                      (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0 */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D0_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D0_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D0_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D0_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D1_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D1_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D1_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D1_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D2_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D2_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D2_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D2_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D3_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D3_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D3_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_D3_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA0_RESETVAL           (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1 */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D4_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D4_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D4_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D4_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D5_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D5_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D5_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D5_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D6_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D6_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D6_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D6_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D7_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D7_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D7_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_D7_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_DATA1_RESETVAL           (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_CMD_RESETVAL             (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITE_RESETVAL           (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_READ_RESETVAL            (0x00000000U)

/* DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP */

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKC_BUS_SAFETY_ERR_STAT_WRITERESP_RESETVAL       (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_CTRL */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ENABLE_MASK (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ENABLE_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ENABLE_RESETVAL (0x00000007U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ENABLE_MAX (0x00000007U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ERR_CLEAR_MASK (0x00000100U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ERR_CLEAR_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ERR_CLEAR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_ERR_CLEAR_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_TYPE_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_TYPE_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_TYPE_RESETVAL (0x0000001FU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_TYPE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_CTRL_RESETVAL                     (0x001F0007U)

/* DSS_L3_BANKD_BUS_SAFETY_FI */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_MASK (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_MASK (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_SHIFT (0x00000001U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MASK (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_SHIFT (0x00000002U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_MAIN_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MASK (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_SHIFT (0x00000003U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_GLOBAL_SAFE_REQ_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SEC_MASK (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SEC_SHIFT (0x00000004U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SEC_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DED_MASK (0x00000020U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DED_SHIFT (0x00000005U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DED_MAX (0x00000001U)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DATA_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DATA_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DATA_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_DATA_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_MAIN_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_MAIN_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_MAIN_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_MAIN_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SAFE_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SAFE_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SAFE_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_DSS_L3_BANKD_BUS_SAFETY_FI_SAFE_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_FI_RESETVAL                       (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_ERR_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_ERR_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_ERR_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_ERR_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_CHECK_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_CHECK_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_CHECK_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_COMP_CHECK_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_SEC_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_SEC_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_SEC_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_SEC_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_DED_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_DED_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_DED_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_DSS_L3_BANKD_BUS_SAFETY_ERR_DED_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_RESETVAL                      (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0 */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D0_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D0_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D0_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D0_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D1_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D1_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D1_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D1_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D2_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D2_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D2_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D2_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D3_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D3_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D3_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_D3_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA0_RESETVAL           (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1 */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D4_MASK (0x000000FFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D4_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D4_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D4_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D5_MASK (0x0000FF00U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D5_SHIFT (0x00000008U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D5_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D5_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D6_MASK (0x00FF0000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D6_SHIFT (0x00000010U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D6_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D6_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D7_MASK (0xFF000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D7_SHIFT (0x00000018U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D7_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_D7_MAX (0x000000FFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_DATA1_RESETVAL           (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_CMD_RESETVAL             (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITE_RESETVAL           (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_READ_RESETVAL            (0x00000000U)

/* DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP */

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MASK (0xFFFFFFFFU)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_SHIFT (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_RESETVAL (0x00000000U)
#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_STAT_MAX (0xFFFFFFFFU)

#define SDL_DSS_CTRL_DSS_L3_BANKD_BUS_SAFETY_ERR_STAT_WRITERESP_RESETVAL       (0x00000000U)


#ifdef __cplusplus
}
#endif
#endif  /* SDL_DSS_L3_HW_H_ */
