/*
 * SDL ECC
 *
 * Software Diagnostics Library module for ECC
 *
 *  Copyright (c) Texas Instruments Incorporated 2022-2023
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef INCLUDE_SDL_ECC_SOC_H_
#define INCLUDE_SDL_ECC_SOC_H_

#include <stdint.h>
#include <sdl/sdl_ecc.h>
#include <sdl/ecc/sdl_ip_ecc.h>
#include <sdl/include/sdl_types.h>
#include <sdl/esm/soc/am273x/sdl_esm_core.h>
#include <sdl/ecc/sdl_ecc_priv.h>
#include <sdl/include/am273x/sdlr_soc_ecc_aggr.h>
#include <sdl/include/am273x/soc_config.h>
#include <sdl/include/am273x/sdlr_intr_esm_dss.h>
#include <sdl/include/am273x/sdlr_intr_esm_mss.h>
#include <sdl/include/am273x/sdlr_soc_baseaddress.h>


#define SDL_ECC_WIDTH_UNDEFINED 0x1

/* define Max memEntries for each aggregator (i.e. the number of RAM ID's with * Wrapper type) */
#define SDL_R5FSS0_CORE0_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES (28U)
#define SDL_R5FSS0_CORE1_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES (28U)
#define SDL_MSS_ECC_AGG_MSS_RAM_IDS_TOTAL_ENTRIES 		(8U)
#define SDL_DSS_ECC_AGG_RAM_IDS_TOTAL_ENTRIES 			(22U)
#define SDL_MSS_MCANA_ECC_RAM_IDS_TOTAL_ENTRIES 		(1U)
#define SDL_MSS_MCANB_ECC_RAM_IDS_TOTAL_ENTRIES 		(1U)
#define SDL_CPSW3GCSS_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES    (8U)
#define SDL_ECC_Base_Address_TOTAL_ENTRIES              (7U)

#define SDL_MSS_CPSW0_ECC_U_BASE					    (SDL_MSS_CPSW_U_BASE + 0x3F000u)
/* define parity control register addresses */
#define SDL_TCM_PARITY_ERRFRC	    				(0x02120144)

/* MSS TPCC */
#define TPCC_PARITY_CTRL							(0x0212015Cu)
#define SDL_R5FSS0_CORE0_TPCC0_PARITY_STATUS		(0x02120160u)
/* DSS TPCC */
#define DSS_TPCCA_PARITY_CTRL						(0x060200BCU)
#define DSS_TPCCB_PARITY_CTRL						(0x060200C0U)
#define DSS_TPCCC_PARITY_CTRL						(0x060200C4U)
#define SDL_R5FSS0_CORE0_TPCCA_PARITY_STATUS		(0x060200C8U)
#define SDL_R5FSS0_CORE0_TPCCB_PARITY_STATUS		(0x060200CCU)
#define SDL_R5FSS0_CORE0_TPCCC_PARITY_STATUS		(0x060200D0U)
/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_R5FSS0_CORE0_ECC_AGGR
 * -----------------------------------------------------------------------------------
 */
static const SDL_MemConfig_t SDL_R5FSS0_CORE0_ECC_AGGR_MemEntries[SDL_R5FSS0_CORE0_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM0_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM1_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM2_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM2_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM3_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM3_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK0_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK0_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK1_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK1_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK2_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK2_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK3_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK3_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM0_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM1_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM2_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM2_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM3_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM3_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDIRTY_RAM_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDIRTY_RAM_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDIRTY_RAM_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM0_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM1_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM2_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM2_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM3_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM3_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM4_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM4_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM4_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM5_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM5_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM5_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM6_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM6_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM6_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM7_RAM_ID, 0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM7_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM7_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK0_RAM_ID, 0x0u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK0_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK1_RAM_ID, 0x00u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK1_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK0_RAM_ID, 0x00080000u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK0_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK1_RAM_ID, 0x00080000u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK1_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK0_RAM_ID, 0x00080000u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK0_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK1_RAM_ID, 0x00080000u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK1_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_KS_VIM_RAMECC_RAM_ID, 0x02082000u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_KS_VIM_RAMECC_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_KS_VIM_RAMECC_ROW_WIDTH, ((bool)true) },
};

/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_R5FSS0_CORE1_ECC_AGGR
 * -----------------------------------------------------------------------------------
 */
static const SDL_MemConfig_t SDL_R5FSS0_CORE1_ECC_AGGR_MemEntries[SDL_R5FSS0_CORE1_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM0_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM1_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM2_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM2_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM3_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM3_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK0_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK0_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK1_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK1_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK2_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK2_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK3_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK3_RAM_SIZE, 8u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM0_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM1_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM2_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM2_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM3_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM3_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDIRTY_RAM_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDIRTY_RAM_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDIRTY_RAM_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM0_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM0_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM1_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM1_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM2_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM2_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM2_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM3_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM3_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM3_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM4_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM4_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM4_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM5_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM5_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM5_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM6_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM6_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM6_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM7_RAM_ID, 0u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM7_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM7_ROW_WIDTH, ((bool)false) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK0_RAM_ID, 0x4000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK0_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK1_RAM_ID, 0x4000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK1_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK0_RAM_ID, 0x00084000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK0_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK1_RAM_ID, 0x00084000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK1_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK0_RAM_ID, 0x00084000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK0_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK0_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK1_RAM_ID, 0x00084000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK1_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK1_ROW_WIDTH, ((bool)true) },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_KS_VIM_RAMECC_RAM_ID, 0x020A2000u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_KS_VIM_RAMECC_RAM_SIZE, 4u,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_KS_VIM_RAMECC_ROW_WIDTH, ((bool)true) },
};

/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_MSS_ECC_AGG_MSS
 * -----------------------------------------------------------------------------------
 */
const SDL_MemConfig_t SDL_MSS_ECC_AGG_MSS_MemEntries[SDL_MSS_ECC_AGG_MSS_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_MSS_ECC_AGG_MSS_MSS_L2RAMA_ECC_RAM_ID, 0x10200000u,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMA_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMA_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_MSS_ECC_AGG_MSS_MSS_L2RAMB_ECC_RAM_ID,  0x10280000u,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMB_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMB_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_MSS_ECC_AGG_MSS_MSS_MBOX_ECC_RAM_ID, 0xC5000000u,
      SDL_MSS_ECC_AGG_MSS_MSS_MBOX_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_MBOX_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_MSS_ECC_AGG_MSS_MSS_RETRAM_ECC_RAM_ID, 0xC5010000u,
      SDL_MSS_ECC_AGG_MSS_MSS_RETRAM_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_RETRAM_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_MSS_ECC_AGG_MSS_MSS_GPADC_DATA_RAM_ECC_RAM_ID, 0xC5030000u,
      SDL_MSS_ECC_AGG_MSS_MSS_GPADC_DATA_RAM_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_GPADC_DATA_RAM_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A0_ECC_RAM_ID, 0u,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A0_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A0_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A1_ECC_RAM_ID, 0u,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A1_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A1_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_MSS_ECC_AGG_MSS_MSS_TPTC_B0_ECC_RAM_ID, 0u,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_B0_ECC_RAM_SIZE, 8u,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_B0_ECC_ROW_WIDTH, ((bool)false) },
};

/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_DSS_ECC_AGG
 * -----------------------------------------------------------------------------------
 */
const SDL_MemConfig_t SDL_DSS_ECC_AGG_MemEntries[SDL_DSS_ECC_AGG_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_DSS_ECC_AGG_DSS_L3RAMA_ECC_RAM_ID, 0x88000000u,
      SDL_DSS_ECC_AGG_DSS_L3RAMA_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_L3RAMA_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_L3RAMB_ECC_RAM_ID, 0x88100000u,
      SDL_DSS_ECC_AGG_DSS_L3RAMB_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_L3RAMB_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_L3RAMC_ECC_RAM_ID, 0x88200000u,
      SDL_DSS_ECC_AGG_DSS_L3RAMC_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_L3RAMC_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_L3RAMD_ECC_RAM_ID, 0x88300000u,
      SDL_DSS_ECC_AGG_DSS_L3RAMD_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_L3RAMD_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_MAILBOX_ECC_RAM_ID, 0x83100000u,
      SDL_DSS_ECC_AGG_DSS_MAILBOX_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_MAILBOX_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_CM4_RAM_B0_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B0_ECC_RAM_SIZE, 4u,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B0_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_CM4_RAM_B1_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B1_ECC_RAM_SIZE, 4u,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B1_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_CM4_RAM_B2_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B2_ECC_RAM_SIZE, 4u,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B2_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_CM4_MAILBOX_ECC_RAM_ID, 0x48000000u,
      SDL_DSS_ECC_AGG_DSS_CM4_MAILBOX_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_CM4_MAILBOX_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_A0_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_A0_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_A0_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_A1_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_A1_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_A1_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_B0_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_B0_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_B0_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_B1_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_B1_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_B1_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C0_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C0_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C0_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C1_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C1_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C1_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C2_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C2_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C2_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C3_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C3_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C3_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C4_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C4_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C4_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C5_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C5_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_TPTC_C5_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_RSS_TPTC_A0_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_RSS_TPTC_A0_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_RSS_TPTC_A0_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_RSS_TPTC_A1_FIFO_ECC_RAM_ID, 0u,
      SDL_DSS_ECC_AGG_RSS_TPTC_A1_FIFO_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_RSS_TPTC_A1_FIFO_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_DSS_ECC_AGG_DSS_HWA_PARAM_RAM_ECC_RAM_ID, 0x06060000u,
      SDL_DSS_ECC_AGG_DSS_HWA_PARAM_RAM_ECC_RAM_SIZE, 8u,
      SDL_DSS_ECC_AGG_DSS_HWA_PARAM_RAM_ECC_ROW_WIDTH, ((bool)true) },
};

/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_MSS_MCANA_ECC
 * -----------------------------------------------------------------------------------
 */
const SDL_MemConfig_t SDL_MSS_MCANA_ECC_MemEntries[SDL_MSS_MCANA_ECC_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_MSS_MCANA_ECC_MSS_MCANA_ECC_RAM_ID, 0u,
      SDL_MSS_MCANA_ECC_MSS_MCANA_ECC_RAM_SIZE, 4u,
      SDL_MSS_MCANA_ECC_MSS_MCANA_ECC_ROW_WIDTH, ((bool)false) },
};

/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_MSS_MCANB_ECC
 * -----------------------------------------------------------------------------------
 */
const SDL_MemConfig_t SDL_MSS_MCANB_ECC_MemEntries[SDL_MSS_MCANB_ECC_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_MSS_MCANB_ECC_MSS_MCANB_ECC_RAM_ID, 0u,
      SDL_MSS_MCANB_ECC_MSS_MCANB_ECC_RAM_SIZE, 4u,
      SDL_MSS_MCANB_ECC_MSS_MCANB_ECC_ROW_WIDTH, ((bool)false) },
};

/** ----------------------------------------------------------------------------------
 * This structure holds the memory config for each memory subtype SDL_CPSW3GCSS_ECC_AGGR
 * -----------------------------------------------------------------------------------
 */
static const SDL_MemConfig_t SDL_CPSW3GCSS_ECC_AGGR_MemEntries[SDL_CPSW3GCSS_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES] =
{
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_ALE_RAM_ECC_RAM_ID, 0x0703E000u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_ALE_RAM_ECC_RAM_SIZE, 71u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_ALE_RAM_ECC_ROW_WIDTH, ((bool)true) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL1_ECC_RAM_ID, 0u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL1_ECC_RAM_SIZE, 32u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL1_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL2_ECC_RAM_ID, 0u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL2_ECC_RAM_SIZE, 32u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL2_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL3_ECC_RAM_ID, 0u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL3_ECC_RAM_SIZE, 32u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL3_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL4_ECC_RAM_ID, 0u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL4_ECC_RAM_SIZE, 32u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL4_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL5_ECC_RAM_ID, 0u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL5_ECC_RAM_SIZE, 32u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL5_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL6_ECC_RAM_ID, 0u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL6_ECC_RAM_SIZE, 32u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL6_ECC_ROW_WIDTH, ((bool)false) },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_EST_RAM_ECC_RAM_ID, 0x07032000u,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_EST_RAM_ECC_RAM_SIZE, 4u,
      SDL_ECC_WIDTH_UNDEFINED, ((bool)true) },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_R5FSS0_CORE0_ECC_AGGR
 * -------------------------------------------------------------------------------------
 */
static const SDL_RAMIdEntry_t SDL_R5FSS0_CORE0_ECC_AGGR_RamIdTable[SDL_R5FSS0_CORE0_ECC_AGGR_NUM_RAMS] =
{
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM2_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM2_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM3_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM3_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_ITAG_RAM3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK2_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK2_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK3_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK3_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_IDATA_BANK3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM2_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM2_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM3_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM3_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DTAG_RAM3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDIRTY_RAM_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDIRTY_RAM_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDIRTY_RAM_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM2_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM2_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM3_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM3_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM4_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM4_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM4_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM5_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM5_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM5_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM6_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM6_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM6_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM7_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM7_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_DDATA_RAM7_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_ATCM0_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B0TCM0_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK0_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK1_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_PULSAR_SL_B1TCM0_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_KS_VIM_RAMECC_RAM_ID,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_KS_VIM_RAMECC_INJECT_TYPE,
      SDL_R5FSS0_CORE0_ECC_AGGR_CPU0_KS_VIM_RAMECC_ECC_TYPE,
      0u,
      NULL },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_R5FSS0_CORE1_ECC_AGGR
 * -------------------------------------------------------------------------------------
 */
static const SDL_RAMIdEntry_t SDL_R5FSS0_CORE1_ECC_AGGR_RamIdTable[SDL_R5FSS0_CORE1_ECC_AGGR_NUM_RAMS] =
{
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM2_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM2_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM3_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM3_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_ITAG_RAM3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK2_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK2_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK3_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK3_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_IDATA_BANK3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM2_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM2_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM3_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM3_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DTAG_RAM3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDIRTY_RAM_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDIRTY_RAM_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDIRTY_RAM_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM2_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM2_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM2_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM3_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM3_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM3_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM4_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM4_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM4_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM5_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM5_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM5_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM6_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM6_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM6_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM7_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM7_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_DDATA_RAM7_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_ATCM1_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B0TCM1_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK0_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK0_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK0_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK1_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK1_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_PULSAR_SL_B1TCM1_BANK1_ECC_TYPE,
      0u,
      NULL },
    { SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_KS_VIM_RAMECC_RAM_ID,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_KS_VIM_RAMECC_INJECT_TYPE,
      SDL_R5FSS0_CORE1_ECC_AGGR_CPU1_KS_VIM_RAMECC_ECC_TYPE,
      0u,
      NULL },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_MSS_ECC_AGG_MSS
 * -------------------------------------------------------------------------------------
 */
const SDL_RAMIdEntry_t SDL_MSS_ECC_AGG_MSS_RamIdTable[SDL_MSS_ECC_AGG_MSS_NUM_RAMS] =
{
    { SDL_MSS_ECC_AGG_MSS_MSS_L2RAMA_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMA_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMA_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_L2RAMB_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMB_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_L2RAMB_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_MBOX_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_MBOX_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_MBOX_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_RETRAM_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_RETRAM_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_RETRAM_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_GPADC_DATA_RAM_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_GPADC_DATA_RAM_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_GPADC_DATA_RAM_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A0_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A0_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A0_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A1_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A1_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_A1_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_MSS_ECC_AGG_MSS_MSS_TPTC_B0_ECC_RAM_ID,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_B0_ECC_INJECT_TYPE,
      SDL_MSS_ECC_AGG_MSS_MSS_TPTC_B0_ECC_ECC_TYPE,
      0u,
      NULL },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_DSS_ECC_AGG
 * -------------------------------------------------------------------------------------
 */
const SDL_RAMIdEntry_t SDL_DSS_ECC_AGG_RamIdTable[SDL_DSS_ECC_AGG_NUM_RAMS] =
{
    { SDL_DSS_ECC_AGG_DSS_L3RAMA_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_L3RAMA_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_L3RAMA_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_L3RAMB_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_L3RAMB_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_L3RAMB_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_L3RAMC_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_L3RAMC_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_L3RAMC_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_L3RAMD_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_L3RAMD_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_L3RAMD_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_MAILBOX_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_MAILBOX_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_MAILBOX_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_CM4_RAM_B0_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B0_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B0_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_CM4_RAM_B1_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B1_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B1_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_CM4_RAM_B2_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B2_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_CM4_RAM_B2_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_CM4_MAILBOX_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_CM4_MAILBOX_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_CM4_MAILBOX_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_A0_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_A0_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_A0_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_A1_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_A1_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_A1_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_B0_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_B0_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_B0_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_B1_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_B1_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_B1_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C0_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_C0_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_C0_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C1_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_C1_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_C1_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C2_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_C2_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_C2_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C3_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_C3_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_C3_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C4_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_C4_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_C4_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_TPTC_C5_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_TPTC_C5_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_TPTC_C5_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_RSS_TPTC_A0_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_RSS_TPTC_A0_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_RSS_TPTC_A0_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_RSS_TPTC_A1_FIFO_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_RSS_TPTC_A1_FIFO_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_RSS_TPTC_A1_FIFO_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_DSS_ECC_AGG_DSS_HWA_PARAM_RAM_ECC_RAM_ID,
      SDL_DSS_ECC_AGG_DSS_HWA_PARAM_RAM_ECC_INJECT_TYPE,
      SDL_DSS_ECC_AGG_DSS_HWA_PARAM_RAM_ECC_ECC_TYPE,
      0u,
      NULL },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_MSS_MCANA_ECC
 * -------------------------------------------------------------------------------------
 */
const SDL_RAMIdEntry_t SDL_MSS_MCANA_ECC_RamIdTable[SDL_MSS_MCANA_ECC_NUM_RAMS] =
{
    { SDL_MSS_MCANA_ECC_MSS_MCANA_ECC_RAM_ID,
      SDL_MSS_MCANA_ECC_MSS_MCANA_ECC_INJECT_TYPE,
      SDL_MSS_MCANA_ECC_MSS_MCANA_ECC_ECC_TYPE,
      0u,
      NULL },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_MSS_MCANB_ECC
 * -------------------------------------------------------------------------------------
 */
const SDL_RAMIdEntry_t SDL_MSS_MCANB_ECC_RamIdTable[SDL_MSS_MCANB_ECC_NUM_RAMS] =
{
    { SDL_MSS_MCANB_ECC_MSS_MCANB_ECC_RAM_ID,
      SDL_MSS_MCANB_ECC_MSS_MCANB_ECC_INJECT_TYPE,
      SDL_MSS_MCANB_ECC_MSS_MCANB_ECC_ECC_TYPE,
      0u,
      NULL },
};

/** ------------------------------------------------------------------------------------
 * This structure holds the list of Ram Ids for each memory subtype in SDL_CPSW3GCSS_ECC_AGGR
 * -------------------------------------------------------------------------------------
 */
static const SDL_RAMIdEntry_t SDL_CPSW3GCSS_ECC_AGGR_RamIdTable[SDL_CPSW3GCSS_ECC_AGGR_NUM_RAMS] =
{
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_ALE_RAM_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_ALE_RAM_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_ALE_RAM_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL1_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL1_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL1_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL2_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL2_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL2_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL3_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL3_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL3_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL4_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL4_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL4_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL5_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL5_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL5_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL6_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL6_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW_3GC_CORE_ECC_ECC_CTRL6_ECC_ECC_TYPE,
      0u,
      NULL },
    { SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_EST_RAM_ECC_RAM_ID,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_EST_RAM_ECC_INJECT_TYPE,
      SDL_CPSW3GCSS_ECC_AGGR_CPSW3GCSS_EST_RAM_ECC_ECC_TYPE,
      0u,
      NULL },
};

static SDL_ecc_aggrRegs * const SDL_ECC_aggrBaseAddressTable[SDL_ECC_Base_Address_TOTAL_ENTRIES] =
{
    ((SDL_ecc_aggrRegs *)((uintptr_t)SDL_MSS_ECC_AGG_R5A_U_BASE)),
    ((SDL_ecc_aggrRegs *)((uintptr_t)SDL_MSS_ECC_AGG_R5B_U_BASE)),
    ((SDL_ecc_aggrRegs *)((uintptr_t)SDL_MSS_ECC_AGG_MSS_U_BASE)),
    ((SDL_ecc_aggrRegs *)((uintptr_t)SDL_DSS_ECC_AGG_U_BASE)),
    ((SDL_ecc_aggrRegs *)((uintptr_t)SDL_MSS_MCANA_ECC_U_BASE )),
    ((SDL_ecc_aggrRegs *)((uintptr_t)SDL_MSS_MCANB_ECC_U_BASE)),
	((SDL_ecc_aggrRegs *)((uintptr_t)SDL_MSS_CPSW0_ECC_U_BASE)),
};

SDL_ecc_aggrRegs * SDL_ECC_aggrTransBaseAddressTable[SDL_ECC_MEMTYPE_MAX];
/**
 */
static const SDL_EccAggrEntry_t SDL_ECC_aggrTable[SDL_ECC_MEMTYPE_MAX] =
{

    /* Index: SDL_MSS_ECC_AGG_R5A (0) */
    {
        SDL_R5FSS0_CORE0_ECC_AGGR_NUM_RAMS,
        SDL_R5FSS0_CORE0_ECC_AGGR_RamIdTable,
        SDL_R5FSS0_CORE0_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES,
        SDL_R5FSS0_CORE0_ECC_AGGR_MemEntries,
        SDL_ESM_INST_MSS_ESM,
        SDL_ESMG1_ECCAGGA_SERR,
        SDL_ESMG1_ECCAGGA_UERR
    },
    /* Index: SDL_MSS_ECC_AGG_R5B (1) */
    {
        SDL_R5FSS0_CORE1_ECC_AGGR_NUM_RAMS,
        SDL_R5FSS0_CORE1_ECC_AGGR_RamIdTable,
        SDL_R5FSS0_CORE1_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES,
        SDL_R5FSS0_CORE1_ECC_AGGR_MemEntries,
        SDL_ESM_INST_MSS_ESM,
        SDL_ESMG1_ECCAGGB_SERR,
        SDL_ESMG1_ECCAGGB_UERR
    },
    /* Index: SDL_MSS_ECC_AGG_MSS (2) */
    {
        SDL_MSS_ECC_AGG_MSS_NUM_RAMS,
        SDL_MSS_ECC_AGG_MSS_RamIdTable,
        SDL_MSS_ECC_AGG_MSS_RAM_IDS_TOTAL_ENTRIES,
        SDL_MSS_ECC_AGG_MSS_MemEntries,
        SDL_ESM_INST_MSS_ESM,
        SDL_ESMG1_ECCAGGMSS_SERR,
        SDL_ESMG1_ECCAGGMSS_UERR
    },
    /* Index: SDL_DSS_ECC_AGG (3) */
    {
        SDL_DSS_ECC_AGG_NUM_RAMS,
        SDL_DSS_ECC_AGG_RamIdTable,
        SDL_DSS_ECC_AGG_RAM_IDS_TOTAL_ENTRIES,
        SDL_DSS_ECC_AGG_MemEntries,
        SDL_ESM_INST_DSS_ESM,
        SDL_DSS_ESMG1_DSS_ECC_AGG_SERR,
        SDL_DSS_ESMG1_DSS_ECC_AGG_UERR
    },
    /* Index: SDL_MSS_MCANA_ECC (4) */
    {
        SDL_MSS_MCANA_ECC_NUM_RAMS,
        SDL_MSS_MCANA_ECC_RamIdTable,
        SDL_MSS_MCANA_ECC_RAM_IDS_TOTAL_ENTRIES,
        SDL_MSS_MCANA_ECC_MemEntries,
        SDL_ESM_INST_MSS_ESM,
        SDL_ESMG1_MCANA_SERR,
        SDL_ESMG1_MCANA_UERR
    },
    /* Index: SDL_MSS_MCANB_ECC (5) */
    {
        SDL_MSS_MCANB_ECC_NUM_RAMS,
        SDL_MSS_MCANB_ECC_RamIdTable,
        SDL_MSS_MCANB_ECC_RAM_IDS_TOTAL_ENTRIES,
        SDL_MSS_MCANB_ECC_MemEntries,
        SDL_ESM_INST_MSS_ESM,
        SDL_ESMG1_MCANB_SERR,
        SDL_ESMG1_MCANB_UERR
    },
	/* Index: SDL_CPSW3GCSS_ECC_AGGR (6) */
    {
        SDL_CPSW3GCSS_ECC_AGGR_NUM_RAMS,
        SDL_CPSW3GCSS_ECC_AGGR_RamIdTable,
        SDL_CPSW3GCSS_ECC_AGGR_RAM_IDS_TOTAL_ENTRIES,
        SDL_CPSW3GCSS_ECC_AGGR_MemEntries,
        SDL_ESM_INST_MSS_ESM,
        SDL_ESMG1_CPSW_SERR,
        SDL_ESMG1_CPSW_UERR,
    }

 };
 #endif /* INCLUDE_SDL_ECC_SOC_H_ */
