name: 'Commit Message Check'

on:
  pull_request_target
  

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-22.04
    steps:
      - name: Check Title
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^a'
          error: 'Your first line has to contain a soc and module like "am64x: i2c: add support for intr priority".'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true' 
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{5,72}$'
          error: 'The maximum line length of 72 characters is exceeded.'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true' 
          accessToken: ${{ secrets.GITHUB_TOKEN }} 
      - name: Check for Fixes
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: 'Fixes: [A-Z\-_]*-\d*(, [A-Z\-_]*-\d*)*'
          error: 'You need at mention fixes like "Fixes: SITSW-1234" line.'
          excludeTitle: 'true' 
          checkAllCommitMessages: 'true' 
          accessToken: ${{ secrets.GITHUB_TOKEN }} 