/* =============================================================================
 *   Copyright (c) 2024 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef CSL_PSILCFG_THREAD_MAP_H_
#define CSL_PSILCFG_THREAD_MAP_H_

/*-----------------------------------------------------------------------------
 *  The following nomenclature is used in this file:
 *
 *  o "SAUL0 PSIL Slave Map"
 *                -----
 *      "Slave" means ingress into navss from the PSI-L endpoint
 *
 *  o "SAUL0 PSIL Master Map"
 *                ------
 *      "Master" means egress from navss to the PSI-L endpoint
 *
 *  o #define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILS_THREAD_OFFSET      (0x4000U)
 *                                             -
 *      "S" means a source thread (from the perspective of navss)
 *
 *  o #define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILD_THREAD_CNT         (2U)
 *                                             -
 *      "D" means a destination thread (from the perspective of navss)
 *
 *  o #define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILS_THREAD_CNT         (4U)
 *                                               ----------
 *      "THREAD_CNT" is the thread count for the specified source or
 *      destination thread
 *
 *  o #define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILD_THREAD_OFFSET      (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILS_THREAD_OFFSET)
 *                                               -------------
 *      "THREAD_OFFSET" is the starting thread # for the specified source or
 *      destination thread of the PSI-L endpoint
 *---------------------------------------------------------------------------*/

/** \brief Destination thread offset */
#define CSL_PSILCFG_DEST_THREAD_OFFSET      (0x8000U)

/**
 *  \anchor CSL_PsilcfgThreadMap
 *  \name PSIL thread map for main and mcu navss
 *
 *  Map of all PSIL threads
 *
 *  @{
 */
/*-----------------------------------------------------------------------------
 * navss_main thread map
 *---------------------------------------------------------------------------*/
/* UDMAC0 TCFGSTRM Map */
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_TCFGSTRM_THREAD_OFFSET   (0x0000U)
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_TCFGSTRM_THREAD_CNT      (1U)

/* UDMAC0 RCFGSTRM Map */
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_RCFGSTRM_THREAD_OFFSET   (0x0000U)
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_RCFGSTRM_THREAD_CNT      (1U)

/* UDMAC0 TTRSTRM Map */
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_TTRSTRM_THREAD_OFFSET    (0x0008U)
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_TTRSTRM_THREAD_CNT       (128U)

/* UDMAC0 RTRSTRM Map */
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_RTRSTRM_THREAD_OFFSET    (0x0008U)
#define CSL_PSILCFG_NAVSS_MAIN_UDMAC0_RTRSTRM_THREAD_CNT       (128U)

/* UDMAP0 TSTRM Map */
#define CSL_PSILCFG_NAVSS_MAIN_UDMAP0_TSTRM_THREAD_OFFSET      (0x1000U)
#define CSL_PSILCFG_NAVSS_MAIN_UDMAP0_TSTRM_THREAD_CNT         (120U)

/* UDMAP0 RSTRM Map */
#define CSL_PSILCFG_NAVSS_MAIN_UDMAP0_RSTRM_THREAD_OFFSET      (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_UDMAP0_TSTRM_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_UDMAP0_RSTRM_THREAD_CNT         (150U)

/* SAUL0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILS_THREAD_OFFSET       (0x4000U)
#define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILS_THREAD_CNT          (4U)

/* SAUL0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILD_THREAD_OFFSET       (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_SAUL0_PSILD_THREAD_CNT          (2U)

/* ICSS_G0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G0_PSILS_THREAD_OFFSET     (0x4100U)
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G0_PSILS_THREAD_CNT        (16U)

/* ICSS_G0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G0_PSILD_THREAD_OFFSET     (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_ICSS_G0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G0_PSILD_THREAD_CNT        (20U)

/* ICSS_G1 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G1_PSILS_THREAD_OFFSET     (0x4200U)
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G1_PSILS_THREAD_CNT        (16U)

/* ICSS_G1 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G1_PSILD_THREAD_OFFSET     (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_ICSS_G1_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G1_PSILD_THREAD_CNT        (20U)

/* ICSS_G2 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G2_PSILS_THREAD_OFFSET     (0x4300U)
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G2_PSILS_THREAD_CNT        (16U)

/* ICSS_G2 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G2_PSILD_THREAD_OFFSET     (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_ICSS_G2_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_ICSS_G2_PSILD_THREAD_CNT        (20U)

/* PDMA_MAIN0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILS_THREAD_OFFSET  (0x4400U)
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILS_THREAD_CNT     (32U)

/* PDMA_MAIN0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILD_THREAD_OFFSET  (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILD_THREAD_CNT     (32U)

/* PDMA_MAIN1 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET  (0x4500U)
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_CNT     (16U)

/* PDMA_MAIN1 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET  (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_CNT     (16U)

/* PDMA_DEBUG PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILS_THREAD_OFFSET  (0x4600U)
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILS_THREAD_CNT     (16U)

/* PDMA_DEBUG PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILD_THREAD_OFFSET  (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILD_THREAD_CNT     (16U)

/* CAL0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_CAL0_PSILS_THREAD_OFFSET        (0x4700U)
#define CSL_PSILCFG_NAVSS_MAIN_CAL0_PSILS_THREAD_CNT           (8U)

/* CAL0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_CAL0_PSILD_THREAD_OFFSET        (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_CAL0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_CAL0_PSILD_THREAD_CNT           (1U)

/* MSMC0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_MSMC0_PSILS_THREAD_OFFSET       (0x4800U)
#define CSL_PSILCFG_NAVSS_MAIN_MSMC0_PSILS_THREAD_CNT          (32U)

/* MSMC0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_MSMC0_PSILD_THREAD_OFFSET       (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_MSMC0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_MSMC0_PSILD_THREAD_CNT          (32U)

/* NAVSS_MCU PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MAIN_NAVSS_MCU_PSILS_THREAD_OFFSET   (0x6000U)
#define CSL_PSILCFG_NAVSS_MAIN_NAVSS_MCU_PSILS_THREAD_CNT      (8193U)

/* NAVSS_MCU PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MAIN_NAVSS_MCU_PSILD_THREAD_OFFSET   (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MAIN_NAVSS_MCU_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MAIN_NAVSS_MCU_PSILD_THREAD_CNT      (8193U)

/*-----------------------------------------------------------------------------
 * navss_mcu thread map
 *---------------------------------------------------------------------------*/

/* CFG PROXY Map */
#define CSL_PSILCFG_NAVSS_MCU_CFG_PROXY_THREAD_OFFSET         (0x0001U)
#define CSL_PSILCFG_NAVSS_MCU_CFG_PROXY_THREAD_CNT            (1U)

/* UDMAC0 TTRSTRM Map */
#define CSL_PSILCFG_NAVSS_MCU_UDMAC0_TTRSTRM_THREAD_OFFSET    (0x0008U)
#define CSL_PSILCFG_NAVSS_MCU_UDMAC0_TTRSTRM_THREAD_CNT       (128U)

/* UDMAC0 RTRSTRM Map */
#define CSL_PSILCFG_NAVSS_MCU_UDMAC0_RTRSTRM_THREAD_OFFSET    (0x0008U)
#define CSL_PSILCFG_NAVSS_MCU_UDMAC0_RTRSTRM_THREAD_CNT       (128U)

/* NAVSS PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MCU_NAVSS_PSILS_THREAD_OFFSET       (0x1000U)
#define CSL_PSILCFG_NAVSS_MCU_NAVSS_PSILS_THREAD_CNT          (16383U)

/* NAVSS PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MCU_NAVSS_PSILD_THREAD_OFFSET       (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MCU_NAVSS_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MCU_NAVSS_PSILD_THREAD_CNT          (16383U)

/* UDMAP0 TSTRM Map */
#define CSL_PSILCFG_NAVSS_MCU_UDMAP0_TSTRM_THREAD_OFFSET      (0x6000U)
#define CSL_PSILCFG_NAVSS_MCU_UDMAP0_TSTRM_THREAD_CNT         (48U)

/* UDMAP0 RSTRM Map */
#define CSL_PSILCFG_NAVSS_MCU_UDMAP0_RSTRM_THREAD_OFFSET      (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MCU_UDMAP0_TSTRM_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MCU_UDMAP0_RSTRM_THREAD_CNT         (48U)

/* CPSW0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MCU_CPSW0_PSILS_THREAD_OFFSET       (0x7000U)
#define CSL_PSILCFG_NAVSS_MCU_CPSW0_PSILS_THREAD_CNT          (1U)

/* CPSW0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MCU_CPSW0_PSILD_THREAD_OFFSET       (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MCU_CPSW0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MCU_CPSW0_PSILD_THREAD_CNT          (8U)

/* PDMA_MCU0 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_OFFSET   (0x7100U)
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_CNT      (16U)

/* PDMA_MCU0 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILD_THREAD_OFFSET   (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILD_THREAD_CNT      (16U)

/* PDMA_MCU1 PSIL Slave Map */
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET   (0x7200U)
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_CNT      (16U)

/* PDMA_MCU1 PSIL Master Map */
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET   (CSL_PSILCFG_DEST_THREAD_OFFSET | CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET)
#define CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_CNT      (16U)
/* @} */

/**
 *  \anchor CSL_PdmaCh
 *  \name PDMA Channels for AM65XX
 *
 *  List of all PDMA channels across main and MCU domains
 *
 *  @{
 */

/**
 *  \anchor CSL_PdmaChMainTx
 *  \name Main TX PDMA Channels for AM65XX
 *
 *  List of all Main PDMA TX channels
 *
 *  @{
 */
/*
 * PDMA Debug TX Channels
 */
/* None */
/*
 * PDMA Main0 TX Channels
 */
#define CSL_PDMA_CH_MAIN_MCASP0_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILD_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MAIN_MCASP1_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILD_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MAIN_MCASP2_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILD_THREAD_OFFSET + 2U)
/*
 * PDMA Main1 TX Channels
 */
#define CSL_PDMA_CH_MAIN_MCSPI0_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MAIN_MCSPI0_CH1_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MAIN_MCSPI0_CH2_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 2U)
#define CSL_PDMA_CH_MAIN_MCSPI0_CH3_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 3U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 4U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH1_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 5U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH2_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 6U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH3_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 7U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 8U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH1_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 9U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH2_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 10U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH3_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 11U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 12U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH1_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 13U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH2_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 14U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH3_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 15U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH0_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 16U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH1_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 17U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH2_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 18U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH3_TX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 19U)
#define CSL_PDMA_CH_MAIN_UART0_CH0_TX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 20U)
#define CSL_PDMA_CH_MAIN_UART1_CH0_TX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 21U)
#define CSL_PDMA_CH_MAIN_UART2_CH0_TX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILD_THREAD_OFFSET + 22U)
/* @} */

/**
 *  \anchor CSL_PdmaChMcuTx
 *  \name MCU TX PDMA Channels for AM65XX
 *
 *  List of all MCU PDMA TX channels
 *
 *  @{
 */
/*
 * PDMA MCU0 TX Channels
 */
/* None */
/*
 * PDMA MCU1 TX Channels
 */
#define CSL_PDMA_CH_MCU_MCSPI0_CH0_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MCU_MCSPI0_CH1_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MCU_MCSPI0_CH2_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 2U)
#define CSL_PDMA_CH_MCU_MCSPI0_CH3_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 3U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH0_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 4U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH1_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 5U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH2_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 6U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH3_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 7U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH0_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 8U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH1_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 9U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH2_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 10U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH3_TX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 11U)
#define CSL_PDMA_CH_MCU_MCAN0_CH0_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 12U)
#define CSL_PDMA_CH_MCU_MCAN0_CH1_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 13U)
#define CSL_PDMA_CH_MCU_MCAN0_CH2_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 14U)
#define CSL_PDMA_CH_MCU_MCAN1_CH0_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 15U)
#define CSL_PDMA_CH_MCU_MCAN1_CH1_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 16U)
#define CSL_PDMA_CH_MCU_MCAN1_CH2_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 17U)
#define CSL_PDMA_CH_MCU_UART0_CH0_TX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILD_THREAD_OFFSET + 18U)
/* @} */

/**
 *  \anchor CSL_PdmaChMainRx
 *  \name Main RX PDMA Channels for AM65XX
 *
 *  List of all Main PDMA RX channels
 *
 *  @{
 */
/*
 * PDMA Debug RX Channels
 */
#define CSL_PDMA_CH_MAIN_DEBUG_MCU_RX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILS_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MAIN_DEBUG_MAIN_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILS_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MAIN_DEBUG_CC_RX    (CSL_PSILCFG_NAVSS_MAIN_PDMA_DEBUG_PSILS_THREAD_OFFSET + 2U)
/*
 * PDMA Main0 RX Channels
 */
#define CSL_PDMA_CH_MAIN_MCASP0_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILS_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MAIN_MCASP1_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILS_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MAIN_MCASP2_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN0_PSILS_THREAD_OFFSET + 2U)
/*
 * PDMA Main1 RX Channels
 */
#define CSL_PDMA_CH_MAIN_MCSPI0_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MAIN_MCSPI0_CH1_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MAIN_MCSPI0_CH2_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 2U)
#define CSL_PDMA_CH_MAIN_MCSPI0_CH3_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 3U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 4U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH1_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 5U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH2_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 6U)
#define CSL_PDMA_CH_MAIN_MCSPI1_CH3_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 7U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 8U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH1_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 9U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH2_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 10U)
#define CSL_PDMA_CH_MAIN_MCSPI2_CH3_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 11U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 12U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH1_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 13U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH2_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 14U)
#define CSL_PDMA_CH_MAIN_MCSPI3_CH3_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 15U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH0_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 16U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH1_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 17U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH2_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 18U)
#define CSL_PDMA_CH_MAIN_MCSPI4_CH3_RX  (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 19U)
#define CSL_PDMA_CH_MAIN_UART0_CH0_RX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 20U)
#define CSL_PDMA_CH_MAIN_UART1_CH0_RX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 21U)
#define CSL_PDMA_CH_MAIN_UART2_CH0_RX   (CSL_PSILCFG_NAVSS_MAIN_PDMA_MAIN1_PSILS_THREAD_OFFSET + 22U)
/* @} */

/**
 *  \anchor CSL_PdmaChMcuRx
 *  \name MCU RX PDMA Channels for AM65XX
 *
 *  List of all MCU PDMA RX channels
 *
 *  @{
 */
/*
 * PDMA MCU0 RX Channels
 */
#define CSL_PDMA_CH_MCU_ADC0_CH0_RX     (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MCU_ADC0_CH1_RX     (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MCU_ADC1_CH0_RX     (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_OFFSET + 2U)
#define CSL_PDMA_CH_MCU_ADC1_CH1_RX     (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU0_PSILS_THREAD_OFFSET + 3U)
/*
 * PDMA MCU1 RX Channels
 */
#define CSL_PDMA_CH_MCU_MCSPI0_CH0_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 0U)
#define CSL_PDMA_CH_MCU_MCSPI0_CH1_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 1U)
#define CSL_PDMA_CH_MCU_MCSPI0_CH2_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 2U)
#define CSL_PDMA_CH_MCU_MCSPI0_CH3_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 3U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH0_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 4U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH1_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 5U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH2_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 6U)
#define CSL_PDMA_CH_MCU_MCSPI1_CH3_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 7U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH0_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 8U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH1_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 9U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH2_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 10U)
#define CSL_PDMA_CH_MCU_MCSPI2_CH3_RX   (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 11U)
#define CSL_PDMA_CH_MCU_MCAN0_CH0_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 12U)
#define CSL_PDMA_CH_MCU_MCAN0_CH1_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 13U)
#define CSL_PDMA_CH_MCU_MCAN0_CH2_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 14U)
#define CSL_PDMA_CH_MCU_MCAN1_CH0_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 15U)
#define CSL_PDMA_CH_MCU_MCAN1_CH1_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 16U)
#define CSL_PDMA_CH_MCU_MCAN1_CH2_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 17U)
#define CSL_PDMA_CH_MCU_UART0_CH0_RX    (CSL_PSILCFG_NAVSS_MCU_PDMA_MCU1_PSILS_THREAD_OFFSET + 18U)
/* @} */

/* @} */

#endif
